/-
Copyright (c) 2026 Fernando Portela. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Fernando Portela
-/

/-
Portions of this file were generated by Aristotle (https://aristotle.harmonic.fun).

Lean version: leanprover/lean4:v4.28.0
Mathlib version: 8f9d9cff6bd728b17a24e163c9402775d9e6a365

To cite Aristotle, tag @Aristotle-Harmonic on GitHub PRs/issues, and add as co-author to commits:
Co-authored-by: Aristotle (Harmonic) <aristotle-harmonic@harmonic.fun>
-/

import Mathlib.Data.Real.Basic
import Mathlib.Algebra.Order.Ring.Star
import Mathlib.Data.Int.Star
import Mathlib.Data.Int.ConditionallyCompleteOrder
import Mathlib.AlgebraicTopology.SimplexCategory.Basic
import Mathlib.Algebra.Ring.BooleanRing
import Mathlib.Data.Int.Interval
import Mathlib.Data.ZMod.QuotientRing
import Mathlib.Algebra.BigOperators.Group.Finset.Defs
import Mathlib.Order.ConditionallyCompleteLattice.Basic

namespace KrafftSieve

/--
In a complete CRT period, fixing one coordinate of a family of two independent
choices leaves exactly half of the Boolean choices.  This weighted form is the
combinatorial summation identity needed by the Gibbs-dip expectation argument.
-/
lemma crt_two_choices_coordinate_sum {m : ℕ} (a : Fin m → ℕ)
    [NeZero (∏ i, a i)]
    (hcop : Pairwise (fun i j => Nat.Coprime (a i) (a j)))
    (u v : (i : Fin m) → ZMod (a i)) (hne : ∀ i, u i ≠ v i)
    (i : Fin m) (f : ZMod (a i) → ℝ) :
    ∑ y ∈ (Finset.Ico 0 ((∏ j, a j) : ℤ)).filter (fun y : ℤ =>
        ∀ j, (y : ZMod (a j)) = u j ∨ (y : ZMod (a j)) = v j),
      f (y : ZMod (a i)) =
      (2 ^ (m - 1) : ℝ) * (f (u i) + f (v i)) := by
  obtain ⟨g, hg⟩ : ∃ g : (∀ j, ZMod (a j)) ≃+* ZMod (∏ j, (a j)),
      ∀ j x, ((g x).val : ZMod (a j)) = x j := by
    -- By the Chinese Remainder Theorem, there exists a ring isomorphism between
    -- $ZMod (\prod_{j} a_j)$ and $\prod_{j} ZMod (a_j)$.
    have h_crt_iso : Nonempty (ZMod (∏ j, (a j)) ≃+* (∀ j, ZMod (a j))) := by
      exact ⟨ ( ZMod.prodEquivPi a hcop ) ⟩
    obtain ⟨ g ⟩ := h_crt_iso
    refine ⟨ g.symm, ?_ ⟩
    intro j x
    have h_crt_iso : ∀ y : ZMod (∏ j, (a j)), (g y) j = y.val := by
      intro y
      have h_crt_iso : ∀ y : ℕ, y < ∏ j, (a j) → (g y) j = y := by
        intro y hy; have := g.map_add ( y : ZMod ( ∏ j, a j ) ) 0
        simp_all +decide
      have := h_crt_iso y.val ( ZMod.val_lt y ) ; aesop
    rw [ ← h_crt_iso, g.apply_symm_apply ]
  -- Consider the set of all possible combinations of $u$ and $v$.
  set S := Finset.image (fun b : (j : Fin m) → Bool => g (fun j => if b j then v j else u j))
                        (Finset.univ : Finset ((j : Fin m) → Bool)) with hS_def
  -- By definition of $S$, we know that every element in $S$ is of the form $g(b)$ for some
  -- $b : (j : Fin m) → Bool$.
  have hS : Finset.filter (fun y : ℕ => ∀ j, (y : ZMod (a j)) = u j ∨ (y : ZMod (a j)) = v j)
      (Finset.Ico 0 (∏ j, (a j))) = Finset.image (fun x => x.val) S := by
    ext y; simp only [Nat.Ico_zero_eq_range, Finset.mem_filter, Finset.mem_range, hS_def,
      Finset.mem_image, Finset.mem_univ, true_and, exists_exists_eq_and]
    constructor
    · intro hy
      obtain ⟨b, hb⟩ : ∃ b : (j : Fin m) → Bool, ∀ j,
          (y : ZMod (a j)) = if b j then v j else u j := by
        exact ⟨ fun j => if ( y : ZMod ( a j ) ) = v j then Bool.true else Bool.false, fun j => by
          specialize hy; specialize hy; cases hy.2 j <;> aesop ⟩
      use b
      convert congr_arg ZMod.val ( g.apply_symm_apply ( y : ZMod ( ∏ j, a j ) ) ) using 1
      · congr! 2
        ext j; specialize hg j ( g.symm ( y : ZMod ( ∏ j, a j ) ) ) ; aesop
      · exact Eq.symm ( ZMod.val_cast_of_lt hy.1 )
    · rintro ⟨ b, rfl ⟩ ; exact ⟨ by exact ZMod.val_lt _, fun j => by
        specialize hg j ( fun j => if b j = true then v j else u j ) ; aesop ⟩
  -- By definition of $S$, we know that every element in $S$ is of the form $g(b)$ for some
  -- $b : (j : Fin m) → Bool$. Therefore, we can rewrite the sum as:
  have h_sum : ∑ y ∈ Finset.filter (fun y : ℕ => ∀ j, (y : ZMod (a j)) = u j ∨ (y : ZMod (a j)) = v j) (Finset.Ico 0 (∏ j, (a j))), f (y : ZMod (a i)) = ∑ b : (j : Fin m) → Bool, f (if b i then v i else u i) := by
    rw [ show ( Finset.filter ( fun y : ℕ => ∀ j : Fin m, ( y : ZMod ( a j ) ) = u j ∨ ( y : ZMod ( a j ) ) = v j ) ( Finset.Ico 0 ( ∏ j : Fin m, a j ) ) ) = Finset.image ( fun b : ( j : Fin m ) → Bool => ( g fun j => if b j = true then v j else u j ).val ) Finset.univ from ?_ ]
    · rw [ Finset.sum_image ]
      · exact Finset.sum_congr rfl fun x hx => by specialize hg i ( fun j => if x j = true then v j else u j ) ; aesop
      · intro b hb b' hb' h; have := hg i ( fun j => if b j then v j else u j ) ; have := hg i ( fun j => if b' j then v j else u j ) ; simp_all +decide [ funext_iff ]
        have := g.injective ( show g ( fun k => if b k then v k else u k ) = g ( fun k => if b' k then v k else u k ) from by
                                exact ZMod.val_injective _ h ) ; simp_all +decide [ funext_iff ]
        grind
    · aesop
  convert h_sum using 1
  · refine Finset.sum_bij ( fun x hx => Int.toNat x ) ?_ ?_ ?_ ?_
    · simp +decide only [Finset.mem_filter, Finset.mem_Ico, Nat.Ico_zero_eq_range,
      Finset.mem_range, and_imp]
      intro x hx₁ hx₂ hx₃; norm_cast at *; simp_all +decide
    · grind
    · simp +decide only [Nat.Ico_zero_eq_range, Finset.mem_filter, Finset.mem_range,
      Finset.mem_Ico, exists_prop, and_imp]
      exact fun b hb hb' => ⟨ b, ⟨ ⟨ Nat.cast_nonneg _, mod_cast hb ⟩, mod_cast hb' ⟩, rfl ⟩
    · simp +decide only [Finset.mem_filter, Finset.mem_Ico, and_imp]
      exact fun x hx₁ hx₂ hx₃ => by rw [ ← Int.toNat_of_nonneg hx₁ ] ; norm_cast
  · -- Let's simplify the sum
    have h_sum_simplified : ∑ b : (j : Fin m) → Bool, f (if b i then v i else u i) =
        ∑ b : (j : Fin m) → Bool, f (u i) +
        ∑ b : (j : Fin m) → Bool, (f (v i) - f (u i)) * (if b i then 1 else 0) := by
      rw [ ← Finset.sum_add_distrib ] ; congr ; ext b ; split_ifs <;> ring
    -- Let's simplify the sum
    have h_sum_indicator : ∑ b : (j : Fin m) → Bool, (if b i then 1 else 0) = 2 ^ (m - 1) := by
      have h_sum_indicator : Finset.card (Finset.filter (fun b : (j : Fin m) → Bool => b i = true) Finset.univ) =
          Finset.card (Finset.univ : Finset ((j : Fin m) → Bool)) / 2 := by
        have h_sum_indicator : Finset.card (Finset.filter (fun b : (j : Fin m) → Bool => b i = true) Finset.univ) =
            Finset.card (Finset.filter (fun b : (j : Fin m) → Bool => b i = false) Finset.univ) := by
          rw [ Finset.card_filter, Finset.card_filter ]
          rw [ ← Equiv.sum_comp ( Equiv.addRight ( Pi.single i true ) ) ] ; aesop
        have h_sum_indicator2 : Finset.card (Finset.filter (fun b : (j : Fin m) → Bool => b i = true) Finset.univ) +
            Finset.card (Finset.filter (fun b : (j : Fin m) → Bool => b i = false) Finset.univ) =
            Finset.card (Finset.univ : Finset ((j : Fin m) → Bool)) := by
          rw [ Finset.card_filter, Finset.card_filter ]
          rw [ ← Finset.sum_add_distrib, Finset.card_eq_sum_ones ] ; congr ; ext ; aesop
        grind
      rw [Finset.sum_boole, h_sum_indicator]
      simp only [Finset.card_univ, Fintype.card_pi, Fintype.card_bool, Finset.prod_const,
        Fintype.card_fin, Nat.cast_id]
      cases m with
      | zero => exact Fin.elim0 i
      | succ n =>
        have h : (2 ^ (n + 1) : ℕ) / 2 = 2 ^ n := by
          rw [pow_add, pow_one, Nat.mul_div_cancel _ (by decide)]
        norm_cast
        -- rw [h]
    simp_all only [Finset.sum_ite, Finset.sum_const, smul_eq_mul, nsmul_eq_mul, mul_ite, mul_one,
      mul_zero, add_zero]
    cases m with
    | zero => fin_cases i
    | succ n =>
      simp_all only [Finset.card_univ, Fintype.card_pi, Fintype.card_bool, Finset.prod_const,
        Nat.cast_pow, Nat.cast_ofNat, add_tsub_cancel_right]
      have h_card : Fintype.card (Fin (n + 1)) = n + 1 := Fintype.card_fin (n + 1)
      rw [h_card]
      have h_pow : (2 ^ (n + 1) : ℝ) = 2 * 2 ^ n := by
        rw [pow_succ, mul_comm]
      rw [h_pow]
      ring

end KrafftSieve
