/-
Copyright (c) 2026 Fernando Portela. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Fernando Portela
-/

/-
Portions of this file were generated by Aristotle (https://aristotle.harmonic.fun).

Lean version: leanprover/lean4:v4.28.0
Mathlib version: 8f9d9cff6bd728b17a24e163c9402775d9e6a365

To cite Aristotle, tag @Aristotle-Harmonic on GitHub PRs/issues, and add as co-author to commits:
Co-authored-by: Aristotle (Harmonic) <aristotle-harmonic@harmonic.fun>
-/

import Mathlib.Topology.Defs.Basic
import Mathlib.Algebra.BigOperators.Group.Finset.Defs
import Mathlib.Analysis.Complex.Trigonometric
import Mathlib.Analysis.SpecialFunctions.Trigonometric.Basic
import Mathlib.MeasureTheory.Integral.Bochner.Basic
import Mathlib.MeasureTheory.Constructions.Pi
import Mathlib.MeasureTheory.Constructions.UnitInterval
import Mathlib.Analysis.SpecialFunctions.Integrals.Basic
import KrafftSieve.ProfiniteRKHS

/-!
# Dirichlet-kernel exact quadrature (self-contained)

This module builds the exact "reproducing" quadrature machinery used to bridge a continuous
integral against a continuous window and a discrete windowed grid sum.

The key object is the (real) Dirichlet kernel `dirichletKernel M s = 1 + 2 ∑_{k=1}^M cos(2π k s)`.
It reproduces the values of any real trigonometric polynomial of degree `≤ M` at a point `a`
through integration over the unit interval:
`∫ t, cos(2π m t) · dirichletKernel M (t - a) dt = cos(2π m a)` whenever `|m| ≤ M`.

Extending this by the product-to-sum expansion yields the exact reproducing identity for a product
of cosines with integer frequencies whose absolute values sum to at most `M`, and, summing the
kernel over a grid, the exact windowed quadrature identity `prod_cos_reproWindow`.

Everything here is stated over the unit interval `unitInterval` with the `volume` measure, so that
it transfers verbatim to `X₀ := I` and `μ₀ := volume` used elsewhere in the project.
-/

namespace KrafftSieve

open scoped unitInterval BigOperators Real
open unitInterval MeasureTheory

/-
Base shifted-cosine integral over the unit interval: the average of `cos (2π j t + φ)` is
`cos φ` if `j = 0` and `0` otherwise.
-/
theorem base_cos_shift_integral (j : ℤ) (φ : ℝ) :
    ∫ t : unitInterval, Real.cos (2 * Real.pi * (j : ℝ) * (t : ℝ) + φ) ∂(volume) =
      if j = 0 then Real.cos φ else 0 := by
  convert (MeasureTheory.integral_subtype (measurableSet_Icc)
    (fun t => Real.cos (2 * Real.pi * j * t + φ))) using 1
  split_ifs with hj
  · subst hj
    simp
  · simp_all only [integral_Icc_eq_integral_Ioc,
      ← intervalIntegral.integral_of_le zero_le_one, ne_eq, mul_eq_zero,
      OfNat.ofNat_ne_zero, Real.pi_ne_zero, or_self, Int.cast_eq_zero,
      not_false_eq_true, intervalIntegral.integral_comp_mul_add, mul_inv_rev,
      mul_zero, zero_add, mul_one, integral_cos, smul_eq_mul,
      zero_eq_mul, inv_eq_zero, false_or]
    rw [Real.sin_sub_sin]
    ring_nf
    norm_num
    exact Or.inl (Real.sin_eq_zero_iff.mpr ⟨j, by ring⟩)

/-- Product-to-sum expansion of a product of cosines over a `Finset`, indexed by a
powerset of sign choices. -/
theorem dirichlet_prod_cos_expand {ι : Type*} [DecidableEq ι] (A : Finset ι) (θ : ι → ℝ) :
    ∏ i ∈ A, Real.cos (θ i) =
      (2 ^ A.card : ℝ)⁻¹ *
        ∑ B ∈ A.powerset, Real.cos ((∑ i ∈ B, θ i) - ∑ i ∈ A \ B, θ i) := by
  induction A using Finset.induction with
  | empty => norm_num
  | @insert a A ha ih =>
    rw [Finset.card_insert_of_notMem ha, Finset.prod_insert ha, ih,
      Finset.sum_powerset_insert ha, ← Finset.sum_add_distrib]
    simp only [Finset.mul_sum]
    rw [pow_succ]
    refine Finset.sum_congr rfl fun B hB => ?_
    have haB : a ∉ B := fun h => ha (Finset.mem_powerset.mp hB h)
    have h1 : insert a A \ B = insert a (A \ B) := Finset.insert_sdiff_of_notMem A haB
    have h2 : insert a A \ insert a B = A \ B := by
      ext x; simp only [Finset.mem_sdiff, Finset.mem_insert]; constructor
      · rintro ⟨(rfl | hx), hx2⟩
        · exact absurd (Or.inl rfl) hx2
        · exact ⟨hx, fun h => hx2 (Or.inr h)⟩
      · rintro ⟨hx, hx2⟩
        refine ⟨Or.inr hx, fun h => ?_⟩
        rcases h with rfl | h
        · exact ha hx
        · exact hx2 h
    have haAB : a ∉ A \ B := fun h => ha (Finset.mem_sdiff.mp h).1
    rw [h1, Finset.sum_insert haAB, Finset.sum_insert haB, h2]
    have key : ∀ s u : ℝ, Real.cos (s - (θ a + u)) + Real.cos (θ a + s - u)
        = 2 * Real.cos (θ a) * Real.cos (s - u) := by
      intro s u
      have e1 : s - (θ a + u) = (s - u) - θ a := by ring
      have e2 : θ a + s - u = θ a + (s - u) := by ring
      rw [e1, e2, Real.cos_sub, Real.cos_add]; ring
    rw [key]; ring

/-- The real Dirichlet kernel of degree `M`. -/
noncomputable def dirichletKernel (M : ℕ) (s : ℝ) : ℝ :=
  1 + 2 * ∑ k ∈ Finset.Icc 1 M, Real.cos (2 * Real.pi * (k : ℝ) * s)

/-- The Dirichlet kernel is continuous in its argument. -/
lemma dirichletKernel_continuous (M : ℕ) : Continuous (dirichletKernel M) := by
  unfold dirichletKernel
  fun_prop

/-
Per-term integral appearing in the Dirichlet reproducing computation:
`∫ cos(2π m t) · cos(2π k (t - a)) dt` over the unit interval equals
`cos(2π k a) · ((𝟙[m=k] + 𝟙[m=-k]) / 2)`.
-/
lemma cos_mul_cos_shift_integral (m : ℤ) (k : ℕ) (a : ℝ) :
    ∫ t : unitInterval,
        Real.cos (2 * Real.pi * (m : ℝ) * (t : ℝ)) *
          Real.cos (2 * Real.pi * (k : ℝ) * ((t : ℝ) - a)) ∂(volume) =
      Real.cos (2 * Real.pi * (k : ℝ) * a) *
        (((if m = (k : ℤ) then (1 : ℝ) else 0) + (if m = -(k : ℤ) then (1 : ℝ) else 0)) / 2) := by
  have key : ∀ t : unitInterval,
      Real.cos (2 * Real.pi * (m : ℝ) * (t : ℝ)) *
          Real.cos (2 * Real.pi * (k : ℝ) * ((t : ℝ) - a))
        = Real.cos (2 * Real.pi * ((m + (k : ℤ) : ℤ) : ℝ) * (t : ℝ) +
            (-(2 * Real.pi * (k : ℝ) * a))) / 2
          + Real.cos (2 * Real.pi * ((m - (k : ℤ) : ℤ) : ℝ) * (t : ℝ) +
            (2 * Real.pi * (k : ℝ) * a)) / 2 := by
    intro t
    have e1 : (2 * Real.pi * ((m + (k : ℤ) : ℤ) : ℝ) * (t : ℝ) + (-(2 * Real.pi * (k : ℝ) * a)))
            = 2 * Real.pi * (m : ℝ) * (t : ℝ) + 2 * Real.pi * (k : ℝ) * ((t : ℝ) - a) := by
      push_cast; ring
    have e2 : (2 * Real.pi * ((m - (k : ℤ) : ℤ) : ℝ) * (t : ℝ) + (2 * Real.pi * (k : ℝ) * a))
            = 2 * Real.pi * (m : ℝ) * (t : ℝ) - 2 * Real.pi * (k : ℝ) * ((t : ℝ) - a) := by
      push_cast; ring
    rw [e1, e2, Real.cos_add, Real.cos_sub]; ring
  rw [MeasureTheory.integral_congr_ae (Filter.Eventually.of_forall key)]
  have hcont1 : Continuous (fun t : unitInterval =>
      Real.cos (2 * Real.pi * ((m + (k : ℤ) : ℤ) : ℝ) * (t : ℝ) +
        (-(2 * Real.pi * (k : ℝ) * a))) / 2) := by fun_prop
  have hcont2 : Continuous (fun t : unitInterval =>
      Real.cos (2 * Real.pi * ((m - (k : ℤ) : ℤ) : ℝ) * (t : ℝ) +
        (2 * Real.pi * (k : ℝ) * a)) / 2) := by fun_prop
  rw [MeasureTheory.integral_add
      (hcont1.integrable_of_hasCompactSupport (HasCompactSupport.of_compactSpace _))
      (hcont2.integrable_of_hasCompactSupport (HasCompactSupport.of_compactSpace _)),
    MeasureTheory.integral_div, MeasureTheory.integral_div,
    base_cos_shift_integral, base_cos_shift_integral, Real.cos_neg]
  have hh1 : (m + (k : ℤ) = 0) ↔ (m = -(k : ℤ)) := by omega
  have hh2 : (m - (k : ℤ) = 0) ↔ (m = (k : ℤ)) := by omega
  by_cases h1 : m = (k : ℤ) <;> by_cases h2 : m = -(k : ℤ) <;>
    simp only [hh1, hh2, h1, h2, if_false, if_pos] <;> ring_nf <;>
    simp_all

/-
Reproducing property of the Dirichlet kernel for a single cosine of frequency `m`
with `|m| ≤ M`.
-/
theorem dirichlet_cos_repro (M : ℕ) (m : ℤ) (a : ℝ) (hm : m.natAbs ≤ M) :
    ∫ t : unitInterval,
        Real.cos (2 * Real.pi * (m : ℝ) * (t : ℝ)) * dirichletKernel M ((t : ℝ) - a) ∂(volume) =
      Real.cos (2 * Real.pi * (m : ℝ) * a) := by
  -- Split the integral into two parts: one involving the constant term
  -- and the other involving the sum of cosines.
  have h_split : ∫ t : unitInterval,
        Real.cos (2 * Real.pi * (m : ℝ) * (t : ℝ)) *
          (1 + 2 * ∑ k ∈ Finset.Icc 1 M,
            Real.cos (2 * Real.pi * (k : ℝ) * ((t : ℝ) - a))) ∂(volume) =
      (∫ t : unitInterval, Real.cos (2 * Real.pi * (m : ℝ) * (t : ℝ)) ∂(volume)) +
        2 * ∑ k ∈ Finset.Icc 1 M,
          (∫ t : unitInterval, Real.cos (2 * Real.pi * (m : ℝ) * (t : ℝ)) *
            Real.cos (2 * Real.pi * (k : ℝ) * ((t : ℝ) - a)) ∂(volume)) := by
    simp +decide only [Finset.mul_sum _ _ _, mul_add, ← integral_const_mul]
    rw [ MeasureTheory.integral_add, MeasureTheory.integral_finsetSum ]
    · grind
    · intro i hi
      refine Continuous.integrable_of_hasCompactSupport ?_ ?_
      · fun_prop
      · rw [ hasCompactSupport_iff_eventuallyEq ]
        norm_num [ Filter.EventuallyEq ]
    · exact Continuous.integrable_of_hasCompactSupport
        (by exact Continuous.mul (Real.continuous_cos.comp <| by continuity) continuous_const)
        (by exact HasCompactSupport.of_compactSpace _)
    · refine Continuous.integrable_of_hasCompactSupport ?_ ?_
      · fun_prop
      · rw [ hasCompactSupport_iff_eventuallyEq ]
        norm_num [ Filter.EventuallyEq ]
  have hconst : (∫ t : unitInterval, Real.cos (2 * Real.pi * (m : ℝ) * (t : ℝ)) ∂(volume))
      = (if m = 0 then (1 : ℝ) else 0) := by
    have := base_cos_shift_integral m 0
    simpa using this
  simp only [dirichletKernel]
  rw [h_split, hconst]
  rw [Finset.sum_congr rfl (fun k hk => cos_mul_cos_shift_integral m k a)]
  by_cases hm0 : m = 0
  · subst hm0
    rw [Finset.sum_eq_zero (fun x hx => ?_)]
    · simp
    · rw [Finset.mem_Icc] at hx
      rw [if_neg (by omega), if_neg (by omega)]
      simp
  · rw [if_neg hm0]
    rcases lt_or_gt_of_ne hm0 with hneg | hpos
    · -- m < 0: the term k = m.natAbs contributes via `m = -k`
      rw [Finset.sum_eq_single m.natAbs]
      · rw [if_neg (by omega), if_pos (by omega)]
        have hcast : ((m.natAbs : ℝ)) = -(m : ℝ) := by
          have hk : (m.natAbs : ℤ) = -m := by omega
          have h2 := congrArg (fun z : ℤ => (z : ℝ)) hk
          simpa using h2
        rw [hcast, show (2 * Real.pi * -(m:ℝ) * a) = -(2 * Real.pi * (m:ℝ) * a) by ring,
          Real.cos_neg]
        ring
      · intro x hx hxne
        rw [Finset.mem_Icc] at hx
        rw [if_neg (by omega), if_neg (by omega)]
        simp
      · intro hnot
        exfalso; apply hnot; rw [Finset.mem_Icc]
        exact ⟨by omega, le_trans (by omega) hm⟩
    · -- m > 0: the term k = m.toNat contributes via `m = k`
      rw [Finset.sum_eq_single m.toNat]
      · rw [if_pos (by omega), if_neg (by omega)]
        have hcast : ((m.toNat : ℝ)) = (m : ℝ) := by
          have hk : (m.toNat : ℤ) = m := Int.toNat_of_nonneg (by omega)
          exact_mod_cast hk
        rw [hcast]; ring
      · intro x hx hxne
        rw [Finset.mem_Icc] at hx
        rw [if_neg (by omega), if_neg (by omega)]
        simp
      · intro hnot
        exfalso; apply hnot; rw [Finset.mem_Icc]
        refine ⟨by omega, ?_⟩
        have hmt : m.toNat = m.natAbs := by omega
        rw [hmt]; exact le_trans (by omega) hm

open scoped Classical in
/-- Reproducing property of the Dirichlet kernel for a product of cosines with integer
frequencies `g i`, provided the sum of the absolute frequencies is at most `M`. -/
theorem prod_cos_dirichlet_repro (M : ℕ) (a : ℝ) {ι : Type*}
    (A : Finset ι) (g : ι → ℤ) (hM : ∑ i ∈ A, (g i).natAbs ≤ M) :
    ∫ t : unitInterval, (∏ i ∈ A, Real.cos (2 * Real.pi * (g i : ℝ) * (t : ℝ))) *
        dirichletKernel M ((t : ℝ) - a) ∂(volume) =
      ∏ i ∈ A, Real.cos (2 * Real.pi * (g i : ℝ) * a) := by
  -- Apply the product-to-sum expansion to the integrand.
  have h_prod_to_sum : (∫ t : unitInterval,
      (∏ i ∈ A, Real.cos (2 * Real.pi * (g i) * (t : ℝ))) *
        dirichletKernel M ((t : ℝ) - a) ∂(volume)) =
    (2 ^ A.card : ℝ)⁻¹ * (∑ B ∈ A.powerset, ∫ t : unitInterval,
      (Real.cos (2 * Real.pi * (∑ i ∈ B, g i - ∑ i ∈ A \ B, g i) * (t : ℝ))) *
        dirichletKernel M ((t : ℝ) - a) ∂(volume)) := by
      rw [ ← MeasureTheory.integral_finsetSum ]
      · rw [ ← MeasureTheory.integral_const_mul ]
        congr with t
        rw [ dirichlet_prod_cos_expand ]
        simp +decide [ mul_sub, mul_comm, mul_left_comm, Finset.mul_sum _ _ _ ]
      · intro B hB
        apply_rules [Continuous.integrable_of_hasCompactSupport, Continuous.mul]
          <;> norm_num [dirichletKernel_continuous]
        · fun_prop (disch := norm_num)
        · exact dirichletKernel_continuous M |> Continuous.comp <| by continuity
        · rw [ hasCompactSupport_iff_eventuallyEq ]
          simp +decide [ Filter.EventuallyEq ]
  -- Apply the reproducing property of the Dirichlet kernel to each term in the sum.
  have h_reproducing : ∀ B ∈ A.powerset, (∫ t : unitInterval,
      (Real.cos (2 * Real.pi * (∑ i ∈ B, g i - ∑ i ∈ A \ B, g i) * (t : ℝ))) *
        dirichletKernel M ((t : ℝ) - a) ∂(volume)) =
    (Real.cos (2 * Real.pi * (∑ i ∈ B, g i - ∑ i ∈ A \ B, g i) * a)) := by
      intro B hB
      have h_freq_bound : Int.natAbs (∑ i ∈ B, g i - ∑ i ∈ A \ B, g i) ≤ M := by
        refine le_trans ?_ hM
        rw [ ← Finset.sum_sdiff ( Finset.mem_powerset.mp hB ) ]
        cases abs_cases (∑ i ∈ B, g i - ∑ i ∈ A \ B, g i) <;>
          cases abs_cases (∑ i ∈ B, g i) <;>
          cases abs_cases (∑ i ∈ A \ B, g i) <;>
          linarith [abs_le.mp (Finset.abs_sum_le_sum_abs (fun i => g i) B),
            abs_le.mp (Finset.abs_sum_le_sum_abs (fun i => g i) (A \ B))]
      exact dirichlet_cos_repro M (∑ i ∈ B, g i - ∑ i ∈ A \ B, g i) a
        h_freq_bound |> fun h => by simpa using h
  rw [ h_prod_to_sum, Finset.sum_congr rfl h_reproducing ]
  convert dirichlet_prod_cos_expand A ( fun i => 2 * Real.pi * ( g i : ℝ ) * a ) |> Eq.symm using 1
  simp +decide [ mul_sub, sub_mul, Finset.mul_sum _ _ _, Finset.sum_mul ]

/-- The reproducing continuous window built from a discrete window `ψ` on the grid of `N`
equally spaced points, using a Dirichlet kernel of degree `M`. -/
noncomputable def reproWindow (N M : ℕ) (ψ : ℕ → ℝ) (t : ℝ) : ℝ :=
  (1 / (N : ℝ)) * ∑ y ∈ Finset.range N, ψ y * dirichletKernel M (t - (y : ℝ) / (N : ℝ))

/-- The reproducing window is continuous. -/
lemma reproWindow_continuous (N M : ℕ) (ψ : ℕ → ℝ) : Continuous (reproWindow N M ψ) := by
  unfold reproWindow
  refine continuous_const.mul (continuous_finsetSum _ fun y _ => ?_)
  exact continuous_const.mul ((dirichletKernel_continuous _).comp (by fun_prop))

open scoped Classical in
/-- **Exact windowed quadrature.** Integrating a product of cosines (with total absolute frequency
at most `M`) against the reproducing window reproduces exactly the corresponding windowed Riemann
sum over the grid of `N` equally spaced points. -/
theorem prod_cos_reproWindow (N M : ℕ) (ψ : ℕ → ℝ) {ι : Type*}
    (A : Finset ι) (g : ι → ℤ) (hM : ∑ i ∈ A, (g i).natAbs ≤ M) :
    ∫ t : unitInterval, (∏ i ∈ A, Real.cos (2 * Real.pi * (g i : ℝ) * (t : ℝ))) *
        reproWindow N M ψ (t : ℝ) ∂(volume) =
      (1 / (N : ℝ)) * ∑ y ∈ Finset.range N,
        ψ y * ∏ i ∈ A, Real.cos (2 * Real.pi * (g i : ℝ) * ((y : ℝ) / (N : ℝ))) := by
  -- Use the linearity of the integral and the definition of `reproWindow`.
  have h_integral : ∫ t : unitInterval,
      (∏ i ∈ A, (Real.cos (2 * Real.pi * (g i : ℝ) * t))) *
        (reproWindow N M ψ t) ∂volume =
      (1 / N : ℝ) * ∑ y ∈ Finset.range N, ψ y * ∫ t : unitInterval,
        (∏ i ∈ A, (Real.cos (2 * Real.pi * (g i : ℝ) * t))) *
          dirichletKernel M (t - (y : ℝ) / N) ∂volume := by
                   simp +decide only [reproWindow, Finset.mul_sum _ _ _, ← integral_const_mul]
                   rw [ MeasureTheory.integral_finsetSum ]
                   · exact Finset.sum_congr rfl fun _ _ => by congr; ext; ring
                   · intro y hy; apply_rules [ Continuous.integrable_of_hasCompactSupport ]
                     · ring_nf
                       refine Continuous.mul ?_ ?_
                       · fun_prop
                       · exact dirichletKernel_continuous M |> Continuous.comp <| by continuity
                     · rw [ hasCompactSupport_iff_eventuallyEq ]
                       simp +decide [ Filter.EventuallyEq ]
  exact h_integral.trans (by
    congr; ext y
    exact prod_cos_dirichlet_repro M (y / N) A g hM ▸ by rfl)

/-!
## Task 6: bridging the exact quadrature to the Haar integral over `X`

The exact Dirichlet quadrature above computes a continuous integral of a trigonometric
polynomial as an exact discrete average over a finite grid. We now re-verify that this exact
quadrature is *isomorphic to the Haar integral over the profinite space* `X` from
`ProfiniteRKHS.lean`: for a character (and hence, by linearity, any trigonometric polynomial)
depending only on the coordinates of a finite window `I`, its integral against the normalized
Haar measure `haarProb` equals its discrete average over the finite grid
`∏_{i ∈ I} ℤ/pᵢℤ`.  By the Chinese Remainder Theorem this finite grid is isomorphic to
`ℤ/qℤ`, with `q = ∏_{i ∈ I} pᵢ` the primorial modulus (e.g. `q = q n`, `|I| = w n` for the
`n`-th window), so this is exactly the discrete average over `ℤ/q(n)ℤ`.
-/

open MeasureTheory
open scoped BigOperators

/-- Embedding of a finite grid point (a tuple over the coordinates in the window `s`) into the
profinite ambient space `X`, extending by `0` outside the window. -/
noncomputable def gridEmbed (s : Finset ℕ) (z : (i : s) → ZMod (globalPrime i)) : X :=
  fun j => if h : j ∈ s then z ⟨j, h⟩ else 0

lemma gridEmbed_apply_mem (s : Finset ℕ) (z : (i : s) → ZMod (globalPrime i))
    {j : ℕ} (hj : j ∈ s) : gridEmbed s z j = z ⟨j, hj⟩ := by
  simp [gridEmbed, hj]

/-
The uniform measure of a singleton in a finite cyclic factor is `1 / pᵢ`.
-/
lemma unifMeasure_real_singleton (i : ℕ) (z : ZMod (globalPrime i)) :
    (unifMeasure i).real {z} = ((globalPrime i : ℝ))⁻¹ := by
  unfold unifMeasure
  rw [ MeasureTheory.measureReal_def ] ; norm_num [PMF.uniformOfFintype_apply]

/-
For a family of finite measures on finite spaces with measurable singletons, the product
measure of a singleton is the product of the singleton masses.
-/
lemma measureReal_pi_singleton {ι : Type*} [Fintype ι] {α : ι → Type*}
    [∀ i, MeasurableSpace (α i)] [∀ i, MeasurableSingletonClass (α i)]
    (ν : (i : ι) → Measure (α i)) [∀ i, IsFiniteMeasure (ν i)]
    (z : (i : ι) → α i) :
    (Measure.pi ν).real {z} = ∏ i, (ν i).real {z i} := by
  rw [ MeasureTheory.measureReal_def, show { z } = Set.pi Set.univ fun i => { z i } by
    ext
    simp +decide [ funext_iff ], MeasureTheory.Measure.pi_pi ]
  norm_num [ MeasureTheory.measureReal_def ]

/-
A character supported on the finite window `I` factors through the finite grid: its value
at `x` depends only on the coordinates in `I`, so it agrees with its value at the grid point
obtained by restricting `x` to `I` and extending by `0`.
-/
lemma charFun_gridEmbed_restrict (s : Finset ℕ) (k : ℕ →₀ ℤ) (hk : k.support ⊆ s) (x : X) :
    charFun k (gridEmbed s (s.restrict x)) = charFun k x := by
  refine Finset.prod_congr rfl fun i hi => ?_
  rw [ gridEmbed_apply_mem s _ ( hk hi ) ] ; rfl

/-
**Task 6 (Haar integral = discrete grid average).**
For a character `charFun k` supported on the finite window `I`, its Haar integral over the
profinite space `X` equals its exact discrete average over the finite grid
`∏_{i ∈ I} ℤ/pᵢℤ` with primorial modulus `q = ∏_{i ∈ I} pᵢ`.
-/
theorem charFun_haar_integral_eq_gridAverage (s : Finset ℕ) (k : ℕ →₀ ℤ) (hk : k.support ⊆ s) :
    ∫ x, charFun k x ∂haarProb
      = (((∏ i ∈ s, globalPrime i : ℕ)) : ℂ)⁻¹ *
          ∑ z : (i : s) → ZMod (globalPrime i), charFun k (gridEmbed s z) := by
  -- By definition of `haarProb`, we know that it is the product measure of the uniform measures
  -- on each `ZMod (globalPrime i)`.
  have h_haar_prob : haarProb.map (s.restrict) = Measure.pi (fun i : s => unifMeasure i) := by
    unfold haarProb
    exact MeasureTheory.Measure.infinitePi_map_restrict unifMeasure
  have h_integral_eq : ∫ x, charFun k x ∂haarProb =
      ∫ z, charFun k (gridEmbed s z) ∂(Measure.pi (fun i : s => unifMeasure i)) := by
    rw [ ← h_haar_prob, MeasureTheory.integral_map ]
    · exact congr_arg _ ( funext fun x => charFun_gridEmbed_restrict s k hk x ▸ rfl )
    · fun_prop
    · refine Continuous.aestronglyMeasurable ?_
      exact charFun_continuous k |> Continuous.comp <| by
        exact continuous_pi_iff.mpr fun i => by unfold gridEmbed; split_ifs <;> continuity
  rw [ h_integral_eq, MeasureTheory.integral_fintype ]
  · rw [ Finset.mul_sum _ _ _ ] ; congr ; ext ; rw [ measureReal_pi_singleton ]
    norm_num [ unifMeasure_real_singleton ] ; ring_nf
    exact Or.inl <| by conv_rhs => rw [ ← Finset.prod_attach ]
  · refine Continuous.integrable_of_hasCompactSupport ?_ ?_
    · refine continuous_finsetProd _ fun i hi => ?_
      fun_prop
    · rw [ hasCompactSupport_iff_eventuallyEq ]
      simp +decide [ Filter.EventuallyEq ]

/-
**Task 6 (trigonometric-polynomial version).**
By linearity, the Haar integral over `X` of any trigonometric polynomial supported on the
window `I` equals its exact discrete average over the finite grid `∏_{i ∈ I} ℤ/pᵢℤ`.
-/
theorem trigPoly_haar_integral_eq_gridAverage (s : Finset ℕ) (S : Finset (ℕ →₀ ℤ))
    (c : (ℕ →₀ ℤ) → ℂ) (hS : ∀ k ∈ S, k.support ⊆ s) :
    ∫ x, (∑ k ∈ S, c k * charFun k x) ∂haarProb
      = (((∏ i ∈ s, globalPrime i : ℕ)) : ℂ)⁻¹ *
          ∑ z : (i : s) → ZMod (globalPrime i), (∑ k ∈ S, c k * charFun k (gridEmbed s z)) := by
  rw [ MeasureTheory.integral_finsetSum ]
  · simp +decide only [integral_const_mul]
    rw [ Finset.sum_congr rfl fun k hk => by
      rw [ charFun_haar_integral_eq_gridAverage s k ( hS k hk ) ] ]
    simp +decide only [Finset.mul_sum _ _ _, mul_left_comm]
    exact Finset.sum_comm
  · intro k hk
    refine MeasureTheory.Integrable.const_mul ?_ _
    exact MeasureTheory.MemLp.integrable one_le_two ( charFun_memLp k )

end KrafftSieve
