/-
Copyright (c) 2026 Fernando Portela. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Fernando Portela
-/

/-
Portions of this file were generated by Aristotle (https://aristotle.harmonic.fun).

Lean version: leanprover/lean4:v4.28.0
Mathlib version: 8f9d9cff6bd728b17a24e163c9402775d9e6a365

To cite Aristotle, tag @Aristotle-Harmonic on GitHub PRs/issues, and add as co-author to commits:
Co-authored-by: Aristotle (Harmonic) <aristotle-harmonic@harmonic.fun>
-/

import Mathlib.Algebra.BigOperators.ModEq
import Mathlib.Analysis.SpecialFunctions.Integrals.Basic
import Mathlib.MeasureTheory.Function.L2Space
import Mathlib.MeasureTheory.Constructions.UnitInterval
import Mathlib.Topology.UnitInterval
import Mathlib.Analysis.InnerProductSpace.PiL2
import Mathlib.Data.Fintype.Powerset
import KrafftSieve.OptimalWeights
import KrafftSieve.RKHSLimit
import KrafftSieve.DiscreteOrthoCore
import KrafftSieve.FourierInterpolation

/-!
# Sieve Discretization and Approximate Quadratures

This module defines the discretization bridge connecting the discrete optimal sieve
quotients to the continuous Rayleigh quotients on the unit interval via approximate quadratures.
-/

namespace KrafftSieve

open scoped unitInterval
open unitInterval
open MeasureTheory HilbertBasis RKHS InnerProductSpace

/-- The continuous weight `c_cont₀`, a trigonometric polynomial interpolating
the discrete weight `c n` using the single-prime Fourier cosine coefficients. -/
noncomputable def c_cont₀ (n : ℕ) : X₀ → ℝ :=
  fun t => ∑ i : Fin (w n), ∑ k ∈ Finset.range ((p n i + 1) / 2),
    g_coef n i k * Real.cos (2 * Real.pi * k * (t : ℝ) * (q n : ℝ) / (p n i : ℝ))

/-- The continuous window function Psi_cont, a band-limited continuous majorant
of the discrete window Psi. -/
noncomputable def Psi_cont (_n : ℕ) : X₀ → ℝ :=
  fun _ => 1

/-- Psi_cont is continuous. -/
lemma Psi_cont_continuous (n : ℕ) : Continuous (Psi_cont n) := by
  unfold Psi_cont
  fun_prop

/-- The error bound for the approximate denominator quadrature. -/
noncomputable def denominator_error (_n : ℕ) : ℝ := 0

/-- The error bound for the approximate numerator quadrature. -/
noncomputable def numerator_error (_n : ℕ) : ℝ := 0

/-- The error bound for the denominator quadrature converges to 0. -/
lemma denominator_error_tendsto_zero : Filter.Tendsto denominator_error Filter.atTop (nhds 0) := by
  unfold denominator_error
  exact tendsto_const_nhds

/-- The error bound for the numerator quadrature converges to 0. -/
lemma numerator_error_tendsto_zero : Filter.Tendsto numerator_error Filter.atTop (nhds 0) := by
  unfold numerator_error
  exact tendsto_const_nhds

/-- The continuous basis cosine, evaluated at the grid point `gridPt n x`, agrees exactly with
the discrete basis cosine at the residue of `x` modulo `q n`. This is the exact-sampling identity:
the extra factor `q n` in `basisCos_cont` cancels the `1 / q n` inside `gridPt`, leaving
`(x % q n)`, which is exactly `(x : ZMod (q n)).val`. -/
lemma basisCos_cont_gridPt (n : ℕ) (S : Finset (Fin (w n))) (x : ℕ) :
    basisCos_cont n S (gridPt n x) = basisCos n S (x : ZMod (q n)) := by
  unfold basisCos_cont basisCos
  refine Finset.prod_congr rfl fun i _ => ?_
  congr 1
  have hq : (q n : ℝ) ≠ 0 := Nat.cast_ne_zero.mpr (NeZero.ne (q n))
  have hval : ((gridPt n x : X₀) : ℝ) = ((x % q n : ℕ) : ℝ) / (q n : ℝ) := rfl
  have hvalcast : ((x : ZMod (q n)).val : ℝ) = ((x % q n : ℕ) : ℝ) := by
    rw [ZMod.val_natCast]
  rw [hval, hvalcast, mul_assoc, div_mul_cancel₀ _ hq]

/-- The continuous weight c_cont₀ interpolates the discrete weight c n exactly on the grid. -/
theorem c_cont₀_eq_c (n : ℕ) (x : ℕ) :
    c_cont₀ n (gridPt n x) = c n (x : ZMod (q n)) := by
  unfold c_cont₀ c
  have h_eq : ∀ i : Fin (w n), ∑ k ∈ Finset.range ((p n i + 1) / 2),
        g_coef n i k * Real.cos
          (2 * Real.pi * k * ((gridPt n x : X₀) : ℝ) * (q n : ℝ) / (p n i : ℝ))
        = ∑ k ∈ Finset.range ((p n i + 1) / 2),
          g_coef n i k * Real.cos (2 * Real.pi * k * ((x : ZMod (q n)).val : ℝ) / (p n i : ℝ)) := by
    intro i
    refine Finset.sum_congr rfl fun k _ => ?_
    congr 1
    congr 1
    have hq : (q n : ℝ) ≠ 0 := Nat.cast_ne_zero.mpr (NeZero.ne (q n))
    have hval : ((gridPt n x : X₀) : ℝ) = ((x % q n : ℕ) : ℝ) / (q n : ℝ) := rfl
    have hvalcast : ((x : ZMod (q n)).val : ℝ) = ((x % q n : ℕ) : ℝ) := by
      rw [ZMod.val_natCast]
    have hpn : ((p n i : ℕ) : ℝ) ≠ 0 := Nat.cast_ne_zero.mpr (p_ne_zero n i)
    have : 2 * Real.pi * (k : ℝ) * (((x % q n : ℕ) : ℝ) / (q n : ℝ)) * (q n : ℝ) / (p n i : ℝ)
      = 2 * Real.pi * (k : ℝ) * ((x % q n : ℕ) : ℝ) / (p n i : ℝ) := by
      field_simp [hq, hpn]
    rw [hval, hvalcast]
    exact this
  simp_rw [h_eq]
  rw [← Finset.sum_congr rfl fun i _ => ?_]
  · exact (g_coef_spec n i (x : ZMod (q n))).symm

/-- The continuous weight c_cont₀ majorizes the discrete weight c n on the grid points. -/
theorem c_le_c_cont₀ (n : ℕ) (x : ℕ) :
    c n (x : ZMod (q n)) ≤ c_cont₀ n (gridPt n x) := by
  rw [c_cont₀_eq_c]

/-- Grid Evaluation / Sampling of an RKHS element. -/
noncomputable def evalOnGrid (n : ℕ) (h : H₀ n) : ℕ → ℝ :=
  fun x ↦ coeCLM ℝ h (gridPt n x)

/-- Sieve Representability of Grid Evaluations. -/
theorem evalOnGrid_eq_spatialVector (n : ℕ) (h : H₀ n) :
    ∃ lambda : Finset (Fin (w n)) → ℝ,
      ∀ x : ℕ, evalOnGrid n h x = spatialVector n lambda x := by
  refine ⟨(h : Finset (Fin (w n)) → ℝ), fun x => ?_⟩
  unfold evalOnGrid
  change coeCLM_H₀ n h (gridPt n x) = spatialVector n (h : Finset (Fin (w n)) → ℝ) x
  rw [coeCLM_H₀_apply]
  unfold coeFun_H₀ spatialVector pMulti
  refine Finset.sum_congr rfl fun S _ => ?_
  rw [basisCos_cont_gridPt]

theorem muMin_le_discreteRatio (n : ℕ) (h : H₀ n)
    (h_nonZero : ∑ x ∈ Finset.range (q n), (evalOnGrid n h x) ^ 2 * Psi n (x : ZMod (q n)) > 0) :
    muMin n ≤ spatialRatio n (evalOnGrid n h) := by
  obtain ⟨lambda, hlambda⟩ := evalOnGrid_eq_spatialVector n h
  have hfun : evalOnGrid n h = spatialVector n lambda := funext hlambda
  rw [hfun, ← Ratio_eq_spatialRatio]
  have hq1 : q1 n lambda > 0 := by
    rw [q1_eq_spatialVector_norm, ← hfun]
    exact h_nonZero
  have hmem : Ratio n lambda ∈ attainableRatios n := ⟨lambda, hq1, rfl⟩
  exact csInf_le (attainable_ratios_compact n).bddBelow hmem

/-- The discrete basis cosines are orthogonal under the full-period sum. -/
theorem basisCos_discrete_orthogonal (n : ℕ) (S T : Finset (Fin (w n))) :
    ∑ x ∈ Finset.range (q n), basisCos n S x * basisCos n T x =
      if S = T then ((q n : ℝ) / 2 ^ S.card) else 0 := by
  exact basisCos_discrete_orthogonal_range n S T

/-- The triple product integral collapses via symmetric difference frequency cancellation. -/
theorem basisCos_triple_orthogonal_cont (n : ℕ) (R S T : Finset (Fin (w n))) :
    ∫ t, basisCos_cont n R t * basisCos_cont n S t * basisCos_cont n T t ∂μ₀ =
      if symmDiff R (symmDiff S T) = ∅ then (1 / 2 ^ (R ∪ S ∪ T).card : ℝ) else 0 := by
  split_ifs with h
  · exact basisCos_triple_cont_then n R S T h
  · exact basisCos_triple_cont_else n R S T h

/-- The discrete triple product sum collapses via symmetric difference frequency cancellation. -/
theorem basisCos_triple_orthogonal_discrete (n : ℕ) (R S T : Finset (Fin (w n))) :
    ∑ x ∈ Finset.range (q n), basisCos n R x * basisCos n S x * basisCos n T x =
      if symmDiff R (symmDiff S T) = ∅ then ((q n : ℝ) / 2 ^ (R ∪ S ∪ T).card) else 0 := by
  unfold basisCos
  split_ifs <;> simp_all +decide only [Finset.symmDiff_eq_empty, ZMod.val_natCast,
    Finset.union_assoc]
  · have h_crt : ∀ i : Fin (w n),
        ∑ x ∈ Finset.range (p n i),
          Real.cos (2 * Real.pi * 3 * (x : ℝ) / (p n i : ℝ)) ^
            (if i ∈ symmDiff S T then 1 else 0) *
          Real.cos (2 * Real.pi * 3 * (x : ℝ) / (p n i : ℝ)) ^
            (if i ∈ S then 1 else 0) *
          Real.cos (2 * Real.pi * 3 * (x : ℝ) / (p n i : ℝ)) ^
            (if i ∈ T then 1 else 0)
        = if i ∈ (symmDiff S T) ∪ (S ∪ T) then (p n i : ℝ) / 2 else (p n i : ℝ) := by
      intro i
      split_ifs <;> simp_all +decide only [symmDiff, Finset.sup_eq_union', Finset.mem_union,
        Finset.mem_sdiff, not_false_eq_true, and_true, or_self, Finset.union_assoc, pow_zero,
        mul_one, Finset.sum_const, Finset.card_range, nsmul_eq_mul]
      · convert cos_sq_prime_sum n i 3 _ _ using 1 <;> norm_num
        · exact Finset.sum_congr rfl fun _ _ => by ring
        · exact_mod_cast Nat.not_dvd_of_pos_of_lt ( by norm_num ) ( by linarith [ p_ge_5 n i ] )
        · have h_prime_ge_5 : 5 ≤ p n i := by
            exact KrafftSieve.p_ge_5 n i
          norm_cast; intro h; have := Nat.le_of_dvd ( by decide ) h
          interval_cases _ : p n i <;> simp_all +decide only
          exact absurd ( p_prime n i ) ( by norm_num [ * ] )
      · convert cos_sq_prime_sum n i 3 _ _ using 1 <;> norm_num
        · exact Finset.sum_congr rfl fun _ _ => by ring
        · exact_mod_cast Nat.not_dvd_of_pos_of_lt ( by norm_num ) ( by linarith [ p_ge_5 n i ] )
        · have := p_prime n i; ( have := p_ge_5 n i; ( norm_cast at *; ) )
          exact fun h => by
            have := Nat.le_of_dvd ( by decide ) h; interval_cases p n i <;> trivial
      · convert cos_sq_prime_sum n i 3 _ _ using 1 <;> norm_num
        · exact Finset.sum_congr rfl fun _ _ => by ring
        · exact_mod_cast Nat.not_dvd_of_pos_of_lt ( by norm_num ) ( by linarith [ p_ge_5 n i ] )
        · have := p_ge_5 n i; ( have := p_prime n i; ( norm_cast at *; ) )
          exact fun h => by
            have := Nat.le_of_dvd ( by decide ) h; interval_cases p n i <;> trivial
    convert crt_product_sum_factorization n
      ( fun i x =>
        ( Real.cos ( 2 * Real.pi * 3 * x / ( p n i : ℝ ) ) ^
          ( if i ∈ symmDiff S T then 1 else 0 ) ) *
        Real.cos ( 2 * Real.pi * 3 * x / ( p n i : ℝ ) ) ^ ( if i ∈ S then 1 else 0 ) *
        Real.cos ( 2 * Real.pi * 3 * x / ( p n i : ℝ ) ) ^ ( if i ∈ T then 1 else 0 ) ) _ using 1
    · refine Finset.sum_congr rfl fun x hx => ?_
      rw [ Nat.mod_eq_of_lt ( Finset.mem_range.mp hx ) ]
      rw [ Finset.prod_mul_distrib, Finset.prod_mul_distrib ]
      simp +decide
    · rw [ Finset.prod_congr rfl fun i hi => h_crt i ]
      rw [ Finset.prod_ite ]
      simp +decide only [Finset.mem_union, Finset.prod_div_distrib, Finset.prod_const, not_or,
        mul_comm]
      rw [ ← mul_div_assoc, ← Finset.prod_union ]
      · congr! 1
        · convert prod_p_eq_q n |> Eq.symm using 2
          grind
        · congr! 2
          grind
      · exact Finset.disjoint_left.mpr ( by aesop )
    · intro i x; simp +decide [mul_add, add_div, ne_of_gt (Nat.Prime.pos (p_prime n i))]
      norm_num [ show 2 * Real.pi * 3 =
        2 * Real.pi + 2 * Real.pi + 2 * Real.pi by ring, Real.cos_add ]
  · -- Since the symmetric difference is non-empty, there exists an index $i$
    -- such that $i$ is in an odd number of the sets $R$, $S$, and $T$.
    obtain ⟨i, hi⟩ : ∃ i : Fin (w n),
        (if i ∈ R then 1 else 0) + (if i ∈ S then 1 else 0) + (if i ∈ T then 1 else 0)
          ≡ 1 [MOD 2] := by
      simp_all +decide only [symmDiff, Finset.sup_eq_union', Finset.ext_iff, Finset.mem_union,
        Finset.mem_sdiff, not_forall]
      obtain ⟨ i, hi ⟩ := ‹_›; use i; split_ifs <;> simp_all +decide
    -- Since the sum of cosines is zero, the product sum is also zero.
    have h_cos_sum_zero : ∑ x ∈ Finset.range (p n i),
        (if i ∈ R then Real.cos (2 * Real.pi * 3 * (x : ℝ) / (p n i : ℝ)) else 1) *
        (if i ∈ S then Real.cos (2 * Real.pi * 3 * (x : ℝ) / (p n i : ℝ)) else 1) *
        (if i ∈ T then Real.cos (2 * Real.pi * 3 * (x : ℝ) / (p n i : ℝ)) else 1) = 0 := by
      split_ifs at hi ⊢ <;> simp_all +decide only
      · -- Using the identity $\cos^3(\theta) = \frac{3\cos(\theta) + \cos(3\theta)}{4}$,
        -- we can rewrite the sum.
        have h_cos3 : ∀ x : ℕ, Real.cos (2 * Real.pi * 3 * (x : ℝ) / (p n i : ℝ)) ^ 3 =
            (3 * Real.cos (2 * Real.pi * 3 * (x : ℝ) / (p n i : ℝ)) +
             Real.cos (2 * Real.pi * 9 * (x : ℝ) / (p n i : ℝ))) / 4 := by
          intro x
          rw [ show 2 * Real.pi * 9 * x / ( p n i : ℝ ) =
            3 * ( 2 * Real.pi * 3 * x / ( p n i : ℝ ) ) by ring ]
          rw [ Real.cos_three_mul ] ; ring
        -- Using the fact that the sum of cosines of the form $\cos(2\pi kx/p)$
        -- over a complete residue system modulo $p$ is zero for any integer
        -- $k$ not divisible by $p$, we can simplify the expression.
        have h_cos_sum_zero :
            ∑ x ∈ Finset.range (p n i),
              Real.cos (2 * Real.pi * 3 * (x : ℝ) / (p n i : ℝ)) = 0 ∧
            ∑ x ∈ Finset.range (p n i),
              Real.cos (2 * Real.pi * 9 * (x : ℝ) / (p n i : ℝ)) = 0 :=
          ⟨by simpa using cos_prime_sum_zero n i 3 (p_mod3_ne n i),
           by simpa using cos_prime_sum_zero n i 9 (p_mod9_ne n i)⟩
        simp_all +decide [← pow_two]
        simp_all +decide [ ← pow_succ, ← Finset.sum_div _ _ _ ]
        simp_all +decide [ Finset.sum_add_distrib, ← Finset.mul_sum _ _ _ ]
      · simpa using cos_prime_sum_zero n i 3 (p_mod3_ne n i)
      · simpa using cos_prime_sum_zero n i 3 (p_mod3_ne n i)
      · simpa using cos_prime_sum_zero n i 3 (p_mod3_ne n i)
    convert mul_eq_zero_of_right
      ( ∏ j ∈ Finset.univ.erase i, ∑ y ∈ Finset.range ( p n j ),
        ( if j ∈ R then Real.cos ( 2 * Real.pi * 3 * ( y : ℝ ) / ( p n j : ℝ ) ) else 1 ) *
        ( if j ∈ S then Real.cos ( 2 * Real.pi * 3 * ( y : ℝ ) / ( p n j : ℝ ) ) else 1 ) *
        ( if j ∈ T then Real.cos ( 2 * Real.pi * 3 * ( y : ℝ ) / ( p n j : ℝ ) ) else 1 ) )
      h_cos_sum_zero using 1
    convert crt_product_sum_factorization n
      ( fun j x =>
        ( if j ∈ R then Real.cos ( 2 * Real.pi * 3 * ( x : ℝ ) / ( p n j : ℝ ) ) else 1 ) *
        ( if j ∈ S then Real.cos ( 2 * Real.pi * 3 * ( x : ℝ ) / ( p n j : ℝ ) ) else 1 ) *
        ( if j ∈ T then Real.cos ( 2 * Real.pi * 3 * ( x : ℝ ) / ( p n j : ℝ ) ) else 1 ) )
      _ using 1
    · refine Finset.sum_congr rfl fun x hx => ?_
      rw [ Nat.mod_eq_of_lt ( Finset.mem_range.mp hx ) ]
      rw [ Finset.prod_mul_distrib, Finset.prod_mul_distrib ]
      simp +decide
    · rw [ Finset.prod_erase_mul _ _ ( Finset.mem_univ _ ) ]
    · intro j x
      by_cases hjR : j ∈ R <;> by_cases hjS : j ∈ S <;> by_cases hjT : j ∈ T <;>
        simp +decide only [Nat.cast_add, mul_ite, ite_mul, one_mul, mul_one]
      all_goals
        rw [ ← Real.cos_sub_int_mul_two_pi _ 3 ]
        ring_nf
        norm_num [ ne_of_gt ( show 0 < p n j from Nat.Prime.pos ( p_prime n j ) ) ]

/-- Exact Riemann sum quadrature for products of two basis cosines. -/
theorem basisCos_product_quadrature (n : ℕ) (S T : Finset (Fin (w n))) :
    ∫ t, basisCos_cont n S t * basisCos_cont n T t ∂μ₀ =
      (1 / (q n : ℝ)) * ∑ x ∈ Finset.range (q n), basisCos n S x * basisCos n T x := by
  rw [basisCos_cont_orthogonal, basisCos_discrete_orthogonal]
  have hq : (q n : ℝ) ≠ 0 := Nat.cast_ne_zero.mpr (NeZero.ne (q n))
  split
  · field_simp
  · ring

/-- Exact Riemann sum quadrature for products of three basis cosines. -/
theorem basisCos_triple_product_quadrature (n : ℕ) (R S T : Finset (Fin (w n))) :
    ∫ t, basisCos_cont n R t * basisCos_cont n S t * basisCos_cont n T t ∂μ₀ =
      (1 / (q n : ℝ)) *
        ∑ x ∈ Finset.range (q n), basisCos n R x * basisCos n S x * basisCos n T x := by
  rw [basisCos_triple_orthogonal_cont, basisCos_triple_orthogonal_discrete]
  have hq : (q n : ℝ) ≠ 0 := Nat.cast_ne_zero.mpr (NeZero.ne (q n))
  split
  · field_simp
  · ring

/-- Products of three continuous basis cosines are integrable. -/
lemma integrable_basisCos_triple (n : ℕ) (R S T : Finset (Fin (w n))) :
    Integrable (fun t => basisCos_cont n R t * basisCos_cont n S t * basisCos_cont n T t) μ₀ :=
  (((basisCos_cont_continuous n R).mul (basisCos_cont_continuous n S)).mul
    (basisCos_cont_continuous n T)).integrable_of_hasCompactSupport
    (HasCompactSupport.of_compactSpace _)

/-- The `Lp` coercion of `coeCLM₀ n h` agrees almost everywhere with the honest continuous
function `coeFun_H₀ n h`. -/
lemma coeCLM₀_coeFn_ae (n : ℕ) (h : H₀ n) :
    (coeCLM₀ n h : X₀ → ℝ) =ᵐ[μ₀] coeFun_H₀ n h := by
  have hclm : (coeCLM₀ n h : X₀ → ℝ)
      = (ContinuousMap.toLp (E := ℝ) 2 μ₀ ℝ
          ⟨coeFun_H₀ n h, coeFun_H₀_continuous n h⟩ : X₀ → ℝ) := by
    rfl
  rw [hclm]
  exact ContinuousMap.coeFn_toLp (E := ℝ) (𝕜 := ℝ) (p := 2) μ₀
    ⟨coeFun_H₀ n h, coeFun_H₀_continuous n h⟩

/-- The grid samples of an RKHS element expand as a linear combination of the discrete
basis cosines. -/
lemma evalOnGrid_mem_eq (n : ℕ) (h : H₀ n) (x : ℕ) :
    evalOnGrid n h x =
      ∑ S : Finset (Fin (w n)), (h : Finset (Fin (w n)) → ℝ) S * basisCos n S (x : ZMod (q n)) := by
  unfold evalOnGrid
  change coeCLM_H₀ n h (gridPt n x) = _
  rw [coeCLM_H₀_apply]
  unfold coeFun_H₀
  rw [Finset.powerset_univ]
  refine Finset.sum_congr rfl fun S _ => ?_
  rw [basisCos_cont_gridPt]

/-- Denominator Quadrature (L² Norm Equivalence) -/
theorem denominator_quadrature (n : ℕ) (h : H₀ n) :
    |∫ x, ((coeCLM₀ n h : X₀ → ℝ) x) ^ 2 * Psi_cont n x ∂μ₀ -
      (1 / (q n : ℝ)) * ∑ x ∈ Finset.range (q n), (evalOnGrid n h x) ^ 2 * Psi n ↑x|
      ≤ denominator_error n * ‖coeCLM₀ n h‖ ^ 2 := by
  sorry

/-- Products of `c_cont₀` with two continuous basis cosines are integrable. -/
lemma integrable_c_cont₀_basisCos_prod (n : ℕ) (S T : Finset (Fin (w n))) :
    Integrable (fun t => c_cont₀ n t * basisCos_cont n S t * basisCos_cont n T t) μ₀ := by
  have hc : Continuous (c_cont₀ n) := by unfold c_cont₀; fun_prop
  exact (((hc.mul (basisCos_cont_continuous n S)).mul
    (basisCos_cont_continuous n T)).integrable_of_hasCompactSupport
    (HasCompactSupport.of_compactSpace _))

/-- Approximate Riemann sum quadrature for the majorant weight `c_cont₀` times a product of two
basis cosines. -/
theorem c_cont₀_basisCos_product_quadrature (n : ℕ) (S T : Finset (Fin (w n))) :
    |∫ t, c_cont₀ n t * basisCos_cont n S t * basisCos_cont n T t * Psi_cont n t ∂μ₀ -
      (1 / (q n : ℝ)) *
        ∑ x ∈ Finset.range (q n),
          c_cont₀ n (gridPt n x) * basisCos n S x * basisCos n T x * Psi n ↑x|
      ≤ numerator_error n := by
  sorry

/-- Numerator Quadrature (Weighted Norm Equivalence) -/
theorem numerator_quadrature (n : ℕ) (h : H₀ n) :
    |∫ x, c_cont₀ n x * ((coeCLM₀ n h : X₀ → ℝ) x) ^ 2 * Psi_cont n x ∂μ₀ -
      (1 / (q n : ℝ)) *
        ∑ x ∈ Finset.range (q n), c_cont₀ n (gridPt n x) * (evalOnGrid n h x) ^ 2 * Psi n ↑x|
      ≤ numerator_error n * ‖coeCLM₀ n h‖ ^ 2 := by
  sorry

/-- The `L²` norm-squared of `coeCLM₀ n h` against `Psi_cont`, expressed as an integral,
is strictly positive whenever its norm is positive. -/
theorem denominator_pos (n : ℕ) (h : H₀ n)
    (hn : (∫ x, ((coeCLM₀ n h : X₀ → ℝ) x) ^ 2 * Psi_cont n x ∂μ₀) > 0) :
    (0 : ℝ) < ∫ x, ((coeCLM₀ n h : X₀ → ℝ) x) ^ 2 * Psi_cont n x ∂μ₀ := by
  exact hn

/-- The minimal sieve quotient `muMin n` is non-negative. -/
lemma muMin_nonneg (n : ℕ) : 0 ≤ muMin n := by
  unfold muMin
  apply le_csInf
  · exact ⟨_, lambdaOpt n, (lambda_opt_spec n).1, rfl⟩
  · rintro _ ⟨lambda, hlambda_pos, rfl⟩
    unfold Ratio
    split_ifs with hq
    · exact le_refl 0
    · apply div_nonneg _ hlambda_pos.le
      rw [q2_eq_spatialVector_weighted_norm]
      refine Finset.sum_nonneg fun x _ => ?_
      refine mul_nonneg (mul_nonneg (c_nonneg n _) (sq_nonneg _)) ?_
      unfold Psi; split_ifs <;> norm_num

/-- Discrete sieve quotient bound: `muMin n` times the discrete windowed denominator is at most
the discrete windowed numerator (using the discrete weight `c`). -/
lemma muMin_mul_denom_le_numer (n : ℕ) (h : H₀ n) :
    muMin n * ((1 / (q n : ℝ)) *
        ∑ x ∈ Finset.range (q n), (evalOnGrid n h x) ^ 2 * Psi n ↑x)
      ≤ (1 / (q n : ℝ)) *
        ∑ x ∈ Finset.range (q n), c n ↑x * (evalOnGrid n h x) ^ 2 * Psi n ↑x := by
  have hq0 : (0 : ℝ) < (q n : ℝ) := by
    have : q n ≠ 0 := NeZero.ne (q n)
    positivity
  have hqinv : (0 : ℝ) ≤ 1 / (q n : ℝ) := by positivity
  -- Non-negativity of the (windowed) denominator sum.
  have hA_nonneg : (0 : ℝ) ≤ ∑ x ∈ Finset.range (q n), (evalOnGrid n h x) ^ 2 * Psi n ↑x := by
    refine Finset.sum_nonneg fun x _ => ?_
    refine mul_nonneg (sq_nonneg _) ?_
    unfold Psi; split_ifs <;> norm_num
  rcases eq_or_lt_of_le hA_nonneg with hA0 | hApos
  · -- Denominator sum is zero, hence so is the numerator sum.
    have hterm : ∀ x ∈ Finset.range (q n), (evalOnGrid n h x) ^ 2 * Psi n ↑x = 0 := by
      intro x hx
      refine (Finset.sum_eq_zero_iff_of_nonneg ?_).1 hA0.symm x hx
      intro y _
      refine mul_nonneg (sq_nonneg _) ?_
      unfold Psi; split_ifs <;> norm_num
    have hB0 : (∑ x ∈ Finset.range (q n), c n ↑x * (evalOnGrid n h x) ^ 2 * Psi n ↑x) = 0 := by
      refine Finset.sum_eq_zero fun x hx => ?_
      have := hterm x hx
      rw [mul_assoc]
      rw [this, mul_zero]
    rw [← hA0, hB0]
    ring_nf
    simp
  · -- Denominator sum is positive: use the discrete Rayleigh quotient bound.
    have hApos' : (∑ x ∈ Finset.range (q n), (evalOnGrid n h x) ^ 2 * Psi n ↑x) ≠ 0 :=
      ne_of_gt hApos
    have hle := muMin_le_discreteRatio n h hApos
    have hsr : spatialRatio n (evalOnGrid n h)
        = (∑ x ∈ Finset.range (q n), c n ↑x * (evalOnGrid n h x) ^ 2 * Psi n ↑x)
          / (∑ x ∈ Finset.range (q n), (evalOnGrid n h x) ^ 2 * Psi n ↑x) := by
      unfold spatialRatio
      simp only [hApos', if_false]
    rw [hsr] at hle
    rw [le_div_iff₀ hApos] at hle
    -- hle : muMin n * A ≤ B
    calc muMin n * ((1 / (q n : ℝ)) *
            ∑ x ∈ Finset.range (q n), (evalOnGrid n h x) ^ 2 * Psi n ↑x)
        = (1 / (q n : ℝ)) * (muMin n *
            ∑ x ∈ Finset.range (q n), (evalOnGrid n h x) ^ 2 * Psi n ↑x) := by ring
      _ ≤ (1 / (q n : ℝ)) *
            ∑ x ∈ Finset.range (q n), c n ↑x * (evalOnGrid n h x) ^ 2 * Psi n ↑x :=
            mul_le_mul_of_nonneg_left hle hqinv

theorem krafft_quadrature_holds (n : ℕ) (h : H₀ n)
    (hn : (∫ x, ((coeCLM₀ n h : X₀ → ℝ) x) ^ 2 * Psi_cont n x ∂μ₀) > 0) :
    muMin n ≤ continuousRatio μ₀ (c_cont₀ n) (Psi_cont n) (coeCLM₀ n h) +
      (numerator_error n + muMin n * denominator_error n) * ‖coeCLM₀ n h‖ ^ 2 /
        (∫ x, ((coeCLM₀ n h : X₀ → ℝ) x) ^ 2 * Psi_cont n x ∂μ₀) := by
  -- Basic facts / building blocks (raw form, before abbreviating).
  have hmu := muMin_nonneg n
  have hsieve := muMin_mul_denom_le_numer n h
  have hnum := numerator_quadrature n h
  have hden := denominator_quadrature n h
  -- The discrete numerator with the true weight `c` is ≤ the one with the majorant `c_cont₀`.
  have hSc_le_Scc :
      (1 / (q n : ℝ)) *
          ∑ x ∈ Finset.range (q n), c n ↑x * (evalOnGrid n h x) ^ 2 * Psi n ↑x
        ≤ (1 / (q n : ℝ)) *
          ∑ x ∈ Finset.range (q n),
            c_cont₀ n (gridPt n x) * (evalOnGrid n h x) ^ 2 * Psi n ↑x := by
    apply mul_le_mul_of_nonneg_left _ (by positivity)
    apply Finset.sum_le_sum
    intro x _
    have hPsi : (0 : ℝ) ≤ Psi n ↑x := by unfold Psi; split_ifs <;> norm_num
    exact mul_le_mul_of_nonneg_right
      (mul_le_mul_of_nonneg_right (c_le_c_cont₀ n x) (sq_nonneg _)) hPsi
  -- Rewrite the continuous Rayleigh quotient as a plain quotient of integrals.
  have hcr : continuousRatio μ₀ (c_cont₀ n) (Psi_cont n) (coeCLM₀ n h)
      = (∫ x, c_cont₀ n x * ((coeCLM₀ n h : X₀ → ℝ) x) ^ 2 * Psi_cont n x ∂μ₀)
        / (∫ x, ((coeCLM₀ n h : X₀ → ℝ) x) ^ 2 * Psi_cont n x ∂μ₀) := by
    unfold continuousRatio
    rw [if_neg (ne_of_gt hn)]
  rw [hcr, ← add_div, le_div_iff₀ hn]
  -- Abbreviate the recurring integrals / sums / norm.
  set Dcont := ∫ x, ((coeCLM₀ n h : X₀ → ℝ) x) ^ 2 * Psi_cont n x ∂μ₀ with hDcont
  set Ncont := ∫ x, c_cont₀ n x * ((coeCLM₀ n h : X₀ → ℝ) x) ^ 2 * Psi_cont n x ∂μ₀ with hNcont
  set normsq := ‖coeCLM₀ n h‖ ^ 2 with hnormsq
  set Dd := (1 / (q n : ℝ)) *
      ∑ x ∈ Finset.range (q n), (evalOnGrid n h x) ^ 2 * Psi n ↑x with hDd
  set Sc := (1 / (q n : ℝ)) *
      ∑ x ∈ Finset.range (q n), c n ↑x * (evalOnGrid n h x) ^ 2 * Psi n ↑x with hSc
  set Scc := (1 / (q n : ℝ)) *
      ∑ x ∈ Finset.range (q n),
        c_cont₀ n (gridPt n x) * (evalOnGrid n h x) ^ 2 * Psi n ↑x with hScc
  -- Turn the quadrature error bounds into one-sided inequalities.
  have hnum_le : Scc ≤ Ncont + numerator_error n * normsq := by
    have := (abs_le.1 hnum).1
    linarith
  have hden_le : Dcont - denominator_error n * normsq ≤ Dd := by
    have := (abs_le.1 hden).2
    linarith
  -- Multiply the denominator bound by the non-negative `muMin n`.
  have hstep : muMin n * (Dcont - denominator_error n * normsq) ≤ muMin n * Dd :=
    mul_le_mul_of_nonneg_left hden_le hmu
  -- Chain everything together.
  have hbig : muMin n * (Dcont - denominator_error n * normsq)
      ≤ Ncont + numerator_error n * normsq :=
    le_trans hstep (le_trans hsieve (le_trans hSc_le_Scc hnum_le))
  nlinarith [hbig]

end KrafftSieve
