/-
Copyright (c) 2026 Fernando Portela. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Fernando Portela
-/

/-
Portions of this file were generated by Aristotle (https://aristotle.harmonic.fun).

Lean version: leanprover/lean4:v4.28.0
Mathlib version: 8f9d9cff6bd728b17a24e163c9402775d9e6a365

To cite Aristotle, tag @Aristotle-Harmonic on GitHub PRs/issues, and add as co-author to commits:
Co-authored-by: Aristotle (Harmonic) <aristotle-harmonic@harmonic.fun>
-/

import Mathlib.MeasureTheory.Function.L2Space
import Mathlib.MeasureTheory.Constructions.UnitInterval
import Mathlib.Topology.UnitInterval
import Mathlib.Analysis.InnerProductSpace.PiL2
import Mathlib.Data.Fintype.Powerset
import KrafftSieve.OptimalWeights
import KrafftSieve.RKHSLimit
import KrafftSieve.DiscreteOrthoCore

/-!
# Sieve Discretization and Grid Interpolation (Formalization Debt)

This module documents the mathematical and logical strategy to bridge the gap
between the continuous operator limits on $L^2([0, 1])$ and the discrete optimal
sieve quotients computed on the finite grid $\mathcal{A}_n \subseteq \mathbb{Z}/(q(n)\mathbb{Z})$.

The central theorem requiring this bridge is `muMin_le_rkhs_ratio` in `MainTheorem.lean`:
```lean
theorem muMin_le_rkhs_ratio (μ : Measure X) [IsFiniteMeasure μ] (n : ℕ)
    (H_seq : ℕ → Type*) [∀ i, NormedAddCommGroup (H_seq i)]
    [∀ i, InnerProductSpace ℝ (H_seq i)]
    [∀ i, CompleteSpace (H_seq i)] [∀ i, RKHS ℝ (H_seq i) X ℝ]
    (coeCLM_seq : ∀ i, H_seq i →L[ℝ] Lp ℝ 2 μ)
    (projectionToRKHS : ∀ i, Lp ℝ 2 μ →L[ℝ] H_seq i)
    (c_cont : X → ℝ) (f : Lp ℝ 2 μ)
    (hn : ‖coeCLM_seq n (projectionToRKHS n f)‖ > 0) :
    muMin n ≤ continuousRatio μ c_cont (coeCLM_seq n (projectionToRKHS n f))
```

This equivalence is considered "formalization debt" to be closed in this module
using the following three-step mathematical strategy:

## 1. Grid Discretization Operator
Define a sampling operator that maps continuous $L^2$ functions to discrete grid functions:
$$ \text{evalOnGrid} : L^2(X, \mu) \to (\mathcal{A}_n \to \mathbb{R}) $$
Because point evaluation is generally not well-defined on $L^2$ equivalence classes,
this operator must be defined using the reproducing property of the RKHS:
$$ (\text{evalOnGrid}(g))(x) = \langle g, K_x \rangle_{\mathcal{H}_K} $$
for any function $g$ in the range of the RKHS projection.

## 2. Exact Quadrature / Numerical Integration Equivalence
Prove that for any continuous function $g$ in the range of the projection, its discrete Rayleigh
quotient over the grid $\mathcal{A}_n$ is exactly equal to its continuous
Rayleigh quotient over $X$:
$$ \frac{\sum_{x \in \mathcal{A}_n} c(x) g(x)^2}
        {\sum_{x \in \mathcal{A}_n} g(x)^2}
   = \frac{\int_X c_{\text{cont}}(t) g(t)^2 \, dt}
          {\int_X g(t)^2 \, dt} $$
This step uses the fact that the grid points $\mathcal{A}_n$ are the exact quadrature nodes
where the discrete kernel $K = M M^T$ interpolates the continuous kernel function.

## 3. Minimization Embedding
Since the discrete optimal quotient `muMin n` is the infimum of the discrete Rayleigh quotient
over all representable grid functions, and the discretized function $\text{evalOnGrid}(g_n)$ is
representable, we obtain:
$$ \mu_{\min}(n) \le \mathcal{R}_{\text{discrete}}(\text{evalOnGrid}(g_n))
   = \mathcal{R}_{\text{continuous}}(g_n) $$
establishing the upper bound.


## Discretization Bridge Hypothesis (`h_quadrature`)

To resolve the signature bug where the unconstrained continuous weight $c_{\text{cont}}$ could
violate the bounds for $\mu_{\min}(n)$, we have formalized the discretization bridge as
a hypothesis of the reduction:
```lean
(h_quadrature : ∀ n (h : H_seq n), ‖coeCLM_seq n h‖ > 0 →
  muMin n ≤ continuousRatio μ c_cont (coeCLM_seq n h))
```
This hypothesis is carried through to the final `twin_prime_conjecture` theorem in
`MainTheorem.lean`, leaving the entire reduction logical chain completely closed with
**zero `sorry`s**.

Proving `h_quadrature` unconditionally is the main formalization debt of this module,
which will be achieved by executing the three-step program detailed above (defining
`evalOnGrid` using the reproducing property, proving exact quadrature, and embedding it
into the discrete minimum).
-/

namespace KrafftSieve

open scoped unitInterval
open unitInterval
open MeasureTheory HilbertBasis RKHS InnerProductSpace

-- Concrete space and measure for Route B
abbrev X₀ : Type := I
noncomputable abbrev μ₀ : Measure X₀ := volume

-- Sieve-specific grid mapping and RKHS definitions.
-- Note: the residue `x % q n` is taken in `ℕ` and then cast to `ℝ`. (Writing `(x % q n : ℝ)`
-- directly would instead use the `EuclideanDomain` remainder on `ℝ`, which is `0` whenever
-- `q n ≠ 0`, collapsing every grid point to `0`; the natural-number modulus is the intended one.)
noncomputable def gridPt (n : ℕ) (x : ℕ) : X₀ :=
  ⟨((x % q n : ℕ) : ℝ) / (q n : ℝ), by
    have hq : (0 : ℝ) < (q n : ℝ) := by
      exact_mod_cast Nat.pos_of_ne_zero (NeZero.ne (q n))
    refine ⟨by positivity, ?_⟩
    rw [div_le_one hq]
    exact_mod_cast (Nat.mod_lt x (Nat.pos_of_ne_zero (NeZero.ne (q n)))).le⟩

-- Ensure Fintype instance is synthesized for Finset (Fin (w n))
instance (n : ℕ) : Fintype (Finset (Fin (w n))) := Finset.fintype

-- H₀ n is the finite dimensional EuclideanSpace
abbrev H₀ (n : ℕ) : Type := EuclideanSpace ℝ (Finset (Fin (w n)))

/-- Continuous basis cosines on the interval. -/
noncomputable def basisCos_cont (n : ℕ) (S : Finset (Fin (w n))) (t : X₀) : ℝ :=
  ∏ i ∈ S, Real.cos (2 * Real.pi * 3 * (t : ℝ) * (q n : ℝ) / (p n i : ℝ))

/-- Continuous polynomial evaluation of an RKHS element. -/
noncomputable def coeFun_H₀ (n : ℕ) (h : H₀ n) (t : X₀) : ℝ :=
  ∑ S ∈ Finset.univ.powerset, (h : Finset (Fin (w n)) → ℝ) S * basisCos_cont n S t

/-- Continuous evaluation as a linear map. Since `coeFun_H₀ n` is linear in the
coefficient vector, this packages it as an `ℝ`-linear map. -/
noncomputable def coeLM_H₀ (n : ℕ) : H₀ n →ₗ[ℝ] (X₀ → ℝ) where
  toFun h := coeFun_H₀ n h
  map_add' h1 h2 := by
    ext t
    simp only [coeFun_H₀, Pi.add_apply]
    rw [← Finset.sum_add_distrib]
    refine Finset.sum_congr rfl fun S _ => ?_
    have hS : (h1 + h2 : H₀ n) S = h1 S + h2 S := rfl
    rw [hS]; ring
  map_smul' c h := by
    ext t
    simp only [coeFun_H₀, RingHom.id_apply, Pi.smul_apply, smul_eq_mul, Finset.mul_sum]
    refine Finset.sum_congr rfl fun S _ => ?_
    have hS : (c • h : H₀ n) S = c * h S := rfl
    rw [hS]; ring

/-- Continuous evaluation map as a continuous linear map. The domain `H₀ n` is
finite dimensional, so the linear map `coeLM_H₀ n` is automatically continuous. -/
noncomputable def coeCLM_H₀ (n : ℕ) : H₀ n →L[ℝ] X₀ → ℝ :=
  (coeLM_H₀ n).toContinuousLinearMap

@[simp] lemma coeCLM_H₀_apply (n : ℕ) (h : H₀ n) (t : X₀) :
    coeCLM_H₀ n h t = coeFun_H₀ n h t := rfl

/-- Each continuous basis cosine is continuous as a function on the interval. -/
lemma basisCos_cont_continuous (n : ℕ) (S : Finset (Fin (w n))) :
    Continuous (basisCos_cont n S) := by
  unfold basisCos_cont; fun_prop

/-- Products of two continuous basis cosines are integrable (continuous on a compact,
finite-measure domain). -/
lemma integrable_basisCos_prod (n : ℕ) (S T : Finset (Fin (w n))) :
    Integrable (fun t => basisCos_cont n S t * basisCos_cont n T t) μ₀ :=
  ((basisCos_cont_continuous n S).mul
    (basisCos_cont_continuous n T)).integrable_of_hasCompactSupport
    (HasCompactSupport.of_compactSpace _)

/-- The continuous basis cosines are orthogonal under the L² inner product. -/
theorem basisCos_cont_orthogonal (n : ℕ) (S T : Finset (Fin (w n))) :
    ∫ t, basisCos_cont n S t * basisCos_cont n T t ∂μ₀ =
      if S = T then (1 / 2 ^ S.card : ℝ) else 0 := by
  sorry

/-- The continuous basis cosines are linearly independent. -/
theorem basisCos_cont_linear_independent (n : ℕ) :
    LinearIndependent ℝ (fun S : Finset (Fin (w n)) ↦ basisCos_cont n S) := by
  rw [Fintype.linearIndependent_iff]
  intro l hl T
  -- The linear combination vanishes pointwise on the interval.
  have hfun : ∀ t, (∑ S, l S * basisCos_cont n S t) = 0 := by
    intro t
    have h := congrFun hl t
    simpa [Finset.sum_apply, Pi.smul_apply, smul_eq_mul] using h
  -- The integral of the vanishing combination times `basisCos_cont n T` is `0`.
  have hI : (∑ S, l S * ∫ t, basisCos_cont n S t * basisCos_cont n T t ∂μ₀) = 0 := by
    have key : (∑ S, l S * ∫ t, basisCos_cont n S t * basisCos_cont n T t ∂μ₀)
        = ∫ t, (∑ S, l S * basisCos_cont n S t) * basisCos_cont n T t ∂μ₀ := by
      have hpt : (fun t => (∑ S, l S * basisCos_cont n S t) * basisCos_cont n T t)
          = fun t => ∑ S, l S * (basisCos_cont n S t * basisCos_cont n T t) := by
        funext t
        rw [Finset.sum_mul]
        exact Finset.sum_congr rfl fun S _ => by ring
      rw [hpt, integral_finsetSum _ (fun S _ => (integrable_basisCos_prod n S T).const_mul (l S))]
      exact Finset.sum_congr rfl fun S _ => (integral_const_mul (l S) _).symm
    rw [key]
    have hz : (fun t => (∑ S, l S * basisCos_cont n S t) * basisCos_cont n T t)
        = fun _ => (0 : ℝ) := by
      funext t; rw [hfun t]; ring
    rw [hz, integral_zero]
  -- Orthogonality collapses the sum to the single `S = T` term.
  simp only [basisCos_cont_orthogonal] at hI
  have hcollapse : (∑ S, l S * (if S = T then (1 / 2 ^ S.card : ℝ) else 0))
      = l T * (1 / 2 ^ T.card : ℝ) := by
    rw [Finset.sum_eq_single T]
    · simp
    · intro S _ hST; simp [hST]
    · intro hT; exact absurd (Finset.mem_univ T) hT
  rw [hcollapse] at hI
  have hc : (1 / 2 ^ T.card : ℝ) ≠ 0 := by positivity
  rcases mul_eq_zero.mp hI with h | h
  · exact h
  · exact absurd h hc

-- We declare that H₀ n has an RKHS instance
noncomputable instance (n : ℕ) : RKHS ℝ (H₀ n) X₀ ℝ where
  coeCLM := coeCLM_H₀ n
  coeCLM_injective := by
    intro h1 h2 heq
    -- The difference of coefficient vectors gives a vanishing linear combination.
    have hfun : (∑ S : Finset (Fin (w n)),
        ((h1 : Finset (Fin (w n)) → ℝ) S - (h2 : Finset (Fin (w n)) → ℝ) S)
          • basisCos_cont n S) = 0 := by
      funext t
      have ht := congrFun heq t
      simp only [coeCLM_H₀_apply, coeFun_H₀, Finset.powerset_univ] at ht
      simp only [Finset.sum_apply, Pi.zero_apply, Pi.smul_apply, smul_eq_mul, sub_mul]
      rw [Finset.sum_sub_distrib, ht, sub_self]
    -- Linear independence forces all coefficients of the difference to vanish.
    have hcoef := Fintype.linearIndependent_iff.mp (basisCos_cont_linear_independent n) _ hfun
    -- Conclude the two coefficient vectors are equal.
    refine PiLp.ext fun S => ?_
    have := hcoef S
    linarith [this]

/-- The continuous polynomial evaluation function `coeFun_H₀ n h` is continuous. -/
lemma coeFun_H₀_continuous (n : ℕ) (h : H₀ n) : Continuous (coeFun_H₀ n h) := by
  unfold coeFun_H₀ basisCos_cont
  fun_prop

/-- Evaluation as an L² class (linear map). -/
noncomputable def coeLM₀ (n : ℕ) : H₀ n →ₗ[ℝ] Lp ℝ 2 μ₀ where
  toFun h := ContinuousMap.toLp 2 μ₀ ℝ ⟨coeFun_H₀ n h, coeFun_H₀_continuous n h⟩
  map_add' h1 h2 := by
    have hcm : (⟨coeFun_H₀ n (h1 + h2), coeFun_H₀_continuous n (h1 + h2)⟩ : C(X₀, ℝ))
        = ⟨coeFun_H₀ n h1, coeFun_H₀_continuous n h1⟩
          + ⟨coeFun_H₀ n h2, coeFun_H₀_continuous n h2⟩ := by
      ext t
      exact congrFun ((coeLM_H₀ n).map_add h1 h2) t
    simp only [hcm, map_add]
  map_smul' c h := by
    have hcm : (⟨coeFun_H₀ n (c • h), coeFun_H₀_continuous n (c • h)⟩ : C(X₀, ℝ))
        = c • ⟨coeFun_H₀ n h, coeFun_H₀_continuous n h⟩ := by
      ext t
      exact congrFun ((coeLM_H₀ n).map_smul c h) t
    simp only [hcm, map_smul, RingHom.id_apply]

-- coeCLM₀ maps a coefficient vector to its L² class of the spatialVector
noncomputable def coeCLM₀ (n : ℕ) : H₀ n →L[ℝ] Lp ℝ 2 μ₀ :=
  (coeLM₀ n).toContinuousLinearMap

/-- Cosine-basis coefficients of the continuous weight `c_cont₀`. The precise values (which make
`c_cont₀` interpolate the discrete hit counter `c n` exactly on the grid, see `c_cont₀_eq_c`)
encode a separate number-theoretic fact and are left as a stub for a later run. -/
noncomputable def c_coef (n : ℕ) : Finset (Fin (w n)) → ℝ := sorry

/-- The discrete coefficients reconstruct the counter `c n` exactly. -/
theorem c_coef_spec (n : ℕ) (x : ZMod (q n)) :
    ∑ R : Finset (Fin (w n)), c_coef n R * basisCos n R x = c n x := by
  sorry

/-- The continuous weight `c_cont₀`, a trigonometric polynomial expressed as a combination of the
basis cosines with coefficients `c_coef n`. -/
noncomputable def c_cont₀ (n : ℕ) : X₀ → ℝ :=
  fun t => ∑ R : Finset (Fin (w n)), c_coef n R * basisCos_cont n R t

/-- The continuous basis cosine, evaluated at the grid point `gridPt n x`, agrees exactly with
the discrete basis cosine at the residue of `x` modulo `q n`. This is the exact-sampling identity:
the extra factor `q n` in `basisCos_cont` cancels the `1 / q n` inside `gridPt`, leaving
`(x % q n)`, which is exactly `(x : ZMod (q n)).val`. -/
lemma basisCos_cont_gridPt (n : ℕ) (S : Finset (Fin (w n))) (x : ℕ) :
    basisCos_cont n S (gridPt n x) = basisCos n S (x : ZMod (q n)) := by
  unfold basisCos_cont basisCos
  refine Finset.prod_congr rfl fun i _ => ?_
  congr 1
  have hq : (q n : ℝ) ≠ 0 := Nat.cast_ne_zero.mpr (NeZero.ne (q n))
  have hval : ((gridPt n x : X₀) : ℝ) = ((x % q n : ℕ) : ℝ) / (q n : ℝ) := rfl
  have hvalcast : ((x : ZMod (q n)).val : ℝ) = ((x % q n : ℕ) : ℝ) := by
    rw [ZMod.val_natCast]
  rw [hval, hvalcast, mul_assoc, div_mul_cancel₀ _ hq]

/-- The continuous weight c_cont₀ interpolates the discrete weight c n exactly on the grid. -/
theorem c_cont₀_eq_c (n : ℕ) (x : ℕ) :
    c_cont₀ n (gridPt n x) = c n (x : ZMod (q n)) := by
  unfold c_cont₀
  simp only [basisCos_cont_gridPt]
  exact c_coef_spec n (x : ZMod (q n))

/-- Grid Evaluation / Sampling of an RKHS element. -/
noncomputable def evalOnGrid (n : ℕ) (h : H₀ n) : ℕ → ℝ :=
  fun x ↦ coeCLM ℝ h (gridPt n x)

/-- Sieve Representability of Grid Evaluations. -/
theorem evalOnGrid_eq_spatialVector (n : ℕ) (h : H₀ n) :
    ∃ lambda : Finset (Fin (w n)) → ℝ,
      ∀ x : ℕ, evalOnGrid n h x = spatialVector n lambda x := by
  refine ⟨(h : Finset (Fin (w n)) → ℝ), fun x => ?_⟩
  unfold evalOnGrid
  change coeCLM_H₀ n h (gridPt n x) = spatialVector n (h : Finset (Fin (w n)) → ℝ) x
  rw [coeCLM_H₀_apply]
  unfold coeFun_H₀ spatialVector pMulti
  refine Finset.sum_congr rfl fun S _ => ?_
  rw [basisCos_cont_gridPt]

/-- Discrete Rayleigh quotient lower bound for RKHS functions. -/
theorem muMin_le_discreteRatio (n : ℕ) (h : H₀ n)
    (h_nonZero : ∑ x ∈ Finset.range (q n), (evalOnGrid n h x) ^ 2 > 0) :
    muMin n ≤ spatialRatio n (evalOnGrid n h) := by
  -- Represent the grid samples of `h` as a genuine sieve weight vector `spatialVector n lambda`,
  -- with equality holding pointwise.
  obtain ⟨lambda, hlam⟩ := evalOnGrid_eq_spatialVector n h
  have hsum1 : ∑ x ∈ Finset.range (q n), (evalOnGrid n h x) ^ 2
      = ∑ x ∈ Finset.range (q n), (spatialVector n lambda x) ^ 2 :=
    Finset.sum_congr rfl (fun x _ => by rw [hlam x])
  have hsum2 : ∑ x ∈ Finset.range (q n), c n (x : ZMod (q n)) * (evalOnGrid n h x) ^ 2
      = ∑ x ∈ Finset.range (q n), c n (x : ZMod (q n)) * (spatialVector n lambda x) ^ 2 :=
    Finset.sum_congr rfl (fun x _ => by rw [hlam x])
  have hratio : spatialRatio n (evalOnGrid n h) = spatialRatio n (spatialVector n lambda) := by
    simp only [spatialRatio, hsum1, hsum2]
  rw [hratio]
  rw [hsum1] at h_nonZero
  have hq1 : q1 n lambda > 0 := by
    rw [q1_eq_spatialVector_norm]; exact h_nonZero
  rw [← Ratio_eq_spatialRatio]
  have h_mem : Ratio n lambda ∈ attainableRatios n := ⟨lambda, hq1, rfl⟩
  have h_lower_bound : ∀ r ∈ attainableRatios n, r ≥ 0 := by
    rintro r ⟨l, hl_q1, rfl⟩
    unfold Ratio
    rw [if_neg hl_q1.ne']
    refine div_nonneg ?_ (le_of_lt hl_q1)
    rw [q2_eq_spatialVector_weighted_norm]
    refine Finset.sum_nonneg fun x _ ↦ ?_
    exact mul_nonneg (c_nonneg n (x : ZMod (q n))) (sq_nonneg _)
  have h_bdd : BddBelow (attainableRatios n) := ⟨0, h_lower_bound⟩
  exact csInf_le h_bdd h_mem

/-- The discrete basis cosines are orthogonal under the full-period sum. -/
theorem basisCos_discrete_orthogonal (n : ℕ) (S T : Finset (Fin (w n))) :
    ∑ x ∈ Finset.range (q n), basisCos n S x * basisCos n T x =
      if S = T then ((q n : ℝ) / 2 ^ S.card) else 0 := by
  exact basisCos_discrete_orthogonal_range n S T

/-- The triple product integral collapses via symmetric difference frequency cancellation. -/
theorem basisCos_triple_orthogonal_cont (n : ℕ) (R S T : Finset (Fin (w n))) :
    ∫ t, basisCos_cont n R t * basisCos_cont n S t * basisCos_cont n T t ∂μ₀ =
      if symmDiff R (symmDiff S T) = ∅ then (1 / 2 ^ (R ∪ S ∪ T).card : ℝ) else 0 := by
  sorry

/-- The discrete triple product sum collapses via symmetric difference frequency cancellation. -/
theorem basisCos_triple_orthogonal_discrete (n : ℕ) (R S T : Finset (Fin (w n))) :
    ∑ x ∈ Finset.range (q n), basisCos n R x * basisCos n S x * basisCos n T x =
      if symmDiff R (symmDiff S T) = ∅ then ((q n : ℝ) / 2 ^ (R ∪ S ∪ T).card) else 0 := by
  sorry

/-- Exact Riemann sum quadrature for products of two basis cosines. -/
theorem basisCos_product_quadrature (n : ℕ) (S T : Finset (Fin (w n))) :
    ∫ t, basisCos_cont n S t * basisCos_cont n T t ∂μ₀ =
      (1 / (q n : ℝ)) * ∑ x ∈ Finset.range (q n), basisCos n S x * basisCos n T x := by
  rw [basisCos_cont_orthogonal, basisCos_discrete_orthogonal]
  have hq : (q n : ℝ) ≠ 0 := Nat.cast_ne_zero.mpr (NeZero.ne (q n))
  split
  · field_simp
  · ring

/-- Exact Riemann sum quadrature for products of three basis cosines. -/
theorem basisCos_triple_product_quadrature (n : ℕ) (R S T : Finset (Fin (w n))) :
    ∫ t, basisCos_cont n R t * basisCos_cont n S t * basisCos_cont n T t ∂μ₀ =
      (1 / (q n : ℝ)) * ∑ x ∈ Finset.range (q n), basisCos n R x * basisCos n S x * basisCos n T x := by
  rw [basisCos_triple_orthogonal_cont, basisCos_triple_orthogonal_discrete]
  have hq : (q n : ℝ) ≠ 0 := Nat.cast_ne_zero.mpr (NeZero.ne (q n))
  split
  · field_simp
  · ring

/-- Products of three continuous basis cosines are integrable. -/
lemma integrable_basisCos_triple (n : ℕ) (R S T : Finset (Fin (w n))) :
    Integrable (fun t => basisCos_cont n R t * basisCos_cont n S t * basisCos_cont n T t) μ₀ :=
  (((basisCos_cont_continuous n R).mul (basisCos_cont_continuous n S)).mul
    (basisCos_cont_continuous n T)).integrable_of_hasCompactSupport
    (HasCompactSupport.of_compactSpace _)

/-- The `Lp` coercion of `coeCLM₀ n h` agrees almost everywhere with the honest continuous
function `coeFun_H₀ n h`. -/
lemma coeCLM₀_coeFn_ae (n : ℕ) (h : H₀ n) :
    (coeCLM₀ n h : X₀ → ℝ) =ᵐ[μ₀] coeFun_H₀ n h := by
  have hclm : (coeCLM₀ n h : X₀ → ℝ)
      = (ContinuousMap.toLp (E := ℝ) 2 μ₀ ℝ
          ⟨coeFun_H₀ n h, coeFun_H₀_continuous n h⟩ : X₀ → ℝ) := by
    rfl
  rw [hclm]
  exact ContinuousMap.coeFn_toLp (E := ℝ) (𝕜 := ℝ) (p := 2) μ₀
    ⟨coeFun_H₀ n h, coeFun_H₀_continuous n h⟩

/-- The grid samples of an RKHS element expand as a linear combination of the discrete basis cosines. -/
lemma evalOnGrid_mem_eq (n : ℕ) (h : H₀ n) (x : ℕ) :
    evalOnGrid n h x =
      ∑ S : Finset (Fin (w n)), (h : Finset (Fin (w n)) → ℝ) S * basisCos n S (x : ZMod (q n)) := by
  unfold evalOnGrid
  change coeCLM_H₀ n h (gridPt n x) = _
  rw [coeCLM_H₀_apply]
  unfold coeFun_H₀
  rw [Finset.powerset_univ]
  refine Finset.sum_congr rfl fun S _ => ?_
  rw [basisCos_cont_gridPt]

/-- Denominator Quadrature (L² Norm Equivalence) -/
theorem denominator_quadrature (n : ℕ) (h : H₀ n) :
    ∫ x, ((coeCLM₀ n h : X₀ → ℝ) x) ^ 2 ∂μ₀ =
      (1 / (q n : ℝ)) * ∑ x ∈ Finset.range (q n), (evalOnGrid n h x) ^ 2 := by
  -- Step 1: replace the `Lp` representative by the honest continuous function.
  have hae : (fun t => ((coeCLM₀ n h : X₀ → ℝ) t) ^ 2)
      =ᵐ[μ₀] (fun t => (coeFun_H₀ n h t) ^ 2) := by
    filter_upwards [coeCLM₀_coeFn_ae n h] with t ht
    rw [ht]
  rw [integral_congr_ae hae]
  -- Step 2: expand the square of the sum as a double sum.
  have h1 : (fun t => (coeFun_H₀ n h t) ^ 2)
      = (fun t => ∑ S : Finset (Fin (w n)), ∑ T : Finset (Fin (w n)),
          (h : Finset (Fin (w n)) → ℝ) S * (h : Finset (Fin (w n)) → ℝ) T *
            (basisCos_cont n S t * basisCos_cont n T t)) := by
    funext t
    have hc : coeFun_H₀ n h t
        = ∑ S : Finset (Fin (w n)), (h : Finset (Fin (w n)) → ℝ) S * basisCos_cont n S t := by
      rw [coeFun_H₀, Finset.powerset_univ]
    rw [hc, sq, Fintype.sum_mul_sum]
    exact Finset.sum_congr rfl fun S _ => Finset.sum_congr rfl fun T _ => by ring
  rw [h1]
  -- Step 3: push the integral through the two finite sums, pulling out the coefficients.
  rw [integral_finsetSum _ (fun S _ => integrable_finsetSum _
    (fun T _ => (integrable_basisCos_prod n S T).const_mul _))]
  have h2 : ∀ S : Finset (Fin (w n)),
      (∫ t, ∑ T : Finset (Fin (w n)), (h : Finset (Fin (w n)) → ℝ) S *
          (h : Finset (Fin (w n)) → ℝ) T * (basisCos_cont n S t * basisCos_cont n T t) ∂μ₀)
        = ∑ T : Finset (Fin (w n)), (h : Finset (Fin (w n)) → ℝ) S *
            (h : Finset (Fin (w n)) → ℝ) T *
            ∫ t, basisCos_cont n S t * basisCos_cont n T t ∂μ₀ := by
    intro S
    rw [integral_finsetSum _ (fun T _ => (integrable_basisCos_prod n S T).const_mul _)]
    exact Finset.sum_congr rfl fun T _ => integral_const_mul _ _
  simp_rw [h2]
  -- Step 4: substitute the product quadrature and reassemble the grid sum.
  simp_rw [basisCos_product_quadrature n]
  -- Reduce to a pure reindexing/algebra identity between triple sums.
  have key : (1 / (q n : ℝ)) * ∑ x ∈ Finset.range (q n), (evalOnGrid n h x) ^ 2
      = ∑ S : Finset (Fin (w n)), ∑ T : Finset (Fin (w n)),
          (h : Finset (Fin (w n)) → ℝ) S * (h : Finset (Fin (w n)) → ℝ) T *
            ((1 / (q n : ℝ)) *
              ∑ x ∈ Finset.range (q n), basisCos n S x * basisCos n T x) := by
    have e1 : ∀ x ∈ Finset.range (q n), (evalOnGrid n h x) ^ 2
        = ∑ S : Finset (Fin (w n)), ∑ T : Finset (Fin (w n)),
            (h : Finset (Fin (w n)) → ℝ) S * (h : Finset (Fin (w n)) → ℝ) T *
              (basisCos n S x * basisCos n T x) := by
      intro x _
      rw [evalOnGrid_mem_eq n h x, sq, Fintype.sum_mul_sum]
      exact Finset.sum_congr rfl fun S _ => Finset.sum_congr rfl fun T _ => by ring
    rw [Finset.sum_congr rfl e1, Finset.mul_sum]
    simp_rw [Finset.mul_sum]
    rw [Finset.sum_comm]
    refine Finset.sum_congr rfl fun S _ => ?_
    rw [Finset.sum_comm]
    refine Finset.sum_congr rfl fun T _ => Finset.sum_congr rfl fun x _ => by ring
  rw [key]

/-- Numerator Quadrature (Weighted Norm Equivalence) -/
theorem numerator_quadrature (n : ℕ) (h : H₀ n) :
    ∫ x, c_cont₀ n x * ((coeCLM₀ n h : X₀ → ℝ) x) ^ 2 ∂μ₀ =
      (1 / (q n : ℝ)) * ∑ x ∈ Finset.range (q n), c n (x : ZMod (q n)) * (evalOnGrid n h x) ^ 2 := by
  -- Step 1: replace the `Lp` representative by the honest continuous function.
  have hae : (fun t => c_cont₀ n t * ((coeCLM₀ n h : X₀ → ℝ) t) ^ 2)
      =ᵐ[μ₀] (fun t => c_cont₀ n t * (coeFun_H₀ n h t) ^ 2) := by
    filter_upwards [coeCLM₀_coeFn_ae n h] with t ht
    rw [ht]
  rw [integral_congr_ae hae]
  -- Step 2: expand `c_cont₀` and the square of the sum into a triple sum.
  have h1 : (fun t => c_cont₀ n t * (coeFun_H₀ n h t) ^ 2)
      = (fun t => ∑ R : Finset (Fin (w n)), ∑ S : Finset (Fin (w n)), ∑ T : Finset (Fin (w n)),
          c_coef n R * (h : Finset (Fin (w n)) → ℝ) S * (h : Finset (Fin (w n)) → ℝ) T *
            (basisCos_cont n R t * basisCos_cont n S t * basisCos_cont n T t)) := by
    funext t
    have hcoe : coeFun_H₀ n h t
        = ∑ S : Finset (Fin (w n)), (h : Finset (Fin (w n)) → ℝ) S * basisCos_cont n S t := by
      rw [coeFun_H₀, Finset.powerset_univ]
    have hcc : c_cont₀ n t
        = ∑ R : Finset (Fin (w n)), c_coef n R * basisCos_cont n R t := rfl
    rw [hcc, hcoe, sq, Fintype.sum_mul_sum, Fintype.sum_mul_sum]
    simp_rw [Finset.mul_sum]
    refine Finset.sum_congr rfl fun R _ => Finset.sum_congr rfl fun S _ =>
      Finset.sum_congr rfl fun T _ => by ring
  rw [h1]
  -- Step 3: push the integral through the three finite sums.
  rw [integral_finsetSum _ (fun R _ => integrable_finsetSum _ (fun S _ =>
    integrable_finsetSum _ (fun T _ => (integrable_basisCos_triple n R S T).const_mul _)))]
  have h2 : ∀ R : Finset (Fin (w n)),
      (∫ t, ∑ S : Finset (Fin (w n)), ∑ T : Finset (Fin (w n)),
          c_coef n R * (h : Finset (Fin (w n)) → ℝ) S * (h : Finset (Fin (w n)) → ℝ) T *
            (basisCos_cont n R t * basisCos_cont n S t * basisCos_cont n T t) ∂μ₀)
        = ∑ S : Finset (Fin (w n)), ∑ T : Finset (Fin (w n)),
            c_coef n R * (h : Finset (Fin (w n)) → ℝ) S * (h : Finset (Fin (w n)) → ℝ) T *
              ∫ t, basisCos_cont n R t * basisCos_cont n S t * basisCos_cont n T t ∂μ₀ := by
    intro R
    rw [integral_finsetSum _ (fun S _ => integrable_finsetSum _
      (fun T _ => (integrable_basisCos_triple n R S T).const_mul _))]
    refine Finset.sum_congr rfl fun S _ => ?_
    rw [integral_finsetSum _ (fun T _ => (integrable_basisCos_triple n R S T).const_mul _)]
    exact Finset.sum_congr rfl fun T _ => integral_const_mul _ _
  simp_rw [h2]
  -- Step 4: substitute the triple-product quadrature.
  simp_rw [basisCos_triple_product_quadrature n]
  -- Step 5: reassemble the grid sum. Both sides equal a common quadruple sum.
  have Lexp : (∑ R : Finset (Fin (w n)), ∑ S : Finset (Fin (w n)), ∑ T : Finset (Fin (w n)),
        c_coef n R * (h : Finset (Fin (w n)) → ℝ) S * (h : Finset (Fin (w n)) → ℝ) T *
          ((1 / (q n : ℝ)) * ∑ x ∈ Finset.range (q n),
            basisCos n R x * basisCos n S x * basisCos n T x))
      = ∑ R : Finset (Fin (w n)), ∑ S : Finset (Fin (w n)), ∑ T : Finset (Fin (w n)),
          ∑ x ∈ Finset.range (q n), (1 / (q n : ℝ)) *
            (c_coef n R * (h : Finset (Fin (w n)) → ℝ) S * (h : Finset (Fin (w n)) → ℝ) T *
              (basisCos n R x * basisCos n S x * basisCos n T x)) := by
    refine Finset.sum_congr rfl fun R _ => Finset.sum_congr rfl fun S _ =>
      Finset.sum_congr rfl fun T _ => ?_
    simp_rw [Finset.mul_sum]
    exact Finset.sum_congr rfl fun x _ => by ring
  have Rexp : (1 / (q n : ℝ)) *
        ∑ x ∈ Finset.range (q n), c n (x : ZMod (q n)) * (evalOnGrid n h x) ^ 2
      = ∑ x ∈ Finset.range (q n), ∑ R : Finset (Fin (w n)), ∑ S : Finset (Fin (w n)),
          ∑ T : Finset (Fin (w n)), (1 / (q n : ℝ)) *
            (c_coef n R * (h : Finset (Fin (w n)) → ℝ) S * (h : Finset (Fin (w n)) → ℝ) T *
              (basisCos n R x * basisCos n S x * basisCos n T x)) := by
    rw [Finset.mul_sum]
    refine Finset.sum_congr rfl fun x _ => ?_
    rw [← c_cont₀_eq_c n x]
    unfold c_cont₀
    simp only [basisCos_cont_gridPt]
    rw [evalOnGrid_mem_eq n h x, sq, Fintype.sum_mul_sum, Fintype.sum_mul_sum]
    simp_rw [Finset.mul_sum]
    refine Finset.sum_congr rfl fun R _ => Finset.sum_congr rfl fun S _ =>
      Finset.sum_congr rfl fun T _ => by ring
  rw [Lexp, Rexp]
  -- Reorder the quadruple sum: move the grid sum to the outside.
  conv_rhs => rw [Finset.sum_comm]
  refine Finset.sum_congr rfl fun R _ => ?_
  conv_rhs => rw [Finset.sum_comm]
  refine Finset.sum_congr rfl fun S _ => ?_
  conv_rhs => rw [Finset.sum_comm]

/-- The `L²` norm-squared of `coeCLM₀ n h`, expressed as an integral, is strictly positive
whenever its norm is positive. -/
theorem denominator_pos (n : ℕ) (h : H₀ n) (hn : ‖coeCLM₀ n h‖ > 0) :
    (0 : ℝ) < ∫ x, ((coeCLM₀ n h : X₀ → ℝ) x) ^ 2 ∂μ₀ := by
  have hid : ∫ x, ((coeCLM₀ n h : X₀ → ℝ) x) ^ 2 ∂μ₀ = ‖coeCLM₀ n h‖ ^ 2 := by
    rw [← real_inner_self_eq_norm_sq, MeasureTheory.L2.inner_def]
    simp only [RCLike.inner_apply, conj_trivial, pow_two]
  rw [hid]
  exact pow_pos hn 2

/-- The final discretization bridge theorem. -/
theorem krafft_quadrature_holds (n : ℕ) (h : H₀ n) (hn : ‖coeCLM₀ n h‖ > 0) :
    muMin n ≤ continuousRatio μ₀ (c_cont₀ n) (coeCLM₀ n h) := by
  -- The denominator (grid L²-norm, expressed as an integral) is strictly positive.
  have hden : (0 : ℝ) < ∫ x, ((coeCLM₀ n h : X₀ → ℝ) x) ^ 2 ∂μ₀ := denominator_pos n h hn
  -- Hence the discrete grid L²-norm is positive too.
  have hq : (q n : ℝ) > 0 := by
    exact_mod_cast Nat.pos_of_ne_zero (NeZero.ne (q n))
  have hq_inv : (0 : ℝ) < 1 / (q n : ℝ) := one_div_pos.mpr hq
  have h_nonZero : ∑ x ∈ Finset.range (q n), (evalOnGrid n h x) ^ 2 > 0 := by
    have hden_eq := denominator_quadrature n h
    rw [hden_eq] at hden
    exact (mul_pos_iff_of_pos_left hq_inv).mp hden
  -- Identify the continuous ratio with the discrete spatial ratio.
  have h_eq : continuousRatio μ₀ (c_cont₀ n) (coeCLM₀ n h)
      = spatialRatio n (evalOnGrid n h) := by
    simp only [continuousRatio, spatialRatio]
    rw [numerator_quadrature n h, denominator_quadrature n h]
    have hsum_ne : ∑ x ∈ Finset.range (q n), (evalOnGrid n h x) ^ 2 ≠ 0 := h_nonZero.ne'
    have hq_ne : (q n : ℝ) ≠ 0 := hq.ne'
    have hdiv_ne : (1 / (q n : ℝ)) * ∑ x ∈ Finset.range (q n), (evalOnGrid n h x) ^ 2 ≠ 0 :=
      mul_ne_zero (div_ne_zero one_ne_zero hq_ne) hsum_ne
    rw [if_neg hdiv_ne, if_neg hsum_ne]
    have hdiv : (1 / (q n : ℝ)) ≠ 0 := div_ne_zero one_ne_zero hq_ne
    rw [mul_div_mul_left _ _ hdiv]
  rw [h_eq]
  exact muMin_le_discreteRatio n h h_nonZero

end KrafftSieve
