/-
Copyright (c) 2026 Fernando Portela. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Fernando Portela
-/

/-
Portions of this file were generated by Aristotle (https://aristotle.harmonic.fun).

Lean version: leanprover/lean4:v4.28.0
Mathlib version: 8f9d9cff6bd728b17a24e163c9402775d9e6a365

To cite Aristotle, tag @Aristotle-Harmonic on GitHub PRs/issues, and add as co-author to commits:
Co-authored-by: Aristotle (Harmonic) <aristotle-harmonic@harmonic.fun>
-/

import Mathlib.Algebra.BigOperators.ModEq
import Mathlib.Analysis.SpecialFunctions.Integrals.Basic
import Mathlib.MeasureTheory.Function.L2Space
import Mathlib.MeasureTheory.Constructions.UnitInterval
import Mathlib.Topology.UnitInterval
import Mathlib.Analysis.InnerProductSpace.PiL2
import Mathlib.Data.Fintype.Powerset
import KrafftSieve.OptimalWeights
import KrafftSieve.RKHSLimit
import KrafftSieve.DiscreteOrthoCore
import KrafftSieve.FourierInterpolation
import KrafftSieve.DirichletQuadrature

/-!
# Sieve Discretization and Approximate Quadratures

This module defines the discretization bridge connecting the discrete optimal sieve
quotients to the continuous Rayleigh quotients on the unit interval via approximate quadratures.
-/

namespace KrafftSieve

open scoped unitInterval
open unitInterval
open MeasureTheory HilbertBasis RKHS InnerProductSpace

/-- The continuous weight `c_cont₀`, a trigonometric polynomial interpolating
the discrete weight `c n` using the single-prime Fourier cosine coefficients. -/
noncomputable def c_cont₀ (n : ℕ) : X₀ → ℝ :=
  fun t => ∑ i : Fin (w n), ∑ k ∈ Finset.range ((p n i + 1) / 2),
    g_coef n i k * Real.cos (2 * Real.pi * k * (t : ℝ) * (q n : ℝ) / (p n i : ℝ))

/-- The reproducing degree of the continuous window: chosen large enough that every product of
cosines appearing in the numerator/denominator quadratures has total (absolute) frequency at most
`kernelDegree n`, so that the Dirichlet kernel reproduces it exactly. -/
noncomputable def kernelDegree (n : ℕ) : ℕ := q n * (6 * w n + 1)

/-- The continuous window function `Psi_cont`.

Rather than a band-limited majorant (which, being analytic, could not agree with the compactly
supported discrete window `Psi` on the grid — the "analyticity wall"), we use the exact
trigonometric *reproducing* window built from the Dirichlet kernel:
`Psi_cont n t = (1/q) ∑_{y<q} Psi(y) · D_M(t - y/q)` with `M = kernelDegree n`.

This window is a genuine (non band-limited) trigonometric polynomial. Its defining property is that
for every product of cosines with total absolute frequency `≤ M`, integrating against `Psi_cont`
reproduces *exactly* the corresponding windowed Riemann sum over the grid. Consequently the
numerator/denominator quadratures below hold with **zero** error. -/
noncomputable def Psi_cont (n : ℕ) : X₀ → ℝ :=
  fun t => reproWindow (q n) (kernelDegree n) (fun y => Psi n (y : ZMod (q n))) (t : ℝ)

/-- Psi_cont is continuous. -/
lemma Psi_cont_continuous (n : ℕ) : Continuous (Psi_cont n) := by
  unfold Psi_cont
  exact (reproWindow_continuous _ _ _).comp (by fun_prop)

/-- The error bound for the approximate denominator quadrature. -/
noncomputable def denominator_error (_n : ℕ) : ℝ := 0

/-- The error bound for the approximate numerator quadrature. -/
noncomputable def numerator_error (_n : ℕ) : ℝ := 0

/-- The error bound for the denominator quadrature converges to 0. -/
lemma denominator_error_tendsto_zero : Filter.Tendsto denominator_error Filter.atTop (nhds 0) := by
  unfold denominator_error
  exact tendsto_const_nhds

/-- The error bound for the numerator quadrature converges to 0. -/
lemma numerator_error_tendsto_zero : Filter.Tendsto numerator_error Filter.atTop (nhds 0) := by
  unfold numerator_error
  exact tendsto_const_nhds

/-- The continuous basis cosine, evaluated at the grid point `gridPt n x`, agrees exactly with
the discrete basis cosine at the residue of `x` modulo `q n`. This is the exact-sampling identity:
the extra factor `q n` in `basisCos_cont` cancels the `1 / q n` inside `gridPt`, leaving
`(x % q n)`, which is exactly `(x : ZMod (q n)).val`. -/
lemma basisCos_cont_gridPt (n : ℕ) (S : Finset (Fin (w n))) (x : ℕ) :
    basisCos_cont n S (gridPt n x) = basisCos n S (x : ZMod (q n)) := by
  unfold basisCos_cont basisCos
  refine Finset.prod_congr rfl fun i _ => ?_
  congr 1
  have hq : (q n : ℝ) ≠ 0 := Nat.cast_ne_zero.mpr (NeZero.ne (q n))
  have hval : ((gridPt n x : X₀) : ℝ) = ((x % q n : ℕ) : ℝ) / (q n : ℝ) := rfl
  have hvalcast : ((x : ZMod (q n)).val : ℝ) = ((x % q n : ℕ) : ℝ) := by
    rw [ZMod.val_natCast]
  rw [hval, hvalcast, mul_assoc, div_mul_cancel₀ _ hq]

/-- The continuous weight c_cont₀ interpolates the discrete weight c n exactly on the grid. -/
theorem c_cont₀_eq_c (n : ℕ) (x : ℕ) :
    c_cont₀ n (gridPt n x) = c n (x : ZMod (q n)) := by
  unfold c_cont₀ c
  have h_eq : ∀ i : Fin (w n), ∑ k ∈ Finset.range ((p n i + 1) / 2),
        g_coef n i k * Real.cos
          (2 * Real.pi * k * ((gridPt n x : X₀) : ℝ) * (q n : ℝ) / (p n i : ℝ))
        = ∑ k ∈ Finset.range ((p n i + 1) / 2),
          g_coef n i k * Real.cos (2 * Real.pi * k * ((x : ZMod (q n)).val : ℝ) / (p n i : ℝ)) := by
    intro i
    refine Finset.sum_congr rfl fun k _ => ?_
    congr 1
    congr 1
    have hq : (q n : ℝ) ≠ 0 := Nat.cast_ne_zero.mpr (NeZero.ne (q n))
    have hval : ((gridPt n x : X₀) : ℝ) = ((x % q n : ℕ) : ℝ) / (q n : ℝ) := rfl
    have hvalcast : ((x : ZMod (q n)).val : ℝ) = ((x % q n : ℕ) : ℝ) := by
      rw [ZMod.val_natCast]
    have hpn : ((p n i : ℕ) : ℝ) ≠ 0 := Nat.cast_ne_zero.mpr (p_ne_zero n i)
    have : 2 * Real.pi * (k : ℝ) * (((x % q n : ℕ) : ℝ) / (q n : ℝ)) * (q n : ℝ) / (p n i : ℝ)
      = 2 * Real.pi * (k : ℝ) * ((x % q n : ℕ) : ℝ) / (p n i : ℝ) := by
      field_simp [hq, hpn]
    rw [hval, hvalcast]
    exact this
  simp_rw [h_eq]
  rw [← Finset.sum_congr rfl fun i _ => ?_]
  · exact (g_coef_spec n i (x : ZMod (q n))).symm

/-- The continuous weight c_cont₀ majorizes the discrete weight c n on the grid points. -/
theorem c_le_c_cont₀ (n : ℕ) (x : ℕ) :
    c n (x : ZMod (q n)) ≤ c_cont₀ n (gridPt n x) := by
  rw [c_cont₀_eq_c]

/-- Grid Evaluation / Sampling of an RKHS element. -/
noncomputable def evalOnGrid (n : ℕ) (h : H₀ n) : ℕ → ℝ :=
  fun x ↦ coeCLM ℝ h (gridPt n x)

/-- Sieve Representability of Grid Evaluations. -/
theorem evalOnGrid_eq_spatialVector (n : ℕ) (h : H₀ n) :
    ∃ lambda : Finset (Fin (w n)) → ℝ,
      ∀ x : ℕ, evalOnGrid n h x = spatialVector n lambda x := by
  refine ⟨(h : Finset (Fin (w n)) → ℝ), fun x => ?_⟩
  unfold evalOnGrid
  change coeCLM_H₀ n h (gridPt n x) = spatialVector n (h : Finset (Fin (w n)) → ℝ) x
  rw [coeCLM_H₀_apply]
  unfold coeFun_H₀ spatialVector pMulti
  refine Finset.sum_congr rfl fun S _ => ?_
  rw [basisCos_cont_gridPt]

theorem muMin_le_discreteRatio (n : ℕ) (h : H₀ n)
    (h_nonZero : ∑ x ∈ Finset.range (q n), (evalOnGrid n h x) ^ 2 * Psi n (x : ZMod (q n)) > 0) :
    muMin n ≤ spatialRatio n (evalOnGrid n h) := by
  obtain ⟨lambda, hlambda⟩ := evalOnGrid_eq_spatialVector n h
  have hfun : evalOnGrid n h = spatialVector n lambda := funext hlambda
  rw [hfun, ← Ratio_eq_spatialRatio]
  have hq1 : q1 n lambda > 0 := by
    rw [q1_eq_spatialVector_norm, ← hfun]
    exact h_nonZero
  have hmem : Ratio n lambda ∈ attainableRatios n := ⟨lambda, hq1, rfl⟩
  exact csInf_le (attainable_ratios_compact n).bddBelow hmem

/-- The discrete basis cosines are orthogonal under the full-period sum. -/
theorem basisCos_discrete_orthogonal (n : ℕ) (S T : Finset (Fin (w n))) :
    ∑ x ∈ Finset.range (q n), basisCos n S x * basisCos n T x =
      if S = T then ((q n : ℝ) / 2 ^ S.card) else 0 := by
  exact basisCos_discrete_orthogonal_range n S T

/-- The triple product integral collapses via symmetric difference frequency cancellation. -/
theorem basisCos_triple_orthogonal_cont (n : ℕ) (R S T : Finset (Fin (w n))) :
    ∫ t, basisCos_cont n R t * basisCos_cont n S t * basisCos_cont n T t ∂μ₀ =
      if symmDiff R (symmDiff S T) = ∅ then (1 / 2 ^ (R ∪ S ∪ T).card : ℝ) else 0 := by
  split_ifs with h
  · exact basisCos_triple_cont_then n R S T h
  · exact basisCos_triple_cont_else n R S T h

/-- The discrete triple product sum collapses via symmetric difference frequency cancellation. -/
theorem basisCos_triple_orthogonal_discrete (n : ℕ) (R S T : Finset (Fin (w n))) :
    ∑ x ∈ Finset.range (q n), basisCos n R x * basisCos n S x * basisCos n T x =
      if symmDiff R (symmDiff S T) = ∅ then ((q n : ℝ) / 2 ^ (R ∪ S ∪ T).card) else 0 := by
  unfold basisCos
  split_ifs <;> simp_all +decide only [Finset.symmDiff_eq_empty, ZMod.val_natCast,
    Finset.union_assoc]
  · have h_crt : ∀ i : Fin (w n),
        ∑ x ∈ Finset.range (p n i),
          Real.cos (2 * Real.pi * 3 * (x : ℝ) / (p n i : ℝ)) ^
            (if i ∈ symmDiff S T then 1 else 0) *
          Real.cos (2 * Real.pi * 3 * (x : ℝ) / (p n i : ℝ)) ^
            (if i ∈ S then 1 else 0) *
          Real.cos (2 * Real.pi * 3 * (x : ℝ) / (p n i : ℝ)) ^
            (if i ∈ T then 1 else 0)
        = if i ∈ (symmDiff S T) ∪ (S ∪ T) then (p n i : ℝ) / 2 else (p n i : ℝ) := by
      intro i
      split_ifs <;> simp_all +decide only [symmDiff, Finset.sup_eq_union', Finset.mem_union,
        Finset.mem_sdiff, not_false_eq_true, and_true, or_self, Finset.union_assoc, pow_zero,
        mul_one, Finset.sum_const, Finset.card_range, nsmul_eq_mul]
      · convert cos_sq_prime_sum n i 3 _ _ using 1 <;> norm_num
        · exact Finset.sum_congr rfl fun _ _ => by ring
        · exact_mod_cast Nat.not_dvd_of_pos_of_lt ( by norm_num ) ( by linarith [ p_ge_5 n i ] )
        · have h_prime_ge_5 : 5 ≤ p n i := by
            exact KrafftSieve.p_ge_5 n i
          norm_cast; intro h; have := Nat.le_of_dvd ( by decide ) h
          interval_cases _ : p n i <;> simp_all +decide only
          exact absurd ( p_prime n i ) ( by norm_num [ * ] )
      · convert cos_sq_prime_sum n i 3 _ _ using 1 <;> norm_num
        · exact Finset.sum_congr rfl fun _ _ => by ring
        · exact_mod_cast Nat.not_dvd_of_pos_of_lt ( by norm_num ) ( by linarith [ p_ge_5 n i ] )
        · have := p_prime n i; ( have := p_ge_5 n i; ( norm_cast at *; ) )
          exact fun h => by
            have := Nat.le_of_dvd ( by decide ) h; interval_cases p n i <;> trivial
      · convert cos_sq_prime_sum n i 3 _ _ using 1 <;> norm_num
        · exact Finset.sum_congr rfl fun _ _ => by ring
        · exact_mod_cast Nat.not_dvd_of_pos_of_lt ( by norm_num ) ( by linarith [ p_ge_5 n i ] )
        · have := p_ge_5 n i; ( have := p_prime n i; ( norm_cast at *; ) )
          exact fun h => by
            have := Nat.le_of_dvd ( by decide ) h; interval_cases p n i <;> trivial
    convert crt_product_sum_factorization n
      ( fun i x =>
        ( Real.cos ( 2 * Real.pi * 3 * x / ( p n i : ℝ ) ) ^
          ( if i ∈ symmDiff S T then 1 else 0 ) ) *
        Real.cos ( 2 * Real.pi * 3 * x / ( p n i : ℝ ) ) ^ ( if i ∈ S then 1 else 0 ) *
        Real.cos ( 2 * Real.pi * 3 * x / ( p n i : ℝ ) ) ^ ( if i ∈ T then 1 else 0 ) ) _ using 1
    · refine Finset.sum_congr rfl fun x hx => ?_
      rw [ Nat.mod_eq_of_lt ( Finset.mem_range.mp hx ) ]
      rw [ Finset.prod_mul_distrib, Finset.prod_mul_distrib ]
      simp +decide
    · rw [ Finset.prod_congr rfl fun i hi => h_crt i ]
      rw [ Finset.prod_ite ]
      simp +decide only [Finset.mem_union, Finset.prod_div_distrib, Finset.prod_const, not_or,
        mul_comm]
      rw [ ← mul_div_assoc, ← Finset.prod_union ]
      · congr! 1
        · convert prod_p_eq_q n |> Eq.symm using 2
          grind
        · congr! 2
          grind
      · exact Finset.disjoint_left.mpr ( by aesop )
    · intro i x; simp +decide [mul_add, add_div, ne_of_gt (Nat.Prime.pos (p_prime n i))]
      norm_num [ show 2 * Real.pi * 3 =
        2 * Real.pi + 2 * Real.pi + 2 * Real.pi by ring, Real.cos_add ]
  · -- Since the symmetric difference is non-empty, there exists an index $i$
    -- such that $i$ is in an odd number of the sets $R$, $S$, and $T$.
    obtain ⟨i, hi⟩ : ∃ i : Fin (w n),
        (if i ∈ R then 1 else 0) + (if i ∈ S then 1 else 0) + (if i ∈ T then 1 else 0)
          ≡ 1 [MOD 2] := by
      simp_all +decide only [symmDiff, Finset.sup_eq_union', Finset.ext_iff, Finset.mem_union,
        Finset.mem_sdiff, not_forall]
      obtain ⟨ i, hi ⟩ := ‹_›; use i; split_ifs <;> simp_all +decide
    -- Since the sum of cosines is zero, the product sum is also zero.
    have h_cos_sum_zero : ∑ x ∈ Finset.range (p n i),
        (if i ∈ R then Real.cos (2 * Real.pi * 3 * (x : ℝ) / (p n i : ℝ)) else 1) *
        (if i ∈ S then Real.cos (2 * Real.pi * 3 * (x : ℝ) / (p n i : ℝ)) else 1) *
        (if i ∈ T then Real.cos (2 * Real.pi * 3 * (x : ℝ) / (p n i : ℝ)) else 1) = 0 := by
      split_ifs at hi ⊢ <;> simp_all +decide only
      · -- Using the identity $\cos^3(\theta) = \frac{3\cos(\theta) + \cos(3\theta)}{4}$,
        -- we can rewrite the sum.
        have h_cos3 : ∀ x : ℕ, Real.cos (2 * Real.pi * 3 * (x : ℝ) / (p n i : ℝ)) ^ 3 =
            (3 * Real.cos (2 * Real.pi * 3 * (x : ℝ) / (p n i : ℝ)) +
             Real.cos (2 * Real.pi * 9 * (x : ℝ) / (p n i : ℝ))) / 4 := by
          intro x
          rw [ show 2 * Real.pi * 9 * x / ( p n i : ℝ ) =
            3 * ( 2 * Real.pi * 3 * x / ( p n i : ℝ ) ) by ring ]
          rw [ Real.cos_three_mul ] ; ring
        -- Using the fact that the sum of cosines of the form $\cos(2\pi kx/p)$
        -- over a complete residue system modulo $p$ is zero for any integer
        -- $k$ not divisible by $p$, we can simplify the expression.
        have h_cos_sum_zero :
            ∑ x ∈ Finset.range (p n i),
              Real.cos (2 * Real.pi * 3 * (x : ℝ) / (p n i : ℝ)) = 0 ∧
            ∑ x ∈ Finset.range (p n i),
              Real.cos (2 * Real.pi * 9 * (x : ℝ) / (p n i : ℝ)) = 0 :=
          ⟨by simpa using cos_prime_sum_zero n i 3 (p_mod3_ne n i),
           by simpa using cos_prime_sum_zero n i 9 (p_mod9_ne n i)⟩
        simp_all +decide [← pow_two]
        simp_all +decide [ ← pow_succ, ← Finset.sum_div _ _ _ ]
        simp_all +decide [ Finset.sum_add_distrib, ← Finset.mul_sum _ _ _ ]
      · simpa using cos_prime_sum_zero n i 3 (p_mod3_ne n i)
      · simpa using cos_prime_sum_zero n i 3 (p_mod3_ne n i)
      · simpa using cos_prime_sum_zero n i 3 (p_mod3_ne n i)
    convert mul_eq_zero_of_right
      ( ∏ j ∈ Finset.univ.erase i, ∑ y ∈ Finset.range ( p n j ),
        ( if j ∈ R then Real.cos ( 2 * Real.pi * 3 * ( y : ℝ ) / ( p n j : ℝ ) ) else 1 ) *
        ( if j ∈ S then Real.cos ( 2 * Real.pi * 3 * ( y : ℝ ) / ( p n j : ℝ ) ) else 1 ) *
        ( if j ∈ T then Real.cos ( 2 * Real.pi * 3 * ( y : ℝ ) / ( p n j : ℝ ) ) else 1 ) )
      h_cos_sum_zero using 1
    convert crt_product_sum_factorization n
      ( fun j x =>
        ( if j ∈ R then Real.cos ( 2 * Real.pi * 3 * ( x : ℝ ) / ( p n j : ℝ ) ) else 1 ) *
        ( if j ∈ S then Real.cos ( 2 * Real.pi * 3 * ( x : ℝ ) / ( p n j : ℝ ) ) else 1 ) *
        ( if j ∈ T then Real.cos ( 2 * Real.pi * 3 * ( x : ℝ ) / ( p n j : ℝ ) ) else 1 ) )
      _ using 1
    · refine Finset.sum_congr rfl fun x hx => ?_
      rw [ Nat.mod_eq_of_lt ( Finset.mem_range.mp hx ) ]
      rw [ Finset.prod_mul_distrib, Finset.prod_mul_distrib ]
      simp +decide
    · rw [ Finset.prod_erase_mul _ _ ( Finset.mem_univ _ ) ]
    · intro j x
      by_cases hjR : j ∈ R <;> by_cases hjS : j ∈ S <;> by_cases hjT : j ∈ T <;>
        simp +decide only [Nat.cast_add, mul_ite, ite_mul, one_mul, mul_one]
      all_goals
        rw [ ← Real.cos_sub_int_mul_two_pi _ 3 ]
        ring_nf
        norm_num [ ne_of_gt ( show 0 < p n j from Nat.Prime.pos ( p_prime n j ) ) ]

/-- Exact Riemann sum quadrature for products of two basis cosines. -/
theorem basisCos_product_quadrature (n : ℕ) (S T : Finset (Fin (w n))) :
    ∫ t, basisCos_cont n S t * basisCos_cont n T t ∂μ₀ =
      (1 / (q n : ℝ)) * ∑ x ∈ Finset.range (q n), basisCos n S x * basisCos n T x := by
  rw [basisCos_cont_orthogonal, basisCos_discrete_orthogonal]
  have hq : (q n : ℝ) ≠ 0 := Nat.cast_ne_zero.mpr (NeZero.ne (q n))
  split
  · field_simp
  · ring

/-- Exact Riemann sum quadrature for products of three basis cosines. -/
theorem basisCos_triple_product_quadrature (n : ℕ) (R S T : Finset (Fin (w n))) :
    ∫ t, basisCos_cont n R t * basisCos_cont n S t * basisCos_cont n T t ∂μ₀ =
      (1 / (q n : ℝ)) *
        ∑ x ∈ Finset.range (q n), basisCos n R x * basisCos n S x * basisCos n T x := by
  rw [basisCos_triple_orthogonal_cont, basisCos_triple_orthogonal_discrete]
  have hq : (q n : ℝ) ≠ 0 := Nat.cast_ne_zero.mpr (NeZero.ne (q n))
  split
  · field_simp
  · ring

/-- Products of three continuous basis cosines are integrable. -/
lemma integrable_basisCos_triple (n : ℕ) (R S T : Finset (Fin (w n))) :
    Integrable (fun t => basisCos_cont n R t * basisCos_cont n S t * basisCos_cont n T t) μ₀ :=
  (((basisCos_cont_continuous n R).mul (basisCos_cont_continuous n S)).mul
    (basisCos_cont_continuous n T)).integrable_of_hasCompactSupport
    (HasCompactSupport.of_compactSpace _)

/-- The `Lp` coercion of `coeCLM₀ n h` agrees almost everywhere with the honest continuous
function `coeFun_H₀ n h`. -/
lemma coeCLM₀_coeFn_ae (n : ℕ) (h : H₀ n) :
    (coeCLM₀ n h : X₀ → ℝ) =ᵐ[μ₀] coeFun_H₀ n h := by
  have hclm : (coeCLM₀ n h : X₀ → ℝ)
      = (ContinuousMap.toLp (E := ℝ) 2 μ₀ ℝ
          ⟨coeFun_H₀ n h, coeFun_H₀_continuous n h⟩ : X₀ → ℝ) := by
    rfl
  rw [hclm]
  exact ContinuousMap.coeFn_toLp (E := ℝ) (𝕜 := ℝ) (p := 2) μ₀
    ⟨coeFun_H₀ n h, coeFun_H₀_continuous n h⟩

/-- The grid samples of an RKHS element expand as a linear combination of the discrete
basis cosines. -/
lemma evalOnGrid_mem_eq (n : ℕ) (h : H₀ n) (x : ℕ) :
    evalOnGrid n h x =
      ∑ S : Finset (Fin (w n)), (h : Finset (Fin (w n)) → ℝ) S * basisCos n S (x : ZMod (q n)) := by
  unfold evalOnGrid
  change coeCLM_H₀ n h (gridPt n x) = _
  rw [coeCLM_H₀_apply]
  unfold coeFun_H₀
  rw [Finset.powerset_univ]
  refine Finset.sum_congr rfl fun S _ => ?_
  rw [basisCos_cont_gridPt]

/-- Exact reproducing quadrature for a product of cosines against the continuous window
`Psi_cont`, provided the total absolute frequency is at most `kernelDegree n`. This is the
key property of the Dirichlet-kernel window: the continuous integral against `Psi_cont`
equals the corresponding windowed grid sum, with no error. -/
lemma prod_cos_Psi_cont_repro (n : ℕ) {ι : Type*} (A : Finset ι) (g : ι → ℤ)
    (hM : ∑ i ∈ A, (g i).natAbs ≤ kernelDegree n) :
    ∫ t : X₀, (∏ i ∈ A, Real.cos (2 * Real.pi * (g i : ℝ) * (t : ℝ))) * Psi_cont n t ∂μ₀ =
      (1 / (q n : ℝ)) * ∑ y ∈ Finset.range (q n),
        Psi n (y : ZMod (q n)) *
          ∏ i ∈ A, Real.cos (2 * Real.pi * (g i : ℝ) * ((y : ℝ) / (q n : ℝ))) := by
  exact prod_cos_reproWindow (q n) (kernelDegree n) (fun y => Psi n (y : ZMod (q n))) A g hM

/-- The cardinality of any `S : Finset (Fin (w n))` is at most `w n`. -/
lemma card_finset_fin_w_le (n : ℕ) (S : Finset (Fin (w n))) : S.card ≤ w n := by
  simpa using (Finset.card_le_card (Finset.subset_univ S)).trans_eq (by simp)

/-- Frequency bound: the total absolute frequency of the pair product
`basisCos_cont S · basisCos_cont T` is at most `kernelDegree n`. -/
lemma basisCos_pair_freq_bound (n : ℕ) (S T : Finset (Fin (w n))) :
    ∑ x ∈ S.disjSum T,
        (Sum.elim (fun i => ((3 * (q n / p n i) : ℕ) : ℤ))
          (fun i => ((3 * (q n / p n i) : ℕ) : ℤ)) x).natAbs
      ≤ kernelDegree n := by
  rw [Finset.sum_disjSum]
  simp only [Sum.elim_inl, Sum.elim_inr, Int.natAbs_natCast]
  have hbound : ∀ (U : Finset (Fin (w n))), ∑ i ∈ U, (3 * (q n / p n i)) ≤ 3 * (w n * q n) := by
    intro U
    calc ∑ i ∈ U, (3 * (q n / p n i)) ≤ ∑ _i ∈ U, (3 * q n) := by
            apply Finset.sum_le_sum; intro i _
            exact Nat.mul_le_mul_left 3 (Nat.div_le_self _ _)
      _ = U.card * (3 * q n) := by rw [Finset.sum_const, smul_eq_mul]
      _ ≤ w n * (3 * q n) := Nat.mul_le_mul_right _ (card_finset_fin_w_le n U)
      _ = 3 * (w n * q n) := by ring
  have h1 := hbound S
  have h2 := hbound T
  have hk : kernelDegree n = 6 * (w n * q n) + q n := by unfold kernelDegree; ring
  omega

/-- **Key windowed quadrature (denominator).** The continuous integral of a product of two basis
cosines against `Psi_cont` equals the windowed discrete grid sum, exactly. -/
lemma basisCos_pair_Psi_quadrature (n : ℕ) (S T : Finset (Fin (w n))) :
    ∫ t, basisCos_cont n S t * basisCos_cont n T t * Psi_cont n t ∂μ₀ =
      (1 / (q n : ℝ)) * ∑ x ∈ Finset.range (q n),
        basisCos n S ↑x * basisCos n T ↑x * Psi n ↑x := by
  classical
  set G : Fin (w n) → ℤ := fun i => ((3 * (q n / p n i) : ℕ) : ℤ) with hG
  have hpt : ∀ t : X₀, basisCos_cont n S t * basisCos_cont n T t
      = ∏ x ∈ S.disjSum T, Real.cos (2 * Real.pi * ((Sum.elim G G x : ℤ) : ℝ) * (t : ℝ)) := by
    intro t
    rw [basisCos_cont_eq n S t, basisCos_cont_eq n T t]
    simp only [Finset.prod_disjSum, Sum.elim_inl, Sum.elim_inr, hG]
  have hint : (∫ t, basisCos_cont n S t * basisCos_cont n T t * Psi_cont n t ∂μ₀)
      = ∫ t : X₀, (∏ x ∈ S.disjSum T,
          Real.cos (2 * Real.pi * ((Sum.elim G G x : ℤ) : ℝ) * (t : ℝ))) * Psi_cont n t ∂μ₀ := by
    apply MeasureTheory.integral_congr_ae
    filter_upwards with t
    rw [hpt t]
  rw [hint, prod_cos_Psi_cont_repro n (S.disjSum T) (Sum.elim G G) (basisCos_pair_freq_bound n S T)]
  congr 1
  apply Finset.sum_congr rfl
  intro y hy
  have hgrid : ((y : ℝ) / (q n : ℝ)) = ((gridPt n y : X₀) : ℝ) := by
    rw [show ((gridPt n y : X₀) : ℝ) = ((y % q n : ℕ) : ℝ) / (q n : ℝ) from rfl,
        Nat.mod_eq_of_lt (Finset.mem_range.mp hy)]
  rw [hgrid]
  have hprod : (∏ x ∈ S.disjSum T,
        Real.cos (2 * Real.pi * ((Sum.elim G G x : ℤ) : ℝ) * ((gridPt n y : X₀) : ℝ)))
      = basisCos_cont n S (gridPt n y) * basisCos_cont n T (gridPt n y) := (hpt (gridPt n y)).symm
  rw [hprod, basisCos_cont_gridPt, basisCos_cont_gridPt]
  ring

/-- Pure algebraic rearrangement underlying the L² quadrature: a double sum of pairwise windowed
inner products equals the windowed norm of the linear combination. -/
private lemma sq_sum_swap {ι κ : Type*} (P : Finset ι) (R : Finset κ) (c : ι → ℝ)
    (f : ι → κ → ℝ) (ψ : κ → ℝ) (r : ℝ) :
    ∑ S ∈ P, ∑ T ∈ P, c S * c T * (r * ∑ x ∈ R, f S x * f T x * ψ x)
      = r * ∑ x ∈ R, (∑ S ∈ P, c S * f S x) ^ 2 * ψ x := by
  have hL : ∑ S ∈ P, ∑ T ∈ P, c S * c T * (r * ∑ x ∈ R, f S x * f T x * ψ x)
      = ∑ x ∈ R, ∑ S ∈ P, ∑ T ∈ P, r * ((c S * f S x) * (c T * f T x) * ψ x) := by
    simp only [Finset.mul_sum]
    rw [Finset.sum_congr rfl (fun S _ => Finset.sum_comm)]
    rw [Finset.sum_comm]
    exact Finset.sum_congr rfl (fun x _ => Finset.sum_congr rfl
      (fun S _ => Finset.sum_congr rfl (fun T _ => by ring)))
  rw [hL, Finset.mul_sum]
  refine Finset.sum_congr rfl (fun x _ => ?_)
  rw [sq, Finset.sum_mul_sum, Finset.sum_mul, Finset.mul_sum]
  refine Finset.sum_congr rfl (fun S _ => ?_)
  rw [Finset.sum_mul, Finset.mul_sum]

/-- The windowed L² quadrature for a linear combination of continuous basis cosines: the continuous
integral against `Psi_cont` equals the windowed discrete grid sum, exactly. -/
lemma sq_sum_Psi_quadrature (n : ℕ) (c : Finset (Fin (w n)) → ℝ) :
    ∫ t : X₀, (∑ S ∈ Finset.univ.powerset, c S * basisCos_cont n S t) ^ 2 * Psi_cont n t ∂μ₀
      = (1 / (q n : ℝ)) * ∑ x ∈ Finset.range (q n),
          (∑ S ∈ Finset.univ.powerset, c S * basisCos n S ↑x) ^ 2 * Psi n ↑x := by
  classical
  have hcont : ∀ S T : Finset (Fin (w n)),
      Continuous (fun t : X₀ => basisCos_cont n S t * basisCos_cont n T t * Psi_cont n t) :=
    fun S T => ((basisCos_cont_continuous n S).mul (basisCos_cont_continuous n T)).mul
      (Psi_cont_continuous n)
  have hexp : ∀ t : X₀,
      (∑ S ∈ Finset.univ.powerset, c S * basisCos_cont n S t) ^ 2 * Psi_cont n t
      = ∑ S ∈ Finset.univ.powerset, ∑ T ∈ Finset.univ.powerset,
          (c S * c T) * (basisCos_cont n S t * basisCos_cont n T t * Psi_cont n t) := by
    intro t
    rw [sq, Finset.sum_mul_sum, Finset.sum_mul]
    refine Finset.sum_congr rfl (fun S _ => ?_)
    rw [Finset.sum_mul]
    exact Finset.sum_congr rfl (fun T _ => by ring)
  have hintegrable : ∀ S ∈ Finset.univ.powerset,
      Integrable (fun t : X₀ => ∑ T ∈ Finset.univ.powerset,
        (c S * c T) * (basisCos_cont n S t * basisCos_cont n T t * Psi_cont n t)) μ₀ := by
    intro S _
    exact (continuous_finsetSum _ (fun T _ => continuous_const.mul
      (hcont S T))).integrable_of_hasCompactSupport (HasCompactSupport.of_compactSpace _)
  have hintegrable2 : ∀ (S : Finset (Fin (w n))), ∀ T ∈ Finset.univ.powerset,
      Integrable (fun t : X₀ =>
        (c S * c T) * (basisCos_cont n S t * basisCos_cont n T t * Psi_cont n t)) μ₀ := by
    intro S T _
    exact (continuous_const.mul (hcont S T)).integrable_of_hasCompactSupport
      (HasCompactSupport.of_compactSpace _)
  rw [MeasureTheory.integral_congr_ae (Filter.Eventually.of_forall hexp)]
  rw [MeasureTheory.integral_finsetSum _ hintegrable]
  have hinner : ∀ S ∈ Finset.univ.powerset,
      (∫ t : X₀, ∑ T ∈ Finset.univ.powerset,
          (c S * c T) * (basisCos_cont n S t * basisCos_cont n T t * Psi_cont n t) ∂μ₀)
        = ∑ T ∈ Finset.univ.powerset,
          (c S * c T) * ((1 / (q n : ℝ)) * ∑ x ∈ Finset.range (q n),
            basisCos n S ↑x * basisCos n T ↑x * Psi n ↑x) := by
    intro S _
    rw [MeasureTheory.integral_finsetSum _ (hintegrable2 S)]
    refine Finset.sum_congr rfl (fun T _ => ?_)
    rw [MeasureTheory.integral_const_mul, basisCos_pair_Psi_quadrature]
  rw [Finset.sum_congr rfl hinner]
  exact sq_sum_swap Finset.univ.powerset (Finset.range (q n)) c
    (fun S x => basisCos n S ↑x) (fun x => Psi n ↑x) (1 / (q n : ℝ))

/-- Denominator Quadrature (L² Norm Equivalence) -/
theorem denominator_quadrature (n : ℕ) (h : H₀ n) :
    |∫ x, ((coeCLM₀ n h : X₀ → ℝ) x) ^ 2 * Psi_cont n x ∂μ₀ -
      (1 / (q n : ℝ)) * ∑ x ∈ Finset.range (q n), (evalOnGrid n h x) ^ 2 * Psi n ↑x|
      ≤ denominator_error n * ‖coeCLM₀ n h‖ ^ 2 := by
  rw [denominator_error, zero_mul, abs_nonpos_iff, sub_eq_zero]
  have hae : (fun x => ((coeCLM₀ n h : X₀ → ℝ) x) ^ 2 * Psi_cont n x)
      =ᵐ[μ₀] (fun t => (∑ S ∈ Finset.univ.powerset,
          (h : Finset (Fin (w n)) → ℝ) S * basisCos_cont n S t) ^ 2 * Psi_cont n t) := by
    filter_upwards [coeCLM₀_coeFn_ae n h] with x hx
    rw [hx]; rfl
  rw [MeasureTheory.integral_congr_ae hae,
    sq_sum_Psi_quadrature n (h : Finset (Fin (w n)) → ℝ)]
  congr 1
  refine Finset.sum_congr rfl (fun x _ => ?_)
  rw [evalOnGrid_mem_eq, Finset.powerset_univ]

/-- Products of `c_cont₀` with two continuous basis cosines are integrable. -/
lemma integrable_c_cont₀_basisCos_prod (n : ℕ) (S T : Finset (Fin (w n))) :
    Integrable (fun t => c_cont₀ n t * basisCos_cont n S t * basisCos_cont n T t) μ₀ := by
  have hc : Continuous (c_cont₀ n) := by unfold c_cont₀; fun_prop
  exact (((hc.mul (basisCos_cont_continuous n S)).mul
    (basisCos_cont_continuous n T)).integrable_of_hasCompactSupport
    (HasCompactSupport.of_compactSpace _))

/-- Rewrite a single cosine term of `c_cont₀` with its explicit integer frequency `k * (q / p i)`.
-/
lemma c_cont_cos_eq (n : ℕ) (i : Fin (w n)) (k : ℕ) (t : X₀) :
    Real.cos (2 * Real.pi * (k : ℝ) * (t : ℝ) * (q n : ℝ) / (p n i : ℝ))
      = Real.cos (2 * Real.pi * (((k * (q n / p n i) : ℕ) : ℤ) : ℝ) * (t : ℝ)) := by
  congr 1
  have hpi : (p n i : ℝ) ≠ 0 := by exact_mod_cast p_ne_zero n i
  rw [Int.cast_natCast, Nat.cast_mul, Nat.cast_div (p_dvd_q n i) hpi]
  field_simp

/-- The absolute frequency of a `c_cont₀` cosine term is at most `q n` (for the summation range). -/
lemma c_cont_term_natAbs_le (n : ℕ) (i : Fin (w n)) (k : ℕ)
    (hk : k ∈ Finset.range ((p n i + 1) / 2)) :
    (((k * (q n / p n i) : ℕ) : ℤ)).natAbs ≤ q n := by
  rw [Int.natAbs_natCast]
  have hkp : k ≤ p n i := by
    rw [Finset.mem_range] at hk; omega
  calc k * (q n / p n i) ≤ p n i * (q n / p n i) := Nat.mul_le_mul_right _ hkp
    _ = q n := Nat.mul_div_cancel' (p_dvd_q n i)

/-- Tighter frequency bound for a pair product: total absolute frequency is at most
`6 * (w * q)`. -/
lemma basisCos_pair_freq_bound_tight (n : ℕ) (S T : Finset (Fin (w n))) :
    ∑ x ∈ S.disjSum T,
        (Sum.elim (fun i => ((3 * (q n / p n i) : ℕ) : ℤ))
          (fun i => ((3 * (q n / p n i) : ℕ) : ℤ)) x).natAbs
      ≤ 6 * (w n * q n) := by
  rw [Finset.sum_disjSum]
  simp only [Sum.elim_inl, Sum.elim_inr, Int.natAbs_natCast]
  have hbound : ∀ (U : Finset (Fin (w n))), ∑ i ∈ U, (3 * (q n / p n i)) ≤ 3 * (w n * q n) := by
    intro U
    calc ∑ i ∈ U, (3 * (q n / p n i)) ≤ ∑ _i ∈ U, (3 * q n) := by
            apply Finset.sum_le_sum; intro i _
            exact Nat.mul_le_mul_left 3 (Nat.div_le_self _ _)
      _ = U.card * (3 * q n) := by rw [Finset.sum_const, smul_eq_mul]
      _ ≤ w n * (3 * q n) := Nat.mul_le_mul_right _ (card_finset_fin_w_le n U)
      _ = 3 * (w n * q n) := by ring
  have h1 := hbound S
  have h2 := hbound T
  omega

open scoped Classical in
/-- **Key windowed quadrature with an extra cosine factor.** Integrating `cos(2π m t)` times a pair
of basis cosines against `Psi_cont` reproduces exactly the corresponding windowed grid sum, provided
the total absolute frequency (including `m`) is at most `kernelDegree n`. -/
lemma cos_basisCos_pair_Psi_quadrature (n : ℕ) (m : ℤ) (S T : Finset (Fin (w n)))
    (hm : m.natAbs + ∑ x ∈ S.disjSum T,
        (Sum.elim (fun i => ((3 * (q n / p n i) : ℕ) : ℤ))
          (fun i => ((3 * (q n / p n i) : ℕ) : ℤ)) x).natAbs ≤ kernelDegree n) :
    ∫ t, Real.cos (2 * Real.pi * (m : ℝ) * (t : ℝ)) *
        basisCos_cont n S t * basisCos_cont n T t * Psi_cont n t ∂μ₀
      = (1 / (q n : ℝ)) * ∑ y ∈ Finset.range (q n),
          Real.cos (2 * Real.pi * (m : ℝ) * ((gridPt n y : X₀) : ℝ)) *
            basisCos n S ↑y * basisCos n T ↑y * Psi n ↑y := by
  classical
  set G : Fin (w n) → ℤ := fun i => ((3 * (q n / p n i) : ℕ) : ℤ) with hG
  set g : Option (Fin (w n) ⊕ Fin (w n)) → ℤ :=
    fun o => o.elim m (Sum.elim G G) with hg
  set A : Finset (Option (Fin (w n) ⊕ Fin (w n))) :=
    insert none ((S.disjSum T).map Function.Embedding.some) with hA
  have hnone : none ∉ (S.disjSum T).map Function.Embedding.some := by simp
  have hprodpt : ∀ t : X₀,
      Real.cos (2 * Real.pi * (m : ℝ) * (t : ℝ)) * basisCos_cont n S t * basisCos_cont n T t
        = ∏ x ∈ A, Real.cos (2 * Real.pi * ((g x : ℤ) : ℝ) * (t : ℝ)) := by
    intro t
    have hbc : basisCos_cont n S t * basisCos_cont n T t
        = ∏ x ∈ S.disjSum T, Real.cos (2 * Real.pi * ((Sum.elim G G x : ℤ) : ℝ) * (t : ℝ)) := by
      rw [basisCos_cont_eq n S t, basisCos_cont_eq n T t]
      simp only [Finset.prod_disjSum, Sum.elim_inl, Sum.elim_inr, hG]
    rw [hA, Finset.prod_insert hnone, Finset.prod_map]
    have hmap : ∀ x ∈ S.disjSum T,
        Real.cos (2 * Real.pi * ((g (Function.Embedding.some x) : ℤ) : ℝ) * (t : ℝ))
          = Real.cos (2 * Real.pi * ((Sum.elim G G x : ℤ) : ℝ) * (t : ℝ)) := by
      intro x _; simp [hg]
    rw [Finset.prod_congr rfl hmap, ← hbc]
    simp only [hg, Option.elim_none]
    ring
  have hfreq : ∑ x ∈ A, (g x).natAbs ≤ kernelDegree n := by
    rw [hA, Finset.sum_insert hnone, Finset.sum_map]
    have hmap : ∀ x ∈ S.disjSum T,
        (g (Function.Embedding.some x)).natAbs = (Sum.elim G G x).natAbs := by
      intro x _; simp [hg]
    rw [Finset.sum_congr rfl hmap]
    simpa [hg, hG] using hm
  have hint : (∫ t, Real.cos (2 * Real.pi * (m : ℝ) * (t : ℝ)) *
        basisCos_cont n S t * basisCos_cont n T t * Psi_cont n t ∂μ₀)
      = ∫ t : X₀, (∏ x ∈ A, Real.cos (2 * Real.pi * ((g x : ℤ) : ℝ) * (t : ℝ)))
      * Psi_cont n t ∂μ₀ := by
    apply MeasureTheory.integral_congr_ae
    filter_upwards with t
    rw [← hprodpt t]
  rw [hint, prod_cos_Psi_cont_repro n A g hfreq]
  congr 1
  apply Finset.sum_congr rfl
  intro y hy
  have hgrid : ((y : ℝ) / (q n : ℝ)) = ((gridPt n y : X₀) : ℝ) := by
    rw [show ((gridPt n y : X₀) : ℝ) = ((y % q n : ℕ) : ℝ) / (q n : ℝ) from rfl,
        Nat.mod_eq_of_lt (Finset.mem_range.mp hy)]
  rw [hgrid, ← hprodpt (gridPt n y), basisCos_cont_gridPt, basisCos_cont_gridPt]
  ring

/-- Pure algebraic rearrangement for the numerator quadrature: a double sum of per-frequency
weighted grid sums equals the grid sum of the assembled weight. -/
private lemma triple_sum_swap {ι1 ι2 κ : Type*} (Ii : Finset ι1) (Ki : ι1 → Finset ι2)
    (R : Finset κ) (a : ι1 → ι2 → ℝ) (Gg : ι1 → ι2 → κ → ℝ) (Hh : κ → ℝ) (r : ℝ) :
    ∑ i ∈ Ii, ∑ k ∈ Ki i, a i k * (r * ∑ y ∈ R, Gg i k y * Hh y)
      = r * ∑ y ∈ R, (∑ i ∈ Ii, ∑ k ∈ Ki i, a i k * Gg i k y) * Hh y := by
  have hL : ∑ i ∈ Ii, ∑ k ∈ Ki i, a i k * (r * ∑ y ∈ R, Gg i k y * Hh y)
      = ∑ y ∈ R, ∑ i ∈ Ii, ∑ k ∈ Ki i, r * (a i k * Gg i k y * Hh y) := by
    simp only [Finset.mul_sum]
    rw [Finset.sum_congr rfl (fun i _ => Finset.sum_comm)]
    rw [Finset.sum_comm]
    exact Finset.sum_congr rfl (fun y _ => Finset.sum_congr rfl
      (fun i _ => Finset.sum_congr rfl (fun k _ => by ring)))
  rw [hL, Finset.mul_sum]
  refine Finset.sum_congr rfl (fun y _ => ?_)
  rw [Finset.sum_mul, Finset.mul_sum]
  refine Finset.sum_congr rfl (fun i _ => ?_)
  rw [Finset.sum_mul, Finset.mul_sum]

/-- Approximate Riemann sum quadrature for the majorant weight `c_cont₀` times a product of two
basis cosines. -/
theorem c_cont₀_basisCos_product_quadrature (n : ℕ) (S T : Finset (Fin (w n))) :
    |∫ t, c_cont₀ n t * basisCos_cont n S t * basisCos_cont n T t * Psi_cont n t ∂μ₀ -
      (1 / (q n : ℝ)) *
        ∑ x ∈ Finset.range (q n),
          c_cont₀ n (gridPt n x) * basisCos n S x * basisCos n T x * Psi n ↑x|
      ≤ numerator_error n := by
  classical
  rw [numerator_error, abs_nonpos_iff, sub_eq_zero]
  -- continuity of a single c_cont₀-frequency term times the pair and window
  have hcont_term : ∀ (i : Fin (w n)) (k : ℕ),
      Continuous (fun t : X₀ => Real.cos (2 * Real.pi * (k : ℝ) * (t : ℝ) * (q n : ℝ)
        / (p n i : ℝ)) *
        basisCos_cont n S t * basisCos_cont n T t * Psi_cont n t) := by
    intro i k
    exact ((((by fun_prop : Continuous (fun t : X₀ =>
      Real.cos (2 * Real.pi * (k : ℝ) * (t : ℝ) * (q n : ℝ) / (p n i : ℝ)))).mul
      (basisCos_cont_continuous n S)).mul (basisCos_cont_continuous n T)).mul
        (Psi_cont_continuous n))
  -- the per-frequency exact quadrature
  have hterm : ∀ (i : Fin (w n)) (k : ℕ), k ∈ Finset.range ((p n i + 1) / 2) →
      (∫ t : X₀, Real.cos (2 * Real.pi * (k : ℝ) * (t : ℝ) * (q n : ℝ) / (p n i : ℝ)) *
          basisCos_cont n S t * basisCos_cont n T t * Psi_cont n t ∂μ₀)
        = (1 / (q n : ℝ)) * ∑ y ∈ Finset.range (q n),
            Real.cos (2 * Real.pi * (k : ℝ) * ((gridPt n y : X₀) : ℝ) * (q n : ℝ) / (p n i : ℝ)) *
              (basisCos n S ↑y * basisCos n T ↑y * Psi n ↑y) := by
    intro i k hk
    have hfreqbound : (((k * (q n / p n i) : ℕ) : ℤ)).natAbs +
        ∑ x ∈ S.disjSum T, (Sum.elim (fun i => ((3 * (q n / p n i) : ℕ) : ℤ))
          (fun i => ((3 * (q n / p n i) : ℕ) : ℤ)) x).natAbs ≤ kernelDegree n := by
      have h1 := c_cont_term_natAbs_le n i k hk
      have h2 := basisCos_pair_freq_bound_tight n S T
      have hk2 : kernelDegree n = 6 * (w n * q n) + q n := by unfold kernelDegree; ring
      omega
    have he1 : (fun t : X₀ => Real.cos (2 * Real.pi * (k : ℝ) * (t : ℝ) * (q n : ℝ) / (p n i : ℝ)) *
          basisCos_cont n S t * basisCos_cont n T t * Psi_cont n t)
        = fun t : X₀ => Real.cos (2 * Real.pi * (((k * (q n / p n i) : ℕ) : ℤ) : ℝ) * (t : ℝ)) *
            basisCos_cont n S t * basisCos_cont n T t * Psi_cont n t := by
      funext t; rw [c_cont_cos_eq]
    rw [he1, cos_basisCos_pair_Psi_quadrature n ((k * (q n / p n i) : ℕ) : ℤ) S T hfreqbound]
    congr 1
    refine Finset.sum_congr rfl (fun y _ => ?_)
    rw [← c_cont_cos_eq]
    ring
  -- expand c_cont₀ and pull the sums out of the integral
  have hInt2 : ∀ (i : Fin (w n)), ∀ k ∈ Finset.range ((p n i + 1) / 2),
      Integrable (fun t : X₀ => g_coef n i k *
        (Real.cos (2 * Real.pi * (k : ℝ) * (t : ℝ) * (q n : ℝ) / (p n i : ℝ)) *
          basisCos_cont n S t * basisCos_cont n T t * Psi_cont n t)) μ₀ := by
    intro i k _
    exact (continuous_const.mul (hcont_term i k)).integrable_of_hasCompactSupport
      (HasCompactSupport.of_compactSpace _)
  have hInt1 : ∀ i ∈ (Finset.univ : Finset (Fin (w n))),
      Integrable (fun t : X₀ => ∑ k ∈ Finset.range ((p n i + 1) / 2), g_coef n i k *
        (Real.cos (2 * Real.pi * (k : ℝ) * (t : ℝ) * (q n : ℝ) / (p n i : ℝ)) *
          basisCos_cont n S t * basisCos_cont n T t * Psi_cont n t)) μ₀ := by
    intro i _
    exact (continuous_finsetSum _ (fun k _ => continuous_const.mul
      (hcont_term i k))).integrable_of_hasCompactSupport (HasCompactSupport.of_compactSpace _)
  have hLHS : (∫ t : X₀, c_cont₀ n t * basisCos_cont n S t * basisCos_cont n T t * Psi_cont n t ∂μ₀)
      = ∑ i : Fin (w n), ∑ k ∈ Finset.range ((p n i + 1) / 2),
          g_coef n i k * (∫ t : X₀, Real.cos (2 * Real.pi * (k : ℝ) * (t : ℝ) * (q n : ℝ)
          / (p n i : ℝ)) *
            basisCos_cont n S t * basisCos_cont n T t * Psi_cont n t ∂μ₀) := by
    have he : (fun t : X₀ => c_cont₀ n t * basisCos_cont n S t * basisCos_cont n T t * Psi_cont n t)
        = fun t : X₀ => ∑ i : Fin (w n), ∑ k ∈ Finset.range ((p n i + 1) / 2),
            g_coef n i k * (Real.cos (2 * Real.pi * (k : ℝ) * (t : ℝ) * (q n : ℝ) / (p n i : ℝ)) *
              basisCos_cont n S t * basisCos_cont n T t * Psi_cont n t) := by
      funext t
      simp only [c_cont₀, Finset.sum_mul]
      exact Finset.sum_congr rfl (fun i _ => Finset.sum_congr rfl (fun k _ => by ring))
    rw [he, MeasureTheory.integral_finsetSum _ hInt1]
    refine Finset.sum_congr rfl (fun i _ => ?_)
    rw [MeasureTheory.integral_finsetSum _ (hInt2 i)]
    exact Finset.sum_congr rfl (fun k _ => by rw [MeasureTheory.integral_const_mul])
  rw [hLHS]
  rw [Finset.sum_congr rfl (fun i _ => Finset.sum_congr rfl (fun k hk => by rw [hterm i k hk]))]
  rw [triple_sum_swap Finset.univ (fun i => Finset.range ((p n i + 1) / 2)) (Finset.range (q n))
    (fun i k => g_coef n i k)
    (fun i k y =>
      Real.cos (2 * Real.pi * (k : ℝ) * ((gridPt n y : X₀) : ℝ) * (q n : ℝ) / (p n i : ℝ)))
    (fun y => basisCos n S ↑y * basisCos n T ↑y * Psi n ↑y) (1 / (q n : ℝ))]
  congr 1
  refine Finset.sum_congr rfl (fun x _ => ?_)
  rw [show c_cont₀ n (gridPt n x) = ∑ i : Fin (w n), ∑ k ∈ Finset.range ((p n i + 1) / 2),
        g_coef n i k *
          Real.cos (2 * Real.pi * (k : ℝ) * ((gridPt n x : X₀) : ℝ) * (q n : ℝ) / (p n i : ℝ)) from
            rfl]
  ring

/-- The windowed weighted quadrature for a linear combination of continuous basis cosines: the
continuous integral of `c_cont₀ · (∑ c_S bc_S)²` against `Psi_cont` equals the windowed discrete
grid sum, exactly. -/
lemma c_cont₀_sq_sum_Psi_quadrature (n : ℕ) (c : Finset (Fin (w n)) → ℝ) :
    ∫ t : X₀, c_cont₀ n t * (∑ S ∈ Finset.univ.powerset, c S * basisCos_cont n S t) ^ 2 *
        Psi_cont n t ∂μ₀
      = (1 / (q n : ℝ)) * ∑ x ∈ Finset.range (q n),
          c_cont₀ n (gridPt n x) *
            (∑ S ∈ Finset.univ.powerset, c S * basisCos n S ↑x) ^ 2 * Psi n ↑x := by
  classical
  have hcc : Continuous (c_cont₀ n) := by unfold c_cont₀; fun_prop
  have hcont : ∀ S T : Finset (Fin (w n)),
      Continuous (fun t : X₀ => c_cont₀ n t * basisCos_cont n S t * basisCos_cont n T t *
        Psi_cont n t) :=
    fun S T => (((hcc.mul (basisCos_cont_continuous n S)).mul
      (basisCos_cont_continuous n T)).mul (Psi_cont_continuous n))
  have hexp : ∀ t : X₀,
      c_cont₀ n t * (∑ S ∈ Finset.univ.powerset, c S * basisCos_cont n S t) ^ 2 * Psi_cont n t
      = ∑ S ∈ Finset.univ.powerset, ∑ T ∈ Finset.univ.powerset, (c S * c T)
        * (c_cont₀ n t * basisCos_cont n S t * basisCos_cont n T t * Psi_cont n t) := by
    intro t
    rw [sq, Finset.sum_mul_sum, Finset.mul_sum, Finset.sum_mul]
    refine Finset.sum_congr rfl (fun S _ => ?_)
    rw [Finset.mul_sum, Finset.sum_mul]
    exact Finset.sum_congr rfl (fun T _ => by ring)
  have hInt2 : ∀ (S : Finset (Fin (w n))), ∀ T ∈ Finset.univ.powerset,
      Integrable (fun t : X₀ => (c S * c T) *
        (c_cont₀ n t * basisCos_cont n S t * basisCos_cont n T t * Psi_cont n t)) μ₀ :=
    fun S T _ => (continuous_const.mul (hcont S T)).integrable_of_hasCompactSupport
      (HasCompactSupport.of_compactSpace _)
  have hInt1 : ∀ S ∈ Finset.univ.powerset,
      Integrable (fun t : X₀ => ∑ T ∈ Finset.univ.powerset, (c S * c T) *
        (c_cont₀ n t * basisCos_cont n S t * basisCos_cont n T t * Psi_cont n t)) μ₀ :=
    fun S _ => (continuous_finsetSum _ (fun T _ => continuous_const.mul
      (hcont S T))).integrable_of_hasCompactSupport (HasCompactSupport.of_compactSpace _)
  rw [MeasureTheory.integral_congr_ae (Filter.Eventually.of_forall hexp)]
  rw [MeasureTheory.integral_finsetSum _ hInt1]
  have hinner : ∀ S ∈ Finset.univ.powerset,
      (∫ t : X₀, ∑ T ∈ Finset.univ.powerset, (c S * c T) *
          (c_cont₀ n t * basisCos_cont n S t * basisCos_cont n T t * Psi_cont n t) ∂μ₀)
        = ∑ T ∈ Finset.univ.powerset, (c S * c T) * ((1 / (q n : ℝ)) *
            ∑ x ∈ Finset.range (q n),
              basisCos n S ↑x * basisCos n T ↑x * (c_cont₀ n (gridPt n x) * Psi n ↑x)) := by
    intro S _
    rw [MeasureTheory.integral_finsetSum _ (hInt2 S)]
    refine Finset.sum_congr rfl (fun T _ => ?_)
    rw [MeasureTheory.integral_const_mul]
    have h2 := c_cont₀_basisCos_product_quadrature n S T
    rw [numerator_error, abs_nonpos_iff, sub_eq_zero] at h2
    have hswap : (∑ x ∈ Finset.range (q n),
          c_cont₀ n (gridPt n x) * basisCos n S x * basisCos n T x * Psi n ↑x)
        = ∑ x ∈ Finset.range (q n),
            basisCos n S ↑x * basisCos n T ↑x * (c_cont₀ n (gridPt n x) * Psi n ↑x) :=
      Finset.sum_congr rfl (fun x _ => by ring)
    rw [h2, hswap]
  rw [Finset.sum_congr rfl hinner]
  rw [sq_sum_swap Finset.univ.powerset (Finset.range (q n)) c (fun S x => basisCos n S ↑x)
    (fun x => c_cont₀ n (gridPt n x) * Psi n ↑x) (1 / (q n : ℝ))]
  congr 1
  exact Finset.sum_congr rfl (fun x _ => by ring)

/-- Numerator Quadrature (Weighted Norm Equivalence) -/
theorem numerator_quadrature (n : ℕ) (h : H₀ n) :
    |∫ x, c_cont₀ n x * ((coeCLM₀ n h : X₀ → ℝ) x) ^ 2 * Psi_cont n x ∂μ₀ -
      (1 / (q n : ℝ)) *
        ∑ x ∈ Finset.range (q n), c_cont₀ n (gridPt n x) * (evalOnGrid n h x) ^ 2 * Psi n ↑x|
      ≤ numerator_error n * ‖coeCLM₀ n h‖ ^ 2 := by
  rw [numerator_error, zero_mul, abs_nonpos_iff, sub_eq_zero]
  have hae : (fun x => c_cont₀ n x * ((coeCLM₀ n h : X₀ → ℝ) x) ^ 2 * Psi_cont n x)
      =ᵐ[μ₀] (fun t => c_cont₀ n t * (∑ S ∈ Finset.univ.powerset,
          (h : Finset (Fin (w n)) → ℝ) S * basisCos_cont n S t) ^ 2 * Psi_cont n t) := by
    filter_upwards [coeCLM₀_coeFn_ae n h] with x hx
    rw [hx]; rfl
  rw [MeasureTheory.integral_congr_ae hae,
    c_cont₀_sq_sum_Psi_quadrature n (h : Finset (Fin (w n)) → ℝ)]
  congr 1
  refine Finset.sum_congr rfl (fun x _ => ?_)
  rw [evalOnGrid_mem_eq, Finset.powerset_univ]

/-- The `L²` norm-squared of `coeCLM₀ n h` against `Psi_cont`, expressed as an integral,
is strictly positive whenever its norm is positive. -/
theorem denominator_pos (n : ℕ) (h : H₀ n)
    (hn : (∫ x, ((coeCLM₀ n h : X₀ → ℝ) x) ^ 2 * Psi_cont n x ∂μ₀) > 0) :
    (0 : ℝ) < ∫ x, ((coeCLM₀ n h : X₀ → ℝ) x) ^ 2 * Psi_cont n x ∂μ₀ := by
  exact hn

/-- The minimal sieve quotient `muMin n` is non-negative. -/
lemma muMin_nonneg (n : ℕ) : 0 ≤ muMin n := by
  unfold muMin
  apply le_csInf
  · exact ⟨_, lambdaOpt n, (lambda_opt_spec n).1, rfl⟩
  · rintro _ ⟨lambda, hlambda_pos, rfl⟩
    unfold Ratio
    split_ifs with hq
    · exact le_refl 0
    · apply div_nonneg _ hlambda_pos.le
      rw [q2_eq_spatialVector_weighted_norm]
      refine Finset.sum_nonneg fun x _ => ?_
      refine mul_nonneg (mul_nonneg (c_nonneg n _) (sq_nonneg _)) ?_
      unfold Psi; split_ifs <;> norm_num

/-- Discrete sieve quotient bound: `muMin n` times the discrete windowed denominator is at most
the discrete windowed numerator (using the discrete weight `c`). -/
lemma muMin_mul_denom_le_numer (n : ℕ) (h : H₀ n) :
    muMin n * ((1 / (q n : ℝ)) *
        ∑ x ∈ Finset.range (q n), (evalOnGrid n h x) ^ 2 * Psi n ↑x)
      ≤ (1 / (q n : ℝ)) *
        ∑ x ∈ Finset.range (q n), c n ↑x * (evalOnGrid n h x) ^ 2 * Psi n ↑x := by
  have hq0 : (0 : ℝ) < (q n : ℝ) := by
    have : q n ≠ 0 := NeZero.ne (q n)
    positivity
  have hqinv : (0 : ℝ) ≤ 1 / (q n : ℝ) := by positivity
  -- Non-negativity of the (windowed) denominator sum.
  have hA_nonneg : (0 : ℝ) ≤ ∑ x ∈ Finset.range (q n), (evalOnGrid n h x) ^ 2 * Psi n ↑x := by
    refine Finset.sum_nonneg fun x _ => ?_
    refine mul_nonneg (sq_nonneg _) ?_
    unfold Psi; split_ifs <;> norm_num
  rcases eq_or_lt_of_le hA_nonneg with hA0 | hApos
  · -- Denominator sum is zero, hence so is the numerator sum.
    have hterm : ∀ x ∈ Finset.range (q n), (evalOnGrid n h x) ^ 2 * Psi n ↑x = 0 := by
      intro x hx
      refine (Finset.sum_eq_zero_iff_of_nonneg ?_).1 hA0.symm x hx
      intro y _
      refine mul_nonneg (sq_nonneg _) ?_
      unfold Psi; split_ifs <;> norm_num
    have hB0 : (∑ x ∈ Finset.range (q n), c n ↑x * (evalOnGrid n h x) ^ 2 * Psi n ↑x) = 0 := by
      refine Finset.sum_eq_zero fun x hx => ?_
      have := hterm x hx
      rw [mul_assoc]
      rw [this, mul_zero]
    rw [← hA0, hB0]
    ring_nf
    simp
  · -- Denominator sum is positive: use the discrete Rayleigh quotient bound.
    have hApos' : (∑ x ∈ Finset.range (q n), (evalOnGrid n h x) ^ 2 * Psi n ↑x) ≠ 0 :=
      ne_of_gt hApos
    have hle := muMin_le_discreteRatio n h hApos
    have hsr : spatialRatio n (evalOnGrid n h)
        = (∑ x ∈ Finset.range (q n), c n ↑x * (evalOnGrid n h x) ^ 2 * Psi n ↑x)
          / (∑ x ∈ Finset.range (q n), (evalOnGrid n h x) ^ 2 * Psi n ↑x) := by
      unfold spatialRatio
      simp only [hApos', if_false]
    rw [hsr] at hle
    rw [le_div_iff₀ hApos] at hle
    -- hle : muMin n * A ≤ B
    calc muMin n * ((1 / (q n : ℝ)) *
            ∑ x ∈ Finset.range (q n), (evalOnGrid n h x) ^ 2 * Psi n ↑x)
        = (1 / (q n : ℝ)) * (muMin n *
            ∑ x ∈ Finset.range (q n), (evalOnGrid n h x) ^ 2 * Psi n ↑x) := by ring
      _ ≤ (1 / (q n : ℝ)) *
            ∑ x ∈ Finset.range (q n), c n ↑x * (evalOnGrid n h x) ^ 2 * Psi n ↑x :=
            mul_le_mul_of_nonneg_left hle hqinv

theorem krafft_quadrature_holds (n : ℕ) (h : H₀ n)
    (hn : (∫ x, ((coeCLM₀ n h : X₀ → ℝ) x) ^ 2 * Psi_cont n x ∂μ₀) > 0) :
    muMin n ≤ continuousRatio μ₀ (c_cont₀ n) (Psi_cont n) (coeCLM₀ n h) +
      (numerator_error n + muMin n * denominator_error n) * ‖coeCLM₀ n h‖ ^ 2 /
        (∫ x, ((coeCLM₀ n h : X₀ → ℝ) x) ^ 2 * Psi_cont n x ∂μ₀) := by
  -- Basic facts / building blocks (raw form, before abbreviating).
  have hmu := muMin_nonneg n
  have hsieve := muMin_mul_denom_le_numer n h
  have hnum := numerator_quadrature n h
  have hden := denominator_quadrature n h
  -- The discrete numerator with the true weight `c` is ≤ the one with the majorant `c_cont₀`.
  have hSc_le_Scc :
      (1 / (q n : ℝ)) *
          ∑ x ∈ Finset.range (q n), c n ↑x * (evalOnGrid n h x) ^ 2 * Psi n ↑x
        ≤ (1 / (q n : ℝ)) *
          ∑ x ∈ Finset.range (q n),
            c_cont₀ n (gridPt n x) * (evalOnGrid n h x) ^ 2 * Psi n ↑x := by
    apply mul_le_mul_of_nonneg_left _ (by positivity)
    apply Finset.sum_le_sum
    intro x _
    have hPsi : (0 : ℝ) ≤ Psi n ↑x := by unfold Psi; split_ifs <;> norm_num
    exact mul_le_mul_of_nonneg_right
      (mul_le_mul_of_nonneg_right (c_le_c_cont₀ n x) (sq_nonneg _)) hPsi
  -- Rewrite the continuous Rayleigh quotient as a plain quotient of integrals.
  have hcr : continuousRatio μ₀ (c_cont₀ n) (Psi_cont n) (coeCLM₀ n h)
      = (∫ x, c_cont₀ n x * ((coeCLM₀ n h : X₀ → ℝ) x) ^ 2 * Psi_cont n x ∂μ₀)
        / (∫ x, ((coeCLM₀ n h : X₀ → ℝ) x) ^ 2 * Psi_cont n x ∂μ₀) := by
    unfold continuousRatio
    rw [if_neg (ne_of_gt hn)]
  rw [hcr, ← add_div, le_div_iff₀ hn]
  -- Abbreviate the recurring integrals / sums / norm.
  set Dcont := ∫ x, ((coeCLM₀ n h : X₀ → ℝ) x) ^ 2 * Psi_cont n x ∂μ₀ with hDcont
  set Ncont := ∫ x, c_cont₀ n x * ((coeCLM₀ n h : X₀ → ℝ) x) ^ 2 * Psi_cont n x ∂μ₀ with hNcont
  set normsq := ‖coeCLM₀ n h‖ ^ 2 with hnormsq
  set Dd := (1 / (q n : ℝ)) *
      ∑ x ∈ Finset.range (q n), (evalOnGrid n h x) ^ 2 * Psi n ↑x with hDd
  set Sc := (1 / (q n : ℝ)) *
      ∑ x ∈ Finset.range (q n), c n ↑x * (evalOnGrid n h x) ^ 2 * Psi n ↑x with hSc
  set Scc := (1 / (q n : ℝ)) *
      ∑ x ∈ Finset.range (q n),
        c_cont₀ n (gridPt n x) * (evalOnGrid n h x) ^ 2 * Psi n ↑x with hScc
  -- Turn the quadrature error bounds into one-sided inequalities.
  have hnum_le : Scc ≤ Ncont + numerator_error n * normsq := by
    have := (abs_le.1 hnum).1
    linarith
  have hden_le : Dcont - denominator_error n * normsq ≤ Dd := by
    have := (abs_le.1 hden).2
    linarith
  -- Multiply the denominator bound by the non-negative `muMin n`.
  have hstep : muMin n * (Dcont - denominator_error n * normsq) ≤ muMin n * Dd :=
    mul_le_mul_of_nonneg_left hden_le hmu
  -- Chain everything together.
  have hbig : muMin n * (Dcont - denominator_error n * normsq)
      ≤ Ncont + numerator_error n * normsq :=
    le_trans hstep (le_trans hsieve (le_trans hSc_le_Scc hnum_le))
  nlinarith [hbig]

end KrafftSieve
