/-
Copyright (c) 2026 Fernando Portela. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Fernando Portela
-/

/-
Portions of this file were generated by Aristotle (https://aristotle.harmonic.fun).

Lean version: leanprover/lean4:v4.28.0
Mathlib version: 8f9d9cff6bd728b17a24e163c9402775d9e6a365

To cite Aristotle, tag @Aristotle-Harmonic on GitHub PRs/issues, and add as co-author to commits:
Co-authored-by: Aristotle (Harmonic) <aristotle-harmonic@harmonic.fun>
-/

import KrafftSieve.OptimalWeights
import Mathlib.Data.Pi.Interval

/-!
Core file: the genuinely-true lemmas for discrete orthogonality, proved WITHOUT the
false `sum_evalInterval_eq_range` stub in scope (so the environment is consistent).
-/

namespace KrafftSieve

open scoped BigOperators Real Nat

noncomputable section

/-
Chinese Remainder Theorem factorization of periodic product sums.
-/
theorem crt_product_sum_factorization (n : ℕ) (f : Fin (w n) → ℕ → ℝ)
    (hf : ∀ i x, f i (x + p n i) = f i x) :
    ∑ x ∈ Finset.range (q n), ∏ i : Fin (w n), f i x =
      ∏ i : Fin (w n), ∑ y ∈ Finset.range (p n i), f i y := by
  have h_crt : ∑ x ∈ Finset.range (∏ i : Fin (w n), p n i),
      ∏ i : Fin (w n), f i x = ∏ i : Fin (w n), ∑ y ∈ Finset.range (p n i), f i y := by
    have h_coprime : ∀ i j : Fin (w n), i ≠ j → Nat.Coprime (p n i) (p n j) := by
      intros i j hij
      have h_prime : Nat.Prime (p n i) ∧ Nat.Prime (p n j) := by
        exact ⟨ p_prime n i, p_prime n j ⟩
      have h_distinct : p n i ≠ p n j := by
        have h_distinct : List.Nodup (primesList n) := by
          exact Finset.sort_nodup _ _
        exact fun h => hij <| by have := List.nodup_iff_injective_get.mp h_distinct h; aesop
      exact Nat.coprime_primes h_prime.left h_prime.right |>.2 h_distinct
    -- By the Chinese Remainder Theorem, there is a bijection between the elements of the range of
    -- $q_n$ and the elements of the product of the ranges of $p_n i$.
    have h_crt_bij : ∃ g : (Fin (w n) → ℕ) → ℕ,
        ∀ x : (Fin (w n) → ℕ), (∀ i, x i < p n i) → g x < ∏ i, p n i ∧ ∀ i, g x % p n i = x i := by
      have h_crt_bij : ∀ x : Fin (w n) → ℕ,
          (∀ i, x i < p n i) → ∃ y, y < ∏ i, p n i ∧ ∀ i, y % p n i = x i := by
        intro x hx
        have h_crt : ∃ y, ∀ i, y ≡ x i [MOD p n i] := by
          have h_crt : ∀ i : Fin (w n), ∃ y, y ≡ x i [MOD p n i] ∧
                       ∀ j : Fin (w n), j ≠ i → y ≡ 0 [MOD p n j] := by
            intro i
            obtain ⟨y, hy⟩ : ∃ y, y ≡ 1 [MOD p n i] ∧
                                  y ≡ 0 [MOD (∏ j ∈ Finset.univ.erase i, p n j)] := by
              have := Nat.chineseRemainder ( show
                Nat.Coprime ( p n i ) ( ∏ j ∈ Finset.univ.erase i, p n j ) from
                Nat.Coprime.prod_right fun j hj => h_coprime i j <| by aesop )
              exact ⟨ _, this 1 0 |>.2 ⟩
            use y * x i
            exact ⟨ by simpa using hy.1.mul_right _, fun j hj =>
              Nat.modEq_zero_iff_dvd.mpr <| dvd_mul_of_dvd_left
              ( Nat.dvd_of_mod_eq_zero <| hy.2.of_dvd <| Finset.dvd_prod_of_mem _ <| by aesop ) _ ⟩
          choose y hy₁ hy₂ using h_crt
          use ∑ i, y i
          intro i
          rw [← ZMod.natCast_eq_natCast_iff]
          push_cast
          rw [Finset.sum_eq_single i]
          · have := hy₁ i
            rwa [← ZMod.natCast_eq_natCast_iff] at this
          · intro j _ hj
            have := hy₂ j i hj.symm
            rwa [← ZMod.natCast_eq_natCast_iff, Nat.cast_zero] at this
          · intro hi; exact (hi (Finset.mem_univ i)).elim
        obtain ⟨y, hy⟩ := h_crt
        use y % ∏ i, p n i
        have h_prod_pos : ∏ i, p n i > 0 := Finset.prod_pos fun i _ => p_pos n i
        refine ⟨Nat.mod_lt _ h_prod_pos, fun i => ?_⟩
        have h_div : p n i ∣ ∏ j, p n j := Finset.dvd_prod_of_mem _ (Finset.mem_univ i)
        rw [Nat.mod_mod_of_dvd y h_div]
        have hyi := hy i
        rwa [Nat.ModEq, Nat.mod_eq_of_lt (hx i)] at hyi
      exact ⟨ fun x => if hx : ∀ i, x i < p n i then Classical.choose ( h_crt_bij x hx ) else 0,
        fun x hx => by simpa [ hx ] using Classical.choose_spec ( h_crt_bij x hx ) ⟩
    obtain ⟨g, hg⟩ := h_crt_bij
    have h_crt_bij : Finset.image g (Finset.Iic (fun i => p n i - 1)) =
                     Finset.range (∏ i, p n i) := by
      refine Finset.eq_of_subset_of_card_le ( Finset.image_subset_iff.mpr ?_ ) ?_
      · exact fun x hx => Finset.mem_range.mpr ( hg x ( fun i =>
          Nat.lt_of_le_of_lt ( Finset.mem_Iic.mp hx i )
            ( Nat.pred_lt ( ne_bot_of_gt ( p_pos n i ) ) ) ) |>.1 )
      · rw [ Finset.card_image_of_injOn ]
        · erw [ Finset.card_map, Finset.card_pi ] ; norm_num
          exact Finset.prod_le_prod' fun i _ => by
            rw [ Nat.sub_add_cancel ( Nat.Prime.pos ( p_prime n i ) ) ]
        · intros x hx y hy hxy
          ext i
          have := hg x ( fun i => Nat.lt_of_le_of_lt ( Finset.mem_Iic.mp hx i )
            ( Nat.pred_lt ( ne_bot_of_gt ( p_pos n i ) ) ) )
          have := hg y ( fun i => Nat.lt_of_le_of_lt ( Finset.mem_Iic.mp hy i )
            ( Nat.pred_lt ( ne_bot_of_gt ( p_pos n i ) ) ) )
          aesop
    rw [ ← h_crt_bij, Finset.sum_image ]
    · rw [ Finset.prod_sum ]
      refine Finset.sum_bij (fun x _hx => fun i _ => x i) ?_ ?_ ?_ ?_
      · intro a ha
        simp only [Finset.mem_pi, Finset.mem_univ, Finset.mem_range, forall_true_left]
        intro i
        have := Finset.mem_Iic.mp ha i
        exact lt_of_le_of_lt this (Nat.pred_lt (ne_bot_of_gt (p_pos n i)))
      · intro a₁ _ ha₂ _ h_eq
        ext i
        have h_fun := congr_fun h_eq i
        exact congr_fun h_fun (Finset.mem_univ i)
      · intro b hb
        have hb_mem := Finset.mem_pi.mp hb
        refine ⟨fun i => b i (Finset.mem_univ i), ?_, ?_⟩
        · rw [Finset.mem_Iic]
          intro i
          have hb_lt := hb_mem i (Finset.mem_univ i)
          rw [Finset.mem_range] at hb_lt
          exact Nat.le_sub_one_of_lt hb_lt
        · ext i hi
          rfl
      · intro a ha
        simp only [Finset.prod_attach_univ]
        congr 1
        ext i
        rw [← Nat.mod_add_div (g a) (p n i)]
        have h_lt : ∀ i, a i < p n i := by
          intro i
          exact lt_of_le_of_lt (Finset.mem_Iic.mp ha i) (Nat.pred_lt (ne_bot_of_gt (p_pos n i)))
        rw [hg a h_lt |>.2 i]
        exact Nat.recOn (g a / p n i) rfl fun k hk => by
          rw [Nat.mul_succ, ← add_assoc, hf, hk]
    · intros x hx y hy hxy
      ext i
      have hx_lt : ∀ i, x i < p n i := fun i =>
        lt_of_le_of_lt (Finset.mem_Iic.mp hx i) (Nat.pred_lt (ne_bot_of_gt (p_pos n i)))
      have hy_lt : ∀ i, y i < p n i := fun i =>
        lt_of_le_of_lt (Finset.mem_Iic.mp hy i) (Nat.pred_lt (ne_bot_of_gt (p_pos n i)))
      have hg_x := hg x hx_lt |>.2 i
      have hg_y := hg y hy_lt |>.2 i
      rw [← hg_x, ← hg_y, hxy]
  convert h_crt using 1
  unfold q
  rw [ show primeWindow n = Finset.image ( fun i : Fin ( w n ) => p n i ) Finset.univ from ?_,
       Finset.prod_image ]
  · intro i hi j hj hij
    have h_inj : Function.Injective (fun i : Fin (w n) => p n i) := by
      intro i j hij
      have h_nodup : List.Nodup (primesList n) := Finset.sort_nodup _ _
      have h : w n = (primesList n).length := by
        unfold w primesList
        simp only [Finset.length_sort]
      exact Fin.cast_injective h (List.nodup_iff_injective_get.mp h_nodup hij)
    exact h_inj hij
  · rw [Finset.ext_iff]
    intro a
    rw [mem_P_n_iff_exists_index n a]
    simp only [Finset.mem_image, Finset.mem_univ, true_and]

/-
The sum of cosines modulo a prime `p n i` vanishes for non-zero frequencies.
-/
theorem cos_prime_sum_zero (n : ℕ) (i : Fin (w n)) (k : ℤ) (hk : k % p n i ≠ 0) :
    ∑ x ∈ Finset.range (p n i), Real.cos (2 * Real.pi * (k : ℝ) * x / p n i) = 0 := by
  -- Let $z = e^{2\pi i k / p n i}$, which is a primitive $p n i$-th root of unity.
  set z : ℂ := Complex.exp (2 * Real.pi * Complex.I * k / (p n i : ℂ))
  have hz : z ^ (p n i) = 1 := by
    rw [ ← Complex.exp_nat_mul, mul_comm, Complex.exp_eq_one_iff ]
    exact ⟨ k, by
      rw [ div_mul_cancel₀ _ ( Nat.cast_ne_zero.mpr <| Nat.Prime.ne_zero <| p_prime n i ) ] ; ring ⟩
  have hz_ne_one : z ≠ 1 := by
    rw [ Ne.eq_def, Complex.exp_eq_one_iff ]
    field_simp
    exact fun ⟨ m, hm ⟩ => hk <| Int.emod_eq_zero_of_dvd <| by
      rw [ div_eq_iff ( Nat.cast_ne_zero.mpr <| Nat.Prime.ne_zero <| p_prime n i ) ] at hm
      norm_cast at hm; aesop
  -- The sum of the roots of unity is zero.
  have hsum_roots : ∑ x ∈ Finset.range (p n i), z ^ x = 0 := by
    rw [ geom_sum_eq ] <;> aesop
  rw [show (0 : ℝ) = Complex.re 0 from Complex.zero_re.symm, ← hsum_roots, Complex.re_sum]
  exact Finset.sum_congr rfl fun x hx => by
    rw [← Complex.exp_nat_mul]; norm_num [Complex.exp_re]; ring_nf

/-
The sum of squares of cosines modulo a prime `p n i` equals `p n i / 2`
for non-zero frequencies.
-/
theorem cos_sq_prime_sum (n : ℕ) (i : Fin (w n)) (k : ℤ)
    (_hk1 : k % p n i ≠ 0) (hk2 : (2 * k) % p n i ≠ 0) :
    ∑ x ∈ Finset.range (p n i), (Real.cos (2 * Real.pi * (k : ℝ) * x / p n i)) ^ 2 =
      (p n i : ℝ) / 2 := by
  have h_cos_sq : ∀ x : ℕ, Real.cos (2 * Real.pi * k * x / (p n i)) ^ 2 =
      1 / 2 + Real.cos (2 * Real.pi * (2 * k) * x / (p n i)) / 2 := by
    intro x; rw [ Real.cos_sq ] ; ring_nf
  simp_rw [h_cos_sq]
  rw [Finset.sum_add_distrib]
  have h_const : ∑ _x ∈ Finset.range (p n i), (1 / 2 : ℝ) = (p n i : ℝ) / 2 := by
    simp; ring
  rw [h_const, ← Finset.sum_div]
  have h_cast : ((2 * k : ℤ) : ℝ) = 2 * (k : ℝ) := by push_cast; rfl
  have h_zero : ∑ x ∈ Finset.range (p n i), Real.cos (2 * Real.pi * (2 * ↑k) * x / p n i) = 0 := by
    rw [← h_cast]
    exact cos_prime_sum_zero n i (2 * k) hk2
  rw [h_zero]
  ring

/-
The product of the primes `p n i` over all indices equals the primorial `q n`.
-/
theorem prod_p_eq_q (n : ℕ) : ∏ i : Fin (w n), (p n i : ℝ) = (q n : ℝ) := by
  have h_prod : (∏ i : Fin (w n), p n i : ℕ) = (∏ p ∈ primeWindow n, p : ℕ) := by
    have h_prod : ∏ i : Fin (w n), p n i =
        ∏ x ∈ Finset.image (fun i => p n i) (Finset.univ : Finset (Fin (w n))), x := by
      rw [ Finset.prod_image ]
      intro i hi j hj hij
      have h_unique : List.Nodup (primesList n) := by
        exact Finset.sort_nodup _ _
      have := List.nodup_iff_injective_get.mp h_unique hij; aesop
    convert h_prod using 2
    ext x; simp +decide [ mem_P_n_iff_exists_index ]
  norm_cast

/-
The discrete basis cosines are orthogonal when summed over a full period `range (q n)`.
-/
theorem basisCos_discrete_orthogonal_range (n : ℕ) (S T : Finset (Fin (w n))) :
    ∑ x ∈ Finset.range (q n), basisCos n S (x : ZMod (q n)) * basisCos n T (x : ZMod (q n)) =
      if S = T then ((q n : ℝ) / 2 ^ S.card) else 0 := by
  convert @KrafftSieve.crt_product_sum_factorization n
    (fun i x => (if i ∈ S then Real.cos (2 * Real.pi * 3 * x / (p n i : ℝ)) else 1) *
                 (if i ∈ T then Real.cos (2 * Real.pi * 3 * x / (p n i : ℝ)) else 1)) _ using 1
  · unfold basisCos
    refine Finset.sum_congr rfl fun x hx => by
      rw [Finset.prod_mul_distrib]
      simp +decide [ZMod.val_natCast_of_lt (Finset.mem_range.mp hx)]
  · split_ifs with hST
    · subst hST
      -- For each $i$, if $i \in S$, then
      -- $\sum_{y=0}^{p_i-1} \cos^2(2\pi \cdot 3 \cdot y / p_i) = p_i / 2$.
      have h_cos_sq : ∀ i : Fin (w n), i ∈ S →
          ∑ y ∈ Finset.range (p n i), (Real.cos (2 * Real.pi * 3 * y / p n i)) ^ 2 =
            (p n i : ℝ) / 2 := by
        intro i hi; convert cos_sq_prime_sum n i 3 _ _ using 1 <;> norm_num
        · exact_mod_cast Nat.not_dvd_of_pos_of_lt (by norm_num) (by linarith [p_ge_5 n i])
        · have := p_prime n i; (have := p_ge_5 n i; (norm_cast at *))
          exact fun h => by have := Nat.le_of_dvd (by decide) h; interval_cases p n i <;> trivial
      have h_sum : ∀ i : Fin (w n), ∑ y ∈ Finset.range (p n i),
          ((if i ∈ S then Real.cos (2 * Real.pi * 3 * y / (p n i : ℝ)) else 1) ^ 2) =
            if i ∈ S then (p n i : ℝ) / 2 else (p n i : ℝ) := by
        intro i
        split_ifs with hi
        · exact h_cos_sq i hi
        · rw [Finset.sum_const]
          simp only [Finset.card_range, one_pow, nsmul_one]
      simp_rw [← sq]
      simp_rw [h_sum]
      simp only [Finset.prod_ite, Finset.filter_not]
      simp_rw [div_eq_mul_inv]
      simp_rw [Finset.prod_mul_distrib, Finset.prod_const]
      simp only [Finset.filter_mem_eq_inter, Finset.univ_inter]
      rw [inv_pow]
      rw [← prod_p_eq_q]
      rw [← Finset.prod_sdiff (Finset.subset_univ S)]
      ring
    · -- Since `S ≠ T`, some index lies in exactly one of `S`, `T`; its factor sums to `0`.
      obtain ⟨i, hi⟩ : ∃ i : Fin (w n), (i ∈ S ∧ i ∉ T) ∨ (i ∈ T ∧ i ∉ S) := by
        exact not_forall_not.mp fun h => hST (Finset.ext fun x => by
          have hx := h x
          tauto)
      have hp5 : (5 : ℤ) ≤ (p n i : ℤ) := by exact_mod_cast p_ge_5 n i
      have h3 : (3 : ℤ) % (p n i : ℤ) ≠ 0 := by
        rw [Int.emod_eq_of_lt (by norm_num) (by linarith)]; norm_num
      have hzero := cos_prime_sum_zero n i 3 h3
      rw [Finset.prod_eq_zero (Finset.mem_univ i)]
      rcases hi with ⟨hiS, hiT⟩ | ⟨hiT, hiS⟩ <;>
        · simp only [hiS, hiT, if_true, if_false, one_mul, mul_one]
          exact hzero
  · intro i x
    have hp : (p n i : ℝ) ≠ 0 := Nat.cast_ne_zero.mpr (p_ne_zero n i)
    have hcos : Real.cos (2 * Real.pi * 3 * ((x + p n i : ℕ) : ℝ) / p n i)
        = Real.cos (2 * Real.pi * 3 * (x : ℝ) / p n i) := by
      have harg : (2 * Real.pi * 3 * ((x + p n i : ℕ) : ℝ) / p n i)
          = 2 * Real.pi * 3 * (x : ℝ) / p n i + ((3 : ℤ) : ℝ) * (2 * Real.pi) := by
        rw [show ((x + p n i : ℕ) : ℝ) = (x : ℝ) + (p n i : ℝ) by push_cast; ring]
        field_simp
        ring
      rw [harg, Real.cos_add_int_mul_two_pi]
    simp only [hcos]

end

end KrafftSieve
