/-
Copyright (c) 2026 Fernando Portela. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Fernando Portela
-/

/-
Portions of this file were generated by Aristotle (https://aristotle.harmonic.fun).

Lean version: leanprover/lean4:v4.28.0
Mathlib version: 8f9d9cff6bd728b17a24e163c9402775d9e6a365

To cite Aristotle, tag @Aristotle-Harmonic on GitHub PRs/issues, and add as co-author to commits:
Co-authored-by: Aristotle (Harmonic) <aristotle-harmonic@harmonic.fun>
-/

import Mathlib

/-!
# Auxiliary self-contained lemmas for the Gibbs dip (`GibbsDip.lean`)

This file collects the purely analytic / number-theoretic facts needed for the Gibbs
undershoot argument, stated without reference to the `KrafftSieve` RKHS machinery so that
they are reusable and self-contained.

* `cos_kernel_telescope` — the (multiplicative form of the) Dirichlet cosine kernel identity.
* `undershoot_value` — the Gibbs undershoot: the truncated cosine series of the symmetric
  step function dips below `-0.2` at the half-integer aligned with the residue.
* `exists_crt` — the Chinese Remainder Theorem: existence of a simultaneous solution.
* `sum_valley` — assembling the per-prime undershoots into the global continuous penalty bound.

# TODO
* deal with `set_option maxHeartbeats`
-/

namespace KrafftSieve.GibbsAux

open scoped Real
open Finset

/-
**Dirichlet cosine kernel (telescoping form).**
For every real `θ` and `M : ℕ`,
`2 sin(θ/2) · ∑_{k=0}^{M} cos(kθ) = sin((M + 1/2)θ) + sin(θ/2)`.
This avoids any nonvanishing hypothesis on `sin(θ/2)`.
-/
lemma cos_kernel_telescope (θ : ℝ) (M : ℕ) :
    2 * Real.sin (θ / 2) * ∑ k ∈ Finset.range (M + 1), Real.cos (k * θ)
      = Real.sin (((M : ℝ) + 1 / 2) * θ) + Real.sin (θ / 2) := by
  induction M with
  | zero =>
    simp_all +decide only [zero_add, range_one, sum_singleton, CharP.cast_eq_zero, zero_mul,
      Real.cos_zero, mul_one, one_div]
    ring_nf
  | succ M ih =>
    simp_all +decide only [one_div, sum_range_succ, Nat.cast_add, Nat.cast_one]
    convert congr_arg ( · + 2 * Real.sin ( θ / 2 ) * Real.cos ( ( M + 1 ) * θ ) ) ih using 1
    · ring_nf
    · rw [ show ( M + 1 + 2⁻¹ : ℝ ) * θ = ( M + 1 ) * θ + θ / 2 by ring,
           show ( M + 2⁻¹ : ℝ ) * θ = ( M + 1 ) * θ - θ / 2 by ring ]
      rw [ Real.sin_add, Real.sin_sub ]
      ring_nf

/-
**Closed form of the Gibbs partial sum at the aligned half-integer.**
Under the residue alignment `Y ≡ R + 1 (mod P)` (with `P` an odd prime `≥ 5` and `R = (P+1)/6`),
the truncated symmetric cosine series collapses (via the Dirichlet kernel) to a sum of two
reciprocal-sine terms.
-/
set_option maxHeartbeats 4000000 in
-- reason for change? we haven't tried to optimize yet, duh!
theorem undershoot_closed_form (P R : ℕ) (hP : P.Prime) (hP5 : 5 ≤ P) (hR : R = (P + 1) / 6)
    (Y : ℤ) (hY : Y ≡ (R : ℤ) + 1 [ZMOD (P : ℤ)]) :
    ∑ k ∈ Finset.range ((P + 1) / 2),
        (if k = 0 then 2 / (P : ℝ)
          else if k ≤ (P - 1) / 2 then 4 / (P : ℝ) * Real.cos (2 * Real.pi * k * (R : ℝ) / (P : ℝ))
          else 0)
          * Real.cos (2 * Real.pi * k * ((Y : ℝ) + 0.5) / (P : ℝ))
      = -(1 / (P : ℝ)) * (1 / Real.sin (3 * Real.pi / (2 * P))
          + 1 / Real.sin ((4 * R + 3) * Real.pi / (2 * P))) := by
  -- Let's simplify the expression using the fact that $Y \equiv R + 1 \pmod{P}$.
  obtain ⟨m, hm⟩ : ∃ m : ℤ, Y = R + 1 + P * m := by
    exact hY.symm.dvd.imp fun m hm => by linarith
  -- Let's simplify the expression using the fact that $P$ is odd and $R = (P + 1) / 6$.
  have h_simp : ∑ k ∈ Finset.range ((P + 1) / 2), (if k = 0 then 2 / (P : ℝ) else if k ≤ (P - 1) / 2 then 4 / (P : ℝ) * Real.cos (2 * Real.pi * k * R / P) else 0) * Real.cos (2 * Real.pi * k * (R + 1.5) / P) = -(1 / (P : ℝ)) * (1 / Real.sin (3 * Real.pi / (2 * P)) + 1 / Real.sin ((4 * R + 3) * Real.pi / (2 * P))) := by
    -- Let's simplify the expression using the fact that $P$ is odd and $R = (P + 1) / 6$. We'll
    -- use the Dirichlet kernel identity.
    have h_dirichlet : ∑ k ∈ Finset.range ((P + 1) / 2), (if k = 0 then 2 / (P : ℝ) else if k ≤ (P - 1) / 2 then 4 / (P : ℝ) * Real.cos (2 * Real.pi * k * R / P) else 0) * Real.cos (2 * Real.pi * k * (R + 1.5) / P) = 2 / (P : ℝ) + (2 / (P : ℝ)) * (∑ k ∈ Finset.range ((P - 1) / 2), (Real.cos (2 * Real.pi * (k + 1) * (1.5) / P) + Real.cos (2 * Real.pi * (k + 1) * (2 * R + 1.5) / P))) := by
      have h_split : ∑ k ∈ Finset.range ((P + 1) / 2), (if k = 0 then 2 / (P : ℝ) else if k ≤ (P - 1) / 2 then 4 / (P : ℝ) * Real.cos (2 * Real.pi * k * R / P) else 0) * Real.cos (2 * Real.pi * k * (R + 1.5) / P) = 2 / (P : ℝ) + ∑ k ∈ Finset.range ((P - 1) / 2), (4 / (P : ℝ) * Real.cos (2 * Real.pi * (k + 1) * R / P) * Real.cos (2 * Real.pi * (k + 1) * (R + 1.5) / P)) := by
        rcases Nat.even_or_odd' P with ⟨ c, rfl | rfl ⟩ <;> norm_num at *
        · simp_all +decide [ Nat.prime_mul_iff ]
        · norm_num [ Nat.add_div, Finset.sum_range_succ' ]
          rw [ add_comm, Finset.sum_congr rfl fun x hx => if_pos <| Finset.mem_range.mp hx ]
      rw [ h_split, Finset.mul_sum _ _ _ ]
      refine congr rfl ( Finset.sum_congr rfl fun i hi => ?_ )
      rw [ Real.cos_add_cos ] ; ring_nf
      norm_num [ Real.cos_add, Real.cos_sub ] ; ring
    -- Let's simplify the expression using the fact that $P$ is odd and $R = (P + 1) / 6$. We'll
    -- use the Dirichlet kernel identity to simplify the sums.
    have h_dirichlet_simplified : ∑ k ∈ Finset.range ((P - 1) / 2), Real.cos (2 * Real.pi * (k + 1) * (1.5) / P) = (Real.sin ((P - 1) / 2 * (3 * Real.pi / P) + 3 * Real.pi / (2 * P)) - Real.sin (3 * Real.pi / (2 * P))) / (2 * Real.sin (3 * Real.pi / (2 * P))) := by
      have h_dirichlet_simplified : ∀ n : ℕ, ∑ k ∈ Finset.range n, Real.cos (2 * Real.pi * (k + 1) * (1.5) / P) = (Real.sin (n * (3 * Real.pi / P) + 3 * Real.pi / (2 * P)) - Real.sin (3 * Real.pi / (2 * P))) / (2 * Real.sin (3 * Real.pi / (2 * P))) := by
        intro n; rw [ eq_div_iff ]
        induction n with
        | zero =>
          simp_all +decide
        | succ n =>
          simp_all +decide [ Finset.sum_range_succ, add_mul ]
          ring_nf
          rw [ ← Complex.ofReal_inj ] ; norm_num [ Complex.sin, Complex.cos ] ; ring_nf
          norm_num [ mul_assoc, ← Complex.exp_add ] ; ring_nf
        exact mul_ne_zero two_ne_zero ( ne_of_gt ( Real.sin_pos_of_pos_of_lt_pi ( by positivity ) ( by rw [ div_lt_iff₀ ( by positivity ) ] ; nlinarith [ Real.pi_pos, show ( P : ℝ ) ≥ 5 by norm_cast ] ) ) )
      cases Nat.Prime.odd_of_ne_two hP ( by linarith ) ; aesop
    have h_dirichlet_simplified2 : ∑ k ∈ Finset.range ((P - 1) / 2), Real.cos (2 * Real.pi * (k + 1) * (2 * R + 1.5) / P) = (Real.sin ((P - 1) / 2 * ((4 * R + 3) * Real.pi / P) + (4 * R + 3) * Real.pi / (2 * P)) - Real.sin ((4 * R + 3) * Real.pi / (2 * P))) / (2 * Real.sin ((4 * R + 3) * Real.pi / (2 * P))) := by
      have h_dirichlet_simplified2 : ∀ n : ℕ, ∑ k ∈ Finset.range n, Real.cos (2 * Real.pi * (k + 1) * (2 * R + 1.5) / P) = (Real.sin (n * ((4 * R + 3) * Real.pi / P) + (4 * R + 3) * Real.pi / (2 * P)) - Real.sin ((4 * R + 3) * Real.pi / (2 * P))) / (2 * Real.sin ((4 * R + 3) * Real.pi / (2 * P))) := by
        intro n
        rw [ eq_div_iff ]
        · induction n with
          | zero =>
            simp_all +decide [ add_mul ]
          | succ n =>
            simp_all +decide only [Int.natCast_ediv, Nat.cast_add, Nat.cast_one, Nat.cast_ofNat,
              Int.add_modEq_left_iff, dvd_mul_right, ite_mul, CharP.cast_eq_zero, mul_zero,
              zero_mul, zero_div, Real.cos_zero, mul_one, add_mul, sum_range_succ, one_mul]
            rw [ ← Complex.ofReal_inj ] ; norm_num [ Complex.sin, Complex.cos ] ; ring_nf
            norm_num [ mul_assoc, ← Complex.exp_add ] ; ring_nf
        · norm_num [ Real.sin_eq_zero_iff ]
          intro x hx; rw [ eq_div_iff ( by positivity ) ] at hx
          replace hx := congr_arg ( fun y => y / Real.pi ) hx
          ring_nf at hx; norm_num [ Real.pi_ne_zero ] at hx
          norm_num [ mul_assoc, mul_comm Real.pi _, Real.pi_ne_zero ] at hx
          norm_cast at hx; have := congr_arg Even hx; norm_num [ parity_simps ] at this
      convert h_dirichlet_simplified2 ( ( P - 1 ) / 2 ) using 2
      rw [ Nat.cast_div ( show 2 ∣ P - 1 from even_iff_two_dvd.mp ( hP.even_sub_one <| by linarith ) ) ] <;> norm_num [ hP.pos ]
    rw [ h_dirichlet, Finset.sum_add_distrib, h_dirichlet_simplified, h_dirichlet_simplified2 ]
    ring_nf
    norm_num [ hP.ne_zero, mul_assoc, mul_comm Real.pi ] ; ring_nf
    rw [ show Real.pi * ( 3 / 2 ) = Real.pi / 2 + Real.pi by ring ] ; norm_num ; ring_nf
    rw [ mul_inv_cancel_right₀, mul_inv_cancel_right₀ ] <;> norm_num
    · ring
    · refine ne_of_gt ( Real.sin_pos_of_pos_of_lt_pi ?_ ?_ )
      · positivity
      · field_simp
        norm_cast ; omega
    · exact ne_of_gt ( Real.sin_pos_of_pos_of_lt_pi ( by positivity )
        ( by nlinarith [ Real.pi_pos, show ( P : ℝ ) ≥ 5 by norm_cast,
                         inv_mul_cancel₀ ( by positivity : ( P : ℝ ) ≠ 0 ) ] ) )
  convert h_simp using 3 ; push_cast [ hm ] ; ring_nf
  convert Real.cos_periodic.int_mul ( m * ‹ℕ› ) _ using 2 ; push_cast ; ring_nf
  norm_num [ hP.ne_zero ]
  ring

/-
**The arithmetic bound.** The two-reciprocal-sine expression is `≤ -0.2`.
The first term alone already contributes at least `2/(3π) > 0.2` (since `sin θ ≤ θ`),
and the second term is nonnegative.
-/
theorem undershoot_bound (P R : ℕ) (hP5 : 5 ≤ P) (hR : R = (P + 1) / 6) :
    -(1 / (P : ℝ)) * (1 / Real.sin (3 * Real.pi / (2 * P))
        + 1 / Real.sin ((4 * R + 3) * Real.pi / (2 * P))) ≤ -(0.2 : ℝ) := by
  -- From `hR : R = (P+1)/6`, we have `6 * R ≤ P + 1` (nat division:
  -- `Nat.div_mul_le_self`/`Nat.mul_div_le`).
  -- Since `P ≥ 5`, `4 * R + 3 < 2 * P` (by linarith), which gives `b < π`. Hence `0 < Real.sin b`
  -- by `Real.sin_pos_of_pos_of_lt_pi`.
  have hb : (4 * R + 3) * Real.pi / (2 * P) < Real.pi := by
    rw [ div_lt_iff₀ ] <;> nlinarith [ Real.pi_pos, show ( P : ℝ ) ≥ 5 by norm_cast, show ( R : ℝ ) ≤ ( P + 1 ) / 6 by exact hR.symm ▸ by rw [ le_div_iff₀ ] <;> norm_cast ; linarith [ Nat.div_mul_le_self ( P + 1 ) 6 ] ]
  have hb_pos : 0 < Real.sin ((4 * R + 3) * Real.pi / (2 * P)) := by
    exact Real.sin_pos_of_pos_of_lt_pi ( by positivity ) hb
  -- Since `sin a ≤ a` (by `Real.sin_lt`), `1 / sin a ≥ 1 / a`, so
  -- `(1/P) * (1/sin a + 1/sin b) ≥ (1/P) * (1/a)`.
  have h_bound : (1 / (P : ℝ)) * (1 / Real.sin (3 * Real.pi / (2 * P)) + 1 / Real.sin ((4 * R + 3) * Real.pi / (2 * P))) ≥ (1 / (P : ℝ)) * (1 / (3 * Real.pi / (2 * P))) := by
    gcongr
    exact le_add_of_le_of_nonneg ( one_div_le_one_div_of_le ( Real.sin_pos_of_pos_of_lt_pi ( by positivity ) ( by rw [ div_lt_iff₀ ( by positivity ) ] ; nlinarith [ Real.pi_pos, ( by norm_cast : ( 5 :ℝ ) ≤ P ) ] ) ) ( le_of_lt ( Real.sin_lt <| by positivity ) ) ) ( by positivity )
  -- Since `3 * π < 10`, we have `2 / (3 * π) > 0.2`.
  have h_pi_lt_315 : Real.pi < 3.15 := Real.pi_lt_d2
  ring_nf at *; norm_num at *
  nlinarith [ Real.pi_gt_three, mul_inv_cancel₀ ( by positivity : ( P : ℝ ) ≠ 0 ), mul_inv_cancel₀ ( by positivity : Real.pi ≠ 0 ) ]

/-- **The Gibbs undershoot.**
Let `P` be a prime `≥ 5`, `R = (P+1)/6`, and let `Y` be an integer with `Y ≡ R + 1 (mod P)`.
The truncated symmetric cosine series (the Fourier partial sum of the local step function `g_i`),
evaluated at the half-integer `Y + 1/2`, is at most `-0.2`.

The coefficient expression is exactly `g_coef` inlined (`2/P` for `k = 0`,
`(4/P)·cos(2πkR/P)` for `1 ≤ k ≤ (P-1)/2`, and `0` otherwise). -/
theorem undershoot_value (P R : ℕ) (hP : P.Prime) (hP5 : 5 ≤ P) (hR : R = (P + 1) / 6)
    (Y : ℤ) (hY : Y ≡ (R : ℤ) + 1 [ZMOD (P : ℤ)]) :
    ∑ k ∈ Finset.range ((P + 1) / 2),
        (if k = 0 then 2 / (P : ℝ)
          else if k ≤ (P - 1) / 2 then 4 / (P : ℝ) * Real.cos (2 * Real.pi * k * (R : ℝ) / (P : ℝ))
          else 0)
          * Real.cos (2 * Real.pi * k * ((Y : ℝ) + 0.5) / (P : ℝ)) ≤ -(0.2 : ℝ) := by
  rw [undershoot_closed_form P R hP hP5 hR Y hY]
  exact undershoot_bound P R hP5 hR

/-
**Chinese Remainder Theorem (existence).**
Given pairwise coprime moduli `P i` (all nonzero) over a finite index type, and arbitrary
integer residues `A i`, there is an integer congruent to `A i` modulo `P i` for every `i`.
-/
theorem exists_crt {ι : Type*} [Fintype ι] (P : ι → ℕ) (A : ι → ℤ)
    (hP : ∀ i, P i ≠ 0) (hcop : ∀ i j, i ≠ j → Nat.Coprime (P i) (P j)) :
    ∃ Y : ℤ, ∀ i, Y ≡ A i [ZMOD (P i : ℤ)] := by
  -- Apply the Chinese Remainder Theorem to find such a `Y`.
  have h_crt : ∃ k : ℕ, ∀ i, k ≡ (A i % (P i : ℤ)).toNat [MOD (P i : ℕ)] := by
    have := @Nat.chineseRemainderOfFinset
    specialize this ( fun i => ( A i % ( P i : ℤ ) |> Int.toNat ) ) ( fun i => P i ) Finset.univ ( fun i _ => hP i ) ( fun i _ j _ hij => hcop i j hij ) ; exact ⟨ this.1, fun i => this.2 i ( Finset.mem_univ i ) ⟩
  obtain ⟨ k, hk ⟩ := h_crt; use k; intro i; specialize hk i
  simp_all +decide [ ← Int.natCast_modEq_iff ]
  simp_all +decide [ Int.ModEq, Int.emod_nonneg _ ( Int.natCast_ne_zero.mpr ( hP i ) ) ]

/-
**Assembling the global penalty bound.**
If each modulus `P i` divides `Q` and each per-prime truncated series undershoots below `-0.2`
at `Y + 1/2`, then the sum over all primes, evaluated at the fractional part
`fract((Y + 1/2)/Q)` rescaled by `Q`, is at most `-0.2 · |ι|`.

The rescaling `fract(...) · Q` reproduces `Y + 1/2` modulo `P i` inside each cosine because
`P i ∣ Q`, so each inner sum equals the corresponding undershoot sum.
-/
theorem sum_valley {ι : Type*} [Fintype ι] (P : ι → ℕ) (Q : ℕ) (G : ι → ℕ → ℝ) (Y : ℤ)
    (hQ : 0 < Q) (hdvd : ∀ i, (P i) ∣ Q)
    (hunder : ∀ i, ∑ k ∈ Finset.range ((P i + 1) / 2),
        G i k * Real.cos (2 * Real.pi * k * ((Y : ℝ) + 0.5) / (P i : ℝ)) ≤ -(0.2 : ℝ)) :
    ∑ i : ι, ∑ k ∈ Finset.range ((P i + 1) / 2),
        G i k * Real.cos
          (2 * Real.pi * k * (Int.fract (((Y : ℝ) + 0.5) / (Q : ℝ))) * (Q : ℝ) / (P i : ℝ))
        ≤ -(0.2 : ℝ) * (Fintype.card ι) := by
  -- Apply the inequality from `hunder` to each term in the sum.
  have h_ineq : ∀ i : ι, ∑ k ∈ Finset.range ((P i + 1) / 2), G i k * Real.cos (2 * Real.pi * k * Int.fract ((Y + 0.5 : ℝ) / Q) * Q / (P i)) ≤ -0.2 := by
    intro i
    convert hunder i using 3
    rw [ Int.fract ]
    convert Real.cos_periodic.int_mul ( - ( ⌊ ( Y + 0.5 : ℝ ) / Q⌋ * ‹ℕ› * ( Q / P i ) ) ) _ using 2 ; push_cast ; ring_nf
    rw [ Int.cast_div ( mod_cast hdvd i ) ( by norm_cast; linarith [ Nat.pos_of_dvd_of_pos ( hdvd i ) hQ ] ) ] ; push_cast ; ring_nf
    simpa [ hQ.ne' ] using by ring
  simpa [ mul_comm ] using Finset.sum_le_sum fun i ( hi : i ∈ Finset.univ ) => h_ineq i

/-!
### Quarter-integer variants

The lemmas above are stated at the half-integer offset `+0.5`. The `GibbsDip` argument instead
evaluates the truncated series at the *quarter-integer* offset `+0.25`. The closed form there is
`S = -(√2 / (2P)) · (1 / sin(5π/(4P)) + 1 / sin((8R+3)... ))`, and the resulting undershoot is
bounded above by `-0.1` (in fact by `-2√2/(5π) ≈ -0.18`).
-/

/-
**Closed form of the Gibbs partial sum at the aligned quarter-integer.**
Under `Y ≡ R + 1 (mod P)` with `P` an odd prime `≥ 5` and `R = (P+1)/6`, the truncated symmetric
cosine series evaluated at `Y + 1/4` collapses to a sum of two reciprocal-sine terms.
-/
theorem undershoot_closed_form_quarter (P R : ℕ) (hP : P.Prime) (hP5 : 5 ≤ P)
    (hR : R = (P + 1) / 6) (Y : ℤ) (hY : Y ≡ (R : ℤ) + 1 [ZMOD (P : ℤ)]) :
    ∑ k ∈ Finset.range ((P + 1) / 2),
        (if k = 0 then 2 / (P : ℝ)
          else if k ≤ (P - 1) / 2 then 4 / (P : ℝ) * Real.cos (2 * Real.pi * k * (R : ℝ) / (P : ℝ))
          else 0)
          * Real.cos (2 * Real.pi * k * ((Y : ℝ) + 0.25) / (P : ℝ))
      = -(Real.sqrt 2 / (2 * (P : ℝ))) * (1 / Real.sin (5 * Real.pi / (4 * P))
          + 1 / Real.sin ((8 * R + 5) * Real.pi / (4 * P))) := by
  -- Write Y as R + 1 + P * m for some integer m.
  obtain ⟨m, hm⟩ : ∃ m : ℤ, Y = R + 1 + P * m := by
    exact hY.symm.dvd.imp fun m hm => by linarith
  -- Expand the coefficient: pull out the k=0 term (2/P) and for 1 ≤ k ≤ (P-1)/2 use product-to-sum:
  have h_expand : ∑ k ∈ Finset.range ((P + 1) / 2), (if k = 0 then 2 / (P : ℝ) else if k ≤ (P - 1) / 2 then 4 / (P : ℝ) * Real.cos (2 * Real.pi * k * (R : ℝ) / (P : ℝ)) else 0) * Real.cos (2 * Real.pi * k * ((Y : ℝ) + 0.25) / (P : ℝ)) = (2 / (P : ℝ)) + (2 / (P : ℝ)) * ∑ k ∈ Finset.Ico 1 ((P + 1) / 2), (Real.cos (2 * Real.pi * k * (5 / 4 : ℝ) / (P : ℝ)) + Real.cos (2 * Real.pi * k * (2 * R + 5 / 4 : ℝ) / (P : ℝ))) := by
    have h_expand : ∀ k ∈ Finset.Ico 1 ((P + 1) / 2), (4 / (P : ℝ)) * Real.cos (2 * Real.pi * k * (R : ℝ) / (P : ℝ)) * Real.cos (2 * Real.pi * k * ((Y : ℝ) + 0.25) / (P : ℝ)) = (2 / (P : ℝ)) * (Real.cos (2 * Real.pi * k * (5 / 4 : ℝ) / (P : ℝ)) + Real.cos (2 * Real.pi * k * (2 * R + 5 / 4 : ℝ) / (P : ℝ))) := by
      intro k hk; rw [ Real.cos_add_cos ] ; ring_nf; norm_num [ hm ] ; ring_nf
      norm_num [ hP.ne_zero ] ; ring_nf; norm_num [ mul_assoc, mul_comm Real.pi ]
      exact Or.inl ( by convert Real.cos_periodic.int_mul ( k * m ) _ using 2; push_cast; ring )
    rw [ Finset.sum_eq_add_sum_sdiff_singleton_of_mem ( Finset.mem_range.mpr ( Nat.div_pos ( by linarith ) zero_lt_two ) ) ]
    rw [ Finset.mul_sum _ _ _ ]
    rw [ Finset.sdiff_singleton_eq_erase, Finset.range_eq_Ico ]
    rw [ Finset.Ico_eq_cons_Ioo, Finset.erase_cons ] <;> norm_num
    · refine Finset.sum_congr rfl fun x hx => ?_
      grind
    · linarith
  -- Evaluate each Dirichlet cosine sum with the closed form Σ_{k=1}^{M} cos(kθ) =
  -- (sin((M+1/2)θ) − sin(θ/2))/(2 sin(θ/2)), with M=(P-1)/2.
  have h_dirichlet : ∀ θ : ℝ, Real.sin (θ / 2) ≠ 0 → ∑ k ∈ Finset.Ico 1 ((P + 1) / 2), Real.cos (k * θ) = (Real.sin ((P / 2) * θ) - Real.sin (θ / 2)) / (2 * Real.sin (θ / 2)) := by
    intro θ hθ
    have h_dirichlet_sum : ∑ k ∈ Finset.range ((P + 1) / 2), Real.cos (k * θ) = (Real.sin ((P / 2) * θ) + Real.sin (θ / 2)) / (2 * Real.sin (θ / 2)) := by
      have h_dirichlet_sum : ∀ n : ℕ, ∑ k ∈ Finset.range n, Real.cos (k * θ) = (Real.sin ((n - 1 / 2) * θ) + Real.sin (θ / 2)) / (2 * Real.sin (θ / 2)) := by
        intro n; rw [ eq_div_iff ( mul_ne_zero two_ne_zero hθ ) ]
        induction n with
        | zero =>
          simp_all +decide ; ring_nf
        | succ n =>
          simp_all +decide only [Int.natCast_ediv, Nat.cast_add, Nat.cast_one, Nat.cast_ofNat,
            Int.add_modEq_left_iff, dvd_mul_right, Int.cast_add, Int.cast_one, Int.cast_mul,
            Int.cast_natCast, ite_mul, CharP.cast_eq_zero, mul_zero, zero_mul, zero_div,
            Real.cos_zero, mul_one, ne_eq, one_div, sum_range_succ, add_mul]
          rw [ show ( ( _:ℝ ) + 1 - 2⁻¹ ) * θ = ( ( _:ℝ ) * θ ) + θ / 2 by ring ]
          rw [ show ( ( _:ℝ ) - 2⁻¹ ) * θ = ( ( _:ℝ ) * θ ) - θ / 2 by ring ]
          rw [ Real.sin_add, Real.sin_sub ] ; ring
      convert h_dirichlet_sum ( ( P + 1 ) / 2 ) using 2 ; ring_nf
      rw [ Nat.cast_div ( show 2 ∣ 1 + P from even_iff_two_dvd.mp ( by simpa [ parity_simps ] using hP.eq_two_or_odd'.resolve_left ( by linarith ) ) ) ] <;> norm_num ; ring_nf
    rw [ Finset.sum_Ico_eq_sub _ ] <;> norm_num [ h_dirichlet_sum ]
    · ring_nf ; grind
    · omega
  -- Apply the Dirichlet cosine sum formula to each term in the sum.
  have h_apply_dirichlet : ∑ k ∈ Finset.Ico 1 ((P + 1) / 2), Real.cos (2 * Real.pi * k * (5 / 4 : ℝ) / (P : ℝ)) = (Real.sin ((P / 2) * (5 * Real.pi / (2 * P))) - Real.sin (5 * Real.pi / (4 * P))) / (2 * Real.sin (5 * Real.pi / (4 * P))) ∧ ∑ k ∈ Finset.Ico 1 ((P + 1) / 2), Real.cos (2 * Real.pi * k * (2 * R + 5 / 4 : ℝ) / (P : ℝ)) = (Real.sin ((P / 2) * ((8 * R + 5) * Real.pi / (2 * P))) - Real.sin ((8 * R + 5) * Real.pi / (4 * P))) / (2 * Real.sin ((8 * R + 5) * Real.pi / (4 * P))) := by
    apply And.intro
    · convert h_dirichlet ( 5 * Real.pi / ( 2 * P ) ) _ using 3 <;> ring_nf
      exact ne_of_gt ( Real.sin_pos_of_pos_of_lt_pi ( by positivity ) ( by nlinarith [ Real.pi_pos, show ( P : ℝ ) ≥ 5 by norm_cast, mul_inv_cancel₀ ( by positivity : ( P : ℝ ) ≠ 0 ) ] ) )
    · convert h_dirichlet ( ( 8 * R + 5 ) * Real.pi / ( 2 * P ) ) _ using 3 <;> ring_nf
      refine ne_of_gt ( Real.sin_pos_of_pos_of_lt_pi ?_ ?_ )
      · positivity
      · field_simp
        norm_cast ; linarith [ Nat.div_mul_le_self ( P + 1 ) 6 ]
  rw [ h_expand, Finset.sum_add_distrib, h_apply_dirichlet.1, h_apply_dirichlet.2 ]
  have hP0 : (P : ℝ) ≠ 0 := by positivity
  have hRle : (R : ℝ) ≤ ((P : ℝ) + 1) / 6 := by
    rw [le_div_iff₀ (by norm_num)]; norm_cast; nlinarith [Nat.div_mul_le_self (P + 1) 6, hR]
  have hs1 : Real.sin (5 * Real.pi / (4 * P)) ≠ 0 :=
    ne_of_gt (Real.sin_pos_of_pos_of_lt_pi (by positivity)
      (by rw [div_lt_iff₀ (by positivity)]; nlinarith [Real.pi_pos, show (P : ℝ) ≥ 5 by norm_cast]))
  have hs2 : Real.sin ((8 * R + 5) * Real.pi / (4 * P)) ≠ 0 :=
    ne_of_gt (Real.sin_pos_of_pos_of_lt_pi (by positivity)
      (by rw [div_lt_iff₀ (by positivity)]; nlinarith [Real.pi_pos, show (P : ℝ) ≥ 5 by norm_cast, hRle]))
  have e1 : ((P : ℝ) / 2) * (5 * Real.pi / (2 * P)) = 5 * Real.pi / 4 := by
    field_simp; ring
  have e2 : ((P : ℝ) / 2) * ((8 * R + 5) * Real.pi / (2 * P))
      = 5 * Real.pi / 4 + (R : ℝ) * (2 * Real.pi) := by
    field_simp; ring
  have s5 : Real.sin (5 * Real.pi / 4) = -(Real.sqrt 2 / 2) := by
    rw [show (5 : ℝ) * Real.pi / 4 = Real.pi + Real.pi / 4 by ring, Real.sin_add]
    simp [Real.sin_pi_div_four, Real.cos_pi_div_four, Real.sin_pi, Real.cos_pi]
  rw [e1, e2, Real.sin_add_nat_mul_two_pi, s5]
  set s1 := Real.sin (5 * Real.pi / (4 * P)) with hs1def
  set s2 := Real.sin ((8 * R + 5) * Real.pi / (4 * P)) with hs2def
  field_simp
  ring

/-
**The arithmetic bound (quarter-integer).** The two-reciprocal-sine expression is `≤ -0.1`.
The first term alone contributes at least `2√2/(5π) > 0.1` (since `sin θ ≤ θ`), and the second
term is nonnegative because `(8R+5)π/(4P) < π` for `P ≥ 5`.
-/
theorem undershoot_bound_quarter (P R : ℕ) (hP5 : 5 ≤ P) (hR : R = (P + 1) / 6) :
    -(Real.sqrt 2 / (2 * (P : ℝ))) * (1 / Real.sin (5 * Real.pi / (4 * P))
        + 1 / Real.sin ((8 * R + 5) * Real.pi / (4 * P))) ≤ -(0.1 : ℝ) := by
  -- First, note that $b < \pi$ since $0 < \frac{(8R+5)\pi}{4P} < \pi$ for $P \geq 5$.
  have hb_lt_pi : (8 * R + 5) * Real.pi / (4 * P) < Real.pi := by
    rw [ div_lt_iff₀ ( by positivity ) ]
    nlinarith [ Real.pi_pos, show ( P : ℝ ) ≥ 5 by norm_cast,
                show ( R : ℝ ) ≤ ( P + 1 ) / 6 by
                  rw [ le_div_iff₀ ] <;> norm_cast
                  linarith [ Nat.div_mul_le_self ( P + 1 ) 6 ] ]
  -- Next, show that $1/\sin b \geq 0$.
  have hb_pos : 0 < Real.sin ((8 * R + 5) * Real.pi / (4 * P)) := by
    exact Real.sin_pos_of_pos_of_lt_pi ( by positivity ) hb_lt_pi
  -- Now use the fact that $1 / \sin a \geq 1 / a$ and $1 / \sin b \geq 0$ to bound the expression.
  have h_bound : 1 / Real.sin (5 * Real.pi / (4 * P)) + 1 / Real.sin ((8 * R + 5) * Real.pi / (4 * P)) ≥ 4 * P / (5 * Real.pi) := by
    refine le_add_of_le_of_nonneg ?_ ( one_div_nonneg.mpr hb_pos.le )
    rw [ div_le_div_iff₀ ] <;> try positivity
    · exact le_trans ( mul_le_mul_of_nonneg_left ( le_of_lt ( Real.sin_lt <| by positivity ) ) <| by positivity ) <| by nlinarith [ Real.pi_pos, show ( P : ℝ ) ≥ 5 by norm_cast, mul_div_cancel₀ ( 5 * Real.pi ) ( by positivity : ( 4 * P : ℝ ) ≠ 0 ) ]
    · exact Real.sin_pos_of_pos_of_lt_pi ( by positivity ) ( by rw [ div_lt_iff₀ ( by positivity ) ] ; nlinarith [ Real.pi_pos, show ( P : ℝ ) ≥ 5 by norm_cast ] )
  refine le_trans ( mul_le_mul_of_nonpos_left h_bound <| neg_nonpos_of_nonneg <| by positivity ) ?_
  ring_nf; norm_num [ Real.pi_pos.ne', show P ≠ 0 by linarith ]
  rw [ ← div_eq_mul_inv, div_mul_eq_mul_div, le_div_iff₀ ] <;> nlinarith only [ Real.pi_gt_three, Real.pi_le_four, Real.sqrt_nonneg 2, Real.sq_sqrt zero_le_two ]

/-- **The Gibbs undershoot at the quarter-integer.**
Let `P` be a prime `≥ 5`, `R = (P+1)/6`, and let `Y` be an integer with `Y ≡ R + 1 (mod P)`.
The truncated symmetric cosine series (the Fourier partial sum of the local step function `g_i`),
evaluated at the quarter-integer `Y + 1/4`, is at most `-0.1`. -/
theorem undershoot_value_quarter (P R : ℕ) (hP : P.Prime) (hP5 : 5 ≤ P) (hR : R = (P + 1) / 6)
    (Y : ℤ) (hY : Y ≡ (R : ℤ) + 1 [ZMOD (P : ℤ)]) :
    ∑ k ∈ Finset.range ((P + 1) / 2),
        (if k = 0 then 2 / (P : ℝ)
          else if k ≤ (P - 1) / 2 then 4 / (P : ℝ) * Real.cos (2 * Real.pi * k * (R : ℝ) / (P : ℝ))
          else 0)
          * Real.cos (2 * Real.pi * k * ((Y : ℝ) + 0.25) / (P : ℝ)) ≤ -(0.1 : ℝ) := by
  rw [undershoot_closed_form_quarter P R hP hP5 hR Y hY]
  exact undershoot_bound_quarter P R hP5 hR

/-
**Assembling the global penalty bound (quarter-integer).**
If each modulus `P i` divides `Q` and each per-prime truncated series undershoots below `-0.1`
at `Y + 1/4`, then the sum over all primes, evaluated at the fractional part
`fract((Y + 1/4)/Q)` rescaled by `Q`, is at most `-0.1 · |ι|`.
-/
theorem sum_valley_quarter {ι : Type*} [Fintype ι] (P : ι → ℕ) (Q : ℕ) (G : ι → ℕ → ℝ) (Y : ℤ)
    (hQ : 0 < Q) (hdvd : ∀ i, (P i) ∣ Q)
    (hunder : ∀ i, ∑ k ∈ Finset.range ((P i + 1) / 2),
        G i k * Real.cos (2 * Real.pi * k * ((Y : ℝ) + 0.25) / (P i : ℝ)) ≤ -(0.1 : ℝ)) :
    ∑ i : ι, ∑ k ∈ Finset.range ((P i + 1) / 2),
        G i k * Real.cos
          (2 * Real.pi * k * (Int.fract (((Y : ℝ) + 0.25) / (Q : ℝ))) * (Q : ℝ) / (P i : ℝ))
        ≤ -(0.1 : ℝ) * (Fintype.card ι) := by
  have h_ineq : ∀ i : ι, ∑ k ∈ Finset.range ((P i + 1) / 2), G i k * Real.cos (2 * Real.pi * k * Int.fract ((Y + 0.25 : ℝ) / Q) * Q / (P i : ℝ)) ≤ -0.1 := by
    intro i
    convert hunder i using 3
    rw [Int.fract]
    convert Real.cos_periodic.int_mul ( -⌊ ( Y + 0.25 : ℝ ) / Q⌋ * ‹ℕ› * ( Q / P i ) ) _ using 2
    push_cast ; ring_nf
    rw [ Int.cast_div ( mod_cast hdvd i ) ( by norm_cast; linarith [ Nat.pos_of_dvd_of_pos ( hdvd i ) hQ ] ) ]
    norm_num [ hQ.ne' ] ; ring
  simpa [ mul_comm ] using Finset.sum_le_sum fun i ( hi : i ∈ Finset.univ ) => h_ineq i

/-!
### Negative-root (overshoot) quarter-integer variants

The lemmas above treat the *positive* root `Y ≡ R + 1 (mod P)`. The `GibbsDip` argument also needs
the *negative* root `Y ≡ -R + 1 (mod P)`. There the same product-to-sum / Dirichlet-kernel
calculation collapses the truncated cosine series to
`S = (√2 / (2P)) · (1 / sin((8R-5)π/(4P)) - 1 / sin(5π/(4P)))`, which is bounded above by `0.12`
(the maximum `≈ 0.116` is attained at `P = 7`).
-/

/-- Two-sided Taylor bound for `sin` on `[0,1]` (upper form), a convenience wrapper of
`Real.sin_bound`. -/
lemma sin_taylor_le (x : ℝ) (hx : 0 ≤ x) (hx1 : x ≤ 1) :
    Real.sin x ≤ x - x ^ 3 / 6 + x ^ 4 * (5 / 96) := by
  have h := Real.sin_bound (show |x| ≤ 1 by rwa [abs_of_nonneg hx])
  rw [abs_of_nonneg hx] at h
  have h2 := (abs_le.mp h).2
  have h3 : x^5 / 100 ≤ x^4 * (5 / 96) := by
    have h4 : (1 / 100 : ℝ) ≤ 5 / 96 := by norm_num
    calc x^5 / 100 = x^4 * (x / 100) := by ring
      _ ≤ x^4 * (1 / 100) := by gcongr
      _ ≤ x^4 * (5 / 96) := by exact mul_le_mul_of_nonneg_left h4 (by positivity)
  linarith

/-- Two-sided Taylor bound for `sin` on `[0,1]` (lower form), a convenience wrapper of
`Real.sin_bound`. -/
lemma sin_taylor_ge (x : ℝ) (hx : 0 ≤ x) (hx1 : x ≤ 1) :
    x - x ^ 3 / 6 - x ^ 4 * (5 / 96) ≤ Real.sin x := by
  have h := Real.sin_bound (show |x| ≤ 1 by rwa [abs_of_nonneg hx])
  rw [abs_of_nonneg hx] at h
  have h1 := (abs_le.mp h).1
  have h3 : x^5 / 100 ≤ x^4 * (5 / 96) := by
    have h4 : (1 / 100 : ℝ) ≤ 5 / 96 := by norm_num
    calc x^5 / 100 = x^4 * (x / 100) := by ring
      _ ≤ x^4 * (1 / 100) := by gcongr
      _ ≤ x^4 * (5 / 96) := by exact mul_le_mul_of_nonneg_left h4 (by positivity)
  linarith

/-
**Closed form of the Gibbs partial sum at the aligned quarter-integer, negative root.**
Under `Y ≡ -R + 1 (mod P)` with `P` an odd prime `≥ 5` and `R = (P+1)/6`, the truncated symmetric
cosine series evaluated at `Y + 1/4` collapses to a difference of two reciprocal-sine terms.
-/
set_option maxHeartbeats 4000000 in
-- reason for change? we haven't tried to optimize yet, duh!
theorem overshoot_closed_form_quarter (P R : ℕ) (hP : P.Prime) (hP5 : 5 ≤ P)
    (hR : R = (P + 1) / 6) (Y : ℤ) (hY : Y ≡ -(R : ℤ) + 1 [ZMOD (P : ℤ)]) :
    ∑ k ∈ Finset.range ((P + 1) / 2),
        (if k = 0 then 2 / (P : ℝ)
          else if k ≤ (P - 1) / 2 then 4 / (P : ℝ) * Real.cos (2 * Real.pi * k * (R : ℝ) / (P : ℝ))
          else 0)
          * Real.cos (2 * Real.pi * k * ((Y : ℝ) + 0.25) / (P : ℝ))
      = (Real.sqrt 2 / (2 * (P : ℝ))) * (1 / Real.sin ((8 * (R : ℝ) - 5) * Real.pi / (4 * P))
          - 1 / Real.sin (5 * Real.pi / (4 * P))) := by
  obtain ⟨ m, hm ⟩ := hY.symm.dvd
  -- Split the sum into two parts: one for $k = 0$ and one for $1 \leq k \leq (P - 1) / 2$.
  have h_split : ∑ k ∈ Finset.range ((P + 1) / 2), (if k = 0 then 2 / (P : ℝ) else if k ≤ (P - 1) / 2 then 4 / (P : ℝ) * Real.cos (2 * Real.pi * k * (R : ℝ) / (P : ℝ)) else 0) * Real.cos (2 * Real.pi * k * ((Y : ℝ) + 0.25) / (P : ℝ)) = (2 / (P : ℝ)) + (2 / (P : ℝ)) * ∑ k ∈ Finset.range ((P - 1) / 2), (Real.cos (2 * Real.pi * (k + 1) * (5 / 4 : ℝ) / (P : ℝ)) + Real.cos (2 * Real.pi * (k + 1) * ((8 * R - 5) / 4 : ℝ) / (P : ℝ))) := by
    have h_split : ∑ k ∈ Finset.Ico 1 ((P + 1) / 2), (4 / (P : ℝ) * Real.cos (2 * Real.pi * k * (R : ℝ) / (P : ℝ))) * Real.cos (2 * Real.pi * k * ((Y : ℝ) + 0.25) / (P : ℝ)) = (2 / (P : ℝ)) * ∑ k ∈ Finset.range ((P - 1) / 2), (Real.cos (2 * Real.pi * (k + 1) * (5 / 4 : ℝ) / (P : ℝ)) + Real.cos (2 * Real.pi * (k + 1) * ((8 * R - 5) / 4 : ℝ) / (P : ℝ))) := by
      have h_split : ∀ k ∈ Finset.Ico 1 ((P + 1) / 2), (4 / (P : ℝ) * Real.cos (2 * Real.pi * k * (R : ℝ) / (P : ℝ))) * Real.cos (2 * Real.pi * k * ((Y : ℝ) + 0.25) / (P : ℝ)) = (2 / (P : ℝ)) * (Real.cos (2 * Real.pi * k * (5 / 4 : ℝ) / (P : ℝ)) + Real.cos (2 * Real.pi * k * ((8 * R - 5) / 4 : ℝ) / (P : ℝ))) := by
        intro k hk; rw [ Real.cos_add_cos ] ; ring_nf
        norm_num [ show Y = -R + 1 + P * m by linarith ] ; ring_nf
        norm_num [ hP.ne_zero ]
        exact Or.inl ( by convert Real.cos_periodic.int_mul ( k * m ) _ using 2; push_cast; ring )
      rw [ Finset.sum_congr rfl h_split, Finset.mul_sum _ _ _ ]
      rw [ Finset.sum_Ico_eq_sum_range ] ; norm_num [ add_comm, add_left_comm, add_assoc ]
      grind
    rw [ ← h_split, Finset.sum_Ico_eq_sub _ ] <;> norm_num [ Finset.sum_range_succ' ]
    · rcases Nat.even_or_odd' P with ⟨ c, rfl | rfl ⟩ <;> norm_num [ Nat.add_div ] at *
      · simp_all +decide [ Nat.prime_mul_iff ]
      · norm_num [ Finset.sum_range_succ' ]
        rw [ add_comm, Finset.sum_congr rfl fun x hx => if_pos <| Finset.mem_range.mp hx ]
    · omega
  -- Apply the Dirichlet cosine sum closed form to each family.
  have h_dirichlet : ∀ θ : ℝ, Real.sin (θ / 2) ≠ 0 → ∑ k ∈ Finset.range ((P - 1) / 2), Real.cos ((k + 1) * θ) = (Real.sin ((P / 2) * θ) - Real.sin (θ / 2)) / (2 * Real.sin (θ / 2)) := by
    intro θ hθ
    have h_dirichlet_step : ∀ n : ℕ, ∑ k ∈ Finset.range n, Real.cos ((k + 1) * θ) = (Real.sin ((n + 1 / 2) * θ) - Real.sin (θ / 2)) / (2 * Real.sin (θ / 2)) := by
      intro n; rw [ eq_div_iff ( mul_ne_zero two_ne_zero hθ ) ]
      induction n with
      | zero =>
        simp_all +decide [ add_mul ] ; ring_nf
      | succ n =>
        simp_all +decide only [Int.natCast_ediv, Nat.cast_add, Nat.cast_one, Nat.cast_ofNat,
          ite_mul, CharP.cast_eq_zero, mul_zero, zero_mul, zero_div, Real.cos_zero, mul_one, ne_eq,
          add_mul, one_mul, one_div, sum_range_succ] ; ring_nf
        rw [ ← Complex.ofReal_inj ] ; norm_num [ Complex.sin, Complex.cos ] ; ring_nf
        norm_num [ mul_assoc, ← Complex.exp_add ] ; ring_nf
    cases Nat.Prime.odd_of_ne_two hP ( by linarith ) ; simp_all +decide [ Nat.add_div ] ; ring_nf
  -- Apply the Dirichlet cosine sum closed form to each family and simplify.
  have h_simplify : ∑ k ∈ Finset.range ((P - 1) / 2), (Real.cos (2 * Real.pi * (k + 1) * (5 / 4 : ℝ) / (P : ℝ)) + Real.cos (2 * Real.pi * (k + 1) * ((8 * R - 5) / 4 : ℝ) / (P : ℝ))) = (-Real.sqrt 2 / 2 - Real.sin (5 * Real.pi / (4 * P))) / (2 * Real.sin (5 * Real.pi / (4 * P))) + (Real.sqrt 2 / 2 - Real.sin ((8 * R - 5) * Real.pi / (4 * P))) / (2 * Real.sin ((8 * R - 5) * Real.pi / (4 * P))) := by
    rw [ Finset.sum_add_distrib, show ( ∑ k ∈ Finset.range ( ( P - 1 ) / 2 ), Real.cos ( 2 * Real.pi * ( k + 1 ) * ( 5 / 4 ) / P ) ) = ( Real.sin ( P / 2 * ( 2 * Real.pi * ( 5 / 4 ) / P ) ) - Real.sin ( ( 2 * Real.pi * ( 5 / 4 ) / P ) / 2 ) ) / ( 2 * Real.sin ( ( 2 * Real.pi * ( 5 / 4 ) / P ) / 2 ) ) from ?_, show ( ∑ k ∈ Finset.range ( ( P - 1 ) / 2 ), Real.cos ( 2 * Real.pi * ( k + 1 ) * ( ( 8 * R - 5 ) / 4 ) / P ) ) = ( Real.sin ( P / 2 * ( 2 * Real.pi * ( ( 8 * R - 5 ) / 4 ) / P ) ) - Real.sin ( ( 2 * Real.pi * ( ( 8 * R - 5 ) / 4 ) / P ) / 2 ) ) / ( 2 * Real.sin ( ( 2 * Real.pi * ( ( 8 * R - 5 ) / 4 ) / P ) / 2 ) ) from ?_ ]
    · congr 2 <;> ring_nf <;> norm_num [ mul_assoc, mul_comm, mul_left_comm, hP.ne_zero ]
      · rw [ show Real.pi * ( 5 / 4 ) = Real.pi / 4 + Real.pi by ring, Real.sin_add ] ; norm_num ; ring
      · norm_num [ Real.sin_add, mul_div ] ; ring_nf
        norm_num [ show Real.sin ( Real.pi * R * 2 ) = 0 from Real.sin_eq_zero_iff.mpr ⟨ R * 2, by push_cast; ring ⟩, show Real.cos ( Real.pi * R * 2 ) = 1 from by rw [ Real.cos_eq_one_iff ] ; use R; push_cast; ring, show Real.pi * ( 5 / 4 ) = Real.pi / 4 + Real.pi by ring ] ; ring
    · convert h_dirichlet ( 2 * Real.pi * ( ( 8 * R - 5 ) / 4 ) / P ) _ using 2
      · ring_nf
      · refine ne_of_gt ( Real.sin_pos_of_pos_of_lt_pi ?_ ?_ )
        · exact div_pos ( div_pos ( mul_pos ( by positivity ) ( div_pos ( sub_pos.mpr ( by linarith [ show ( R : ℝ ) ≥ 1 by exact_mod_cast hR.symm ▸ Nat.div_pos ( by linarith ) ( by norm_num ) ] ) ) ( by positivity ) ) ) ( by positivity ) ) ( by positivity )
        · rw [ div_div, div_lt_iff₀ ] <;> nlinarith only [ Real.pi_pos, show ( P : ℝ ) ≥ 5 by norm_cast, show ( R : ℝ ) ≤ ( P + 1 ) / 6 by exact_mod_cast hR.symm ▸ Nat.cast_div_le .. ]
    · convert h_dirichlet ( 2 * Real.pi * ( 5 / 4 ) / P ) _ using 2 <;> ring_nf
      exact ne_of_gt ( Real.sin_pos_of_pos_of_lt_pi ( by positivity ) ( by nlinarith [ Real.pi_pos, show ( P : ℝ ) ≥ 5 by norm_cast, mul_inv_cancel₀ ( by positivity : ( P : ℝ ) ≠ 0 ) ] ) )
  convert h_split using 1
  rw [ h_simplify ] ; ring_nf
  rw [ mul_inv_cancel_right₀, mul_inv_cancel_right₀ ] <;> norm_num
  · ring
  · exact ne_of_gt ( Real.sin_pos_of_pos_of_lt_pi ( by positivity ) ( by nlinarith [ Real.pi_pos, show ( P : ℝ ) ≥ 5 by norm_cast, inv_mul_cancel₀ ( by positivity : ( P : ℝ ) ≠ 0 ) ] ) )
  · rw [ Real.sin_eq_zero_iff_of_lt_of_lt ]
    · field_simp
      nlinarith [ Real.pi_pos, show ( R : ℝ ) ≥ 1 by exact_mod_cast hR.symm ▸ Nat.div_pos ( by linarith ) ( by norm_num ) ]
    · nlinarith only [ Real.pi_pos, show ( P : ℝ ) ≥ 5 by norm_cast, inv_pos.mpr ( by positivity : 0 < ( P : ℝ ) ), mul_inv_cancel₀ ( by positivity : ( P : ℝ ) ≠ 0 ), show ( R : ℝ ) ≥ 0 by positivity, mul_nonneg Real.pi_pos.le ( inv_nonneg.mpr ( by positivity : 0 ≤ ( P : ℝ ) ) ) ]
    · field_simp
      norm_cast
      grind

/-
**The arithmetic bound (quarter-integer, negative root).** The reciprocal-sine difference is
`≤ 0.12`. For `R ≥ 2` (i.e. `P ≥ 11`) the difference is `≤ 0` because `(8R-5)π/(4P) ≥ 5π/(4P)`
and both angles lie in `(0, π/2)`, so `sin((8R-5)π/(4P)) ≥ sin(5π/(4P))`. Only `R = 1`
(i.e. `P ∈ {5,7}`) is nontrivial, and there the bound follows from the Taylor `sin` bounds.
-/
theorem overshoot_bound_quarter (P R : ℕ) (hP : P.Prime) (hP5 : 5 ≤ P) (hR : R = (P + 1) / 6) :
    (Real.sqrt 2 / (2 * (P : ℝ))) * (1 / Real.sin ((8 * (R : ℝ) - 5) * Real.pi / (4 * P))
        - 1 / Real.sin (5 * Real.pi / (4 * P))) ≤ (0.12 : ℝ) := by
  by_cases hR_ge_2 : R ≥ 2
  · have h_sin_bound : Real.sin ((8 * R - 5) * Real.pi / (4 * P)) ≥ Real.sin (5 * Real.pi / (4 * P)) := by
      convert Real.sin_le_sin_of_le_of_le_pi_div_two _ _ _ using 1
      · exact le_trans ( by linarith [ Real.pi_pos ] ) ( div_nonneg ( by positivity ) ( by positivity ) )
      · rw [ div_le_iff₀ ] <;> try positivity
        nlinarith [ Real.pi_pos, show ( P : ℝ ) ≥ 5 by norm_cast,
          show ( R : ℝ ) ≤ ( P + 1 ) / 6 by exact_mod_cast hR.symm ▸ Nat.cast_div_le ..,
          mul_div_cancel₀ ( ( P + 1 : ℝ ) ) ( by norm_num : ( 6 : ℝ ) ≠ 0 ) ]
      · gcongr ; nlinarith [ Real.pi_pos, show ( R : ℝ ) ≥ 2 by norm_cast ]
    refine le_trans ?_ ( show 0 ≤ 0.12 by norm_num )
    exact mul_nonpos_of_nonneg_of_nonpos ( by positivity ) ( sub_nonpos_of_le <|
      one_div_le_one_div_of_le ( Real.sin_pos_of_pos_of_lt_pi ( by positivity ) <|
      by rw [ div_lt_iff₀ <| by positivity ] ; nlinarith [ Real.pi_pos, show ( P : ℝ ) ≥ 5 by norm_cast ] ) h_sin_bound )
  · interval_cases _ : R <;> norm_num at *
    · omega
    · rcases P with ( _ | _ | _ | _ | _ | _ | _ | _ | _ | _ | _ | _ | P )
      · revert hP; decide
      · revert hP; decide
      · omega
      · omega
      · omega
      · norm_num at *
        rw [ show 5 * Real.pi / 20 = Real.pi / 4 by ring, Real.sin_pi_div_four ]
        -- Using the Taylor series expansion for sine, we can approximate $\sin(3\pi/20)$.
        have h_sin_approx : Real.sin (3 * Real.pi / 20) ≥
            3 * Real.pi / 20 - (3 * Real.pi / 20)^3 / 6 - (3 * Real.pi / 20)^4 * (5 / 96) := by
          exact sin_taylor_ge _ ( by positivity ) ( by linarith [ Real.pi_le_four ] )
        -- Substitute the approximation of $\sin(3\pi/20)$ into the inequality.
        have h_subst : Real.sin (3 * Real.pi / 20) ≥ 0.4512 := by
          have h_pi_approx : Real.pi > 3.141592 := by
            grind +suggestions
          have h_le : (0.4512 : ℝ) ≤ 3 * Real.pi / 20 - (3 * Real.pi / 20)^3 / 6 - (3 * Real.pi / 20)^4 * (5 / 96) := by
            norm_num1 at *
            nlinarith [ Real.pi_le_four, (pow_pos ( sub_pos.mpr h_pi_approx ) 2), (pow_pos ( sub_pos.mpr h_pi_approx ) 3) ]
          exact le_trans h_le h_sin_approx
        field_simp
        nlinarith [ Real.sqrt_nonneg 2, Real.sq_sqrt zero_le_two ]
      · revert hP; decide
      · norm_num at *
        -- Use the Taylor series bounds for sine to estimate the values.
        have h_sin_bounds : Real.sin (3 * Real.pi / 28) ≥
            3 * Real.pi / 28 - (3 * Real.pi / 28)^3 / 6 - (3 * Real.pi / 28)^4 * (5 / 96) ∧
            Real.sin (5 * Real.pi / 28) ≤
            5 * Real.pi / 28 - (5 * Real.pi / 28)^3 / 6 + (5 * Real.pi / 28)^4 * (5 / 96) := by
          apply And.intro
          · convert sin_taylor_ge _ _ _ using 1 <;> ring_nf <;> norm_num [ Real.pi_pos ]
            linarith [ Real.pi_le_four ]
          · apply sin_taylor_le
            · positivity
            · linarith [ Real.pi_le_four ]
        -- Substitute the bounds into the expression.
        have h_subst : (Real.sqrt 2 / 14) * ((1 / (3 * Real.pi / 28 - (3 * Real.pi / 28)^3 / 6 -
            (3 * Real.pi / 28)^4 * (5 / 96)) - 1 / (5 * Real.pi / 28 - (5 * Real.pi / 28)^3 / 6 +
            (5 * Real.pi / 28)^4 * (5 / 96)))) ≤ 3 / 25 := by
          rw [ div_sub_div, mul_div, div_le_iff₀ ] <;> ring_nf <;> norm_num
          · have h_pi_approx : Real.pi > 3.141592 ∧ Real.pi < 3.141593 := by
              grind +suggestions
            have h_sqrt2_approx : Real.sqrt 2 < 1.414214 := by
              rw [ Real.sqrt_lt ] <;> norm_num
            nlinarith [ (pow_pos ( sub_pos.mpr h_pi_approx.1 ) 3), (pow_pos ( sub_pos.mpr h_pi_approx.1 ) 4),
              (pow_pos ( sub_pos.mpr h_pi_approx.1 ) 5), (pow_pos ( sub_pos.mpr h_pi_approx.1 ) 6),
              (pow_pos ( sub_pos.mpr h_pi_approx.1 ) 7), (pow_pos ( sub_pos.mpr h_pi_approx.1 ) 8),
              Real.sqrt_nonneg 2, Real.sq_sqrt zero_le_two ]
          · have := Real.pi_lt_d4; norm_num at *
            nlinarith [ (pow_pos Real.pi_pos 3), (pow_pos Real.pi_pos 4), (pow_pos Real.pi_pos 5),
              (pow_pos Real.pi_pos 6), (pow_pos Real.pi_pos 7) ]
          · nlinarith only [ Real.pi_gt_three, Real.pi_le_four, (pow_pos Real.pi_pos 2), (pow_pos Real.pi_pos 3) ]
          · nlinarith only [ Real.pi_gt_three, Real.pi_le_four, (pow_pos Real.pi_pos 2), (pow_pos Real.pi_pos 3) ]
        refine le_trans ?_ h_subst
        gcongr
        · rw [ one_div ] ; exact inv_anti₀ ( by nlinarith only [ Real.pi_gt_three, Real.pi_le_four,
            (pow_pos Real.pi_pos 2), (pow_pos Real.pi_pos 3) ] ) h_sin_bounds.1
        · rw [ inv_eq_one_div, div_le_div_iff₀ ]
          · nlinarith [ Real.pi_gt_three, Real.pi_le_four, (pow_pos Real.pi_pos 2), (pow_pos Real.pi_pos 3),
              (pow_pos Real.pi_pos 4), (Real.sin_pos_of_pos_of_lt_pi ( show 0 < 5 * Real.pi / 28 by positivity )
              ( by linarith [ Real.pi_pos ] )) ]
          · have hpos : 0 < 5 * Real.pi / 28 := by positivity
            have hp3 : (5 * Real.pi / 28)^3 < 5 * Real.pi / 28 := by
              calc (5 * Real.pi / 28)^3 = (5 * Real.pi / 28) * (5 * Real.pi / 28)^2 := by ring
                _ < (5 * Real.pi / 28) * 1 := by
                  gcongr
                  calc (5 * Real.pi / 28)^2 < (5 * 4 / 28)^2 := by gcongr; exact Real.pi_lt_four
                    _ < 1 := by norm_num
                _ = 5 * Real.pi / 28 := by ring
            linarith [pow_pos hpos 4]
          · exact Real.sin_pos_of_pos_of_lt_pi (by positivity) (by linarith [Real.pi_pos])
      · revert hP; decide
      · revert hP; decide
      · revert hP; decide
      · omega
      · omega

/-- **The Gibbs overshoot at the quarter-integer (negative root).**
Let `P` be a prime `≥ 5`, `R = (P+1)/6`, and let `Y` be an integer with `Y ≡ -R + 1 (mod P)`.
The truncated symmetric cosine series, evaluated at the quarter-integer `Y + 1/4`, is at most
`0.12`. -/
theorem overshoot_value_quarter (P R : ℕ) (hP : P.Prime) (hP5 : 5 ≤ P) (hR : R = (P + 1) / 6)
    (Y : ℤ) (hY : Y ≡ -(R : ℤ) + 1 [ZMOD (P : ℤ)]) :
    ∑ k ∈ Finset.range ((P + 1) / 2),
        (if k = 0 then 2 / (P : ℝ)
          else if k ≤ (P - 1) / 2 then 4 / (P : ℝ) * Real.cos (2 * Real.pi * k * (R : ℝ) / (P : ℝ))
          else 0)
          * Real.cos (2 * Real.pi * k * ((Y : ℝ) + 0.25) / (P : ℝ)) ≤ (0.12 : ℝ) := by
  rw [overshoot_closed_form_quarter P R hP hP5 hR Y hY]
  exact overshoot_bound_quarter P R hP hP5 hR

/-
**The averaged Gibbs value at the quarter-integer.**
The arithmetic mean of the positive-root and negative-root evaluations at the quarter offset is
`≤ -0.04`. This uses the two closed forms (`undershoot_closed_form_quarter` and
`overshoot_closed_form_quarter`); the negative `1/sin(5π/(4P))` contributions add up and dominate.
-/
theorem expected_value_quarter (P R : ℕ) (hP : P.Prime) (hP5 : 5 ≤ P) (hR : R = (P + 1) / 6)
    (Ypos Yneg : ℤ) (hpos : Ypos ≡ (R : ℤ) + 1 [ZMOD (P : ℤ)])
    (hneg : Yneg ≡ -(R : ℤ) + 1 [ZMOD (P : ℤ)]) :
    (1 / 2 : ℝ) * (
      (∑ k ∈ Finset.range ((P + 1) / 2),
        (if k = 0 then 2 / (P : ℝ)
          else if k ≤ (P - 1) / 2 then 4 / (P : ℝ) * Real.cos (2 * Real.pi * k * (R : ℝ) / (P : ℝ))
          else 0) * Real.cos (2 * Real.pi * k * ((Ypos : ℝ) + 0.25) / (P : ℝ)))
      + (∑ k ∈ Finset.range ((P + 1) / 2),
        (if k = 0 then 2 / (P : ℝ)
          else if k ≤ (P - 1) / 2 then 4 / (P : ℝ) * Real.cos (2 * Real.pi * k * (R : ℝ) / (P : ℝ))
          else 0) * Real.cos (2 * Real.pi * k * ((Yneg : ℝ) + 0.25) / (P : ℝ)))
    ) ≤ -(0.04 : ℝ) := by
  -- After the rewrites the goal becomes
  -- `(1/2) * (-(√2/(2P))*(1/s1 + 1/s2) + (√2/(2P))*(1/s3 - 1/s1)) ≤ -0.04`, i.e. equivalently
  -- `(√2/(4P)) * (2/s1 + 1/s2 - 1/s3) ≥ 0.04`.
  suffices h_suff : (Real.sqrt 2 / (4 * (P : ℝ))) * (2 / Real.sin (5 * Real.pi / (4 * P)) + 1 / Real.sin ((8 * R + 5) * Real.pi / (4 * P)) - 1 / Real.sin ((8 * R - 5) * Real.pi / (4 * P))) ≥ 0.04 by
    rw [undershoot_closed_form_quarter P R hP hP5 hR Ypos hpos,
        overshoot_closed_form_quarter P R hP hP5 hR Yneg hneg]
    refine le_trans (le_of_eq ?_) (neg_le_neg h_suff)
    ring
  by_cases hR_ge_2 : R ≥ 2
  · -- Since $R \geq 2$, we have $8R - 5 \geq 11$, so the angle of $\sin((8R-5)\pi/(4P))$ is $\geq$
    -- that of $\sin(5\pi/(4P))$, both in $(0, \pi/2)$, giving
    -- $\sin((8R-5)\pi/(4P)) \geq \sin(5\pi/(4P))$.
    have h_sin_ge : Real.sin ((8 * R - 5) * Real.pi / (4 * P)) ≥ Real.sin (5 * Real.pi / (4 * P)) := by
      rw [ ← Real.cos_pi_div_two_sub, ← Real.cos_pi_div_two_sub ]
      refine Real.cos_le_cos_of_nonneg_of_le_pi ?_ ?_ ?_ <;> nlinarith [ Real.pi_pos, show ( P : ℝ ) ≥ 5 by norm_cast, show ( R : ℝ ) ≥ 2 by norm_cast, mul_div_cancel₀ ( ( 8 * R - 5 ) * Real.pi ) ( by positivity : ( 4 * P : ℝ ) ≠ 0 ), mul_div_cancel₀ ( 5 * Real.pi ) ( by positivity : ( 4 * P : ℝ ) ≠ 0 ), show ( R : ℝ ) * 6 ≤ P + 1 by norm_cast; omega ]
    -- Therefore, $2 / \sin(5 \pi / (4P)) + 1 / \sin((8R + 5) \pi / (4P))
    -- - 1 / \sin((8R - 5) \pi / (4P)) \geq 1 / \sin(5 \pi / (4P))$.
    have h_ineq : 2 / Real.sin (5 * Real.pi / (4 * P)) + 1 / Real.sin ((8 * R + 5) * Real.pi / (4 * P)) - 1 / Real.sin ((8 * R - 5) * Real.pi / (4 * P)) ≥ 1 / Real.sin (5 * Real.pi / (4 * P)) := by
      have h_pos : 0 < Real.sin (5 * Real.pi / (4 * P)) ∧ 0 < Real.sin ((8 * R + 5) * Real.pi / (4 * P)) ∧ 0 < Real.sin ((8 * R - 5) * Real.pi / (4 * P)) := by
        refine ⟨ Real.sin_pos_of_pos_of_lt_pi ?_ ?_, Real.sin_pos_of_pos_of_lt_pi ?_ ?_, Real.sin_pos_of_pos_of_lt_pi ?_ ?_ ⟩ <;> try positivity
        · rw [ div_lt_iff₀ ] <;> nlinarith only [ Real.pi_pos, show ( P : ℝ ) ≥ 5 by norm_cast ]
        · rw [ div_lt_iff₀ ( by positivity ) ]
          rw [ mul_comm ] ; gcongr
          norm_cast ; omega
        · exact div_pos ( mul_pos ( sub_pos.mpr ( by norm_cast; linarith ) ) Real.pi_pos ) ( by positivity )
        · rw [ div_lt_iff₀ ( by positivity ) ]
          nlinarith [ Real.pi_pos, show ( R : ℝ ) ≤ P / 6 + 1 / 6 by rw [ hR ] ; rw [ div_add_div, le_div_iff₀ ] <;> norm_cast ; linarith [ Nat.div_mul_le_self ( P + 1 ) 6 ] ]
      ring_nf at *
      nlinarith [ inv_pos.2 h_pos.1, inv_pos.2 h_pos.2.1, inv_pos.2 h_pos.2.2, mul_inv_cancel₀ h_pos.1.ne', mul_inv_cancel₀ h_pos.2.1.ne', mul_inv_cancel₀ h_pos.2.2.ne', mul_le_mul_of_nonneg_left h_sin_ge <| inv_nonneg.2 h_pos.1.le, mul_le_mul_of_nonneg_left h_sin_ge <| inv_nonneg.2 h_pos.2.1.le, mul_le_mul_of_nonneg_left h_sin_ge <| inv_nonneg.2 h_pos.2.2.le ]
    -- Since $\sin(5\pi/(4P)) \leq 5\pi/(4P)$, we have $1 / \sin(5\pi/(4P)) \geq 4P/(5\pi)$.
    have h_sin_bound : 1 / Real.sin (5 * Real.pi / (4 * P)) ≥ 4 * P / (5 * Real.pi) := by
      rw [ ge_iff_le, div_le_div_iff₀ ] <;> norm_num
      · exact le_trans ( mul_le_mul_of_nonneg_left ( le_of_lt ( Real.sin_lt <| by positivity ) ) <| by positivity ) <| by nlinarith [ Real.pi_pos, show ( P : ℝ ) ≥ 5 by norm_cast, mul_div_cancel₀ ( 5 * Real.pi ) ( by positivity : ( 4 * P : ℝ ) ≠ 0 ) ]
      · positivity
      · exact Real.sin_pos_of_pos_of_lt_pi ( by positivity ) ( by rw [ div_lt_iff₀ ( by positivity ) ] ; nlinarith only [ Real.pi_pos, show ( P : ℝ ) ≥ 5 by norm_cast ] )
    refine le_trans ?_ ( mul_le_mul_of_nonneg_left ( h_ineq.trans' h_sin_bound ) <| by positivity )
    rw [ div_mul_div_cancel₀ ( by positivity ) ] ; ring_nf ; norm_num [ Real.pi_pos.ne' ]
    nlinarith only [ Real.pi_gt_three, Real.pi_le_four, Real.sqrt_nonneg 2, Real.sq_sqrt zero_le_two, inv_pos.mpr Real.pi_pos, mul_inv_cancel₀ Real.pi_ne_zero, mul_le_mul_of_nonneg_left Real.pi_le_four <| Real.sqrt_nonneg 2 ]
  · interval_cases R <;> norm_num at *
    · omega
    · have : P ≤ 11 := Nat.le_of_lt_succ ( by omega ) ; interval_cases P <;> norm_num at *
      · rw [ show 5 * Real.pi / 20 = Real.pi / 4 by ring, show 13 * Real.pi / 20 = Real.pi - 7 * Real.pi / 20 by ring, show 3 * Real.pi / 20 = Real.pi / 4 - Real.pi / 10 by ring ] ; norm_num [ Real.sin_pi_sub, Real.sin_sub ] ; ring_nf ; norm_num
        rw [ show Real.pi * ( 7 / 20 ) = Real.pi / 2 - Real.pi * ( 3 / 20 ) by ring, Real.sin_pi_div_two_sub ] ; ring_nf ; norm_num
        refine le_add_of_le_of_nonneg ?_ ?_
        · field_simp
          rw [ add_div', div_mul_eq_mul_div, div_le_iff₀ ] <;> norm_num
          · -- We'll use that $\cos(\pi/10) \approx 0.9511$ and $\sin(\pi/10) \approx 0.3090$.
            have h_cos_sin : Real.cos (Real.pi / 10) > 0.95 ∧ Real.sin (Real.pi / 10) < 0.31 := by
              constructor
              · -- Using the double-angle identity, we have
                -- $\cos(\pi/10) = \sqrt{\frac{1 + \cos(\pi/5)}{2}}$.
                have h_cos_double_angle : Real.cos (Real.pi / 10) = Real.sqrt ((1 + Real.cos (Real.pi / 5)) / 2) := by
                  rw [ Real.cos_eq_sqrt_one_sub_sin_sq, Real.sin_sq, Real.cos_sq ] <;> ring_nf <;> linarith [ Real.pi_pos ]
                rw [ h_cos_double_angle, gt_iff_lt, Real.lt_sqrt ] <;> norm_num
                nlinarith [ Real.sqrt_nonneg 5, Real.sq_sqrt ( show 0 ≤ 5 by norm_num ) ]
              · have := sin_taylor_le ( Real.pi / 10 ) ( by positivity ) ( by linarith [ Real.pi_le_four ] )
                have h_pi_approx : Real.pi < 3.1416 := by
                  grind +suggestions
                exact this.trans_lt ( by norm_num1 at *; nlinarith [ Real.pi_gt_three, pow_pos Real.pi_pos 2, pow_pos Real.pi_pos 3 ] )
            norm_num at h_cos_sin ; linarith
          · rw [ ← Real.cos_pi_div_two_sub ] ; exact Real.cos_lt_cos_of_nonneg_of_le_pi ( by linarith [ Real.pi_pos ] ) ( by linarith [ Real.pi_pos ] ) ( by linarith [ Real.pi_pos ] )
          · exact ne_of_gt ( by rw [ ← Real.cos_pi_div_two_sub ] ; exact sub_pos_of_lt ( Real.cos_lt_cos_of_nonneg_of_le_pi ( by linarith [ Real.pi_pos ] ) ( by linarith [ Real.pi_pos ] ) ( by linarith [ Real.pi_pos ] ) ) )
        · exact mul_nonneg ( mul_nonneg ( Real.sqrt_nonneg _ ) ( inv_nonneg.mpr ( Real.cos_nonneg_of_mem_Icc ⟨ by linarith [ Real.pi_pos ], by linarith [ Real.pi_pos ] ⟩ ) ) ) ( by norm_num )
      · -- Apply the Taylor bounds to each sine term.
        have h_sin_bounds : Real.sin (5 * Real.pi / 28) ≤ 5 * Real.pi / 28 - (5 * Real.pi / 28)^3 / 6 + (5 * Real.pi / 28)^4 * (5 / 96) ∧ Real.sin (3 * Real.pi / 28) ≥ 3 * Real.pi / 28 - (3 * Real.pi / 28)^3 / 6 - (3 * Real.pi / 28)^4 * (5 / 96) := by
          apply And.intro
          · convert sin_taylor_le _ _ _ using 1 <;> ring_nf <;> norm_num [ Real.pi_pos ]
            linarith [ Real.pi_le_four ]
          · convert sin_taylor_ge ( 3 * Real.pi / 28 ) ( by positivity ) ( by linarith [ Real.pi_le_four ] ) using 1
        -- Substitute the Taylor bounds into the inequality.
        have h_subst : 1 / 25 ≤ (Real.sqrt 2 / 28) * (2 / (5 * Real.pi / 28 - (5 * Real.pi / 28)^3 / 6 + (5 * Real.pi / 28)^4 * (5 / 96)) + 1 - 1 / (3 * Real.pi / 28 - (3 * Real.pi / 28)^3 / 6 - (3 * Real.pi / 28)^4 * (5 / 96))) := by
          have h_pi_bounds : 3.141592 < Real.pi ∧ Real.pi < 3.141593 := by
            grind +suggestions
          field_simp
          rw [ div_add', div_mul_eq_mul_div, div_sub_div, mul_div_assoc' ] <;> try nlinarith [ Real.pi_gt_three, pow_pos Real.pi_pos 3 ]
          rw [ le_div_iff₀ ] <;> norm_num at *
          · have h_sqrt2_bounds : 1.414213 < Real.sqrt 2 ∧ Real.sqrt 2 < 1.414214 := by
              norm_num [ Real.lt_sqrt, Real.sqrt_lt ]
            nlinarith [ pow_pos ( sub_pos.mpr h_pi_bounds.1 ) 3, pow_pos ( sub_pos.mpr h_pi_bounds.1 ) 4, pow_pos ( sub_pos.mpr h_pi_bounds.1 ) 5, pow_pos ( sub_pos.mpr h_pi_bounds.1 ) 6, pow_pos ( sub_pos.mpr h_pi_bounds.1 ) 7, pow_pos ( sub_pos.mpr h_pi_bounds.1 ) 8, pow_pos ( sub_pos.mpr h_pi_bounds.1 ) 9, pow_pos ( sub_pos.mpr h_pi_bounds.1 ) 10 ]
          · exact mul_pos ( by nlinarith [ Real.pi_gt_three, pow_pos Real.pi_pos 3 ] ) ( by nlinarith [ Real.pi_gt_three, pow_pos Real.pi_pos 3 ] )
        refine le_trans h_subst ?_
        gcongr
        · exact Real.sin_pos_of_pos_of_lt_pi ( by positivity ) ( by linarith only [ Real.pi_pos ] )
        · linarith
        · exact one_le_inv₀ ( Real.sin_pos_of_pos_of_lt_pi ( by positivity ) ( by linarith [ Real.pi_pos ] ) ) |>.2 ( Real.sin_le_one _ )
        · rw [ one_div ] ; gcongr
          · nlinarith only [ Real.pi_gt_three, Real.pi_le_four, pow_pos Real.pi_pos 2, pow_pos Real.pi_pos 3 ]
          · grind

end KrafftSieve.GibbsAux
