/-
Copyright (c) 2026 Fernando Portela. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Fernando Portela, Gemini 3.1 Pro (Google DeepMind)
-/

/-
Portions of this file were generated by Aristotle (https://aristotle.harmonic.fun).

Lean version: leanprover/lean4:v4.28.0
Mathlib version: 8f9d9cff6bd728b17a24e163c9402775d9e6a365

To cite Aristotle, tag @Aristotle-Harmonic on GitHub PRs/issues, and add as co-author to commits:
Co-authored-by: Aristotle (Harmonic) <aristotle-harmonic@harmonic.fun>
-/

import KrafftSieve.Discretization
import KrafftSieve.GibbsAux
import KrafftSieve.CRTExpectation
import KrafftSieve.LocalEval
import Mathlib.Analysis.Complex.ExponentialBounds

/-!
# Lemma 5.1: The Unconditional Continuous Penalty Dip (`h_dip`)

This file formally proves the `h_dip` hypothesis of `KrafftSieve.MainTheorem` using the
unconditional analytic Gibbs undershoot of the continuous penalty `c_cont₀ n`.

Unlike the discrete arithmetic search (which depends on finding Twin Primes in the grid),
this proof constructs a specific continuous sub-interval `x = y_CRT + 0.25` where the
truncated Fourier series experiences massive Gibbs oscillations that plunge the penalty
below `1.0`, entirely bypassing the discrete arithmetic barrier.

The heavy self-contained analytic content lives in `KrafftSieve.GibbsAux`.
-/

namespace KrafftSieve

open scoped unitInterval Function
open unitInterval
open MeasureTheory

/--
At the quarter-integer evaluated exactly at the CRT residue offset (positive sign), the local
interpolant experiences a Gibbs undershoot strictly bounded below `-0.1`.
-/
lemma g_i_undershoot_quarter_pos (n : ℕ) (i : Fin (w n)) (y : ℤ)
    (hy : y ≡ (krafftResidue n i : ℤ) + 1 [ZMOD (p n i : ℤ)]) :
    ∑ k ∈ Finset.range ((p n i + 1) / 2),
      g_coef n i k * Real.cos (2 * Real.pi * k * (y + 0.25) / (p n i : ℝ)) ≤ -0.1 := by
  have h := GibbsAux.undershoot_value_quarter (p n i) (krafftResidue n i)
    (p_prime n i) (p_ge_5 n i) rfl y hy
  simpa only [g_coef] using h

/--
At the quarter-integer evaluated exactly at the CRT residue offset (negative sign), the local
interpolant experiences a positive Gibbs overshoot bounded above by `0.12`.
-/
lemma g_i_overshoot_quarter_neg (n : ℕ) (i : Fin (w n)) (y : ℤ)
    (hy : y ≡ -(krafftResidue n i : ℤ) + 1 [ZMOD (p n i : ℤ)]) :
    ∑ k ∈ Finset.range ((p n i + 1) / 2),
      g_coef n i k * Real.cos (2 * Real.pi * k * (y + 0.25) / (p n i : ℝ)) ≤ 0.12 := by
  have h := GibbsAux.overshoot_value_quarter (p n i) (krafftResidue n i)
    (p_prime n i) (p_ge_5 n i) rfl y hy
  simpa only [g_coef] using h

/--
The arithmetic mean of the positive and negative root evaluations at the quarter offset is strictly
negative. (This relies on the fact that the positive root undershoot dominates the negative root
overshoot when appropriately scaled for primes >= 5; specifically, for p=5, the mean is <= -0.04).
-/
lemma g_i_expected_quarter (n : ℕ) (hn : 4 ≤ n) (i : Fin (w n)) (y_pos y_neg : ℤ)
    (h_pos : y_pos ≡ (krafftResidue n i : ℤ) + 1 [ZMOD (p n i : ℤ)])
    (h_neg : y_neg ≡ -(krafftResidue n i : ℤ) + 1 [ZMOD (p n i : ℤ)]) :
    (1 / 2 : ℝ) * (
      (∑ k ∈ Finset.range ((p n i + 1) / 2), g_coef n i k * Real.cos (2 * Real.pi * k * (y_pos + 0.25) / (p n i : ℝ))) +
      (∑ k ∈ Finset.range ((p n i + 1) / 2), g_coef n i k * Real.cos (2 * Real.pi * k * (y_neg + 0.25) / (p n i : ℝ)))
    ) ≤ -0.04 := by
  have h := GibbsAux.expected_value_quarter (p n i) (krafftResidue n i)
    (p_prime n i) (p_ge_5 n i) rfl y_pos y_neg h_pos h_neg
  simpa only [g_coef] using h

/-- The set of CRT roots in the lower half `(0, q/2)`: integers `y` such that for every prime
index `i`, `y ≡ ±krafftResidue n i + 1 (mod p n i)`. These are exactly the points where the
continuous penalty `c_cont₀` experiences the Gibbs undershoot. -/
noncomputable def crtRoots (n : ℕ) : Finset ℤ :=
  (Finset.Ioo (0 : ℤ) ((q n : ℤ) / 2)).filter (fun y =>
    ∀ i : Fin (w n), y ≡ (krafftResidue n i : ℤ) + 1 [ZMOD (p n i : ℤ)] ∨
                     y ≡ -(krafftResidue n i : ℤ) + 1 [ZMOD (p n i : ℤ)])

/-- The point in `X₀` associated with an integer root `y`: the fractional part of `(y+0.25)/q`. -/
noncomputable def rootPt (n : ℕ) (y : ℤ) : X₀ :=
  ⟨(((y : ℝ) + 0.25) / (q n : ℝ)) - ⌊(((y : ℝ) + 0.25) / (q n : ℝ))⌋,
    ⟨Int.fract_nonneg _, (Int.fract_lt_one _).le⟩⟩

/-- The absolute Fourier coefficients of a single local interpolant `g_i` sum to at most `2`
(in fact exactly `2`): `|2/p| + ((p-1)/2)·|4/p| = 2`. -/
lemma g_coef_abs_sum_le_two (n : ℕ) (i : Fin (w n)) :
    ∑ k ∈ Finset.range ((p n i + 1) / 2), |g_coef n i k| ≤ 2 := by
  have hP5 := p_ge_5 n i
  have hPodd : Odd (p n i) := (p_prime n i).odd_of_ne_two (by omega)
  have hP0 : (0 : ℝ) < (p n i : ℝ) := by exact_mod_cast (by omega : 0 < p n i)
  have hPne : (p n i : ℝ) ≠ 0 := ne_of_gt hP0
  obtain ⟨t, ht⟩ := hPodd
  have hm : (p n i + 1) / 2 = t + 1 := by omega
  have hbound : ∀ k ∈ Finset.range ((p n i + 1) / 2),
      |g_coef n i k| ≤ (if k = 0 then 2 / (p n i : ℝ) else 4 / (p n i : ℝ)) := by
    intro k _
    unfold g_coef
    split_ifs with h0 h1
    · rw [abs_of_nonneg (by positivity)]
    · rw [abs_mul]
      have hc : |Real.cos (2 * Real.pi * k * (krafftResidue n i : ℝ) / (p n i : ℝ))| ≤ 1 :=
        Real.abs_cos_le_one _
      have h4 : (0 : ℝ) ≤ 4 / (p n i : ℝ) := by positivity
      rw [abs_of_nonneg h4]
      nlinarith [hc, h4]
    · simpa using (by positivity : (0 : ℝ) ≤ 4 / (p n i : ℝ))
  calc ∑ k ∈ Finset.range ((p n i + 1) / 2), |g_coef n i k|
      ≤ ∑ k ∈ Finset.range ((p n i + 1) / 2),
          (if k = 0 then 2 / (p n i : ℝ) else 4 / (p n i : ℝ)) := Finset.sum_le_sum hbound
    _ = 2 := by
        rw [hm, Finset.sum_range_succ']
        simp only [Nat.succ_ne_zero, if_false, if_true]
        rw [Finset.sum_const, Finset.card_range, nsmul_eq_mul]
        have h2P : (p n i : ℝ) = 2 * (t : ℝ) + 1 := by rw [ht]; push_cast; ring
        rw [h2P]
        have hne : (2 * (t : ℝ) + 1) ≠ 0 := by positivity
        field_simp
        ring

/-- Global pointwise lower bound: since each of the `w n` local interpolants has absolute Fourier
mass at most `2`, and `|cos| ≤ 1`, the continuous penalty is bounded below by `-2 * w n`
everywhere. -/
lemma c_cont₀_ge (n : ℕ) (t : X₀) : -2 * (w n : ℝ) ≤ c_cont₀ n t := by
  have hinner : ∀ i : Fin (w n), (-2 : ℝ) ≤
      ∑ k ∈ Finset.range ((p n i + 1) / 2),
        g_coef n i k * Real.cos (2 * Real.pi * k * (t : ℝ) * (q n : ℝ) / (p n i : ℝ)) := by
    intro i
    have habs : |∑ k ∈ Finset.range ((p n i + 1) / 2),
        g_coef n i k * Real.cos (2 * Real.pi * k * (t : ℝ) * (q n : ℝ) / (p n i : ℝ))| ≤ 2 := by
      calc |∑ k ∈ Finset.range ((p n i + 1) / 2),
              g_coef n i k * Real.cos (2 * Real.pi * k * (t : ℝ) * (q n : ℝ) / (p n i : ℝ))|
          ≤ ∑ k ∈ Finset.range ((p n i + 1) / 2),
              |g_coef n i k * Real.cos (2 * Real.pi * k * (t : ℝ) * (q n : ℝ) / (p n i : ℝ))| :=
            Finset.abs_sum_le_sum_abs _ _
        _ ≤ ∑ k ∈ Finset.range ((p n i + 1) / 2), |g_coef n i k| := by
            refine Finset.sum_le_sum (fun k _ => ?_)
            rw [abs_mul]
            have hc := Real.abs_cos_le_one
              (2 * Real.pi * k * (t : ℝ) * (q n : ℝ) / (p n i : ℝ))
            nlinarith [abs_nonneg (g_coef n i k), hc, abs_nonneg
              (Real.cos (2 * Real.pi * k * (t : ℝ) * (q n : ℝ) / (p n i : ℝ)))]
        _ ≤ 2 := g_coef_abs_sum_le_two n i
    linarith [(abs_le.mp habs).1]
  calc -2 * (w n : ℝ) = ∑ _i : Fin (w n), (-2 : ℝ) := by
        rw [Finset.sum_const, Finset.card_univ, Fintype.card_fin, nsmul_eq_mul]; ring
    _ ≤ ∑ i : Fin (w n), ∑ k ∈ Finset.range ((p n i + 1) / 2),
        g_coef n i k * Real.cos (2 * Real.pi * k * (t : ℝ) * (q n : ℝ) / (p n i : ℝ)) :=
        Finset.sum_le_sum (fun i _ => hinner i)
    _ = c_cont₀ n t := by simp only [c_cont₀]

lemma w_eq_primeCounting_six_mul_add_one (n : ℕ) (hn : 1 ≤ n) : w n + 2 = Nat.primeCounting (6 * n + 1) := by
  rw [ Nat.primeCounting ]
  rw [ Nat.primeCounting', Nat.count_eq_card_filter_range ]
  rw [ show Finset.filter Nat.Prime ( Finset.range ( 6 * n + 1 + 1 ) ) = Finset.filter ( fun x => 5 ≤ x ∧ Nat.Prime x ) ( Finset.range ( 6 * n + 1 + 1 ) ) ∪ { 2, 3 } from ?_, Finset.card_union ] <;> norm_num
  · rfl
  · ext ( _ | _ | _ | _ | _ | p ) <;> simp +arith +decide; all_goals grind

lemma w_ge_sqrt_of_ge_hundred (n : ℕ) (hn : 100 ≤ n) : Nat.sqrt n ≤ w n := by
  -- Apply Chebyshev's theorem with $m = 6n+1$.
  have h_chebyshev : Nat.primeCounting (6 * n + 1) ≥ (6 * n + 1) * Real.log 2 / Real.log (6 * n + 1) - Real.log (6 * n + 2) / Real.log (6 * n + 1) := by
    have h_chebyshev : ∀ m : ℕ, 2 ≤ m → (Nat.primeCounting m : ℝ) ≥ (m * Real.log 2 - Real.log (m + 1)) / Real.log m := by
      intro m hm
      -- Apply Chebyshev's theorem to the prime counting function.
      have h_chebyshev : Real.log (Nat.choose m (m / 2)) ≤ (Nat.primeCounting m : ℝ) * Real.log m := by
        -- By definition of binomial coefficients, we know that $\binom{m}{\lfloor m/2 \rfloor}$ is divisible by all primes $p \leq m$.
        have h_div : (∏ p ∈ Finset.filter Nat.Prime (Finset.range (m + 1)),
            p ^ (Nat.factorization (Nat.choose m (m / 2)) p)) ≤ m ^ (Nat.primeCounting m) := by
          refine le_trans ( Finset.prod_le_prod' fun p hp =>
            Nat.pow_le_pow_right ( Nat.Prime.pos <| Finset.mem_filter.mp hp |>.2 ) <|
            show Nat.factorization ( Nat.choose m ( m / 2 ) ) p ≤ Nat.log p m from ?_ ) ?_
          · have := @Nat.factorization_choose_le_log p m ( m / 2 ) ; aesop
          · refine le_trans ( Finset.prod_le_prod' fun p hp => Nat.pow_log_le_self p <|
              by linarith [ Finset.mem_filter.mp hp ] ) ?_
            norm_num [ Nat.primeCounting ]
            rw [ Nat.primeCounting', Nat.count_eq_card_filter_range ]
        have h_div : (Nat.choose m (m / 2) : ℝ) ≤ m ^ (Nat.primeCounting m) := by
          refine mod_cast le_trans ?_ h_div
          conv_lhs => rw [ ← Nat.prod_factorization_pow_eq_self
            ( Nat.ne_of_gt ( Nat.choose_pos ( Nat.div_le_self m 2 ) ) ) ]
          rw [ Finsupp.prod_of_support_subset ] <;> norm_num
          intro p hp
          simp_all +decide only [Nat.mem_primeFactors, ne_eq, Finset.mem_filter, Finset.mem_range,
            Order.lt_add_one_iff, and_true]
          exact hp.1.dvd_factorial.mp ( dvd_trans hp.2.1
            ( Nat.choose_mul_factorial_mul_factorial
              ( show m / 2 ≤ m from Nat.div_le_self _ _ ) ▸ dvd_mul_of_dvd_left ( dvd_mul_right _ _ ) _ ) )
        simpa using Real.log_le_log
          ( Nat.cast_pos.mpr <| Nat.choose_pos <| Nat.div_le_self _ _ ) h_div
      -- We'll use that $\binom{m}{m/2} \geq \frac{2^m}{m+1}$.
      have h_binom : (Nat.choose m (m / 2) : ℝ) ≥ (2 ^ m) / (m + 1) := by
        rw [ ge_iff_le, div_le_iff₀ ] <;> norm_cast <;> try positivity
        have := Nat.sum_range_choose m
        exact this ▸ le_trans ( Finset.sum_le_sum fun _ _ => Nat.choose_le_middle _ _ )
          ( by simp +decide [ mul_comm ] )
      have := Real.log_le_log ( by positivity ) h_binom
      rw [ Real.log_div ( by positivity ) ( by positivity ), Real.log_pow ] at this
      rw [ ge_iff_le, div_le_iff₀ ( Real.log_pos <| by norm_cast ) ] ; linarith
    convert h_chebyshev ( 6 * n + 1 ) ( by linarith ) using 1 ; push_cast ; ring_nf
  -- Simplify the inequality obtained from Chebyshev's theorem.
  have h_simplified : Nat.primeCounting (6 * n + 1) ≥ Nat.sqrt n + 3 := by
    -- We'll use that $Real.log (6 * n + 2) / Real.log (6 * n + 1) < 2$ for $n \geq 100$.
    have h_log_ratio : Real.log (6 * n + 2) / Real.log (6 * n + 1) < 2 := by
      rw [ div_lt_iff₀ ( Real.log_pos <| by norm_cast; linarith ) ]
      erw [ ← Real.log_pow, Real.log_lt_log_iff ] <;> norm_cast <;> nlinarith
    -- We'll use that $Real.log (6 * n + 1) < 2 * Real.sqrt (n)$ for $n \geq 100$.
    have h_log_bound : Real.log (6 * n + 1) < 2 * Real.sqrt (n) := by
      rw [ Real.log_lt_iff_lt_exp ( by positivity ) ]
      rw [ two_mul, Real.exp_add ]
      -- We'll use that $e^{\sqrt{n}} > 3\sqrt{n}$ for $n \geq 100$.
      have h_exp_gt : Real.exp (Real.sqrt n) > 3 * Real.sqrt n := by
        -- We'll use that $e^{\sqrt{n}} > 3\sqrt{n}$ for $n \geq 100$. This follows from the
        -- exponential growth rate.
        have h_exp_gt : ∀ x : ℝ, 10 ≤ x → Real.exp x > 3 * x := by
          intro x hx; rw [ Real.exp_eq_exp_ℝ ] ; norm_num [ NormedSpace.exp_eq_tsum_div ]
          refine lt_of_lt_of_le ?_ ( Summable.sum_le_tsum ( Finset.range 10 )
            ( fun _ _ => by positivity ) ( by simpa using Real.summable_pow_div_factorial x ) )
          norm_num [ Finset.sum_range_succ, Nat.factorial ]
          nlinarith [ pow_pos ( by linarith : 0 < x ) 2, pow_pos ( by linarith : 0 < x ) 3,
            pow_pos ( by linarith : 0 < x ) 4, pow_pos ( by linarith : 0 < x ) 5,
            pow_pos ( by linarith : 0 < x ) 6, pow_pos ( by linarith : 0 < x ) 7,
            pow_pos ( by linarith : 0 < x ) 8, pow_pos ( by linarith : 0 < x ) 9 ]
        exact h_exp_gt _ <| Real.le_sqrt_of_sq_le <| mod_cast by linarith
      nlinarith [ Real.sqrt_nonneg n, Real.sq_sqrt <| Nat.cast_nonneg n,
        show ( n : ℝ ) ≥ 100 by norm_cast ]
    -- Substitute the bounds into the inequality from Chebyshev's theorem.
    have h_subst : (6 * n + 1) * Real.log 2 / Real.log (6 * n + 1) > Nat.sqrt n + 5 := by
      rw [ gt_iff_lt, lt_div_iff₀ ( Real.log_pos <| by norm_cast; linarith ) ]
      refine lt_of_lt_of_le ( mul_lt_mul_of_pos_left h_log_bound ( by positivity ) ) ?_
      have := Real.log_two_gt_d9 ; norm_num at *
      nlinarith only [ this, show ( n :ℝ ) ≥ 100 by norm_cast, Real.sqrt_nonneg n,
        Real.sq_sqrt <| Nat.cast_nonneg n,
        show ( Nat.sqrt n :ℝ ) ≤ Real.sqrt n by exact Real.le_sqrt_of_sq_le <| mod_cast Nat.sqrt_le' n,
        pow_two_nonneg <| Real.sqrt n - 10 ]
    exact Nat.le_of_lt_succ <| by rw [ ← @Nat.cast_lt ℝ ] ; push_cast; linarith
  linarith [ w_eq_primeCounting_six_mul_add_one n ( by linarith ) ]

lemma trap_exponential_dominates_from_1024 (n : ℕ) (hn : 1024 ≤ n) :
    (2 * (6 * (n : ℝ) ^ 2 + 10 * (n : ℝ) + 3) + 1) < 0.01 * (2 ^ Nat.sqrt n : ℝ) := by
  -- Let $k = \sqrt{n}$. Then $k \geq 32$.
  set k : ℕ := Nat.sqrt n
  have hk : 32 ≤ k := by
    exact Nat.le_sqrt.2 ( by linarith )
  -- Substitute $n < (k+1)^2$ into the inequality.
  have h_sub : (2 : ℝ) * (6 * ((k + 1) ^ 2) ^ 2 + 10 * ((k + 1) ^ 2) + 3) + 1 < 0.01 * 2 ^ k := by
    exact Nat.le_induction ( by norm_num ) ( fun k hk ih ↦ by
      norm_num [ pow_succ' ] at *
      nlinarith [ ( by norm_cast : ( 32 :ℝ ) ≤ k ), pow_pos ( by norm_num : ( 0 :ℝ ) < 2 ) k ] ) k hk
  have hn_le : (n : ℝ) ≤ (k + 1) ^ 2 := by
    have h1 := Nat.lt_succ_sqrt' n
    exact_mod_cast h1.le
  exact lt_of_le_of_lt (by nlinarith only [hn_le]) h_sub


/--
For $n \ge 19$, the exponential growth of the solution space strictly dominates the polynomial
capacity of the trap region.
-/
lemma trap_capacity_lt_exponential (n : ℕ) (hn : 19 ≤ n) :
    (2 * (6 * (n : ℝ) ^ 2 + 10 * (n : ℝ) + 3) + 1) < 0.01 * (2 ^ w n : ℝ) := by
  by_cases hn1024 : n ≥ 1024
  · convert trap_exponential_dominates_from_1024 n hn1024 |> lt_of_lt_of_le <| mul_le_mul_of_nonneg_left ( pow_le_pow_right₀ ( by norm_num : ( 1 : ℝ ) ≤ 2 ) <| show w n ≥ Nat.sqrt n from ?_ ) <| by norm_num using 1
    exact w_ge_sqrt_of_ge_hundred n ( by linarith )
  · norm_num [ w ] at *
    field_simp
    exact mod_cast by interval_cases n <;> native_decide

lemma crt_map_int {m : ℕ} (a : Fin m → ℕ) (hcop : Pairwise (Nat.Coprime on a))
    (y : ℤ) (i : Fin m) :
    (ZMod.prodEquivPi a hcop (y : ZMod (∏ i, a i))) i = (y : ZMod (a i)) := by
  simp +decide

lemma crt_two_choices_Ico_card {m : ℕ} (a : Fin m → ℕ)
    [NeZero (∏ i, a i)]
    (hcop : Pairwise (Nat.Coprime on a))
    (u v : (i : Fin m) → ZMod (a i)) (hne : ∀ i, u i ≠ v i) :
    ((Finset.Ico 0 ((∏ i, a i) : ℤ)).filter (fun y : ℤ =>
      ∀ i, (y : ZMod (a i)) = u i ∨ (y : ZMod (a i)) = v i)).card = 2 ^ m := by
  revert hne v u
  -- By the Chinese Remainder Theorem, there is a bijection between the set of integers $y$ modulo
  -- $Q$ and the set of $m$-tuples $(y_1, y_2, \ldots, y_m)$ where $y_i \in \{u_i, v_i\}$.
  intros u v hne
  have h_bij : Finset.image (fun y : ℤ => fun i : Fin m => (y : ZMod (a i))) (Finset.filter (fun y => ∀ i, (y : ZMod (a i)) = u i ∨ (y : ZMod (a i)) = v i) (Finset.Ico 0 (∏ i, (a i)))) = Finset.image (fun b : Fin m → Bool => fun i => if b i then v i else u i) (Finset.univ : Finset (Fin m → Bool)) := by
    ext b
    simp only [Finset.mem_image, Finset.mem_filter, Finset.mem_Ico, Finset.mem_univ, true_and]
    constructor <;> intro h
    · rcases h with ⟨ y, ⟨ ⟨ hy₀, hy₁ ⟩, hy₂ ⟩, rfl ⟩ ; use fun i => ( y : ZMod ( a i ) ) = v i; ext i; specialize hy₂ i; aesop
    · -- By the Chinese Remainder Theorem, there exists an integer $y$ such that
      -- $y \equiv b_i \pmod{a_i}$ for all $i$.
      obtain ⟨y, hy⟩ : ∃ y : ℤ, ∀ i, (y : ZMod (a i)) = b i := by
        have h_crt : ∀ i, ∃ y : ℤ, (y : ZMod (a i)) = b i ∧ ∀ j ≠ i, (y : ZMod (a j)) = 0 := by
          intro i
          obtain ⟨y, hy⟩ : ∃ y : ℤ, y ≡ (b i).val [ZMOD a i] ∧ ∀ j ≠ i, y ≡ 0 [ZMOD a j] := by
            -- By the Chinese Remainder Theorem, there exists an integer $y$ such that
            -- $y \equiv b_i \pmod{a_i}$ and $y \equiv 0 \pmod{a_j}$ for all $j \neq i$.
            obtain ⟨y, hy⟩ : ∃ y : ℤ, y ≡ 1 [ZMOD a i] ∧ y ≡ 0 [ZMOD (∏ j ∈ Finset.univ.erase i, a j)] := by
              have := Nat.chineseRemainder ( show Nat.Coprime ( a i ) ( ∏ j ∈ Finset.univ.erase i, a j ) from ?_ )
              · obtain ⟨ y, hy₁, hy₂ ⟩ := this 1 0; use y; simp_all +decide [ ← Int.natCast_modEq_iff ]
              · exact Nat.Coprime.prod_right fun j hj => hcop <| by aesop
            use y * (b i).val
            exact ⟨ by simpa using hy.1.mul_right _, fun j hj => Int.modEq_zero_iff_dvd.mpr <| dvd_mul_of_dvd_left ( Int.dvd_of_emod_eq_zero <| hy.2.of_dvd <| mod_cast Finset.dvd_prod_of_mem _ <| by aesop ) _ ⟩
          use y
          simp_all +decide only [ne_eq, ← ZMod.intCast_eq_intCast_iff, Int.cast_natCast,
            Int.cast_zero, not_false_eq_true, implies_true, and_true]
          convert ZMod.natCast_zmod_val ( b i )
          exact ⟨ by intro H; have := NeZero.ne ( ∏ i, a i ) ; simp_all +decide [ Finset.prod_eq_zero ( Finset.mem_univ i ) ] ⟩
        choose y hy₁ hy₂ using h_crt
        use ∑ i, y i; intro i
        simp +decide only [Int.cast_sum]
        rw [ Finset.sum_eq_single i ] <;> aesop
      refine ⟨ y % ∏ i, ( a i : ℤ ), ?_, ?_ ⟩ <;> simp_all +decide only [ne_eq, funext_iff]
      · refine ⟨ ⟨ Int.emod_nonneg _ <| mod_cast NeZero.ne _, Int.emod_lt_of_pos _ <| mod_cast Finset.prod_pos fun i _ => Nat.pos_of_ne_zero <| by intro k; have := NeZero.ne ( ∏ i, a i ) ; simp_all +decide [ Finset.prod_eq_zero ( Finset.mem_univ i ) ] ⟩, ?_ ⟩
        intro i; specialize hy i; simp_all +decide [ Finset.prod_eq_prod_sdiff_singleton_mul ( Finset.mem_univ i ) ]
        simp_all +decide [Int.emod_def]
        grind +ring
      · intro i; specialize hy i; simp_all +decide [Finset.prod_eq_prod_sdiff_singleton_mul
            (Finset.mem_univ i)]
        simp_all +decide [ ← hy, ZMod.intCast_eq_intCast_iff' ]
  convert congr_arg Finset.card h_bij using 1
  · rw [ Finset.card_image_of_injOn ]
    intro x hx y hy; simp_all +decide only [ne_eq, Finset.coe_filter, Finset.mem_Ico,
      Set.mem_setOf_eq, funext_iff]
    intro h; exact (by
    -- Since $x \equiv y \pmod{a_i}$ for all $i$, we have $x \equiv y \pmod{\prod_{i} a_i}$.
    have h_cong : x ≡ y [ZMOD ∏ i, a i] := by
      simp_all +decide only [implies_true, and_true, Int.modEq_iff_dvd]
      convert Finset.prod_dvd_of_coprime _ _ <;> simp_all +decide only [Finset.coe_univ, Finset.mem_univ, ← ZMod.intCast_zmod_eq_zero_iff_dvd, Int.cast_sub, sub_self, imp_self, implies_true]
      exact fun i _ j _ hij => Int.isCoprime_iff_gcd_eq_one.mpr ( hcop hij )
    exact Int.modEq_iff_dvd.mp h_cong.symm |> fun ⟨ k, hk ⟩ => by nlinarith [ show k = 0 by nlinarith ] ;)
  · rw [ Finset.card_image_of_injective ] <;> norm_num [ Function.Injective ]
    intro b₁ b₂ h; ext i
    replace h := congr_fun h i
    by_cases hi : b₁ i = true <;> by_cases hj : b₂ i = true <;> simp_all +decide only [ne_eq,
      ↓reduceIte, Bool.false_eq_true, Bool.not_eq_true, Bool.true_eq_false]
    exact hne i h.symm

lemma krafft_residues_distinct (P : ℕ) (hP : P.Prime) (h5 : 5 ≤ P) :
    (((P + 1) / 6 : ℕ) : ZMod P) + 1 ≠ -((((P + 1) / 6 : ℕ) : ZMod P)) + 1 := by
  haveI := Fact.mk hP; norm_num
  rw [ eq_neg_iff_add_eq_zero ] ; norm_cast
  rw [ ZMod.natCast_eq_zero_iff ]
  exact Nat.not_dvd_of_pos_of_lt ( by omega ) ( by omega )

/-- The simultaneous sign choices give exactly `2 ^ w n` roots in one complete CRT period. -/
lemma card_all_crt_roots (n : ℕ) :
    ((Finset.Ico 0 (q n : ℤ)).filter (fun y =>
      ∀ i : Fin (w n), y ≡ (krafftResidue n i : ℤ) + 1 [ZMOD (p n i : ℤ)] ∨
        y ≡ -(krafftResidue n i : ℤ) + 1 [ZMOD (p n i : ℤ)])).card = 2 ^ w n := by
  have hcop : Pairwise (Nat.Coprime on fun i : Fin (w n) => p n i) := by
    intro i j hij
    have hpne : p n i ≠ p n j := by
      intro hp
      have hnodup : (primesList n).Nodup := Finset.sort_nodup _ _
      have hcast := List.nodup_iff_injective_get.mp hnodup hp
      aesop
    exact (Nat.coprime_primes (p_prime n i) (p_prime n j)).2 hpne
  have hprod : (∏ i : Fin (w n), p n i) = q n := by
    exact_mod_cast prod_p_eq_q n
  rw [← hprod]
  letI : NeZero (∏ i : Fin (w n), p n i) :=
    ⟨Finset.prod_ne_zero_iff.mpr (fun i _ => p_ne_zero n i)⟩
  have hcastprod : ((∏ i : Fin (w n), p n i : ℕ) : ℤ) =
      ∏ i : Fin (w n), (p n i : ℤ) := by push_cast; rfl
  rw [hcastprod]
  simpa [← ZMod.intCast_eq_intCast_iff] using
    (crt_two_choices_Ico_card (fun i : Fin (w n) => p n i) hcop
      (fun i => (krafftResidue n i : ZMod (p n i)) + 1)
      (fun i => -(krafftResidue n i : ZMod (p n i)) + 1)
      (fun i => by
        unfold krafftResidue
        exact krafft_residues_distinct (p n i) (p_prime n i) (p_ge_5 n i)))

/-- The sum of one local interpolant over all simultaneous CRT sign choices is the
half-sized fiber cardinality times its two residue values. -/
lemma sum_local_over_all_crt_roots (n : ℕ) (i : Fin (w n)) :
    let S := (Finset.Ico 0 (q n : ℤ)).filter (fun y =>
      ∀ j : Fin (w n), y ≡ (krafftResidue n j : ℤ) + 1 [ZMOD (p n j : ℤ)] ∨
        y ≡ -(krafftResidue n j : ℤ) + 1 [ZMOD (p n j : ℤ)])
    let E := fun y : ℤ => ∑ k ∈ Finset.range ((p n i + 1) / 2),
      g_coef n i k * Real.cos (2 * Real.pi * k * ((y : ℝ) + 0.25) / (p n i : ℝ))
    ∑ y ∈ S, E y = (2 ^ (w n - 1) : ℝ) *
      (E ((krafftResidue n i : ℤ) + 1) + E (-(krafftResidue n i : ℤ) + 1)) := by
  dsimp only
  letI : NeZero (p n i) := ⟨p_ne_zero n i⟩
  have hcop : Pairwise (fun j k : Fin (w n) => Nat.Coprime (p n j) (p n k)) := by
    intro j k hjk
    have hpne : p n j ≠ p n k := by
      intro hp
      have hnodup : (primesList n).Nodup := Finset.sort_nodup _ _
      have hcast := List.nodup_iff_injective_get.mp hnodup hp
      aesop
    exact (Nat.coprime_primes (p_prime n j) (p_prime n k)).2 hpne
  have hprod : (∏ j : Fin (w n), p n j) = q n := by
    exact_mod_cast prod_p_eq_q n
  letI : NeZero (∏ j : Fin (w n), p n j) :=
    ⟨Finset.prod_ne_zero_iff.mpr (fun j _ => p_ne_zero n j)⟩
  let E := fun y : ℤ => ∑ k ∈ Finset.range ((p n i + 1) / 2),
    g_coef n i k * Real.cos (2 * Real.pi * k * ((y : ℝ) + 0.25) / (p n i : ℝ))
  let F := fun z : ZMod (p n i) => E (z.val : ℤ)
  have H := crt_two_choices_coordinate_sum (fun j : Fin (w n) => p n j) hcop
    (fun j => (krafftResidue n j : ZMod (p n j)) + 1)
    (fun j => -(krafftResidue n j : ZMod (p n j)) + 1)
    (fun j => by
      unfold krafftResidue
      exact krafft_residues_distinct (p n j) (p_prime n j) (p_ge_5 n j)) i F
  have hcastprod : (∏ j : Fin (w n), (p n j : ℤ)) = (q n : ℤ) := by
    rw [← hprod]
    push_cast
    rfl
  rw [hcastprod] at H
  have hsum : ∑ y ∈ (Finset.Ico 0 (q n : ℤ)).filter (fun y =>
      ∀ j : Fin (w n), y ≡ (krafftResidue n j : ℤ) + 1 [ZMOD (p n j : ℤ)] ∨
        y ≡ -(krafftResidue n j : ℤ) + 1 [ZMOD (p n j : ℤ)]), E y =
      ∑ y ∈ (Finset.Ico 0 (q n : ℤ)).filter (fun y =>
      ∀ j : Fin (w n), y ≡ (krafftResidue n j : ℤ) + 1 [ZMOD (p n j : ℤ)] ∨
        y ≡ -(krafftResidue n j : ℤ) + 1 [ZMOD (p n j : ℤ)]), F (y : ZMod (p n i)) := by
    refine Finset.sum_congr rfl fun y hy => ?_
    apply local_eval_eq_of_modEq
    rw [← ZMod.intCast_eq_intCast_iff]
    simp
  rw [hsum]
  have hfilters :
      (Finset.Ico 0 (q n : ℤ)).filter (fun y =>
        ∀ j : Fin (w n), y ≡ (krafftResidue n j : ℤ) + 1 [ZMOD (p n j : ℤ)] ∨
          y ≡ -(krafftResidue n j : ℤ) + 1 [ZMOD (p n j : ℤ)]) =
      (Finset.Ico 0 (q n : ℤ)).filter (fun y =>
        ∀ j : Fin (w n), (y : ZMod (p n j)) = (krafftResidue n j : ZMod (p n j)) + 1 ∨
          (y : ZMod (p n j)) = -(krafftResidue n j : ZMod (p n j)) + 1) := by
    ext y
    simp only [Finset.mem_filter, Finset.mem_Ico]
    simp [← ZMod.intCast_eq_intCast_iff]
  rw [hfilters]
  rw [H]
  congr 2
  · apply local_eval_eq_of_modEq
    rw [← ZMod.intCast_eq_intCast_iff]
    simp
  · apply local_eval_eq_of_modEq
    rw [← ZMod.intCast_eq_intCast_iff]
    simp

/-- Each coordinate contributes at most `-0.04` times the full root-space cardinality. -/
lemma sum_local_over_all_crt_roots_le (n : ℕ) (hn : 4 ≤ n) (i : Fin (w n)) :
    let S := (Finset.Ico 0 (q n : ℤ)).filter (fun y =>
      ∀ j : Fin (w n), y ≡ (krafftResidue n j : ℤ) + 1 [ZMOD (p n j : ℤ)] ∨
        y ≡ -(krafftResidue n j : ℤ) + 1 [ZMOD (p n j : ℤ)])
    let E := fun y : ℤ => ∑ k ∈ Finset.range ((p n i + 1) / 2),
      g_coef n i k * Real.cos (2 * Real.pi * k * ((y : ℝ) + 0.25) / (p n i : ℝ))
    ∑ y ∈ S, E y ≤ -0.04 * (2 ^ w n : ℝ) := by
  dsimp only
  rw [sum_local_over_all_crt_roots n i]
  have hmean := g_i_expected_quarter n hn i
    ((krafftResidue n i : ℤ) + 1) (-(krafftResidue n i : ℤ) + 1)
    (Int.ModEq.refl _) (Int.ModEq.refl _)
  have hw : 0 < w n := by
    rw [w]
    refine Finset.card_pos.mpr ⟨5, ?_⟩
    simp only [primeWindow, Finset.mem_filter, Finset.mem_range]
    constructor <;> norm_num
    omega
  have hpow : (2 ^ w n : ℝ) = 2 * (2 ^ (w n - 1) : ℝ) := by
    have hw' : w n = (w n - 1) + 1 := by omega
    conv_lhs => rw [hw']
    rw [pow_succ]
    ring
  nlinarith [show (0 : ℝ) ≤ (2 ^ (w n - 1) : ℝ) by positivity]

/--
By the Chinese Remainder Theorem independence, the sum of the continuous penalty function evaluated
at `y + 0.25` over all `2^{w(n)}` CRT roots factors exactly into the product of the expected values.
Consequently, the total sum is bounded by `-0.04 * w(n) * 2^{w(n)}`.
-/
lemma sum_c_cont_0_all_roots (n : ℕ) (hn : 4 ≤ n) :
    let S := (Finset.Ico 0 (q n : ℤ)).filter (fun y =>
               ∀ i : Fin (w n), y ≡ (krafftResidue n i : ℤ) + 1 [ZMOD (p n i : ℤ)] ∨
                                y ≡ -(krafftResidue n i : ℤ) + 1 [ZMOD (p n i : ℤ)])
    ∑ y ∈ S, c_cont₀ n ⟨(((y : ℝ) + 0.25) / (q n : ℝ)) - ⌊(((y : ℝ) + 0.25) / (q n : ℝ))⌋, ⟨Int.fract_nonneg _, (Int.fract_lt_one _).le⟩⟩
    ≤ -0.04 * (w n : ℝ) * (2 ^ w n : ℝ) := by
  dsimp only
  let S := (Finset.Ico 0 (q n : ℤ)).filter (fun y =>
    ∀ i : Fin (w n), y ≡ (krafftResidue n i : ℤ) + 1 [ZMOD (p n i : ℤ)] ∨
      y ≡ -(krafftResidue n i : ℤ) + 1 [ZMOD (p n i : ℤ)])
  have hrewrite :
      (∑ y ∈ S, c_cont₀ n
        ⟨(((y : ℝ) + 0.25) / (q n : ℝ)) -
          ⌊(((y : ℝ) + 0.25) / (q n : ℝ))⌋,
          ⟨Int.fract_nonneg _, (Int.fract_lt_one _).le⟩⟩) =
      ∑ i : Fin (w n), ∑ y ∈ S,
        ∑ k ∈ Finset.range ((p n i + 1) / 2),
          g_coef n i k * Real.cos
            (2 * Real.pi * k * ((y : ℝ) + 0.25) / (p n i : ℝ)) := by
    simp only [c_cont₀]
    rw [Finset.sum_comm]
    apply Finset.sum_congr rfl
    intro i hi
    apply Finset.sum_congr rfl
    intro y hy
    apply Finset.sum_congr rfl
    intro k hk
    congr 1
    exact rootPt_local_cos n i y k
  rw [hrewrite]
  calc
    (∑ i : Fin (w n), ∑ y ∈ S,
        ∑ k ∈ Finset.range ((p n i + 1) / 2),
          g_coef n i k * Real.cos
            (2 * Real.pi * k * ((y : ℝ) + 0.25) / (p n i : ℝ)))
        ≤ ∑ _i : Fin (w n), (-0.04 * (2 ^ w n : ℝ)) := by
          apply Finset.sum_le_sum
          intro i hi
          simpa [S] using sum_local_over_all_crt_roots_le n hn i
    _ = -0.04 * (w n : ℝ) * (2 ^ w n : ℝ) := by
      rw [Finset.sum_const, Finset.card_univ, Fintype.card_fin, nsmul_eq_mul]
      ring

lemma weighted_finset_pigeonhole
    (S A : Finset ℤ) (f : ℤ → ℝ) (W N : ℕ)
    (hAS : A ⊆ S) (hcardS : S.card = N)
    (hcardA : (A.card : ℝ) < 0.01 * N)
    (hN : 0 < N) (hW : 0 < W)
    (htrap : ∀ y ∈ A, -2 * (W : ℝ) ≤ f y)
    (hgold : ∀ y ∈ S \ A, -0.02 * (W : ℝ) < f y) :
    -0.04 * (W : ℝ) * N < ∑ y ∈ S, f y := by
  have h_sum_bound : (∑ y ∈ A, f y) + (∑ y ∈ S \ A, f y) > (∑ y ∈ A, -2 * W : ℝ) + (∑ y ∈ S \ A, -0.02 * W : ℝ) := by
    refine add_lt_add_of_le_of_lt ( Finset.sum_le_sum htrap ) ( Finset.sum_lt_sum ?_ ?_ )
    · exact fun x hx => le_of_lt ( hgold x hx )
    · by_cases hA : A = S
      · grind
      · exact Exists.elim ( Finset.exists_of_ssubset ( lt_of_le_of_ne hAS hA ) ) fun x hx =>
          ⟨ x, by aesop ⟩
  simp_all +decide [ Finset.card_sdiff ]
  rw [ Finset.inter_eq_left.mpr hAS ] at h_sum_bound
  rw [ Nat.cast_sub ( by linarith [ Finset.card_le_card hAS ] ) ] at h_sum_bound
  norm_num at * ; nlinarith [ ( by norm_cast : ( 0 :ℝ ) < W ), ( by norm_cast : ( 0 :ℝ ) < N ) ]

lemma int_trap_filter_card_le (S : Finset ℤ) (Q B : ℤ) (hB : 0 ≤ B)
    (hS : ∀ y ∈ S, y ∈ Finset.Ico 0 Q) :
    (S.filter (fun y => ¬ (B < y ∧ y < Q - B))).card ≤ (2 * B + 1).toNat := by
  let A := S.filter (fun y => ¬ (B < y ∧ y < Q - B))
  have hsub : A ⊆ Finset.Icc 0 B ∪ Finset.Ico (Q - B) Q := by
    intro y hy
    have hy' : y ∈ S.filter (fun y => ¬ (B < y ∧ y < Q - B)) := by simpa [A] using hy
    have hyS := (Finset.mem_filter.mp hy').1
    have hyA := (Finset.mem_filter.mp hy').2
    have hyI := Finset.mem_Ico.mp (hS y hyS)
    simp only [Finset.mem_union, Finset.mem_Icc, Finset.mem_Ico]
    omega
  calc
    A.card ≤ (Finset.Icc 0 B ∪ Finset.Ico (Q - B) Q).card := Finset.card_le_card hsub
    _ ≤ (Finset.Icc 0 B).card + (Finset.Ico (Q - B) Q).card := Finset.card_union_le _ _
    _ = (2 * B + 1).toNat := by
      rw [Int.card_Icc, Int.card_Ico]
      omega

/--
Because the $E_{max}$ trap region has polynomial capacity while the total CRT roots scale
exponentially, there exists at least one root $y_{CRT}$ in the golden region (outside the trap
region) where the penalty drops below `-0.02 * w(n)`.
-/
lemma c_cont_0_valley_quarter (n : ℕ) (hn : 19 ≤ n) :
    ∃ y_CRT : ℤ, (6 * (n : ℤ) ^ 2 + 10 * (n : ℤ) + 3) < y_CRT ∧ y_CRT < (q n : ℤ) - (6 * (n : ℤ) ^ 2 + 10 * (n : ℤ) + 3) ∧
    c_cont₀ n ⟨(((y_CRT : ℝ) + 0.25) / (q n : ℝ)) - ⌊(((y_CRT : ℝ) + 0.25) / (q n : ℝ))⌋,
      ⟨Int.fract_nonneg _, (Int.fract_lt_one _).le⟩⟩ ≤ -0.02 * (w n : ℝ) := by
  let S := (Finset.Ico 0 (q n : ℤ)).filter (fun y =>
    ∀ i : Fin (w n), y ≡ (krafftResidue n i : ℤ) + 1 [ZMOD (p n i : ℤ)] ∨
      y ≡ -(krafftResidue n i : ℤ) + 1 [ZMOD (p n i : ℤ)])
  let B : ℤ := 6 * (n : ℤ) ^ 2 + 10 * (n : ℤ) + 3
  let f : ℤ → ℝ := fun y => c_cont₀ n
    ⟨(((y : ℝ) + 0.25) / (q n : ℝ)) - ⌊(((y : ℝ) + 0.25) / (q n : ℝ))⌋,
      ⟨Int.fract_nonneg _, (Int.fract_lt_one _).le⟩⟩
  let A := S.filter (fun y => ¬ (B < y ∧ y < (q n : ℤ) - B))
  by_contra h
  push Not at h
  have hAS : A ⊆ S := Finset.filter_subset _ _
  have hcardS : S.card = 2 ^ w n := by simpa [S] using card_all_crt_roots n
  have hB : 0 ≤ B := by dsimp [B]; positivity
  have hSA : ∀ y ∈ S, y ∈ Finset.Ico 0 (q n : ℤ) := by
    intro y hy
    exact (Finset.mem_filter.mp hy).1
  have hcardA_nat : A.card ≤ (2 * B + 1).toNat := by
    simpa [A] using int_trap_filter_card_le S (q n : ℤ) B hB hSA
  have hcardA : (A.card : ℝ) < 0.01 * (2 ^ w n : ℝ) := by
    have hcap := trap_capacity_lt_exponential n hn
    have hcast : (A.card : ℝ) ≤ 2 * (6 * (n : ℝ) ^ 2 + 10 * (n : ℝ) + 3) + 1 := by
      rw [show (2 * (6 * (n : ℝ) ^ 2 + 10 * (n : ℝ) + 3) + 1) =
        (((2 * B + 1).toNat : ℕ) : ℝ) by
          norm_cast]
      exact_mod_cast hcardA_nat
    exact hcast.trans_lt hcap
  have hw : 0 < w n := by
    rw [w]
    refine Finset.card_pos.mpr ⟨5, ?_⟩
    simp only [primeWindow, Finset.mem_filter, Finset.mem_range]
    constructor
    · omega
    · norm_num
  have hN : 0 < 2 ^ w n := pow_pos (by omega) _
  have htrap : ∀ y ∈ A, -2 * (w n : ℝ) ≤ f y := by
    intro y hy
    exact c_cont₀_ge n _
  have hgold : ∀ y ∈ S \ A, -0.02 * (w n : ℝ) < f y := by
    intro y hy
    have hyS : y ∈ S := (Finset.mem_sdiff.mp hy).1
    have hyA : y ∉ A := (Finset.mem_sdiff.mp hy).2
    have hregion : B < y ∧ y < (q n : ℤ) - B := by
      by_contra hr
      exact hyA (Finset.mem_filter.mpr ⟨hyS, hr⟩)
    simpa [B, f] using h y hregion.1 hregion.2
  have hcardA' : (A.card : ℝ) < 0.01 * ((2 ^ w n : ℕ) : ℝ) := by
    norm_num [Nat.cast_pow] at hcardA ⊢
    exact hcardA
  have hsum := weighted_finset_pigeonhole S A f (w n) (2 ^ w n)
    hAS hcardS hcardA' hN hw htrap hgold
  have htotal := sum_c_cont_0_all_roots n (by omega)
  dsimp only at htotal
  simp only [S, f] at hsum
  have hsum' : -0.04 * (w n : ℝ) * (2 ^ w n : ℝ) <
      ∑ y ∈ S, f y := by
    convert hsum using 1
    norm_num
  simp only [S, f] at hsum'
  exact (not_lt_of_ge htotal) hsum'

/--
For any CRT valley in the golden region, the reproducing window `Psi_cont` is strictly positive
at the quarter-integer. The reproducing degree is a multiple of `4 * q n`, so every shifted
Dirichlet kernel in the window is exactly one at this offset.
-/
lemma Psi_cont_positive_quarter (n : ℕ) (hn : 19 ≤ n) (y_CRT : ℤ)
    (h_gt : (6 * (n : ℤ) ^ 2 + 10 * (n : ℤ) + 3) < y_CRT) (h_lt : y_CRT < (q n : ℤ) - (6 * (n : ℤ) ^ 2 + 10 * (n : ℤ) + 3)) :
    0 < Psi_cont n ⟨(((y_CRT : ℝ) + 0.25) / (q n : ℝ)) - ⌊(((y_CRT : ℝ) + 0.25) / (q n : ℝ))⌋,
      ⟨Int.fract_nonneg _, (Int.fract_lt_one _).le⟩⟩ := by
  have hq : 0 < q n := NeZero.pos _
  have hqR : (0 : ℝ) < q n := by exact_mod_cast hq
  have hy0Z : (0 : ℤ) < y_CRT := by
    have hn0 : (0 : ℤ) ≤ n := by positivity
    nlinarith [h_gt]
  have hy0 : (0 : ℝ) < (y_CRT : ℝ) + 0.25 := by
    have : (0 : ℝ) < y_CRT := by exact_mod_cast hy0Z
    linarith
  have hyqZ : y_CRT + 1 ≤ (q n : ℤ) := by
    have hn0 : (0 : ℤ) ≤ n := by positivity
    nlinarith [h_lt]
  have hyq : (y_CRT : ℝ) + 0.25 < q n := by
    have : (y_CRT : ℝ) + 1 ≤ q n := by exact_mod_cast hyqZ
    linarith
  have hfloor : ⌊((y_CRT : ℝ) + 0.25) / (q n : ℝ)⌋ = 0 := by
    rw [Int.floor_eq_zero_iff]
    constructor
    · positivity
    · exact (div_lt_one hqR).2 hyq
  let x : X₀ := ⟨((y_CRT : ℝ) + 0.25) / (q n : ℝ),
    ⟨(div_nonneg hy0.le hqR.le), (div_lt_one hqR).2 hyq |>.le⟩⟩
  have hx : (⟨(((y_CRT : ℝ) + 0.25) / (q n : ℝ)) -
      ⌊(((y_CRT : ℝ) + 0.25) / (q n : ℝ))⌋,
      ⟨Int.fract_nonneg _, (Int.fract_lt_one _).le⟩⟩ : X₀) = x := by
    apply Subtype.ext
    simp [x, hfloor]
  rw [hx]
  unfold Psi_cont reproWindow
  change 0 < (1 / (q n : ℝ)) * ∑ y ∈ Finset.range (q n),
    Psi n (y : ZMod (q n)) * dirichletKernel (kernelDegree n)
      (((y_CRT : ℝ) + 0.25) / (q n : ℝ) - (y : ℝ) / (q n : ℝ))
  have hk : kernelDegree n = q n * (4 * (2 * w n)) := by
    unfold kernelDegree
    ring
  rw [hk]
  have hkern : ∀ y ∈ Finset.range (q n),
      dirichletKernel (q n * (4 * (2 * w n)))
        (((y_CRT : ℝ) + 0.25) / (q n : ℝ) - (y : ℝ) / (q n : ℝ)) = 1 := by
    intro y _
    convert dirichletKernel_quarter_grid_eq_one (q n) (2 * w n) hq (y_CRT - y) using 1
    push_cast ; ring_nf
  rw [Finset.sum_congr rfl (fun y hy => by rw [hkern y hy, mul_one])]
  have hsum : 0 < ∑ y ∈ Finset.range (q n), Psi n (y : ZMod (q n)) := by
    let y₀ := 6 * n ^ 2 + 10 * n + 3
    have hy₀q : y₀ < q n := q_bound n (by omega)
    have hy₀mem : y₀ ∈ Finset.range (q n) := Finset.mem_range.mpr hy₀q
    have hy₀val : (y₀ : ZMod (q n)).val = y₀ := by
      rw [ZMod.val_natCast, Nat.mod_eq_of_lt hy₀q]
    have hterm : Psi n (y₀ : ZMod (q n)) = 1 := by
      unfold Psi
      rw [if_pos]
      rw [hy₀val]
      exact Finset.mem_Icc.mpr ⟨by omega, le_rfl⟩
    refine Finset.sum_pos' ?_ ⟨y₀, hy₀mem, ?_⟩
    · intro y _
      unfold Psi
      split_ifs <;> positivity
    · rw [hterm]
      norm_num
  exact mul_pos (one_div_pos.mpr hqR) hsum

/-- Every nonempty open subset of the unit interval `X₀` has positive volume. -/
lemma volume_pos_of_isOpen_nonempty (s : Set X₀) (hs : IsOpen s) (hne : s.Nonempty) :
    0 < (volume : Measure X₀) s := by
  rw [show (volume : Measure X₀) = (volume : Measure ℝ).comap Subtype.val from rfl]
  have hemb : MeasurableEmbedding ((↑) : X₀ → ℝ) :=
    MeasurableEmbedding.subtype_coe measurableSet_Icc
  rw [hemb.comap_apply]
  obtain ⟨x, hx⟩ := hne
  obtain ⟨V, hV_open, hVs⟩ := (isOpen_induced_iff.mp hs)
  have hxV : (x : ℝ) ∈ V := by
    have : x ∈ Subtype.val ⁻¹' V := by rw [hVs]; exact hx
    exact this
  obtain ⟨ε, hε, hball⟩ := Metric.isOpen_iff.mp hV_open (x : ℝ) hxV
  set a := max 0 ((x : ℝ) - ε / 2) with ha
  set b := min 1 ((x : ℝ) + ε / 2) with hb
  have hx01 : (x : ℝ) ∈ Set.Icc (0 : ℝ) 1 := x.2
  have hab : a < b := by
    have hax : a ≤ (x : ℝ) := max_le hx01.1 (by linarith)
    have hxb : (x : ℝ) ≤ b := le_min hx01.2 (by linarith)
    rcases lt_or_eq_of_le hx01.2 with h1 | h1
    · have : (x : ℝ) < b := lt_min h1 (by linarith)
      linarith
    · have ha1 : a < 1 := max_lt (by norm_num) (by rw [← h1]; linarith)
      have hb1 : b = 1 := by rw [hb, ← h1]; exact min_eq_left (by linarith)
      rw [hb1]; linarith [ha1, h1]
  have hsub : Set.Icc a b ⊆ V := by
    intro y hy
    apply hball
    have h1 : (x : ℝ) - ε / 2 ≤ y := le_trans (le_max_right _ _) hy.1
    have h2 : y ≤ (x : ℝ) + ε / 2 := le_trans hy.2 (min_le_right _ _)
    rw [Metric.mem_ball, Real.dist_eq, abs_lt]
    constructor <;> linarith
  have hsub01 : Set.Icc a b ⊆ Set.Icc (0 : ℝ) 1 := fun y hy =>
    ⟨le_trans (le_max_left _ _) hy.1, le_trans hy.2 (min_le_left _ _)⟩
  have hpos : (0 : ENNReal) < volume (Set.Icc a b) := by
    rw [Real.volume_Icc, ENNReal.ofReal_pos]; linarith
  calc (0 : ENNReal) < volume (Set.Icc a b) := hpos
    _ ≤ volume (Subtype.val '' s) := by
        apply measure_mono
        intro y hy
        exact ⟨⟨y, hsub01 hy⟩, by rw [← hVs]; exact hsub hy, rfl⟩

/--
The continuous penalty `c_cont₀` drops below 1 and `Psi_cont` has positive integral on a set,
satisfying the `h_dip` hypothesis unconditionally for $n \ge 19$.

The witnessing set is the (open) region where `Psi_cont` is positive and `c_cont₀ < 1`; it contains
the Gibbs valley point, hence is nonempty (positive volume), and `Psi_cont` is positive throughout,
so its integral is positive.
-/
theorem h_dip_unconditional (n : ℕ) (hn : 19 ≤ n) :
    ∃ s : Set X₀, MeasurableSet s ∧
    0 < ∫ t in s, Psi_cont n t ∂(volume : Measure X₀) ∧
    ∀ t ∈ s, c_cont₀ n t < 1 := by
  obtain ⟨y_CRT, h_gt, h_lt, hc⟩ := c_cont_0_valley_quarter n hn
  set x0 : X₀ := ⟨(((y_CRT : ℝ) + 0.25) / (q n : ℝ)) - ⌊(((y_CRT : ℝ) + 0.25) / (q n : ℝ))⌋,
      ⟨Int.fract_nonneg _, (Int.fract_lt_one _).le⟩⟩ with hx0
  have hPsi0 : 0 < Psi_cont n x0 := Psi_cont_positive_quarter n hn y_CRT h_gt h_lt
  have hc0 : c_cont₀ n x0 < 1 := by
    have hw : (0 : ℝ) ≤ (w n : ℝ) := Nat.cast_nonneg _
    nlinarith [hc, hw]
  have hcont_c : Continuous (c_cont₀ n) := by unfold c_cont₀; fun_prop
  have hcont_P : Continuous (Psi_cont n) := Psi_cont_continuous n
  set s : Set X₀ := {t | 0 < Psi_cont n t ∧ c_cont₀ n t < 1} with hs_def
  have hs_open : IsOpen s :=
    (isOpen_lt continuous_const hcont_P).inter (isOpen_lt hcont_c continuous_const)
  have hx0s : x0 ∈ s := ⟨hPsi0, hc0⟩
  refine ⟨s, hs_open.measurableSet, ?_, fun t ht => ht.2⟩
  have hInt : IntegrableOn (Psi_cont n) s (volume : Measure X₀) :=
    (hcont_P.continuousOn.integrableOn_compact isCompact_univ).mono_set (Set.subset_univ s)
  have hnn : 0 ≤ᵐ[(volume : Measure X₀).restrict s] (Psi_cont n) := by
    filter_upwards [ae_restrict_mem hs_open.measurableSet] with t ht using (ht.1).le
  rw [setIntegral_pos_iff_support_of_nonneg_ae hnn hInt]
  have hsupp : Function.support (Psi_cont n) ∩ s = s := by
    ext t
    simp only [Set.mem_inter_iff, Function.mem_support, hs_def, Set.mem_setOf_eq]
    exact ⟨fun h => h.2, fun h => ⟨ne_of_gt h.1, h⟩⟩
  rw [hsupp]
  exact volume_pos_of_isOpen_nonempty s hs_open ⟨x0, hx0s⟩

end KrafftSieve
