/-
Copyright (c) 2026 Fernando Portela. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Fernando Portela, Gemini 3.5 Flash (Google DeepMind)
-/

/-
Portions of this file were generated by Aristotle (https://aristotle.harmonic.fun).

Lean version: leanprover/lean4:v4.28.0
Mathlib version: 8f9d9cff6bd728b17a24e163c9402775d9e6a365

To cite Aristotle, tag @Aristotle-Harmonic on GitHub PRs/issues, and add as co-author to commits:
Co-authored-by: Aristotle (Harmonic) <aristotle-harmonic@harmonic.fun>
-/

import KrafftSieve.SelbergWeights
import Mathlib.Analysis.InnerProductSpace.Projection.Submodule
import Mathlib.Analysis.InnerProductSpace.PiL2


/-!
# Optimal Weights

This module constructs the truly multidimensional optimal weights $\lambda$ for the Krafft Sieve
and explores the properties of the resulting polynomial $P(x)$ and weight $W_\lambda(x)$.
-/

namespace KrafftSieve

open scoped BigOperators
open scoped Real
open scoped Nat

open scoped Pointwise

noncomputable section

/--
Define the basis function for a subset of prime indices $S \subseteq \{1, \dots, w\}$.
The basis function is the product of the 3rd harmonic cosines for each prime in $S$.
$$ B_S(x) = \prod_{i \in S} \cos\left( \frac{6\pi x}{p_i} \right) $$
-/
noncomputable def basisCos (n : ℕ) (S : Finset (Fin (w n))) (x : ZMod (q n)) : ℝ :=
  ∏ i ∈ S, Real.cos (2 * Real.pi * 3 * (x.val : ℝ) / (p n i : ℝ))

/--
Define the multidimensional polynomial $P(x)$ as a linear combination of
the basis functions $B_S(x)$ with coefficients $\lambda_S$.
$$ P(x) = \sum_{S \subseteq \{1, \dots, w\}} \lambda_S B_S(x) $$
-/
noncomputable def pMulti (n : ℕ) (lambda : Finset (Fin (w n)) → ℝ) (x : ZMod (q n)) : ℝ :=
  ∑ S ∈ Finset.univ.powerset, lambda S * basisCos n S x

/--
Define the truly multidimensional weight function $W_{\lambda}(x)$ as the square of the
polynomial $P(x)$ restricted to the interval $\mathcal{A}_n$.
$$ W_{\lambda}(x) = \begin{cases} (P(x))^2 & \text{if } x \in \mathcal{A}_n \\
0 & \text{otherwise} \end{cases} $$
-/
noncomputable def wTrulyMulti (n : ℕ) (lambda : Finset (Fin (w n)) → ℝ) (x : ZMod (q n)) : ℝ :=
  if x.val ∈ evalInterval n then (pMulti n lambda x) ^ 2 else 0

/--
Define the dual spatial kernel matrix $K_{x, y}$.
$K_{x, y} = \sum_{S \subseteq \{1, \dots, w\}} B_S(x) B_S(y)$
-/
noncomputable def spatialKernel (n : ℕ) (x y : ZMod (q n)) : ℝ :=
  ∑ S ∈ Finset.univ.powerset, basisCos n S x * basisCos n S y

/--
Theorem: The dual spatial kernel has a closed-form product representation.
$$ K_{x, y} = \prod_{p \in \mathcal{P}_n} ( 1 + \cos(6\pi x / p) \cos(6\pi y / p) ) $$
-/
theorem spatialKernel_eq_prod (n : ℕ) (x y : ZMod (q n)) :
    spatialKernel n x y = ∏ i : Fin (w n),
      (1 + Real.cos (6 * Real.pi * (x.val : ℝ) / (p n i : ℝ)) *
            Real.cos (6 * Real.pi * (y.val : ℝ) / (p n i : ℝ))) := by
  unfold spatialKernel
  have h_basis : ∀ S : Finset (Fin (w n)),
      basisCos n S x * basisCos n S y =
        ∏ i ∈ S, (Real.cos (6 * Real.pi * (x.val : ℝ) / (p n i : ℝ)) *
                  Real.cos (6 * Real.pi * (y.val : ℝ) / (p n i : ℝ))) := by
    intro S
    unfold basisCos
    have h_angle : ∀ (z : ZMod (q n)) (i : Fin (w n)),
        2 * Real.pi * 3 * (z.val : ℝ) / (p n i : ℝ) = 6 * Real.pi * (z.val : ℝ) / (p n i : ℝ) := by
      intro z i
      ring
    simp_rw [h_angle]
    rw [← Finset.prod_mul_distrib]
  simp_rw [h_basis]
  exact (@Finset.prod_one_add (Fin (w n)) ℝ _
    (fun i ↦ Real.cos (6 * Real.pi * (x.val : ℝ) / (p n i : ℝ)) *
              Real.cos (6 * Real.pi * (y.val : ℝ) / (p n i : ℝ)))
    Finset.univ).symm

/--
Define the matrix $M_1$ corresponding to the first moment $sum1$.
$M_1(S, T) = \sum_{x \in \text{range}(q_n)} B_S(x) B_T(x) \Psi(x)$
-/
noncomputable def matrix1 (n : ℕ) (S T : Finset (Fin (w n))) : ℝ :=
  ∑ x ∈ Finset.range (q n), basisCos n S (x : ZMod (q n)) * basisCos n T (x : ZMod (q n)) *
    Psi n (x : ZMod (q n))

/--
Define the matrix $M_2$ corresponding to the second moment $sum2$.
$M_2(S, T) = \sum_{x \in \text{range}(q_n)} c(x) B_S(x) B_T(x) \Psi(x)$
-/
noncomputable def matrix2 (n : ℕ) (S T : Finset (Fin (w n))) : ℝ :=
  ∑ x ∈ Finset.range (q n), c n (x : ZMod (q n)) * basisCos n S (x : ZMod (q n)) *
    basisCos n T (x : ZMod (q n)) * Psi n (x : ZMod (q n))

/--
Define the quadratic form $q1(\lambda) = \lambda^T M_1 \lambda$.
-/
noncomputable def q1 (n : ℕ) (lambda : Finset (Fin (w n)) → ℝ) : ℝ :=
  ∑ S ∈ Finset.univ.powerset, ∑ T ∈ Finset.univ.powerset, lambda S * matrix1 n S T * lambda T

/--
Define the quadratic form $q2(\lambda) = \lambda^T M_2 \lambda$.
-/
noncomputable def q2 (n : ℕ) (lambda : Finset (Fin (w n)) → ℝ) : ℝ :=
  ∑ S ∈ Finset.univ.powerset, ∑ T ∈ Finset.univ.powerset, lambda S * matrix2 n S T * lambda T

/--
Define the Rayleigh quotient $R(\lambda) = \frac{q2(\lambda)}{q1(\lambda)}$.
Defined to be $\infty$ if $q1(\lambda) = 0$ (though $q1$ is positive definite on
non-zero $\lambda$ if the basis is linearly independent on $evalInterval$).
-/
noncomputable def Ratio (n : ℕ) (lambda : Finset (Fin (w n)) → ℝ) : ℝ :=
  if q1 n lambda = 0 then 0 else (q2 n lambda) / (q1 n lambda)

/--
Helper: q1 equals the sum of squares of pMulti over range (q n).
-/
private lemma Q_1_sum_sq (n : ℕ) (lambda : Finset (Fin (w n)) → ℝ) :
    q1 n lambda = ∑ x ∈ Finset.range (q n),
      (pMulti n lambda (x : ZMod (q n))) ^ 2 * Psi n (x : ZMod (q n)) := by
  unfold q1 pMulti matrix1
  simp +decide only [Finset.mul_sum _ _ _, Finset.sum_mul _ _ _, mul_comm, mul_left_comm, sq]
  exact Eq.symm (by
    rw [Finset.sum_comm]
    exact Finset.sum_congr rfl fun _ _ =>
      Finset.sum_comm.trans (Finset.sum_congr rfl fun _ _ =>
        Finset.sum_congr rfl fun _ _ => by ring))

/--
The truly multidimensional weight function is non-negative everywhere.
-/
lemma W_truly_multi_nonneg (n : ℕ) (lambda : Finset (Fin (w n)) → ℝ) (x : ZMod (q n)) :
    wTrulyMulti n lambda x ≥ 0 := by
  by_cases hx : x.val ∈ evalInterval n <;>
    simp_all +decide only [wTrulyMulti, ↓reduceIte, ge_iff_le,
    le_refl]
  exact sq_nonneg _

/--
The truly multidimensional weight function is supported on $\mathcal{A}_n$.
-/
lemma W_truly_multi_support (n : ℕ) (lambda : Finset (Fin (w n)) → ℝ) (x : ZMod (q n))
    (hx : x.val ∉ evalInterval n) :
  wTrulyMulti n lambda x = 0 := by
    exact if_neg hx

/--
Lemma: The first moment $sum1$ of the truly multidimensional weight is equal to
the quadratic form $q1$.
-/
lemma S_1_eq_Q_1 (n : ℕ) (lambda : Finset (Fin (w n)) → ℝ) :
    sum1 n (wTrulyMulti n lambda) = q1 n lambda := by
  sorry

/--
Lemma: The second moment $sum2$ of the truly multidimensional weight is equal to
the quadratic form $q2$.
-/
lemma S_2_eq_Q_2 (n : ℕ) (lambda : Finset (Fin (w n)) → ℝ) :
    sum2 n (wTrulyMulti n lambda) = q2 n lambda := by
  sorry

/--
Lemma: The existence of coefficients $\lambda$ such that $q2(\lambda) < q1(\lambda)$
is sufficient for Krafft Sufficiency.
-/
lemma sufficiency_of_Q (n : ℕ) (lambda : Finset (Fin (w n)) → ℝ) (h : q2 n lambda < q1 n lambda) :
    KrafftSufficiency n := by
  sorry

/--
The spatial representation of the polynomial $P(x)$ as a function from $\mathbb{N}$ to $\mathbb{R}$.
-/
def spatialVector (n : ℕ) (lambda : Finset (Fin (w n)) → ℝ) (x : ℕ) : ℝ :=
  pMulti n lambda (x : ZMod (q n))

/--
Theorem: Primal quadratic form q1 is the spatial L2 norm of the spatial vector.
-/
lemma q1_eq_spatialVector_norm (n : ℕ) (lambda : Finset (Fin (w n)) → ℝ) :
    q1 n lambda = ∑ x ∈ Finset.range (q n),
      (spatialVector n lambda x)^2 * Psi n (x : ZMod (q n)) := by
  unfold spatialVector
  exact Q_1_sum_sq n lambda

/--
Helper: q2 equals the weighted sum of squares of pMulti over range (q n).
-/
lemma q2_sum_sq (n : ℕ) (lambda : Finset (Fin (w n)) → ℝ) :
    q2 n lambda =
      ∑ x ∈ Finset.range (q n),
        c n (x : ZMod (q n)) * (pMulti n lambda (x : ZMod (q n))) ^ 2 * Psi n (x : ZMod (q n)) := by
  unfold q2 pMulti matrix2
  simp +decide only [Finset.mul_sum _ _ _, Finset.sum_mul _ _ _, mul_comm, mul_left_comm, sq]
  exact Eq.symm (by
    rw [Finset.sum_comm]
    exact Finset.sum_congr rfl fun _ _ =>
      Finset.sum_comm.trans (Finset.sum_congr rfl fun _ _ =>
        Finset.sum_congr rfl fun _ _ => by ring))

/--
Theorem: Primal quadratic form q2 is the spatial weighted L2 norm of the spatial vector.
-/
lemma q2_eq_spatialVector_weighted_norm (n : ℕ) (lambda : Finset (Fin (w n)) → ℝ) :
    q2 n lambda =
      ∑ x ∈ Finset.range (q n),
        c n (x : ZMod (q n)) * (spatialVector n lambda x)^2 * Psi n (x : ZMod (q n)) := by
  unfold spatialVector
  exact q2_sum_sq n lambda

/--
The spatial Rayleigh quotient of a spatial vector.
-/
noncomputable def spatialRatio (n : ℕ) (v : ℕ → ℝ) : ℝ :=
  let q1_v := ∑ x ∈ Finset.range (q n), (v x)^2 * Psi n (x : ZMod (q n))
  let q2_v :=
    ∑ x ∈ Finset.range (q n), c n (x : ZMod (q n)) * (v x)^2 * Psi n (x : ZMod (q n))
  if q1_v = 0 then 0 else q2_v / q1_v

/--
Theorem: The primal Rayleigh quotient equals the spatial Rayleigh quotient.
-/
lemma Ratio_eq_spatialRatio (n : ℕ) (lambda : Finset (Fin (w n)) → ℝ) :
    Ratio n lambda = spatialRatio n (spatialVector n lambda) := by
  unfold Ratio spatialRatio
  rw [q1_eq_spatialVector_norm, q2_eq_spatialVector_weighted_norm]


/--
Define the set of attainable ratios.
-/
def attainableRatios (n : ℕ) : Set ℝ :=
  { r | ∃ lambda : Finset (Fin (w n)) → ℝ, q1 n lambda > 0 ∧ r = Ratio n lambda }

/--
Define $\mu_{min}(n)$ as the infimum of the attainable ratios.
-/
noncomputable def muMin (n : ℕ) : ℝ := sInf (attainableRatios n)

/--
Theorem: If the minimum attainable ratio $\mu_{min}(n)$ is strictly less than 1,
then the Krafft Sufficiency condition holds.
-/
theorem mu_min_lt_one_implies_sufficiency (n : ℕ) (h : muMin n < 1) :
    KrafftSufficiency n := by
  sorry

/--
Abbreviation for the index set of the coefficients, which is the power set of prime indices.
-/
abbrev Idx (n : ℕ) := Finset (Fin (w n))

/--
The kernel of the quadratic form $q1$.
-/
def kernelQ1 (n : ℕ) : Submodule ℝ (Idx n → ℝ) :=
  { carrier := { lambda | q1 n lambda = 0 },
    add_mem' := by
      intros a b ha hb
      have h_sum : q1 n (a + b) = q1 n a + q1 n b + 2 * (∑ S ∈ Finset.univ.powerset,
          ∑ T ∈ Finset.univ.powerset, a S * matrix1 n S T * b T) := by
        unfold q1
        change ∑ S ∈ _, ∑ T ∈ _, (a S + b S) * matrix1 n S T * (a T + b T) = _
        simp only [add_mul, mul_add, Finset.sum_add_distrib]
        have h_comm : ∑ x ∈ Finset.univ.powerset, ∑ x_1 ∈ Finset.univ.powerset,
            b x * matrix1 n x x_1 * a x_1 =
            ∑ S ∈ Finset.univ.powerset, ∑ T ∈ Finset.univ.powerset, a S * matrix1 n S T * b T := by
          rw [Finset.sum_comm]
          exact Finset.sum_congr rfl fun S _ => Finset.sum_congr rfl fun T _ => by
            unfold matrix1
            have h_inner : ∑ x ∈ Finset.range (q n), basisCos n S ↑x * basisCos n T ↑x * Psi n ↑x =
                ∑ x ∈ Finset.range (q n), basisCos n T ↑x * basisCos n S ↑x * Psi n ↑x := by
              exact Finset.sum_congr rfl fun _ _ => by ring
            rw [h_inner]
            ring
        linarith
      have h_sum2 : q1 n (a - b) = q1 n a + q1 n b - 2 * (∑ S ∈ Finset.univ.powerset,
          ∑ T ∈ Finset.univ.powerset, a S * matrix1 n S T * b T) := by
        unfold q1
        change ∑ S ∈ _, ∑ T ∈ _, (a S - b S) * matrix1 n S T * (a T - b T) = _
        simp only [sub_mul, mul_sub, Finset.sum_sub_distrib]
        have h_comm : ∑ x ∈ Finset.univ.powerset, ∑ x_1 ∈ Finset.univ.powerset,
            b x * matrix1 n x x_1 * a x_1 =
            ∑ S ∈ Finset.univ.powerset, ∑ T ∈ Finset.univ.powerset, a S * matrix1 n S T * b T := by
          rw [Finset.sum_comm]
          exact Finset.sum_congr rfl fun S _ => Finset.sum_congr rfl fun T _ => by
            unfold matrix1
            have h_inner : ∑ x ∈ Finset.range (q n), basisCos n S ↑x * basisCos n T ↑x * Psi n ↑x =
                ∑ x ∈ Finset.range (q n), basisCos n T ↑x * basisCos n S ↑x * Psi n ↑x := by
              exact Finset.sum_congr rfl fun _ _ => by ring
            rw [h_inner]
            ring
        linarith
      have h_nonneg : ∀ (lambda : Idx n → ℝ), q1 n lambda ≥ 0 := fun lambda => by
        rw [Q_1_sum_sq]
        refine Finset.sum_nonneg fun x _ => ?_
        have h_psi : Psi n (x : ZMod (q n)) ≥ 0 := by unfold Psi; split_ifs <;> norm_num
        exact mul_nonneg (sq_nonneg _) h_psi
      grind,
    zero_mem' := by unfold q1; aesop,
    smul_mem' := by
      -- By definition of $q1$, we know that $q1(c • x) = c^2 * q1(x)$.
      have hQ1_smul : ∀ (c : ℝ) (x : Idx n → ℝ), q1 n (c • x) = c^2 * q1 n x := by
        simp_all +decide only [q1, Finset.powerset_univ, Pi.smul_apply, smul_eq_mul, matrix1]
        exact fun c x => by
          rw [ Finset.mul_sum _ _ _ ]
          exact Finset.sum_congr rfl fun _ _ => by
            rw [ Finset.mul_sum _ _ _ ]
            exact Finset.sum_congr rfl fun _ _ => by ring
      intro c x a
      simp_all [Set.mem_setOf_eq, mul_zero] }

/--
Lemma: $q1(\lambda) = 0$ if and only if $P_{multi}(\lambda, x) = 0$ for all $x \in \mathcal{A}_n$.
-/
lemma Q_1_eq_zero_iff (n : ℕ) (lambda : Idx n → ℝ) :
    q1 n lambda = 0 ↔ ∀ x : ZMod (q n), x.val ∈ evalInterval n → pMulti n lambda x = 0 := by
  sorry

/--
Lemma: $q1$ is non-negative for all $\lambda$.
-/
lemma Q_1_nonneg (n : ℕ) (lambda : Idx n → ℝ) : q1 n lambda ≥ 0 := by
  rw [Q_1_sum_sq]
  refine Finset.sum_nonneg fun x _ => ?_
  have h_psi : Psi n (x : ZMod (q n)) ≥ 0 := by unfold Psi; split_ifs <;> norm_num
  exact mul_nonneg (sq_nonneg _) h_psi

/--
Define the standard dot product on the space of coefficients.
-/
def dotProduct (n : ℕ) (u v : Idx n → ℝ) : ℝ :=
  ∑ S : Idx n, u S * v S

/--
The orthogonal complement of the kernel of $q1$ with respect to the standard dot product.
-/
def kernelQ1Perp (n : ℕ) : Submodule ℝ (Idx n → ℝ) :=
  { carrier := { v | ∀ u ∈ kernelQ1 n, dotProduct n u v = 0 },
    add_mem' := by
      -- By definition of dot product, we have:
      have h_dot_product_linear : ∀ {a b : Idx n → ℝ}, ∀ u : Idx n → ℝ,
        dotProduct n u (a + b) = dotProduct n u a + dotProduct n u b := by
        -- By definition of dot product, we can expand the left-hand side as the sum of the
        -- products of corresponding components.
        simp [dotProduct, Finset.sum_add_distrib, mul_add]
      aesop,
    zero_mem' := by
      -- The dot product of any vector with the zero vector is zero.
      simp [dotProduct],
    smul_mem' := by
      -- By definition of dot product, we have dotProduct n u (c • x) = c * dotProduct n u x.
      simp only [dotProduct, Set.mem_setOf_eq, Pi.smul_apply, smul_eq_mul]
      exact fun c x hx u hu => by
        simpa [ mul_left_comm, Finset.mul_sum _ _ _ ] using
          mul_eq_zero_of_right c ( hx u hu )
  }

/--
The unit sphere in the orthogonal complement of the kernel of $q1$.
-/
def spherePerp (n : ℕ) : Set (Idx n → ℝ) :=
  { lambda | lambda ∈ kernelQ1Perp n ∧ dotProduct n lambda lambda = 1 }

/--
Lemma: $q1$ is strictly positive on the unit sphere of the orthogonal complement.
-/
lemma Q_1_pos_on_sphere_perp (n : ℕ) (lambda : Idx n → ℝ) (h : lambda ∈ spherePerp n) :
    q1 n lambda > 0 := by
  -- By definition of $spherePerp$, we know that $\lambda$ is in the orthogonal complement
  -- of $kernelQ1$ and $\|\lambda\| = 1$.
  obtain ⟨h_lambda_perp, h_lambda_norm⟩ := h
  contrapose! h_lambda_norm
  have h_lambda_kernel : lambda ∈ kernelQ1 n :=
    le_antisymm h_lambda_norm ( Q_1_nonneg n lambda )
  have := h_lambda_perp ( lambda ) h_lambda_kernel
  simp_all +decide [ dotProduct ]

/--
Lemma: $q1$ is not identically zero.
-/
lemma Q_1_not_zero (n : ℕ) : ∃ lambda : Idx n → ℝ, q1 n lambda ≠ 0 := by
  use fun S => if S = ∅ then 1 else 0
  rw [← S_1_eq_Q_1]
  unfold sum1 wTrulyMulti pMulti basisCos
  simp only [ZMod.val_natCast, Finset.powerset_univ, ite_mul, one_mul, zero_mul, Finset.sum_ite_eq',
    Finset.mem_univ, ↓reduceIte, Finset.prod_empty, one_pow, Finset.sum_boole, ne_eq,
    Nat.cast_eq_zero, Finset.card_eq_zero, Finset.filter_eq_empty_iff, not_forall,
    Decidable.not_not]
  -- The sum is over evalInterval. The term is (sum_S ...)^2.
  -- If lambda is delta_empty, sum_S is basisCos(empty) = 1.
  -- So term is 1^2 = 1.
  -- Sum is |evalInterval| = L n.
  -- L n = 12n + 4 > 0.
  use 6 * n^2 - 2 * n
  rcases n with _ | _ | n <;> simp +arith +decide only [sq, Nat.mul_succ, Nat.reduceSubDiff,
    exists_prop] at *
  unfold evalInterval; ring_nf; norm_num
  rw [ Nat.mod_eq_of_lt ] <;> norm_num
  · constructor <;> nlinarith [ Nat.sub_add_cancel ( by
      nlinarith : n * 2 ≤ 20 + n * 24 + n ^ 2 * 6 ) ]
  · refine lt_of_lt_of_le ?_ ( q_bound _ ?_ )
    · exact Nat.lt_succ_of_le ( Nat.sub_le_of_le_add <| by nlinarith )
    · linarith

/--
Lemma: The Rayleigh quotient is scale-invariant.
-/
lemma Ratio_scale (n : ℕ) (lambda : Idx n → ℝ) (c : ℝ) (hc : c ≠ 0) :
    Ratio n (c • lambda) = Ratio n lambda := by
  have h_pull_1 : q1 n (c • lambda) = c^2 * q1 n lambda := by
    unfold q1
    change ∑ S ∈ _, ∑ T ∈ _, (c * lambda S) * matrix1 n S T * (c * lambda T) = _
    have h_pull : ∑ S ∈ Finset.univ.powerset, ∑ T ∈ Finset.univ.powerset,
        (c * lambda S) * matrix1 n S T * (c * lambda T) =
        ∑ S ∈ Finset.univ.powerset, c^2 * ∑ T ∈ Finset.univ.powerset,
        lambda S * matrix1 n S T * lambda T := by
      exact Finset.sum_congr rfl fun S _ => by
        rw [Finset.mul_sum]; congr 1; ext T; ring
    rw [h_pull, ← Finset.mul_sum]
  have h_pull_2 : q2 n (c • lambda) = c^2 * q2 n lambda := by
    unfold q2
    change ∑ S ∈ _, ∑ T ∈ _, (c * lambda S) * matrix2 n S T * (c * lambda T) = _
    have h_pull : ∑ S ∈ Finset.univ.powerset, ∑ T ∈ Finset.univ.powerset,
        (c * lambda S) * matrix2 n S T * (c * lambda T) =
        ∑ S ∈ Finset.univ.powerset, c^2 * ∑ T ∈ Finset.univ.powerset,
        lambda S * matrix2 n S T * lambda T := by
      exact Finset.sum_congr rfl fun S _ => by
        rw [Finset.mul_sum]; congr 1; ext T; ring
    rw [h_pull, ← Finset.mul_sum]
  unfold Ratio
  rw [h_pull_1, h_pull_2]
  have hc2 : c^2 ≠ 0 := by positivity
  by_cases hQ : q1 n lambda = 0
  · simp only [hQ, mul_zero, ite_true]
  · simp only [hQ, hc2, ite_false, mul_eq_zero, or_false]
    rw [mul_div_mul_left _ _ hc2]

/--
Lemma: For any vector $v$, the square of any component is bounded by the dot product.
-/
lemma sq_le_dot_product (n : ℕ) (v : Idx n → ℝ) (i : Idx n) :
    (v i)^2 ≤ dotProduct n v v :=
  Finset.single_le_sum ( fun a _ =>
    mul_self_nonneg ( v a ) ) ( Finset.mem_univ i ) |> le_trans ( by nlinarith )

/--
Lemma: Any vector can be decomposed into a component in the kernel of $q1$ and a component
in the orthogonal complement.
-/
lemma decomposition (n : ℕ) (x : Idx n → ℝ) :
  ∃ u ∈ kernelQ1 n, ∃ v ∈ kernelQ1Perp n, x = u + v := by
  -- Since kernelQ1 n and kernelQ1Perp n are complementary subspaces, their direct sum is
  -- the entire space.
  have h_compl : kernelQ1 n ⊔ kernelQ1Perp n = ⊤ := by
    convert Submodule.sup_orthogonal_of_hasOrthogonalProjection
    rotate_left
    · exact ℝ
    · exact EuclideanSpace ℝ ( Idx n )
    all_goals try infer_instance
    · exact Submodule.span ℝ { v : EuclideanSpace ℝ ( Idx n ) | q1 n ( fun i => v i ) = 0 }
    · constructor
      intro v
      have h_decomp : ∀ v : EuclideanSpace ℝ (Idx n),
          ∃ w ∈ Submodule.span ℝ {v : EuclideanSpace ℝ (Idx n) | q1 n (fun i => v i) = 0},
          v - w ∈ (Submodule.span ℝ
            {v : EuclideanSpace ℝ (Idx n) | q1 n (fun i => v i) = 0})ᗮ := by
        intro v
        have h_decomp_S : ∀ (S : Submodule ℝ (EuclideanSpace ℝ (Idx n))),
            ∃ w ∈ S, v - w ∈ Sᗮ := by
          intro S
          have h_mem_sup : v ∈ S ⊔ Sᗮ := by
            rw [ Submodule.sup_orthogonal_of_hasOrthogonalProjection ]
            aesop
          rw [ Submodule.mem_sup ] at h_mem_sup
          obtain ⟨ y, hy, z, hz, rfl ⟩ := h_mem_sup
          exact ⟨ y, hy, by simpa using hz ⟩
        exact h_decomp_S _
      exact h_decomp v
    · constructor <;> intro h
      · exact Submodule.sup_orthogonal_of_hasOrthogonalProjection
      · convert h using 1
        constructor <;> intro h <;> rw [ Submodule.eq_top_iff' ] at * <;>
          simp_all +decide only [Submodule.mem_sup, Submodule.mem_orthogonal, implies_true]
        intro x
        obtain ⟨ y, hy, z, hz, h ⟩ := h ( WithLp.equiv 2 ( Idx n → ℝ ) |>.symm x )
        refine ⟨ fun i => y i, ?_, fun i => z i, ?_, ?_ ⟩
        · refine Submodule.span_induction ?_ ?_ ?_ ?_ hy
          · intro x_2 h_2
            simp_all only [WithLp.equiv_symm_apply, Set.mem_setOf_eq]
            exact h_2
          · exact show q1 n ( fun _ => 0 ) = 0 from by unfold q1; norm_num
          · exact fun x y hx hy hx' hy' => Submodule.add_mem _ hx' hy'
          · simp +decide [ kernelQ1, q1 ]
            simp +contextual [ mul_assoc, mul_comm, mul_left_comm ]
            simp +contextual [ ← Finset.mul_sum _ _ _ ]
        · intro u hu; specialize hz ( WithLp.equiv 2 ( Idx n → ℝ ) |>.symm u )
          simp_all +decide only [inner, WithLp.equiv_symm_apply]
          convert hz _ using 1
          · exact Finset.sum_congr rfl fun _ _ => mul_comm _ _
          · exact Submodule.subset_span hu
        · convert congr_arg ( fun f => ( WithLp.equiv 2 ( Idx n → ℝ ) ) f ) h using 1
          · ext; simp [Pi.add_apply]
          · simp
  simpa [ eq_comm ] using Submodule.mem_sup.mp ( h_compl.symm ▸ Submodule.mem_top :
    x ∈ kernelQ1 n ⊔ kernelQ1Perp n )

/--
Lemma: The polynomial $P_{multi}$ is linear in $\lambda$.
-/
lemma P_multi_add (n : ℕ) (u v : Idx n → ℝ) (x : ZMod (q n)) :
    pMulti n (u + v) x = pMulti n u x + pMulti n v x := by
  unfold pMulti
  simp [Finset.sum_add_distrib, add_mul]

/--
Lemma: The unit sphere in the orthogonal complement is compact.
-/
lemma sphere_perp_compact (n : ℕ) : IsCompact (spherePerp n) := by
  rw [Metric.isCompact_iff_isClosed_bounded]
  constructor
  · -- Closed
    apply IsClosed.inter
    · -- kernelQ1Perp is closed
      haveI : FiniteDimensional ℝ (Idx n → ℝ) := by infer_instance
      exact (kernelQ1Perp n).complete_of_finiteDimensional.isClosed
    · -- sphere is closed
      apply isClosed_eq
      · -- dotProduct is continuous
        apply continuous_finsetSum
        intro i hi
        apply Continuous.mul
        · apply continuous_apply
        · apply continuous_apply
      · exact continuous_const
  · -- Bounded
    rw [isBounded_iff_forall_norm_le]
    use 1
    intro lambda hlambda
    have h_dot : dotProduct n lambda lambda = 1 := hlambda.2
    apply pi_norm_le_iff_of_nonneg (by norm_num) |>.2
    intro i
    rw [Real.norm_eq_abs]
    rw [← sq_le_one_iff_abs_le_one]
    rw [← h_dot]
    exact sq_le_dot_product n lambda i

lemma Q_2_add_kernel (n : ℕ) (u v : Idx n → ℝ) (hu : u ∈ kernelQ1 n) :
    q2 n (u + v) = q2 n v := by
  sorry

/--
Lemma: The Rayleigh quotient is invariant under adding a vector from the kernel of $q1$.
-/
lemma Ratio_add_kernel (n : ℕ) (u v : Idx n → ℝ) (hu : u ∈ kernelQ1 n) :
    Ratio n (u + v) = Ratio n v := by
  sorry

/--
Lemma: For any $\lambda$ with $q1(\lambda) > 0$, there exists $v \in \text{sphere\_perp}(n)$
such that $\text{Ratio}(n, \lambda) = \text{Ratio}(n, v)$.
-/
lemma exists_sphere_perp_ratio_eq (n : ℕ) (lambda : Idx n → ℝ) (hQ1 : q1 n lambda > 0) :
    ∃ v ∈ spherePerp n, Ratio n lambda = Ratio n v := by
  sorry

/--
Lemma: The set of attainable ratios is the image of the unit sphere in the orthogonal complement
under the Rayleigh quotient map.
-/
lemma attainable_ratios_eq_image_sphere_perp (n : ℕ) :
    attainableRatios n = (spherePerp n).image (Ratio n) := by
  sorry

/--
Lemma: The set of attainable ratios is compact.
-/
lemma attainable_ratios_compact (n : ℕ) : IsCompact (attainableRatios n) := by
  sorry

/--
Lemma: The minimum attainable ratio is attained by some coefficient vector $\lambda$.
-/
lemma exists_minimizer (n : ℕ) :
    ∃ lambda : Idx n → ℝ, q1 n lambda > 0 ∧ Ratio n lambda = muMin n := by
  sorry

/--
Define the optimal coefficient vector $\lambda_{opt}$ which attains the minimum ratio.
-/
noncomputable def lambdaOpt (n : ℕ) : Idx n → ℝ :=
  (exists_minimizer n).choose

/--
Properties of the optimal coefficient vector.
-/
lemma lambda_opt_spec (n : ℕ) :
    q1 n (lambdaOpt n) > 0 ∧ Ratio n (lambdaOpt n) = muMin n :=
  (exists_minimizer n).choose_spec

/--
Define the optimal truly multidimensional weight function $W_{opt}$.
-/
noncomputable def wOpt (n : ℕ) : ZMod (q n) → ℝ :=
  wTrulyMulti n (lambdaOpt n)

/--
Theorem: The optimal weight function satisfies the Krafft Sufficiency condition if and only if
$\mu_{min}(n) < 1$.
-/
theorem W_opt_is_sufficient_iff (n : ℕ) :
    (sum2 n (wOpt n) < sum1 n (wOpt n)) ↔ muMin n < 1 := by
  sorry

/--
Helper lemma: The hit count function c is non-negative everywhere.
-/
lemma c_nonneg (n : ℕ) (x : ZMod (q n)) : c n x ≥ 0 := by
  unfold c g
  refine Finset.sum_nonneg fun i _ ↦ ?_
  split_ifs <;> norm_num

/--
Definition: The sieve projection is full rank if the mapping from
coefficients to spatial vectors on ZMod (q n) is surjective.
-/
def IsFullRank (n : ℕ) : Prop :=
  ∀ v : ZMod (q n) → ℝ, ∃ lambda : Finset (Fin (w n)) → ℝ,
    ∀ x : ZMod (q n), pMulti n lambda x = v x

/--
Helper: a sum of `f` over the casts of `Finset.range m` equals the sum of `f` over all
of `ZMod m` (the casting map `range m → ZMod m` is a bijection when `m ≠ 0`).
-/
private lemma sum_range_zmod (m : ℕ) [NeZero m] (f : ZMod m → ℝ) :
    ∑ x ∈ Finset.range m, f (x : ZMod m) = ∑ y : ZMod m, f y := by
  apply Finset.sum_nbij' (i := fun x : ℕ => (x : ZMod m)) (j := fun y : ZMod m => y.val)
  · intro a _; exact Finset.mem_univ _
  · intro a _; simp [Finset.mem_range, ZMod.val_lt]
  · intro a ha; simp only [Finset.mem_range] at ha; exact ZMod.val_natCast_of_lt ha
  · intro a _; simp [ZMod.natCast_val, ZMod.cast_id]
  · intro a _; rfl

/--
Theorem: If the sieve is full rank and there exists a twin prime in A_n,
then the minimum sieve quotient muMin n is exactly 0.
-/
theorem muMin_eq_zero_of_fullRank_and_twinPrime (n : ℕ)
    (h_rank : IsFullRank n)
    (h_tp : ∃ x_0 ∈ evalInterval n, c n (x_0 : ZMod (q n)) = 0) :
    muMin n = 0 := by
  sorry

/--
Theorem: The Krafft Sieve Guarantee holds if $\mu_{min}(n) < 1$.
-/
theorem krafft_sieve_guarantee_with_mu_min (n : ℕ) (h : muMin n < 1) :
    ∃ x ∈ evalInterval n, Nat.Prime (6 * x - 1) ∧ Nat.Prime (6 * x + 1) := by
  have := mu_min_lt_one_implies_sufficiency n h
  by_cases hn : n ≥ 1 <;> simp_all +decide only [KrafftSufficiency, ge_iff_le, not_le,
    Nat.lt_one_iff]
  obtain ⟨ W, hW₁, hW₂, hW₃ ⟩ := this
  apply krafft_sieve_guarantee n hn ⟨ W, hW₁, hW₂, hW₃ ⟩

end

end KrafftSieve
