/-
Copyright (c) 2026 Fernando Portela. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Fernando Portela, Gemini 3.5 Flash (Google DeepMind)
-/

/-
Portions of this file were generated by Aristotle (https://aristotle.harmonic.fun).

Lean version: leanprover/lean4:v4.28.0
Mathlib version: 8f9d9cff6bd728b17a24e163c9402775d9e6a365

To cite Aristotle, tag @Aristotle-Harmonic on GitHub PRs/issues, and add as co-author to commits:
Co-authored-by: Aristotle (Harmonic) <aristotle-harmonic@harmonic.fun>
-/

import KrafftSieve.SelbergWeights
import Mathlib.Analysis.InnerProductSpace.Projection.Submodule
import Mathlib.Analysis.InnerProductSpace.PiL2

/-!
# Optimal Weights

This module constructs the truly multidimensional optimal weights $\lambda$ for the Krafft Sieve
and explores the properties of the resulting polynomial $P(x)$ and weight $W_\lambda(x)$.
-/

namespace KrafftSieve

open scoped BigOperators
open scoped Real
open scoped Nat

open scoped Pointwise

noncomputable section

/--
Define the basis function for a subset of prime indices $S \subseteq \{1, \dots, w\}$.
The basis function is the product of the 3rd harmonic cosines for each prime in $S$.
$$ B_S(x) = \prod_{i \in S} \cos\left( \frac{6\pi x}{p_i} \right) $$
-/
noncomputable def basisCos (n : ℕ) (S : Finset (Fin (w n))) (x : ZMod (q n)) : ℝ :=
  ∏ i ∈ S, Real.cos (2 * Real.pi * 3 * (x.val : ℝ) / (p n i : ℝ))

/--
Define the multidimensional polynomial $P(x)$ as a linear combination of
the basis functions $B_S(x)$ with coefficients $\lambda_S$.
$$ P(x) = \sum_{S \subseteq \{1, \dots, w\}} \lambda_S B_S(x) $$
-/
noncomputable def pMulti (n : ℕ) (lambda : Finset (Fin (w n)) → ℝ) (x : ZMod (q n)) : ℝ :=
  ∑ S ∈ Finset.univ.powerset, lambda S * basisCos n S x

/--
Define the truly multidimensional weight function $W_{\lambda}(x)$ as the square of the
polynomial $P(x)$ restricted to the interval $\mathcal{A}_n$.
$$ W_{\lambda}(x) = \begin{cases} (P(x))^2 & \text{if } x \in \mathcal{A}_n \\
0 & \text{otherwise} \end{cases} $$
-/
noncomputable def wTrulyMulti (n : ℕ) (lambda : Finset (Fin (w n)) → ℝ) (x : ZMod (q n)) : ℝ :=
  if x.val ∈ evalInterval n then (pMulti n lambda x) ^ 2 else 0

/--
Define the dual spatial kernel matrix $K_{x, y}$.
$K_{x, y} = \sum_{S \subseteq \{1, \dots, w\}} B_S(x) B_S(y)$
-/
noncomputable def spatialKernel (n : ℕ) (x y : ZMod (q n)) : ℝ :=
  ∑ S ∈ Finset.univ.powerset, basisCos n S x * basisCos n S y

/--
Theorem: The dual spatial kernel has a closed-form product representation.
$$ K_{x, y} = \prod_{p \in \mathcal{P}_n} ( 1 + \cos(6\pi x / p) \cos(6\pi y / p) ) $$
-/
theorem spatialKernel_eq_prod (n : ℕ) (x y : ZMod (q n)) :
    spatialKernel n x y = ∏ i : Fin (w n),
      (1 + Real.cos (6 * Real.pi * (x.val : ℝ) / (p n i : ℝ)) *
            Real.cos (6 * Real.pi * (y.val : ℝ) / (p n i : ℝ))) := by
  unfold spatialKernel
  have h_basis : ∀ S : Finset (Fin (w n)),
      basisCos n S x * basisCos n S y =
        ∏ i ∈ S, (Real.cos (6 * Real.pi * (x.val : ℝ) / (p n i : ℝ)) *
                  Real.cos (6 * Real.pi * (y.val : ℝ) / (p n i : ℝ))) := by
    intro S
    unfold basisCos
    have h_angle : ∀ (z : ZMod (q n)) (i : Fin (w n)),
        2 * Real.pi * 3 * (z.val : ℝ) / (p n i : ℝ) = 6 * Real.pi * (z.val : ℝ) / (p n i : ℝ) := by
      intro z i
      ring
    simp_rw [h_angle]
    rw [← Finset.prod_mul_distrib]
  simp_rw [h_basis]
  exact (@Finset.prod_one_add (Fin (w n)) ℝ _
    (fun i ↦ Real.cos (6 * Real.pi * (x.val : ℝ) / (p n i : ℝ)) *
              Real.cos (6 * Real.pi * (y.val : ℝ) / (p n i : ℝ)))
    Finset.univ).symm

/--
Define the matrix $M_1$ corresponding to the first moment $sum1$.
$M_1(S, T) = \sum_{x \in \text{range}(q_n)} B_S(x) B_T(x) \Psi(x)$
-/
noncomputable def matrix1 (n : ℕ) (S T : Finset (Fin (w n))) : ℝ :=
  ∑ x ∈ Finset.range (q n), basisCos n S (x : ZMod (q n)) * basisCos n T (x : ZMod (q n)) *
    Psi n (x : ZMod (q n))

/--
Define the matrix $M_2$ corresponding to the second moment $sum2$.
$M_2(S, T) = \sum_{x \in \text{range}(q_n)} c(x) B_S(x) B_T(x) \Psi(x)$
-/
noncomputable def matrix2 (n : ℕ) (S T : Finset (Fin (w n))) : ℝ :=
  ∑ x ∈ Finset.range (q n), c n (x : ZMod (q n)) * basisCos n S (x : ZMod (q n)) *
    basisCos n T (x : ZMod (q n)) * Psi n (x : ZMod (q n))

/--
Define the quadratic form $q1(\lambda) = \lambda^T M_1 \lambda$.
-/
noncomputable def q1 (n : ℕ) (lambda : Finset (Fin (w n)) → ℝ) : ℝ :=
  ∑ S ∈ Finset.univ.powerset, ∑ T ∈ Finset.univ.powerset, lambda S * matrix1 n S T * lambda T

/--
Define the quadratic form $q2(\lambda) = \lambda^T M_2 \lambda$.
-/
noncomputable def q2 (n : ℕ) (lambda : Finset (Fin (w n)) → ℝ) : ℝ :=
  ∑ S ∈ Finset.univ.powerset, ∑ T ∈ Finset.univ.powerset, lambda S * matrix2 n S T * lambda T

/--
Define the Rayleigh quotient $R(\lambda) = \frac{q2(\lambda)}{q1(\lambda)}$.
Defined to be $\infty$ if $q1(\lambda) = 0$ (though $q1$ is positive definite on
non-zero $\lambda$ if the basis is linearly independent on $evalInterval$).
-/
noncomputable def Ratio (n : ℕ) (lambda : Finset (Fin (w n)) → ℝ) : ℝ :=
  if q1 n lambda = 0 then 0 else (q2 n lambda) / (q1 n lambda)

/--
Helper: q1 equals the sum of squares of pMulti over range (q n).
-/
private lemma Q_1_sum_sq (n : ℕ) (lambda : Finset (Fin (w n)) → ℝ) :
    q1 n lambda = ∑ x ∈ Finset.range (q n),
      (pMulti n lambda (x : ZMod (q n))) ^ 2 * Psi n (x : ZMod (q n)) := by
  unfold q1 pMulti matrix1
  simp +decide only [Finset.mul_sum _ _ _, Finset.sum_mul _ _ _, mul_comm, mul_left_comm, sq]
  exact Eq.symm (by
    rw [Finset.sum_comm]
    exact Finset.sum_congr rfl fun _ _ =>
      Finset.sum_comm.trans (Finset.sum_congr rfl fun _ _ =>
        Finset.sum_congr rfl fun _ _ => by ring))

/--
The truly multidimensional weight function is non-negative everywhere.
-/
lemma W_truly_multi_nonneg (n : ℕ) (lambda : Finset (Fin (w n)) → ℝ) (x : ZMod (q n)) :
    wTrulyMulti n lambda x ≥ 0 := by
  by_cases hx : x.val ∈ evalInterval n <;>
    simp_all +decide only [wTrulyMulti, ↓reduceIte, ge_iff_le,
    le_refl]
  exact sq_nonneg _

/--
The truly multidimensional weight function is supported on $\mathcal{A}_n$.
-/
lemma W_truly_multi_support (n : ℕ) (lambda : Finset (Fin (w n)) → ℝ) (x : ZMod (q n))
    (hx : x.val ∉ evalInterval n) :
  wTrulyMulti n lambda x = 0 := by
    exact if_neg hx

/-
Corrected version of `S_1_eq_Q_1` (false at `n = 0`): for `1 ≤ n`, the first moment `sum1` of
the truly multidimensional weight equals the quadratic form `q1`.
-/
lemma S_1_eq_Q_1_pos (n : ℕ) (hn : 1 ≤ n) (lambda : Finset (Fin (w n)) → ℝ) :
    sum1 n (wTrulyMulti n lambda) = q1 n lambda := by
  rw [Q_1_sum_sq]
  have hsub : evalInterval n ⊆ Finset.range (q n) := by
    intro y hy
    rw [Finset.mem_range]
    exact lt_of_le_of_lt (Finset.mem_Icc.mp hy).2 (q_bound n hn)
  have hval : ∀ y ∈ Finset.range (q n), ((y : ZMod (q n)).val = y) :=
    fun y hy => ZMod.val_natCast_of_lt (Finset.mem_range.mp hy)
  rw [← Finset.sum_subset hsub (by
    intro y hy hy'
    have hz : Psi n (y : ZMod (q n)) = 0 := by
      unfold Psi; rw [if_neg]; rw [hval y hy]; exact hy'
    rw [hz, mul_zero])]
  unfold sum1
  refine Finset.sum_congr rfl (fun x hx => ?_)
  have hxe : (x : ZMod (q n)).val ∈ evalInterval n := by
    rw [hval x (hsub hx)]; exact hx
  unfold wTrulyMulti Psi
  rw [if_pos hxe, if_pos hxe, mul_one]

/--
Helper: q2 equals the weighted sum of squares of pMulti over range (q n).
-/
lemma q2_sum_sq (n : ℕ) (lambda : Finset (Fin (w n)) → ℝ) :
    q2 n lambda =
      ∑ x ∈ Finset.range (q n),
        c n (x : ZMod (q n)) * (pMulti n lambda (x : ZMod (q n))) ^ 2 * Psi n (x : ZMod (q n)) := by
  unfold q2 pMulti matrix2
  simp +decide only [Finset.mul_sum _ _ _, Finset.sum_mul _ _ _, mul_comm, mul_left_comm, sq]
  exact Eq.symm (by
    rw [Finset.sum_comm]
    exact Finset.sum_congr rfl fun _ _ =>
      Finset.sum_comm.trans (Finset.sum_congr rfl fun _ _ =>
        Finset.sum_congr rfl fun _ _ => by ring))

/-
Corrected version of `S_2_eq_Q_2` (false at `n = 0`): for `1 ≤ n`, the second moment `sum2` of
the truly multidimensional weight equals the quadratic form `q2`.
-/
lemma S_2_eq_Q_2_pos (n : ℕ) (hn : 1 ≤ n) (lambda : Finset (Fin (w n)) → ℝ) :
    sum2 n (wTrulyMulti n lambda) = q2 n lambda := by
  rw [q2_sum_sq]
  have hsub : evalInterval n ⊆ Finset.range (q n) := fun y hy =>
    Finset.mem_range.mpr (lt_of_le_of_lt (Finset.mem_Icc.mp hy).2 (q_bound n hn))
  have hval : ∀ y ∈ Finset.range (q n), ((y : ZMod (q n)).val = y) :=
    fun y hy => ZMod.val_natCast_of_lt (Finset.mem_range.mp hy)
  rw [← Finset.sum_subset hsub (by
    intro y hy hy'
    have hz : Psi n (y : ZMod (q n)) = 0 := by
      unfold Psi; rw [if_neg]; rw [hval y hy]; exact hy'
    rw [hz, mul_zero])]
  unfold sum2
  refine Finset.sum_congr rfl (fun x hx => ?_)
  have hxe : (x : ZMod (q n)).val ∈ evalInterval n := by
    rw [hval x (hsub hx)]; exact hx
  unfold wTrulyMulti Psi
  rw [if_pos hxe, if_pos hxe]
  ring

/-
Lemma: The existence of coefficients $\lambda$ such that $q2(\lambda) < q1(\lambda)$
is sufficient for Krafft Sufficiency.
-/
lemma sufficiency_of_Q (n : ℕ) (lambda : Finset (Fin (w n)) → ℝ) (h : q2 n lambda < q1 n lambda) :
    KrafftSufficiency n := by
  by_cases hn : n = 0
  · -- Degenerate case `n = 0`: `q 0 = 1`, `w 0 = 0` so `c 0 ≡ 0`; take the constant weight `1`.
    subst hn
    have hq : q 0 = 1 := by decide
    have huniv : (Finset.univ : Finset (Fin (w 0))) = ∅ := by rw [show w 0 = 0 from by decide]; rfl
    refine ⟨fun _ => 1, fun _ => by norm_num, fun x hx => ?_, ?_⟩
    · apply absurd _ hx
      have hlt : x.val < q 0 := ZMod.val_lt x
      simp only [evalInterval, Finset.mem_Icc]
      omega
    · have hc : ∀ x : ZMod (q 0), c 0 x = 0 := by
        intro x; unfold c; rw [huniv]; simp
      have hs2 : sum2 0 (fun _ => 1) = 0 := by unfold sum2; simp [hc]
      have hs1 : sum1 0 (fun _ => (1 : ℝ)) = 4 := by unfold sum1; simp [evalInterval]
      rw [hs1, hs2]; norm_num
  · exact ⟨wTrulyMulti n lambda, fun x => W_truly_multi_nonneg n lambda x,
      fun x hx => W_truly_multi_support n lambda x hx, by
        rw [S_1_eq_Q_1_pos n (Nat.pos_of_ne_zero hn) lambda,
          S_2_eq_Q_2_pos n (Nat.pos_of_ne_zero hn) lambda]; exact h⟩

/--
The spatial representation of the polynomial $P(x)$ as a function from $\mathbb{N}$ to $\mathbb{R}$.
-/
def spatialVector (n : ℕ) (lambda : Finset (Fin (w n)) → ℝ) (x : ℕ) : ℝ :=
  pMulti n lambda (x : ZMod (q n))

/--
Theorem: Primal quadratic form q1 is the spatial L2 norm of the spatial vector.
-/
lemma q1_eq_spatialVector_norm (n : ℕ) (lambda : Finset (Fin (w n)) → ℝ) :
    q1 n lambda = ∑ x ∈ Finset.range (q n),
      (spatialVector n lambda x)^2 * Psi n (x : ZMod (q n)) := by
  unfold spatialVector
  exact Q_1_sum_sq n lambda

/--
Theorem: Primal quadratic form q2 is the spatial weighted L2 norm of the spatial vector.
-/
lemma q2_eq_spatialVector_weighted_norm (n : ℕ) (lambda : Finset (Fin (w n)) → ℝ) :
    q2 n lambda =
      ∑ x ∈ Finset.range (q n),
        c n (x : ZMod (q n)) * (spatialVector n lambda x)^2 * Psi n (x : ZMod (q n)) := by
  unfold spatialVector
  exact q2_sum_sq n lambda

/--
The spatial Rayleigh quotient of a spatial vector.
-/
noncomputable def spatialRatio (n : ℕ) (v : ℕ → ℝ) : ℝ :=
  let q1_v := ∑ x ∈ Finset.range (q n), (v x)^2 * Psi n (x : ZMod (q n))
  let q2_v :=
    ∑ x ∈ Finset.range (q n), c n (x : ZMod (q n)) * (v x)^2 * Psi n (x : ZMod (q n))
  if q1_v = 0 then 0 else q2_v / q1_v

/--
Theorem: The primal Rayleigh quotient equals the spatial Rayleigh quotient.
-/
lemma Ratio_eq_spatialRatio (n : ℕ) (lambda : Finset (Fin (w n)) → ℝ) :
    Ratio n lambda = spatialRatio n (spatialVector n lambda) := by
  unfold Ratio spatialRatio
  rw [q1_eq_spatialVector_norm, q2_eq_spatialVector_weighted_norm]


/--
Define the set of attainable ratios.
-/
def attainableRatios (n : ℕ) : Set ℝ :=
  { r | ∃ lambda : Finset (Fin (w n)) → ℝ, q1 n lambda > 0 ∧ r = Ratio n lambda }

/--
Define $\mu_{min}(n)$ as the infimum of the attainable ratios.
-/
noncomputable def muMin (n : ℕ) : ℝ := sInf (attainableRatios n)

/-
Theorem: If the minimum attainable ratio $\mu_{min}(n)$ is strictly less than 1,
then the Krafft Sufficiency condition holds.
-/
theorem mu_min_lt_one_implies_sufficiency (n : ℕ) (h : muMin n < 1) :
    KrafftSufficiency n := by
  by_contra h_contra
  -- By the definition of infimum, there exists a $\lambda$ such that:
  -- q1 n \lambda > 0 and Ratio n \lambda < 1.
  obtain ⟨lambda, hlambda_pos, hlambda_ratio⟩ :
      ∃ lambda : Finset (Fin (w n)) → ℝ, q1 n lambda > 0 ∧ Ratio n lambda < 1 := by
    contrapose! h
    refine le_csInf ?_ ?_
    · obtain ⟨lambda, hlambda⟩ : ∃ lambda : Finset (Fin (w n)) → ℝ, q1 n lambda > 0 := by
        use fun S => if S = ∅ then 1 else 0
        simp +decide only [ q1, matrix1 ]
        unfold basisCos Psi; norm_num
        refine ⟨ 6 * n ^ 2 - 2 * n, ?_ ⟩
        norm_num [ evalInterval ]
        by_cases hn : n ≥ 1
        · rw [ Nat.mod_eq_of_lt ]
          · exact ⟨by linarith [q_bound n hn,
              Nat.sub_add_cancel (by nlinarith : 2 * n ≤ 6 * n ^ 2)], by omega, by omega⟩
          · exact lt_of_le_of_lt ( Nat.sub_le _ _ ) ( by nlinarith [ q_bound n hn ] )
        · interval_cases n ; simp +decide
      exact ⟨ _, ⟨ lambda, hlambda, rfl ⟩ ⟩
    · rintro _ ⟨ lambda, hlambda_pos, rfl ⟩ ; exact h _ hlambda_pos
  have hRatio_eq : Ratio n lambda = q2 n lambda / q1 n lambda :=
    if_neg (ne_of_gt hlambda_pos)
  rw [hRatio_eq] at hlambda_ratio
  rw [div_lt_one hlambda_pos] at hlambda_ratio
  exact h_contra (sufficiency_of_Q n lambda hlambda_ratio)

/--
Abbreviation for the index set of the coefficients, which is the power set of prime indices.
-/
abbrev Idx (n : ℕ) := Finset (Fin (w n))

/--
The kernel of the quadratic form $q1$.
-/
def kernelQ1 (n : ℕ) : Submodule ℝ (Idx n → ℝ) :=
  { carrier := { lambda | q1 n lambda = 0 },
    add_mem' := by
      intros a b ha hb
      have h_sum : q1 n (a + b) = q1 n a + q1 n b + 2 * (∑ S ∈ Finset.univ.powerset,
          ∑ T ∈ Finset.univ.powerset, a S * matrix1 n S T * b T) := by
        unfold q1
        change ∑ S ∈ _, ∑ T ∈ _, (a S + b S) * matrix1 n S T * (a T + b T) = _
        simp only [add_mul, mul_add, Finset.sum_add_distrib]
        have h_comm : ∑ x ∈ Finset.univ.powerset, ∑ x_1 ∈ Finset.univ.powerset,
            b x * matrix1 n x x_1 * a x_1 =
            ∑ S ∈ Finset.univ.powerset, ∑ T ∈ Finset.univ.powerset, a S * matrix1 n S T * b T := by
          rw [Finset.sum_comm]
          exact Finset.sum_congr rfl fun S _ => Finset.sum_congr rfl fun T _ => by
            unfold matrix1
            have h_inner : ∑ x ∈ Finset.range (q n), basisCos n S ↑x * basisCos n T ↑x * Psi n ↑x =
                ∑ x ∈ Finset.range (q n), basisCos n T ↑x * basisCos n S ↑x * Psi n ↑x := by
              exact Finset.sum_congr rfl fun _ _ => by ring
            rw [h_inner]
            ring
        linarith
      have h_sum2 : q1 n (a - b) = q1 n a + q1 n b - 2 * (∑ S ∈ Finset.univ.powerset,
          ∑ T ∈ Finset.univ.powerset, a S * matrix1 n S T * b T) := by
        unfold q1
        change ∑ S ∈ _, ∑ T ∈ _, (a S - b S) * matrix1 n S T * (a T - b T) = _
        simp only [sub_mul, mul_sub, Finset.sum_sub_distrib]
        have h_comm : ∑ x ∈ Finset.univ.powerset, ∑ x_1 ∈ Finset.univ.powerset,
            b x * matrix1 n x x_1 * a x_1 =
            ∑ S ∈ Finset.univ.powerset, ∑ T ∈ Finset.univ.powerset, a S * matrix1 n S T * b T := by
          rw [Finset.sum_comm]
          exact Finset.sum_congr rfl fun S _ => Finset.sum_congr rfl fun T _ => by
            unfold matrix1
            have h_inner : ∑ x ∈ Finset.range (q n), basisCos n S ↑x * basisCos n T ↑x * Psi n ↑x =
                ∑ x ∈ Finset.range (q n), basisCos n T ↑x * basisCos n S ↑x * Psi n ↑x := by
              exact Finset.sum_congr rfl fun _ _ => by ring
            rw [h_inner]
            ring
        linarith
      have h_nonneg : ∀ (lambda : Idx n → ℝ), q1 n lambda ≥ 0 := fun lambda => by
        rw [Q_1_sum_sq]
        refine Finset.sum_nonneg fun x _ => ?_
        have h_psi : Psi n (x : ZMod (q n)) ≥ 0 := by unfold Psi; split_ifs <;> norm_num
        exact mul_nonneg (sq_nonneg _) h_psi
      grind,
    zero_mem' := by unfold q1; aesop,
    smul_mem' := by
      -- By definition of $q1$, we know that $q1(c • x) = c^2 * q1(x)$.
      have hQ1_smul : ∀ (c : ℝ) (x : Idx n → ℝ), q1 n (c • x) = c^2 * q1 n x := by
        simp_all +decide only [q1, Finset.powerset_univ, Pi.smul_apply, smul_eq_mul, matrix1]
        exact fun c x => by
          rw [ Finset.mul_sum _ _ _ ]
          exact Finset.sum_congr rfl fun _ _ => by
            rw [ Finset.mul_sum _ _ _ ]
            exact Finset.sum_congr rfl fun _ _ => by ring
      intro c x a
      simp_all [Set.mem_setOf_eq, mul_zero] }

/-
Lemma: $q1(\lambda) = 0$ if and only if $P_{multi}(\lambda, x) = 0$ for all $x \in \mathcal{A}_n$.
-/
lemma Q_1_eq_zero_iff (n : ℕ) (lambda : Idx n → ℝ) :
    q1 n lambda = 0 ↔ ∀ x : ZMod (q n), x.val ∈ evalInterval n → pMulti n lambda x = 0 := by
  rw [Q_1_sum_sq,
    Finset.sum_eq_zero_iff_of_nonneg (fun x _ =>
      mul_nonneg (sq_nonneg _) (by unfold Psi; split_ifs <;> norm_num))]
  constructor
  · intro h x hx
    have hlt : x.val < q n := ZMod.val_lt x
    have hx0 := h x.val (Finset.mem_range.mpr hlt)
    have hxcast : ((x.val : ℕ) : ZMod (q n)) = x := by
      simp [ZMod.natCast_val, ZMod.cast_id]
    rw [hxcast] at hx0
    have hpsi : Psi n x = 1 := by unfold Psi; rw [if_pos hx]
    rw [hpsi, mul_one] at hx0
    exact pow_eq_zero_iff (by norm_num) |>.mp hx0
  · intro h y _
    by_cases hyv : (y : ZMod (q n)).val ∈ evalInterval n
    · rw [h (y : ZMod (q n)) hyv]; ring
    · have hz : Psi n (y : ZMod (q n)) = 0 := by unfold Psi; rw [if_neg hyv]
      rw [hz, mul_zero]

/--
Lemma: $q1$ is non-negative for all $\lambda$.
-/
lemma Q_1_nonneg (n : ℕ) (lambda : Idx n → ℝ) : q1 n lambda ≥ 0 := by
  rw [Q_1_sum_sq]
  refine Finset.sum_nonneg fun x _ => ?_
  have h_psi : Psi n (x : ZMod (q n)) ≥ 0 := by unfold Psi; split_ifs <;> norm_num
  exact mul_nonneg (sq_nonneg _) h_psi

/--
Define the standard dot product on the space of coefficients.
-/
def dotProduct (n : ℕ) (u v : Idx n → ℝ) : ℝ :=
  ∑ S : Idx n, u S * v S

/--
The orthogonal complement of the kernel of $q1$ with respect to the standard dot product.
-/
def kernelQ1Perp (n : ℕ) : Submodule ℝ (Idx n → ℝ) :=
  { carrier := { v | ∀ u ∈ kernelQ1 n, dotProduct n u v = 0 },
    add_mem' := by
      -- By definition of dot product, we have:
      have h_dot_product_linear : ∀ {a b : Idx n → ℝ}, ∀ u : Idx n → ℝ,
        dotProduct n u (a + b) = dotProduct n u a + dotProduct n u b := by
        -- By definition of dot product, we can expand the left-hand side as the sum of the
        -- products of corresponding components.
        simp [dotProduct, Finset.sum_add_distrib, mul_add]
      aesop,
    zero_mem' := by
      -- The dot product of any vector with the zero vector is zero.
      simp [dotProduct],
    smul_mem' := by
      -- By definition of dot product, we have dotProduct n u (c • x) = c * dotProduct n u x.
      simp only [dotProduct, Set.mem_setOf_eq, Pi.smul_apply, smul_eq_mul]
      exact fun c x hx u hu => by
        simpa [ mul_left_comm, Finset.mul_sum _ _ _ ] using
          mul_eq_zero_of_right c ( hx u hu )
  }

/--
The unit sphere in the orthogonal complement of the kernel of $q1$.
-/
def spherePerp (n : ℕ) : Set (Idx n → ℝ) :=
  { lambda | lambda ∈ kernelQ1Perp n ∧ dotProduct n lambda lambda = 1 }

/--
Lemma: $q1$ is strictly positive on the unit sphere of the orthogonal complement.
-/
lemma Q_1_pos_on_sphere_perp (n : ℕ) (lambda : Idx n → ℝ) (h : lambda ∈ spherePerp n) :
    q1 n lambda > 0 := by
  -- By definition of $spherePerp$, we know that $\lambda$ is in the orthogonal complement
  -- of $kernelQ1$ and $\|\lambda\| = 1$.
  obtain ⟨h_lambda_perp, h_lambda_norm⟩ := h
  contrapose! h_lambda_norm
  have h_lambda_kernel : lambda ∈ kernelQ1 n :=
    le_antisymm h_lambda_norm ( Q_1_nonneg n lambda )
  have := h_lambda_perp ( lambda ) h_lambda_kernel
  simp_all +decide [ dotProduct ]

/-
Lemma: $q1$ is not identically zero.
-/
lemma Q_1_not_zero (n : ℕ) : ∃ lambda : Idx n → ℝ, q1 n lambda ≠ 0 := by
  -- Choose the vector `λ` with `λ_∅ = 1` and `λ_S = 0` for all `S ≠ ∅`.
  refine ⟨fun S => if S = ∅ then 1 else 0, ?_⟩
  -- For this `λ`, `pMulti` is the constant `1` (only the empty subset contributes, and
  -- `basisCos n ∅ = 1`).
  have hpM : ∀ x : ZMod (q n),
      pMulti n (fun S => if S = ∅ then (1 : ℝ) else 0) x = 1 := by
    intro x
    unfold pMulti basisCos
    simp [Finset.sum_ite_eq']
  rw [Q_1_sum_sq]
  simp only [hpM, one_pow, one_mul]
  -- Goal: `∑ x ∈ range (q n), Psi n ↑x ≠ 0`.  The lower endpoint `m := 6*n^2 - 2*n` of
  -- `evalInterval n` lies in `range (q n)` and contributes `1`.
  have hmlt : 6 * n ^ 2 - 2 * n < q n := by
    rcases Nat.eq_zero_or_pos n with h0 | hpos
    · subst h0; decide
    · exact lt_of_le_of_lt (le_trans (Nat.sub_le _ _) (by nlinarith)) (q_bound n hpos)
  have hmr : 6 * n ^ 2 - 2 * n ∈ Finset.range (q n) := Finset.mem_range.mpr hmlt
  have hmval : ((6 * n ^ 2 - 2 * n : ℕ) : ZMod (q n)).val = 6 * n ^ 2 - 2 * n :=
    ZMod.val_natCast_of_lt hmlt
  have hme : ((6 * n ^ 2 - 2 * n : ℕ) : ZMod (q n)).val ∈ evalInterval n := by
    rw [hmval]; unfold evalInterval; rw [Finset.mem_Icc]
    exact ⟨le_refl _, by omega⟩
  have hPsim : Psi n ((6 * n ^ 2 - 2 * n : ℕ) : ZMod (q n)) = 1 := by
    unfold Psi; rw [if_pos hme]
  have hle : (1 : ℝ) ≤ ∑ x ∈ Finset.range (q n), Psi n (x : ZMod (q n)) := by
    rw [← hPsim]
    refine Finset.single_le_sum (f := fun x : ℕ => Psi n (x : ZMod (q n))) ?_ hmr
    intro x _
    change (0 : ℝ) ≤ Psi n (x : ZMod (q n))
    unfold Psi; split_ifs <;> norm_num
  exact ne_of_gt (lt_of_lt_of_le one_pos hle)

/--
Lemma: The Rayleigh quotient is scale-invariant.
-/
lemma Ratio_scale (n : ℕ) (lambda : Idx n → ℝ) (c : ℝ) (hc : c ≠ 0) :
    Ratio n (c • lambda) = Ratio n lambda := by
  have h_pull_1 : q1 n (c • lambda) = c^2 * q1 n lambda := by
    unfold q1
    change ∑ S ∈ _, ∑ T ∈ _, (c * lambda S) * matrix1 n S T * (c * lambda T) = _
    have h_pull : ∑ S ∈ Finset.univ.powerset, ∑ T ∈ Finset.univ.powerset,
        (c * lambda S) * matrix1 n S T * (c * lambda T) =
        ∑ S ∈ Finset.univ.powerset, c^2 * ∑ T ∈ Finset.univ.powerset,
        lambda S * matrix1 n S T * lambda T := by
      exact Finset.sum_congr rfl fun S _ => by
        rw [Finset.mul_sum]; congr 1; ext T; ring
    rw [h_pull, ← Finset.mul_sum]
  have h_pull_2 : q2 n (c • lambda) = c^2 * q2 n lambda := by
    unfold q2
    change ∑ S ∈ _, ∑ T ∈ _, (c * lambda S) * matrix2 n S T * (c * lambda T) = _
    have h_pull : ∑ S ∈ Finset.univ.powerset, ∑ T ∈ Finset.univ.powerset,
        (c * lambda S) * matrix2 n S T * (c * lambda T) =
        ∑ S ∈ Finset.univ.powerset, c^2 * ∑ T ∈ Finset.univ.powerset,
        lambda S * matrix2 n S T * lambda T := by
      exact Finset.sum_congr rfl fun S _ => by
        rw [Finset.mul_sum]; congr 1; ext T; ring
    rw [h_pull, ← Finset.mul_sum]
  unfold Ratio
  rw [h_pull_1, h_pull_2]
  have hc2 : c^2 ≠ 0 := by positivity
  by_cases hQ : q1 n lambda = 0
  · simp only [hQ, mul_zero, ite_true]
  · simp only [hQ, hc2, ite_false, mul_eq_zero, or_false]
    rw [mul_div_mul_left _ _ hc2]

/--
Lemma: For any vector $v$, the square of any component is bounded by the dot product.
-/
lemma sq_le_dot_product (n : ℕ) (v : Idx n → ℝ) (i : Idx n) :
    (v i)^2 ≤ dotProduct n v v :=
  Finset.single_le_sum ( fun a _ =>
    mul_self_nonneg ( v a ) ) ( Finset.mem_univ i ) |> le_trans ( by nlinarith )

/--
Lemma: Any vector can be decomposed into a component in the kernel of $q1$ and a component
in the orthogonal complement.
-/
lemma decomposition (n : ℕ) (x : Idx n → ℝ) :
  ∃ u ∈ kernelQ1 n, ∃ v ∈ kernelQ1Perp n, x = u + v := by
  -- Since kernelQ1 n and kernelQ1Perp n are complementary subspaces, their direct sum is
  -- the entire space.
  have h_compl : kernelQ1 n ⊔ kernelQ1Perp n = ⊤ := by
    convert Submodule.sup_orthogonal_of_hasOrthogonalProjection
    rotate_left
    · exact ℝ
    · exact EuclideanSpace ℝ ( Idx n )
    all_goals try infer_instance
    · exact Submodule.span ℝ { v : EuclideanSpace ℝ ( Idx n ) | q1 n ( fun i => v i ) = 0 }
    · constructor
      intro v
      have h_decomp : ∀ v : EuclideanSpace ℝ (Idx n),
          ∃ w ∈ Submodule.span ℝ {v : EuclideanSpace ℝ (Idx n) | q1 n (fun i => v i) = 0},
          v - w ∈ (Submodule.span ℝ
            {v : EuclideanSpace ℝ (Idx n) | q1 n (fun i => v i) = 0})ᗮ := by
        intro v
        have h_decomp_S : ∀ (S : Submodule ℝ (EuclideanSpace ℝ (Idx n))),
            ∃ w ∈ S, v - w ∈ Sᗮ := by
          intro S
          have h_mem_sup : v ∈ S ⊔ Sᗮ := by
            rw [ Submodule.sup_orthogonal_of_hasOrthogonalProjection ]
            aesop
          rw [ Submodule.mem_sup ] at h_mem_sup
          obtain ⟨ y, hy, z, hz, rfl ⟩ := h_mem_sup
          exact ⟨ y, hy, by simpa using hz ⟩
        exact h_decomp_S _
      exact h_decomp v
    · constructor <;> intro h
      · exact Submodule.sup_orthogonal_of_hasOrthogonalProjection
      · convert h using 1
        constructor <;> intro h <;> rw [ Submodule.eq_top_iff' ] at * <;>
          simp_all +decide only [Submodule.mem_sup, Submodule.mem_orthogonal, implies_true]
        intro x
        obtain ⟨ y, hy, z, hz, h ⟩ := h ( WithLp.equiv 2 ( Idx n → ℝ ) |>.symm x )
        refine ⟨ fun i => y i, ?_, fun i => z i, ?_, ?_ ⟩
        · refine Submodule.span_induction ?_ ?_ ?_ ?_ hy
          · intro x_2 h_2
            simp_all only [WithLp.equiv_symm_apply, Set.mem_setOf_eq]
            exact h_2
          · exact show q1 n ( fun _ => 0 ) = 0 from by unfold q1; norm_num
          · exact fun x y hx hy hx' hy' => Submodule.add_mem _ hx' hy'
          · simp +decide [ kernelQ1, q1 ]
            simp +contextual [ mul_assoc, mul_comm, mul_left_comm ]
            simp +contextual [ ← Finset.mul_sum _ _ _ ]
        · intro u hu; specialize hz ( WithLp.equiv 2 ( Idx n → ℝ ) |>.symm u )
          simp_all +decide only [inner, WithLp.equiv_symm_apply]
          convert hz _ using 1
          · exact Finset.sum_congr rfl fun _ _ => mul_comm _ _
          · exact Submodule.subset_span hu
        · convert congr_arg ( fun f => ( WithLp.equiv 2 ( Idx n → ℝ ) ) f ) h using 1 <;>
            simp
  simpa [ eq_comm ] using Submodule.mem_sup.mp ( h_compl.symm ▸ Submodule.mem_top :
    x ∈ kernelQ1 n ⊔ kernelQ1Perp n )

/--
Lemma: The polynomial $P_{multi}$ is linear in $\lambda$.
-/
lemma P_multi_add (n : ℕ) (u v : Idx n → ℝ) (x : ZMod (q n)) :
    pMulti n (u + v) x = pMulti n u x + pMulti n v x := by
  unfold pMulti
  simp [Finset.sum_add_distrib, add_mul]

/--
Lemma: The unit sphere in the orthogonal complement is compact.
-/
lemma sphere_perp_compact (n : ℕ) : IsCompact (spherePerp n) := by
  rw [Metric.isCompact_iff_isClosed_bounded]
  constructor
  · -- Closed
    apply IsClosed.inter
    · -- kernelQ1Perp is closed
      haveI : FiniteDimensional ℝ (Idx n → ℝ) := by infer_instance
      exact (kernelQ1Perp n).complete_of_finiteDimensional.isClosed
    · -- sphere is closed
      have hcont : Continuous (fun lambda : Idx n → ℝ => dotProduct n lambda lambda) := by
        unfold dotProduct
        exact continuous_finsetSum _ (fun i _ => (continuous_apply i).mul (continuous_apply i))
      exact isClosed_eq hcont continuous_const
  · -- Bounded
    rw [isBounded_iff_forall_norm_le]
    use 1
    intro lambda hlambda
    have h_dot : dotProduct n lambda lambda = 1 := hlambda.2
    apply pi_norm_le_iff_of_nonneg (by norm_num) |>.2
    intro i
    rw [Real.norm_eq_abs]
    rw [← sq_le_one_iff_abs_le_one]
    rw [← h_dot]
    exact sq_le_dot_product n lambda i

/-
Lemma: `q1` is invariant under adding a vector from the kernel of `q1`.
-/
lemma q1_add_kernel (n : ℕ) (u v : Idx n → ℝ) (hu : u ∈ kernelQ1 n) :
    q1 n (u + v) = q1 n v := by
  convert Q_1_sum_sq n (u + v) using 1
  convert Q_1_sum_sq n v using 2
  by_cases h : (↑‹ℕ› : ZMod (q n)).val ∈ evalInterval n <;>
    simp_all +decide only [P_multi_add]
  · have := Q_1_eq_zero_iff n u |>.1 hu (↑‹ℕ› : ZMod (q n))
    simp_all +decide [ZMod.val_natCast, Nat.mod_eq_of_lt]
  · unfold Psi; aesop

lemma Q_2_add_kernel (n : ℕ) (u v : Idx n → ℝ) (hu : u ∈ kernelQ1 n) :
    q2 n (u + v) = q2 n v := by
  rw [q2_sum_sq, q2_sum_sq]
  refine Finset.sum_congr rfl fun x hx => ?_
  by_cases hx' : (x : ZMod (q n)).val ∈ evalInterval n <;>
    simp_all +decide only [P_multi_add]
  · have := Q_1_eq_zero_iff n u |>.1 hu (↑x : ZMod (q n))
    simp_all +decide [ZMod.val_natCast, Nat.mod_eq_of_lt]
  · unfold Psi; aesop

/-
Lemma: The Rayleigh quotient is invariant under adding a vector from the kernel of $q1$.
-/
lemma Ratio_add_kernel (n : ℕ) (u v : Idx n → ℝ) (hu : u ∈ kernelQ1 n) :
    Ratio n (u + v) = Ratio n v := by
  unfold Ratio; rw [ q1_add_kernel n u v hu, Q_2_add_kernel n u v hu ]

/-
Lemma: For any $\lambda$ with $q1(\lambda) > 0$, there exists $v \in \text{sphere\_perp}(n)$
such that $\text{Ratio}(n, \lambda) = \text{Ratio}(n, v)$.
-/
lemma exists_sphere_perp_ratio_eq (n : ℕ) (lambda : Idx n → ℝ) (hQ1 : q1 n lambda > 0) :
    ∃ v ∈ spherePerp n, Ratio n lambda = Ratio n v := by
  -- By `decomposition n lambda`, obtain `u ∈ kernelQ1 n`, `w ∈ kernelQ1Perp n`
  -- with `lambda = u + w`.
  obtain ⟨u, hu, w, hw, hw_eq⟩ : ∃ u ∈ kernelQ1 n, ∃ w ∈ kernelQ1Perp n, lambda = u + w :=
    decomposition n lambda
  have h_ratio_eq : Ratio n lambda = Ratio n w := by
    rw [ hw_eq, Ratio_add_kernel n u w hu ]
  obtain ⟨c, hc⟩ : ∃ c : ℝ, c > 0 ∧ dotProduct n (c • w) (c • w) = 1 := by
    have h_dot_pos : dotProduct n w w > 0 := by
      contrapose! hQ1
      rw [ hw_eq, q1_add_kernel n u w hu ]
      exact Q_1_eq_zero_iff n w |>.2 ( fun x hx => by
        have h_w_zero : ∀ i : Idx n, w i = 0 := by
          intro i
          have h_sq := sq_le_dot_product n w i
          have h_le : (w i) ^ 2 ≤ 0 := le_trans h_sq hQ1
          exact sq_eq_zero_iff.mp ( le_antisymm h_le ( sq_nonneg _ ) )
        unfold pMulti; simp +decide [ h_w_zero ] ; ) |> le_of_eq
    use 1 / Real.sqrt (dotProduct n w w)
    simp_all +decide [ dotProduct, mul_left_comm, mul_comm ]
    simp +decide [ ← mul_assoc, ← Finset.sum_mul ]
    grind +revert
  use c • w
  have hc_ne : c ≠ 0 := hc.1.ne'
  refine ⟨ ⟨ Submodule.smul_mem _ _ hw, hc.2 ⟩, ?_ ⟩
  rw [ h_ratio_eq, Ratio_scale n w c hc_ne ]

/-
Lemma: The set of attainable ratios is the image of the unit sphere in the orthogonal complement
under the Rayleigh quotient map.
-/
lemma attainable_ratios_eq_image_sphere_perp (n : ℕ) :
    attainableRatios n = (spherePerp n).image (Ratio n) := by
  ext r; constructor
  · rintro ⟨ lambda, hq1, rfl ⟩
    obtain ⟨ v, hv, hv' ⟩ := exists_sphere_perp_ratio_eq n lambda hq1; use v; aesop
  · simp +zetaDelta only [Set.mem_image, forall_exists_index, and_imp] at *
    exact fun x hx hr => ⟨ x, Q_1_pos_on_sphere_perp n x hx, hr.symm ⟩

/-
Lemma: The set of attainable ratios is compact.
-/
lemma attainable_ratios_compact (n : ℕ) : IsCompact (attainableRatios n) := by
  rw [attainable_ratios_eq_image_sphere_perp]
  have h_cont : ContinuousOn (fun l => q2 n l / q1 n l) (spherePerp n) := by
    refine ContinuousOn.div ?_ ?_ ?_
    · refine Continuous.continuousOn ?_
      exact continuous_finsetSum _ fun _ _ => continuous_finsetSum _ fun _ _ =>
        Continuous.mul (Continuous.mul (continuous_apply _) continuous_const) (continuous_apply _)
    · refine Continuous.continuousOn ?_
      unfold q1; continuity
    · exact fun x hx => ne_of_gt (Q_1_pos_on_sphere_perp n x hx)
  refine IsCompact.image_of_continuousOn (sphere_perp_compact n) ?_
  refine h_cont.congr fun l hl => ?_
  unfold Ratio; aesop

/-
Lemma: The minimum attainable ratio is attained by some coefficient vector $\lambda$.
-/
lemma exists_minimizer (n : ℕ) :
    ∃ lambda : Idx n → ℝ, q1 n lambda > 0 ∧ Ratio n lambda = muMin n := by
  have h_nonempty : attainableRatios n ≠ ∅ := by
    obtain ⟨lambda, hlambda⟩ : ∃ lambda : Idx n → ℝ, q1 n lambda > 0 := by
      exact Exists.elim (Q_1_not_zero n) fun x hx =>
        ⟨x, lt_of_le_of_ne (Q_1_nonneg n x) (Ne.symm hx)⟩
    exact Set.Nonempty.ne_empty ⟨_, ⟨lambda, hlambda, rfl⟩⟩
  obtain ⟨r, hr⟩ : ∃ r ∈ attainableRatios n, r = muMin n := by
    refine ⟨_, IsCompact.sInf_mem (attainable_ratios_compact n) ?_, rfl⟩
    exact Set.nonempty_iff_ne_empty.mpr h_nonempty
  obtain ⟨lambda, hq1, hratio⟩ := hr.1
  use lambda
  refine ⟨hq1, ?_⟩
  rw [← hratio, hr.2]

/--
Define the optimal coefficient vector $\lambda_{opt}$ which attains the minimum ratio.
-/
noncomputable def lambdaOpt (n : ℕ) : Idx n → ℝ :=
  (exists_minimizer n).choose

/--
Properties of the optimal coefficient vector.
-/
lemma lambda_opt_spec (n : ℕ) :
    q1 n (lambdaOpt n) > 0 ∧ Ratio n (lambdaOpt n) = muMin n :=
  (exists_minimizer n).choose_spec

/--
Define the optimal truly multidimensional weight function $W_{opt}$.
-/
noncomputable def wOpt (n : ℕ) : ZMod (q n) → ℝ :=
  wTrulyMulti n (lambdaOpt n)

/-
Theorem: The optimal weight function satisfies the Krafft Sufficiency condition if and only if
$\mu_{min}(n) < 1$.
-/
theorem W_opt_is_sufficient_iff (n : ℕ) :
    (sum2 n (wOpt n) < sum1 n (wOpt n)) ↔ muMin n < 1 := by
  by_cases hn : n = 0 <;> simp_all +decide only [wOpt]
  · subst hn
    unfold sum1 sum2 wTrulyMulti
    norm_num [Finset.sum_range_succ, evalInterval]
    unfold q c pMulti
    norm_num [Finset.sum_range_succ, Finset.sum_range_zero]
    unfold g
    norm_num [Finset.sum_range_succ, Finset.prod_range_succ, primeWindow]
    have hIcc : (Finset.Icc 0 3 : Finset ℕ) = {0, 1, 2, 3} := rfl
    rw [hIcc, Finset.sum_insert, Finset.sum_insert, Finset.sum_insert] <;>
      norm_num [Finset.prod_filter, Finset.prod_range_succ, Finset.sum_range_succ, basisCos]
    constructor <;> intro h <;> contrapose! h
    · have := lambda_opt_spec 0
      norm_num at this
      unfold Ratio at this
      unfold q2 at this
      norm_num at this
      unfold matrix2 at this
      unfold c at this
      unfold g at this
      norm_num at this
      linarith
    · have := lambda_opt_spec 0
      have h_empty_set : (Finset.univ : Finset (Finset (Fin (w 0)))) = {∅} := rfl
      have h_opt_0 : lambdaOpt 0 = 0 := by
        ext i
        fin_cases i
        norm_num [h_empty_set] at *
        nlinarith
      norm_num [h_opt_0] at this
      unfold q1 at this
      norm_num at this
  · rw [S_1_eq_Q_1_pos n (Nat.pos_of_ne_zero hn) (lambdaOpt n),
        S_2_eq_Q_2_pos n (Nat.pos_of_ne_zero hn) (lambdaOpt n)]
    have := lambda_opt_spec n
    unfold Ratio at this
    rw [← this.2, if_neg this.1.ne']
    rw [div_lt_one this.1]

/--
Helper lemma: The hit count function c is non-negative everywhere.
-/
lemma c_nonneg (n : ℕ) (x : ZMod (q n)) : c n x ≥ 0 := by
  unfold c g
  refine Finset.sum_nonneg fun i _ ↦ ?_
  split_ifs <;> norm_num

/--
Definition: The sieve projection is full rank if the mapping from
coefficients to spatial vectors on ZMod (q n) is surjective.
-/
def IsFullRank (n : ℕ) : Prop :=
  ∀ v : ZMod (q n) → ℝ, ∃ lambda : Finset (Fin (w n)) → ℝ,
    ∀ x : ZMod (q n), pMulti n lambda x = v x

/--
Helper: a sum of `f` over the casts of `Finset.range m` equals the sum of `f` over all
of `ZMod m` (the casting map `range m → ZMod m` is a bijection when `m ≠ 0`).
-/
private lemma sum_range_zmod (m : ℕ) [NeZero m] (f : ZMod m → ℝ) :
    ∑ x ∈ Finset.range m, f (x : ZMod m) = ∑ y : ZMod m, f y := by
  apply Finset.sum_nbij' (i := fun x : ℕ => (x : ZMod m)) (j := fun y : ZMod m => y.val)
  · intro a _; exact Finset.mem_univ _
  · intro a _; simp [Finset.mem_range, ZMod.val_lt]
  · intro a ha; simp only [Finset.mem_range] at ha; exact ZMod.val_natCast_of_lt ha
  · intro a _; simp [ZMod.natCast_val, ZMod.cast_id]
  · intro a _; rfl

/-
Theorem: If the sieve is full rank and there exists a twin prime in A_n,
then the minimum sieve quotient muMin n is exactly 0.
-/
theorem muMin_eq_zero_of_fullRank_and_twinPrime (n : ℕ)
    (h_rank : IsFullRank n)
    (h_tp : ∃ x_0 ∈ evalInterval n, c n (x_0 : ZMod (q n)) = 0) :
    muMin n = 0 := by
  -- We show 0 is attainable using h_tp and h_rank by constructing lambda with
  -- q1 n lambda = 1 and q2 n lambda = 0.
  have h0_in_attainable : (0 : ℝ) ∈ attainableRatios n := by
    obtain ⟨x_0, hx0_mem, hx0_c⟩ := h_tp
    let v : ZMod (q n) → ℝ := fun y => if y = (x_0 : ZMod (q n)) then 1 else 0
    obtain ⟨lambda, hlam⟩ := h_rank v
    have hv_x0 : v (↑x_0 : ZMod (q n)) = 1 := by simp [v]
    have hv_ne_x0 : ∀ y : ZMod (q n), y ≠ (x_0 : ZMod (q n)) → v y = 0 := by
      exact fun y hy => if_neg hy
    have hPsi_x0 : Psi n (↑x_0 : ZMod (q n)) = 1 := by
      unfold Psi
      rw [if_pos]
      by_cases hn : n = 0
      · subst hn
        have hq0 : q 0 = 1 := rfl
        have hval0 : (x_0 : ZMod (q 0)).val = 0 := by
          rw [hq0, Subsingleton.elim (x_0 : ZMod 1) 0, ZMod.val_zero]
        rw [hval0]
        exact Finset.mem_Icc.mpr ⟨le_refl 0, by decide⟩
      · have hn_pos : 0 < n := Nat.pos_of_ne_zero hn
        have hq_bound := q_bound n hn_pos
        have hx0_lt : x_0 < q n := by
          have hx0_le : x_0 ≤ 6 * n ^ 2 + 10 * n + 3 := (Finset.mem_Icc.mp hx0_mem).2
          exact lt_of_le_of_lt hx0_le hq_bound
        rw [ZMod.val_natCast_of_lt hx0_lt]
        exact hx0_mem
    have hq1 : q1 n lambda = 1 := by
      have hq1 : q1 n lambda = ∑ y : ZMod (q n), (pMulti n lambda y)^2 * Psi n y := by
        convert Q_1_sum_sq n lambda using 1
        convert sum_range_zmod (q n) _ |> Eq.symm using 1
      rw [hq1, Finset.sum_eq_single (x_0 : ZMod (q n))] <;> aesop
    have hq2 : q2 n lambda = 0 := by
      convert q2_sum_sq n lambda using 1
      rw [Finset.sum_eq_single x_0] <;> aesop
    have hRatio : Ratio n lambda = 0 := by
      unfold Ratio; aesop
    exact ⟨lambda, by linarith [hq1], hRatio.symm⟩
  refine le_antisymm ?_ ?_
  · have h_lb : ∀ r ∈ attainableRatios n, (0 : ℝ) ≤ r := by
      rintro _ ⟨lambda, hlambda_pos, rfl⟩
      unfold Ratio
      split_ifs with h
      · linarith
      · have h_nonneg : 0 ≤ q2 n lambda := by
          rw [q2_sum_sq]
          refine Finset.sum_nonneg fun _ _ => ?_
          refine mul_nonneg (mul_nonneg (c_nonneg n _) (sq_nonneg _)) ?_
          unfold Psi; split_ifs <;> norm_num
        exact div_nonneg h_nonneg hlambda_pos.le
    exact csInf_le ⟨0, h_lb⟩ h0_in_attainable
  · apply le_csInf
    · exact ⟨_, h0_in_attainable⟩
    · rintro _ ⟨lambda, hlambda_pos, rfl⟩
      unfold Ratio
      split_ifs with h
      · linarith
      · have h_nonneg : 0 ≤ q2 n lambda := by
          rw [q2_sum_sq]
          refine Finset.sum_nonneg fun _ _ => ?_
          refine mul_nonneg (mul_nonneg (c_nonneg n _) (sq_nonneg _)) ?_
          unfold Psi; split_ifs <;> norm_num
        exact div_nonneg h_nonneg hlambda_pos.le

/--
Theorem: The Krafft Sieve Guarantee holds if $\mu_{min}(n) < 1$.
-/
theorem krafft_sieve_guarantee_with_mu_min (n : ℕ) (h : muMin n < 1) :
    ∃ x ∈ evalInterval n, Nat.Prime (6 * x - 1) ∧ Nat.Prime (6 * x + 1) := by
  have := mu_min_lt_one_implies_sufficiency n h
  by_cases hn : n ≥ 1 <;> simp_all +decide only [KrafftSufficiency, ge_iff_le, not_le,
    Nat.lt_one_iff]
  obtain ⟨ W, hW₁, hW₂, hW₃ ⟩ := this
  apply krafft_sieve_guarantee n hn ⟨ W, hW₁, hW₂, hW₃ ⟩

end

end KrafftSieve
