/-
Copyright (c) 2026 Fernando Portela. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Fernando Portela
-/

/-
Portions of this file were generated by Aristotle (https://aristotle.harmonic.fun).

Lean version: leanprover/lean4:v4.28.0
Mathlib version: 8f9d9cff6bd728b17a24e163c9402775d9e6a365

To cite Aristotle, tag @Aristotle-Harmonic on GitHub PRs/issues, and add as co-author to commits:
Co-authored-by: Aristotle (Harmonic) <aristotle-harmonic@harmonic.fun>
-/

import Mathlib.Analysis.InnerProductSpace.Reproducing
import Mathlib.Analysis.InnerProductSpace.l2Space
import Mathlib.MeasureTheory.Function.L2Space
import KrafftSieve.RKHSLimitAux

/-!
# RKHS Limits and Mercer's Theorem

This file formalizes the Reproducing Kernel Hilbert Space (RKHS) projection limit
sequence as $n \to \infty$ and states Mercer's spectral theorem for vector-valued RKHS.
-/

open MeasureTheory Matrix HilbertBasis RKHS InnerProductSpace Topology

variable {𝕜 : Type*} [RCLike 𝕜]
variable {X : Type*} [TopologicalSpace X] [CompactSpace X] [MeasurableSpace X] [BorelSpace X]
variable {V : Type*} [NormedAddCommGroup V] [InnerProductSpace 𝕜 V] [CompleteSpace V]
variable {H : Type*} [NormedAddCommGroup H] [InnerProductSpace 𝕜 H] [CompleteSpace H]
variable [RKHS 𝕜 H X V]
variable (μ : Measure X) [IsFiniteMeasure μ]

-- The continuity assumption wrapped as a Fact
variable [hK : Fact (Continuous (fun (p : X × X) ↦ kernel H p.1 p.2))]

-- The integral operator as a continuous linear map from L^2 to L^2
def integralOperator : Lp V 2 μ →L[𝕜] Lp V 2 μ := sorry

/--
The continuous Rayleigh quotient of a function in L^2.
-/
noncomputable def continuousRatio (c_cont : X → ℝ) (Psi_cont : X → ℝ) (f : Lp ℝ 2 μ) : ℝ :=
  let num := ∫ x, c_cont x * (f : X → ℝ) x ^ 2 * Psi_cont x ∂μ
  let den := ∫ x, (f : X → ℝ) x ^ 2 * Psi_cont x ∂μ
  if den = 0 then 0 else num / den

omit [TopologicalSpace X] [CompactSpace X] [BorelSpace X] [IsFiniteMeasure μ] in
/-- The square of the `L²` indicator of `s` (with value `1`) equals `s.indicator 1` a.e. -/
lemma sq_indicatorConstLp_ae (s : Set X) (hs : MeasurableSet s) (hμs : μ s ≠ ⊤) :
    (fun x => ((MeasureTheory.indicatorConstLp 2 hs hμs (1 : ℝ) : X → ℝ) x) ^ 2)
      =ᵐ[μ] s.indicator (fun _ => (1 : ℝ)) := by
  have h_indicator : (indicatorConstLp 2 hs hμs 1 : X → ℝ)
      =ᵐ[μ] (s.indicator (fun _ => (1 : ℝ))) :=
    MeasureTheory.indicatorConstLp_coeFn
  filter_upwards [h_indicator] with x hx using by by_cases hx' : x ∈ s <;> simp_all

omit [TopologicalSpace X] [CompactSpace X] [BorelSpace X] [IsFiniteMeasure μ] in
/-- `c_cont * (indicator of `s`, value `1`)²` equals `s.indicator c_cont` a.e. -/
lemma mul_sq_indicatorConstLp_ae (c_cont : X → ℝ) (s : Set X) (hs : MeasurableSet s)
    (hμs : μ s ≠ ⊤) :
    (fun x => c_cont x * ((MeasureTheory.indicatorConstLp 2 hs hμs (1 : ℝ) : X → ℝ) x) ^ 2)
      =ᵐ[μ] s.indicator c_cont := by
  filter_upwards [sq_indicatorConstLp_ae μ s hs hμs] with x hx
  by_cases hx' : x ∈ s <;> simp_all [Set.indicator]
  cases hx <;> simp [*]

/--
Theorem: There exists a continuous test function in L^2 whose continuous
Rayleigh quotient is strictly less than 1.
-/
theorem exists_continuous_ratio_lt_one (c_cont : X → ℝ) (Psi_cont : X → ℝ)
    [Fact (Continuous Psi_cont)]
    (h_dip : ∃ s : Set X, MeasurableSet s ∧ 0 < ∫ x in s, Psi_cont x ∂μ ∧
      ∀ x ∈ s, c_cont x < 1) :
    ∃ f : Lp ℝ 2 μ, (0 : ℝ) < ∫ x, (f : X → ℝ) x ^ 2 * Psi_cont x ∂μ ∧
      continuousRatio μ c_cont Psi_cont f < 1 := by
  revert h_dip c_cont Psi_cont
  by_contra! h_contra
  obtain ⟨c_cont, Psi_cont, hPsi, ⟨s, hs_meas, hs_pos, hc⟩, h⟩ := h_contra
  obtain ⟨A, hA_meas, hA_pos, hA_subset⟩ : ∃ A : Set X, MeasurableSet A ∧
      0 < ∫ x in A, Psi_cont x ∂μ ∧
      (∀ x ∈ A, c_cont x < 1 ∧ 0 < Psi_cont x) := by
    refine ⟨s ∩ { x | 0 < Psi_cont x },
      hs_meas.inter (measurableSet_lt measurable_const hPsi.1.measurable),
      ?_, ?_⟩
    · have h_split : ∫ x in s, Psi_cont x ∂μ =
          (∫ x in s ∩ {x | 0 < Psi_cont x}, Psi_cont x ∂μ) +
          (∫ x in s ∩ {x | Psi_cont x ≤ 0}, Psi_cont x ∂μ) := by
        rw [← MeasureTheory.setIntegral_union]
        · congr with x; by_cases hx : 0 < Psi_cont x <;> aesop
        · grind +splitIndPred
        · exact hs_meas.inter (measurableSet_le hPsi.1.measurable measurable_const)
        · exact (hPsi.1.integrable_of_hasCompactSupport
            (HasCompactSupport.of_compactSpace _)).integrableOn
        · exact (hPsi.1.integrable_of_hasCompactSupport
            (HasCompactSupport.of_compactSpace _)).integrableOn
      have h_nonpos : ∫ x in s ∩ {x | Psi_cont x ≤ 0}, Psi_cont x ∂μ ≤ 0 := by
        refine MeasureTheory.setIntegral_nonpos
          (hs_meas.inter (measurableSet_le hPsi.1.measurable measurable_const)) ?_
        intro x hx
        exact hx.2
      linarith [show ∫ x in s ∩ {x | Psi_cont x ≤ 0}, Psi_cont x ∂μ ≤ 0 by exact h_nonpos]
    · exact fun x hx => ⟨hc x hx.1, hx.2⟩
  have h_ne_top := MeasureTheory.measure_ne_top μ A
  obtain ⟨f, hf⟩ : ∃ f : Lp ℝ 2 μ,
      ∫ x, (f : X → ℝ) x ^ 2 * Psi_cont x ∂μ = ∫ x in A, Psi_cont x ∂μ ∧
      ∫ x, c_cont x * (f : X → ℝ) x ^ 2 * Psi_cont x ∂μ = ∫ x in A, c_cont x * Psi_cont x ∂μ := by
    refine ⟨MeasureTheory.indicatorConstLp 2 hA_meas h_ne_top 1, ?_, ?_⟩
    · rw [← MeasureTheory.integral_indicator] <;> norm_num [Set.indicator, hA_meas]
      rw [MeasureTheory.integral_congr_ae]
      filter_upwards [sq_indicatorConstLp_ae μ A hA_meas h_ne_top] with x hx using by aesop
    · rw [← MeasureTheory.integral_indicator hA_meas]
      refine MeasureTheory.integral_congr_ae ?_
      filter_upwards [mul_sq_indicatorConstLp_ae μ c_cont A hA_meas h_ne_top] with x hx
      by_cases hx' : x ∈ A <;> simp_all +decide [Set.indicator]
  specialize h f
  simp_all +decide only [continuousRatio, forall_const]
  split_ifs at h <;> try linarith
  rw [le_div_iff₀ hA_pos] at h
  have h_integral_lt : ∫ x in A, (Psi_cont x - c_cont x * Psi_cont x) ∂μ > 0 := by
    rw [gt_iff_lt, MeasureTheory.integral_pos_iff_support_of_nonneg_ae]
    · refine lt_of_lt_of_le ?_ (MeasureTheory.measure_mono
        (fun x (hx : x ∈ A) => ne_of_gt (sub_pos.mpr
          (mul_lt_of_lt_one_left (hA_subset x hx).2 (hA_subset x hx).1))))
      contrapose! hA_pos
      aesop
    · filter_upwards [MeasureTheory.ae_restrict_mem hA_meas] with x hx using
        sub_nonneg_of_le (mul_le_of_le_one_left (le_of_lt (hA_subset x hx |>.2))
          (le_of_lt (hA_subset x hx |>.1)))
    · refine MeasureTheory.Integrable.sub ?_ ?_
      · exact (by
          by_contra h
          rw [MeasureTheory.integral_undef h] at hA_pos
          norm_num at hA_pos)
      · exact (by
          by_contra h
          rw [MeasureTheory.integral_undef h] at *
          linarith)
  rw [MeasureTheory.integral_sub] at h_integral_lt
  · linarith
  · by_contra hni; rw [MeasureTheory.integral_undef hni] at hA_pos; norm_num at hA_pos
  · contrapose! h_integral_lt
    rw [MeasureTheory.integral_undef h_integral_lt] at h; linarith

/--
The continuous bilinear form associated with the weighted L^2 inner product.
-/
noncomputable def weightedBilinearForm (c : X → ℝ) [Fact (Continuous c)] :
    Lp ℝ 2 μ →L[ℝ] Lp ℝ 2 μ →L[ℝ] ℝ :=
  LinearMap.mkContinuous₂ (weightedBilinearFormLin μ c)
    (weightedBilinearForm_exists_bound μ c).choose
    (weightedBilinearForm_exists_bound μ c).choose_spec

omit [IsFiniteMeasure μ] in
theorem weightedBilinearForm_apply (c : X → ℝ) [Fact (Continuous c)] (g h : Lp ℝ 2 μ) :
    weightedBilinearForm μ c g h = ∫ x, c x * (g : X → ℝ) x * (h : X → ℝ) x ∂μ := by
  simp only [weightedBilinearForm, LinearMap.mkContinuous₂_apply, weightedBilinearFormLin_apply]

/-
Theorem: The quadratic form `g ↦ ∫ x, c x * g(x)^2` is continuous on L^2.
-/
omit [IsFiniteMeasure μ] in
theorem quadratic_form_continuous (c : X → ℝ) [Fact (Continuous c)] (f : Lp ℝ 2 μ) :
    ContinuousAt (fun g : Lp ℝ 2 μ ↦ ∫ x, c x * (g : X → ℝ) x ^ 2 ∂μ) f := by
  have h_eq : (fun g : Lp ℝ 2 μ ↦ ∫ x, c x * (g : X → ℝ) x ^ 2 ∂μ) =
      (fun g ↦ weightedBilinearForm μ c g g) := by
    ext g
    have h_apply := weightedBilinearForm_apply μ c g g
    simp only [h_apply]
    congr 1
    ext x
    ring
  rw [h_eq]
  exact ContinuousAt.clm_apply
    (weightedBilinearForm μ c).continuous.continuousAt continuous_id.continuousAt

/-
Theorem: The continuous Rayleigh quotient is continuous at any function in L^2
with positive windowed norm.
-/
omit [IsFiniteMeasure μ] in
theorem continuousRatio_continuous (c_cont : X → ℝ) [Fact (Continuous c_cont)]
    (Psi_cont : X → ℝ) [Fact (Continuous Psi_cont)]
    (f : Lp ℝ 2 μ) (hf : (∫ x, (f : X → ℝ) x ^ 2 * Psi_cont x ∂μ) > 0) :
    ContinuousAt (fun g : Lp ℝ 2 μ ↦ continuousRatio μ c_cont Psi_cont g) f := by
  haveI : Fact (Continuous fun x => c_cont x * Psi_cont x) :=
    ⟨(Fact.out : Continuous c_cont).mul (Fact.out : Continuous Psi_cont)⟩
  -- Continuity of the denominator `g ↦ ∫ (g x)² · Psi_cont x`.
  have hden : ContinuousAt
      (fun g : Lp ℝ 2 μ => ∫ x, (g : X → ℝ) x ^ 2 * Psi_cont x ∂μ) f := by
    convert quadratic_form_continuous μ Psi_cont f using 1
    ac_rfl
  -- Continuity of the numerator `g ↦ ∫ c_cont x · (g x)² · Psi_cont x`.
  have hnum : ContinuousAt
      (fun g : Lp ℝ 2 μ => ∫ x, c_cont x * (g : X → ℝ) x ^ 2 * Psi_cont x ∂μ) f := by
    convert quadratic_form_continuous μ (fun x => c_cont x * Psi_cont x) f using 1
    ac_rfl
  -- Their quotient is continuous at `f` since the denominator is nonzero there.
  have hdiv : ContinuousAt (fun g : Lp ℝ 2 μ =>
      (∫ x, c_cont x * (g : X → ℝ) x ^ 2 * Psi_cont x ∂μ)
        / (∫ x, (g : X → ℝ) x ^ 2 * Psi_cont x ∂μ)) f :=
    hnum.div hden (ne_of_gt hf)
  -- Near `f` the denominator stays positive, so `continuousRatio` agrees with the quotient.
  refine hdiv.congr ?_
  filter_upwards [hden.eventually (lt_mem_nhds hf)] with g hg
  unfold continuousRatio
  aesop


/-- Mercer's Theorem (Refined with Tjeerd's feedback): -/
theorem mercer_theorem :
    ∃ (ι : Type*) (_ : Countable ι)
      (b : HilbertBasis ι 𝕜 (Lp V 2 μ))
      (σ : ι → ℝ),
      (∀ i, 0 ≤ σ i) ∧
      -- The basis elements are eigenfunctions of the integral operator
      (∀ i, (integralOperator μ : Lp V 2 μ →L[𝕜] Lp V 2 μ) (b i) = (σ i : 𝕜) • (b i)) ∧
      -- The kernel decomposition holds in the RKHS (using evaluation)
      -- (where φ_i is the representation of b_i in the RKHS)
      (∀ (x y : X) (v : V),
        kernel H x y v = ∑' i, (σ i : 𝕜) • ⟪v, (b i : X → V) y⟫_𝕜 • (b i : X → V) x) := by
  sorry

-- Sequence of RKHS spaces indexed by sieve parameter n
variable (H_seq : ℕ → Type*)
variable [∀ i, NormedAddCommGroup (H_seq i)] [∀ i, InnerProductSpace 𝕜 (H_seq i)]
variable [∀ i, CompleteSpace (H_seq i)] [∀ i, RKHS 𝕜 (H_seq i) X V]

-- Inclusion maps from each RKHS into L^2
variable (coeCLM : ∀ i, H_seq i →L[𝕜] Lp V 2 μ)

-- Projection operators onto each RKHS space
variable (projectionToRKHS : ∀ i, Lp V 2 μ →L[𝕜] H_seq i)

omit [TopologicalSpace X] [CompactSpace X] [BorelSpace X] [CompleteSpace V] [IsFiniteMeasure μ]
  [∀ (i : ℕ), CompleteSpace (H_seq i)] [(i : ℕ) → RKHS 𝕜 (H_seq i) X V] in
/-- Best-approximation property: if `coeCLM i (projectionToRKHS i g) - g` is orthogonal to
the whole range of `coeCLM i`, then `coeCLM i (projectionToRKHS i f)` is the closest point to
`f` in that range, so its distance to `f` is at most that of any `coeCLM i h`. -/
theorem best_approximation_le
    (h_orthogonal : ∀ i (g : Lp V 2 μ) (h : H_seq i),
      ⟪coeCLM i (projectionToRKHS i g) - g, coeCLM i h⟫_𝕜 = 0)
    (f : Lp V 2 μ) (i : ℕ) (h : H_seq i) :
    ‖coeCLM i (projectionToRKHS i f) - f‖ ≤ ‖coeCLM i h - f‖ := by
  have h_norm_sq : ‖coeCLM i (projectionToRKHS i f) - f‖ ^ 2 =
      ‖coeCLM i h - f‖ ^ 2 - ‖coeCLM i h - coeCLM i (projectionToRKHS i f)‖ ^ 2 := by
    simp_all only [@norm_sub_sq 𝕜, inner_sub_left]
    grind +suggestions
  exact le_of_pow_le_pow_left₀ (by norm_num) (norm_nonneg _)
    (h_norm_sq.le.trans (sub_le_self _ (sq_nonneg _)))

omit [TopologicalSpace X] [CompactSpace X] [BorelSpace X] [CompleteSpace V] [IsFiniteMeasure μ]
     [∀ (i : ℕ), CompleteSpace (H_seq i)] [(i : ℕ) → RKHS 𝕜 (H_seq i) X V] in
/-- Theorem: Strong convergence of the projected functions in L^2. -/
theorem projection_strong_convergence (f : Lp V 2 μ)
    (h_orthogonal : ∀ i (g : Lp V 2 μ) (h : H_seq i),
      ⟪coeCLM i (projectionToRKHS i g) - g, coeCLM i h⟫_𝕜 = 0)
    (h_mono : ∀ (i j : ℕ) (_ : i ≤ j) (x : H_seq i),
      ∃ y : H_seq j, coeCLM i x = coeCLM j y)
    (h_dense : ∀ (g : Lp V 2 μ) (ε : ℝ) (_ : 0 < ε),
      ∃ i, ∃ h : H_seq i, ‖coeCLM i h - g‖ < ε) :
    Filter.Tendsto (fun i ↦ ‖coeCLM i (projectionToRKHS i f) - f‖) Filter.atTop (nhds 0) := by
  rw [Metric.tendsto_nhds]
  intro ε ε_pos
  obtain ⟨i₀, h₀, hh₀⟩ := h_dense f ε ε_pos
  simp only [dist_eq_norm, Filter.eventually_atTop]
  refine ⟨i₀, fun j hj => lt_of_le_of_lt ?_ hh₀⟩
  obtain ⟨y, hy⟩ := h_mono i₀ j hj h₀
  have h_best : ‖coeCLM j (projectionToRKHS j f) - f‖ ≤ ‖coeCLM j y - f‖ :=
    best_approximation_le μ H_seq coeCLM projectionToRKHS h_orthogonal f j y
  simpa [hy] using h_best
