/-
Copyright (c) 2026 Fernando Portela. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Fernando Portela
-/

/-
Portions of this file were generated by Aristotle (https://aristotle.harmonic.fun).

Lean version: leanprover/lean4:v4.28.0
Mathlib version: 8f9d9cff6bd728b17a24e163c9402775d9e6a365

To cite Aristotle, tag @Aristotle-Harmonic on GitHub PRs/issues, and add as co-author to commits:
Co-authored-by: Aristotle (Harmonic) <aristotle-harmonic@harmonic.fun>
-/

import Mathlib.Analysis.InnerProductSpace.l2Space
import Mathlib.MeasureTheory.Function.L2Space

/-!
# Auxiliary lemmas for the weighted `L²` bilinear form

This file develops the machinery used to build `weightedBilinearForm` in `RKHSLimit.lean`,
namely the continuous bilinear form `(g, h) ↦ ∫ x, c x * g x * h x ∂μ` on `L²`, where `c` is a
continuous (hence bounded, as `X` is compact) weight.

It is kept separate from `RKHSLimit.lean` because it only needs the `L²`/integral API
and does not depend on the reproducing-kernel machinery.
-/

open MeasureTheory

variable {X : Type*} [TopologicalSpace X] [CompactSpace X] [MeasurableSpace X] [BorelSpace X]
variable (μ : Measure X) [IsFiniteMeasure μ]

/-
Auxiliary: for `g h ∈ L²` and `c` continuous (hence bounded, as `X` is compact),
the integrand `x ↦ c x * g x * h x` is integrable.
-/
omit [IsFiniteMeasure μ] in
lemma weightedIntegrand_integrable (c : X → ℝ) [Fact (Continuous c)] (g h : Lp ℝ 2 μ) :
    Integrable (fun x => c x * (g : X → ℝ) x * (h : X → ℝ) x) μ := by
  have h_integrable : MeasureTheory.Integrable (fun x => c x * (g x * h x)) μ := by
    have h_cont : Continuous c := (Fact.out : Continuous c)
    have h_bdd : ∃ C, ∀ x, |c x| ≤ C := by
      have h_univ : IsCompact (Set.univ : Set X) := CompactSpace.isCompact_univ
      have h_cont_on : ContinuousOn c Set.univ := h_cont.continuousOn
      obtain ⟨C, hC⟩ := IsCompact.exists_bound_of_continuousOn h_univ h_cont_on
      exact ⟨C, fun x => hC x trivial⟩
    apply MeasureTheory.Integrable.mono'
      (g := fun x => h_bdd.choose * (g x ^ 2 + h x ^ 2))
    · refine MeasureTheory.Integrable.const_mul ?_ _
      refine MeasureTheory.Integrable.add ?_ ?_
      · exact MeasureTheory.MemLp.integrable_sq (MeasureTheory.Lp.memLp g)
      · exact MeasureTheory.MemLp.integrable_sq (MeasureTheory.Lp.memLp _)
    · exact MeasureTheory.AEStronglyMeasurable.mul h_cont.aestronglyMeasurable
        (MeasureTheory.AEStronglyMeasurable.mul g.1.aestronglyMeasurable h.1.aestronglyMeasurable)
    · filter_upwards [] with x using by
        rw [Real.norm_eq_abs, abs_mul, abs_mul]
        have h_bdd_x := h_bdd.choose_spec x
        have h_abs_le : |c x| * (|g x| * |h x|) ≤ h_bdd.choose * (|g x| * |h x|) :=
          mul_le_mul_of_nonneg_right h_bdd_x (by positivity)
        have h_algebra : |g x| * |h x| ≤ g x ^ 2 + h x ^ 2 := by
          cases abs_cases (g x) <;> cases abs_cases (h x) <;>
            nlinarith [sq_nonneg (g x - h x), sq_nonneg (g x + h x)]
        have h_mul_le : h_bdd.choose * (|g x| * |h x|) ≤ h_bdd.choose * (g x ^ 2 + h x ^ 2) :=
          mul_le_mul_of_nonneg_left h_algebra (by linarith [abs_le.mp h_bdd_x])
        exact le_trans h_abs_le h_mul_le
  simpa only [mul_assoc] using h_integrable

/-
Additivity of the weighted integral in the left argument.
-/
omit [IsFiniteMeasure μ] in
lemma weightedBilinearForm_addLeft (c : X → ℝ) [Fact (Continuous c)] (g₁ g₂ h : Lp ℝ 2 μ) :
    (∫ x, c x * ((g₁ + g₂ : Lp ℝ 2 μ) : X → ℝ) x * (h : X → ℝ) x ∂μ)
      = (∫ x, c x * (g₁ : X → ℝ) x * (h : X → ℝ) x ∂μ)
        + ∫ x, c x * (g₂ : X → ℝ) x * (h : X → ℝ) x ∂μ := by
  rw [← MeasureTheory.integral_add]
  · rw [MeasureTheory.integral_congr_ae]
    have h_ae_eq : (fun x => (g₁ + g₂ : X → ℝ) x)
      =ᵐ[μ] (fun x => (g₁ : X → ℝ) x + (g₂ : X → ℝ) x) := by
      exact Filter.Eventually.of_forall fun x => rfl
    filter_upwards [h_ae_eq, MeasureTheory.Lp.coeFn_add g₁ g₂] with x hx₁ hx₂
    simp_all +decide [mul_add, add_mul]
  · exact weightedIntegrand_integrable μ c g₁ h
  · exact weightedIntegrand_integrable μ c g₂ h

/-
Homogeneity of the weighted integral in the left argument.
-/
omit [CompactSpace X] [BorelSpace X] [IsFiniteMeasure μ] in
lemma weightedBilinearForm_smulLeft (c : X → ℝ) [Fact (Continuous c)] (a : ℝ) (g h : Lp ℝ 2 μ) :
    (∫ x, c x * ((a • g : Lp ℝ 2 μ) : X → ℝ) x * (h : X → ℝ) x ∂μ)
      = a • ∫ x, c x * (g : X → ℝ) x * (h : X → ℝ) x ∂μ := by
  rw [← MeasureTheory.integral_smul]
  rw [MeasureTheory.integral_congr_ae]
  filter_upwards [MeasureTheory.Lp.coeFn_smul a g] with x hx using by
    simp +decide [hx, mul_assoc, mul_left_comm]

/-
Additivity of the weighted integral in the right argument.
-/
omit [IsFiniteMeasure μ] in
lemma weightedBilinearForm_addRight (c : X → ℝ) [Fact (Continuous c)] (g h₁ h₂ : Lp ℝ 2 μ) :
    (∫ x, c x * (g : X → ℝ) x * ((h₁ + h₂ : Lp ℝ 2 μ) : X → ℝ) x ∂μ)
      = (∫ x, c x * (g : X → ℝ) x * (h₁ : X → ℝ) x ∂μ)
        + ∫ x, c x * (g : X → ℝ) x * (h₂ : X → ℝ) x ∂μ := by
  rw [← MeasureTheory.integral_add]
  · refine MeasureTheory.integral_congr_ae ?_
    filter_upwards [MeasureTheory.Lp.coeFn_add h₁ h₂] with x hx
    simp only [hx, Pi.add_apply]; ring
  · exact weightedIntegrand_integrable μ c g h₁
  · exact weightedIntegrand_integrable μ c g h₂

/-
Homogeneity of the weighted integral in the right argument.
-/
omit [CompactSpace X] [BorelSpace X] [IsFiniteMeasure μ] in
lemma weightedBilinearForm_smulRight (c : X → ℝ) [Fact (Continuous c)] (a : ℝ) (g h : Lp ℝ 2 μ) :
    (∫ x, c x * (g : X → ℝ) x * ((a • h : Lp ℝ 2 μ) : X → ℝ) x ∂μ)
      = a • ∫ x, c x * (g : X → ℝ) x * (h : X → ℝ) x ∂μ := by
  rw [← MeasureTheory.integral_smul]
  rw [MeasureTheory.integral_congr_ae]
  filter_upwards [MeasureTheory.Lp.coeFn_smul a h] with x hx using by
    simp +decide [hx, mul_assoc, mul_left_comm]

/-- The underlying (not-yet-continuous) bilinear map of the weighted `L²` form. -/
noncomputable def weightedBilinearFormLin (c : X → ℝ) [Fact (Continuous c)] :
    Lp ℝ 2 μ →ₗ[ℝ] Lp ℝ 2 μ →ₗ[ℝ] ℝ :=
  LinearMap.mk₂ ℝ (fun g h => ∫ x, c x * (g : X → ℝ) x * (h : X → ℝ) x ∂μ)
    (weightedBilinearForm_addLeft μ c)
    (weightedBilinearForm_smulLeft μ c)
    (weightedBilinearForm_addRight μ c)
    (weightedBilinearForm_smulRight μ c)

omit [IsFiniteMeasure μ] in
@[simp] lemma weightedBilinearFormLin_apply (c : X → ℝ) [Fact (Continuous c)] (g h : Lp ℝ 2 μ) :
    weightedBilinearFormLin μ c g h = ∫ x, c x * (g : X → ℝ) x * (h : X → ℝ) x ∂μ := rfl

/-
The weighted bilinear form is bounded: `|∫ c g h| ≤ C ‖g‖ ‖h‖` for some `C` (any bound
on `|c|`, which exists since `c` is continuous on the compact space `X`).
-/
omit [IsFiniteMeasure μ] in
lemma weightedBilinearForm_exists_bound (c : X → ℝ) [Fact (Continuous c)] :
    ∃ C : ℝ, ∀ g h : Lp ℝ 2 μ, ‖weightedBilinearFormLin μ c g h‖ ≤ C * ‖g‖ * ‖h‖ := by
  have h_def : ∀ g h : Lp ℝ 2 μ, (weightedBilinearFormLin μ c g h)
    = ∫ x, c x * (g : X → ℝ) x * (h : X → ℝ) x ∂μ := by
    intro g h; rfl
  obtain ⟨M, hM⟩ : ∃ M > 0, ∀ x, |c x| ≤ M := by
    have h_univ : IsCompact (Set.univ : Set X) := CompactSpace.isCompact_univ
    have h_cont : ContinuousOn c Set.univ := (Fact.out : Continuous c).continuousOn
    obtain ⟨M, hM⟩ := IsCompact.exists_bound_of_continuousOn h_univ h_cont
    exact ⟨Max.max M 1, by positivity, fun x => le_trans (hM x trivial) (le_max_left _ _)⟩
  have h_integral_bound : ∀ g h : Lp ℝ 2 μ,
      ‖∫ x, c x * (g : X → ℝ) x * (h : X → ℝ) x ∂μ‖
        ≤ M * ∫ x, |(g : X → ℝ) x| * |(h : X → ℝ) x| ∂μ := by
    intro g h; rw [← MeasureTheory.integral_const_mul]
    refine le_trans (MeasureTheory.norm_integral_le_integral_norm _) ?_
    refine MeasureTheory.integral_mono_of_nonneg ?_ ?_ ?_
    · exact Filter.Eventually.of_forall fun x => norm_nonneg _
    · refine MeasureTheory.Integrable.const_mul ?_ _
      apply MeasureTheory.Integrable.mono'
        (g := fun x => |(g : X → ℝ) x| ^ 2 + |(h : X → ℝ) x| ^ 2)
      · refine MeasureTheory.Integrable.add ?_ ?_
        · have := MeasureTheory.Lp.memLp g
          simpa using this.integrable_norm_pow (by norm_num)
        · have := MeasureTheory.Lp.memLp h
          simpa using this.integrable_norm_pow (by norm_num)
      · exact MeasureTheory.AEStronglyMeasurable.mul g.1.aestronglyMeasurable.norm
          h.1.aestronglyMeasurable.norm
      · filter_upwards [] with x using by
          simpa using by nlinarith only [abs_mul_abs_self (g x), abs_mul_abs_self (h x)]
    · filter_upwards [] with x using by
        simpa [mul_assoc, abs_mul] using mul_le_mul_of_nonneg_right (hM.2 x) (by positivity)
  have h_cauchy_schwarz : ∀ g h : Lp ℝ 2 μ,
      ∫ x, |(g : X → ℝ) x| * |(h : X → ℝ) x| ∂μ
        ≤ (∫ x, |(g : X → ℝ) x|^2 ∂μ)^(1/2 : ℝ) * (∫ x, |(h : X → ℝ) x|^2 ∂μ)^(1/2 : ℝ) := by
    intro g h
    have := @MeasureTheory.integral_mul_norm_le_Lp_mul_Lq
    convert @this X _ μ ℝ _ (fun x => (g : X → ℝ) x) (fun x => (h : X → ℝ) x) 2 2 _ _ _ using 1
      <;> norm_num
    · constructor <;> norm_num
    · exact MeasureTheory.Lp.memLp _
    · exact MeasureTheory.Lp.memLp _
  have h_norm : ∀ g : Lp ℝ 2 μ, (∫ x, |(g : X → ℝ) x|^2 ∂μ)^(1/2 : ℝ) = ‖g‖ := by
    intro g; rw [Lp.norm_def] ; norm_num [← Real.sqrt_eq_rpow]
    rw [eLpNorm_eq_lintegral_rpow_enorm_toReal] <;> norm_num
    rw [← ENNReal.toReal_rpow]
    rw [← Real.sqrt_eq_rpow, Real.sqrt_eq_rpow, ← MeasureTheory.integral_toReal]
    · norm_num [Real.sqrt_eq_rpow, ENNReal.toReal_pow]
    · exact (g.1.aemeasurable.enorm.pow_const _)
    · simp +decide
  exact ⟨M, fun g h => by
    simpa only [h_def, mul_assoc, h_norm] using
      le_trans (h_integral_bound g h) (mul_le_mul_of_nonneg_left (h_cauchy_schwarz g h) hM.1.le)⟩
