/-
Copyright (c) 2026 Fernando Portela. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Fernando Portela
-/

/-
Portions of this file were generated by Aristotle (https://aristotle.harmonic.fun).

Lean version: leanprover/lean4:v4.24.0
Mathlib version: f897ebcf72cd16f89ab4577d0c826cd14afaafc7

To cite Aristotle, tag @Aristotle-Harmonic on GitHub PRs/issues, and add as co-author to commits:
Co-authored-by: Aristotle (Harmonic) <aristotle-harmonic@harmonic.fun>
-/

import KrafftSieve.Turan_SelbergWeights

set_option linter.mathlibStandardSet false

open scoped BigOperators
open scoped Real
open scoped Nat
open scoped Classical
open scoped Pointwise

set_option maxHeartbeats 0
set_option maxRecDepth 4000
set_option synthInstance.maxHeartbeats 20000
set_option synthInstance.maxSize 128

set_option relaxedAutoImplicit false
set_option autoImplicit false

noncomputable section

/-
Define the basis function for the multidimensional weight as a product of cosines over a subset of primes.
-/
/--
Define the basis function for a subset of prime indices $S \subseteq \{1, \dots, w\}$.
The basis function is the product of the 3rd harmonic cosines for each prime in $S$.
$$ B_S(x) = \prod_{i \in S} \cos\left( \frac{6\pi x}{p_i} \right) $$
-/
noncomputable def basis_cos (n : ℕ) (S : Finset (Fin (w n))) (x : ZMod (q n)) : ℝ :=
  ∏ i ∈ S, Real.cos (2 * Real.pi * 3 * (x.val : ℝ) / (p n i : ℝ))

/-
Define the multidimensional polynomial P(x) as a sum over all subsets S of the basis functions B_S(x) weighted by lambda_S.
-/
/--
Define the multidimensional polynomial $P(x)$ as a linear combination of the basis functions $B_S(x)$ with coefficients $\lambda_S$.
$$ P(x) = \sum_{S \subseteq \{1, \dots, w\}} \lambda_S B_S(x) $$
-/
noncomputable def P_multi (n : ℕ) (lambda : Finset (Fin (w n)) → ℝ) (x : ZMod (q n)) : ℝ :=
  ∑ S ∈ Finset.univ.powerset, lambda S * basis_cos n S x

/-
Define the truly multidimensional weight function W_lambda(x) as the square of P(x) restricted to A_n.
-/
/--
Define the truly multidimensional weight function $W_{\lambda}(x)$ as the square of the polynomial $P(x)$ restricted to the interval $\mathcal{A}_n$.
$$ W_{\lambda}(x) = \begin{cases} (P(x))^2 & \text{if } x \in \mathcal{A}_n \\ 0 & \text{otherwise} \end{cases} $$
-/
noncomputable def W_truly_multi (n : ℕ) (lambda : Finset (Fin (w n)) → ℝ) (x : ZMod (q n)) : ℝ :=
  if x.val ∈ A_n n then (P_multi n lambda x) ^ 2 else 0

/-
Define the matrices M_1 and M_2 representing the quadratic forms of S_1 and S_2 in the basis B_S.
-/
/--
Define the matrix $M_1$ corresponding to the first moment $S_1$.
$M_1(S, T) = \sum_{x \in \mathcal{A}_n} B_S(x) B_T(x)$
-/
noncomputable def Matrix_1 (n : ℕ) (S T : Finset (Fin (w n))) : ℝ :=
  ∑ x ∈ A_n n, basis_cos n S (x : ZMod (q n)) * basis_cos n T (x : ZMod (q n))

/--
Define the matrix $M_2$ corresponding to the second moment $S_2$.
$M_2(S, T) = \sum_{x \in \mathcal{A}_n} c(x) B_S(x) B_T(x)$
-/
noncomputable def Matrix_2 (n : ℕ) (S T : Finset (Fin (w n))) : ℝ :=
  ∑ x ∈ A_n n, c n (x : ZMod (q n)) * basis_cos n S (x : ZMod (q n)) * basis_cos n T (x : ZMod (q n))

/-
Define the quadratic forms Q_1 and Q_2 corresponding to the matrices M_1 and M_2.
-/
/--
Define the quadratic form $Q_1(\lambda) = \lambda^T M_1 \lambda$.
-/
noncomputable def Q_1 (n : ℕ) (lambda : Finset (Fin (w n)) → ℝ) : ℝ :=
  ∑ S ∈ Finset.univ.powerset, ∑ T ∈ Finset.univ.powerset, lambda S * Matrix_1 n S T * lambda T

/--
Define the quadratic form $Q_2(\lambda) = \lambda^T M_2 \lambda$.
-/
noncomputable def Q_2 (n : ℕ) (lambda : Finset (Fin (w n)) → ℝ) : ℝ :=
  ∑ S ∈ Finset.univ.powerset, ∑ T ∈ Finset.univ.powerset, lambda S * Matrix_2 n S T * lambda T

/-
Define the Rayleigh quotient R(lambda) = Q_2(lambda) / Q_1(lambda).
-/
/--
Define the Rayleigh quotient $R(\lambda) = \frac{Q_2(\lambda)}{Q_1(\lambda)}$.
Defined to be $\infty$ if $Q_1(\lambda) = 0$ (though $Q_1$ is positive definite on non-zero $\lambda$ if the basis is linearly independent on $A_n$).
-/
noncomputable def Ratio (n : ℕ) (lambda : Finset (Fin (w n)) → ℝ) : ℝ :=
  if Q_1 n lambda = 0 then 0 else (Q_2 n lambda) / (Q_1 n lambda)

/-
Prove that W_truly_multi is non-negative everywhere.
-/
/--
The truly multidimensional weight function is non-negative everywhere.
-/
lemma W_truly_multi_nonneg (n : ℕ) (lambda : Finset (Fin (w n)) → ℝ) (x : ZMod (q n)) :
    W_truly_multi n lambda x ≥ 0 := by
      by_cases hx : x.val ∈ A_n n <;> simp_all +decide [ W_truly_multi ];
      exact sq_nonneg _

/-
Prove that W_truly_multi is supported on A_n.
-/
/--
The truly multidimensional weight function is supported on $\mathcal{A}_n$.
-/
lemma W_truly_multi_support (n : ℕ) (lambda : Finset (Fin (w n)) → ℝ) (x : ZMod (q n))
    (hx : x.val ∉ A_n n) :
    W_truly_multi n lambda x = 0 := by
      exact if_neg hx

/-
Prove that S_1 equals Q_1 for the truly multidimensional weight.
-/
/--
Lemma: The first moment $S_1$ of the truly multidimensional weight is equal to the quadratic form $Q_1$.
-/
lemma S_1_eq_Q_1 (n : ℕ) (lambda : Finset (Fin (w n)) → ℝ) :
    S_1 n (W_truly_multi n lambda) = Q_1 n lambda := by
      unfold Q_1 S_1 W_truly_multi P_multi; norm_cast;
      simp only [ZMod.val_natCast, Finset.powerset_univ];
      rw [ Finset.sum_congr rfl fun x hx => if_pos ?_ ];
      · simp +decide [ Matrix_1, sq, mul_comm, mul_left_comm, Finset.mul_sum _ _ _ ];
        rw [ Finset.sum_comm, Finset.sum_congr rfl fun _ _ => Finset.sum_comm ];
      · unfold A_n at *;
        rcases n with ( _ | _ | n ) <;> norm_num at *;
        · exact le_trans ( Nat.mod_le _ _ ) hx;
        · rcases hx with ⟨ hx₁, hx₂ ⟩ ; interval_cases x <;> native_decide;
        · -- Since $q(n+2)$ is the product of all primes up to $6(n+2)+1$, and $x$ is within the interval $[6(n+2)^2 - 2(n+2), 6(n+2)^2 + 10(n+2) + 3]$, we have $x < q(n+2)$.
          have h_x_lt_q : x < q (n + 2) := by
            have := q_bound ( n + 2 ) ( by linarith );
            linarith;
          rw [ Nat.mod_eq_of_lt h_x_lt_q ] ; aesop

/-
Prove that S_2 equals Q_2 for the truly multidimensional weight.
-/
/--
Lemma: The second moment $S_2$ of the truly multidimensional weight is equal to the quadratic form $Q_2$.
-/
lemma S_2_eq_Q_2 (n : ℕ) (lambda : Finset (Fin (w n)) → ℝ) :
    S_2 n (W_truly_multi n lambda) = Q_2 n lambda := by
      unfold Q_2 S_2 W_truly_multi;
      unfold P_multi Matrix_2; simp +decide [ Finset.sum_mul _ _ _, Finset.mul_sum ] ; ring_nf;
      simp +decide [ Finset.sum_ite, Finset.sum_mul _ _ _, Finset.mul_sum,
        mul_comm, mul_left_comm, pow_two ];
      rw [ ← Finset.sum_comm ] ; refine' Finset.sum_congr rfl fun x hx => _ ;
      rw [ ← Finset.sum_comm ] ; refine' Finset.sum_congr rfl fun y hy => _ ; ring_nf;
      refine' Finset.sum_subset _ _ <;> simp +contextual [ Finset.subset_iff ];
      intro z hz hz'; contrapose! hz'; simp_all only [Finset.mem_univ, ne_eq] ;
      rw [ Nat.mod_eq_of_lt ] ; exact hz;
      refine' lt_of_le_of_lt ( Finset.mem_Icc.mp hz |>.2 ) _;
      exact q_bound n ( Nat.pos_of_ne_zero ( by
        rintro rfl; exact absurd hz' ( by unfold c; aesop ) ) )

/-
Prove that if Q_2(lambda) < Q_1(lambda), then Krafft Admissibility holds.
-/
/--
Lemma: The existence of coefficients $\lambda$ such that $Q_2(\lambda) < Q_1(\lambda)$ is sufficient for Krafft Admissibility.
-/
lemma sufficiency_of_Q (n : ℕ) (lambda : Finset (Fin (w n)) → ℝ) (h : Q_2 n lambda < Q_1 n lambda) :
    Krafft_Admissibility n := by
      use W_truly_multi n lambda;
      exact ⟨ fun x => W_truly_multi_nonneg n lambda x, fun x hx => W_truly_multi_support n lambda x hx, by linarith [ S_1_eq_Q_1 n lambda, S_2_eq_Q_2 n lambda ] ⟩

/-
Define mu_min(n) as the infimum of the attainable Rayleigh quotients.
-/
/--
Define the set of attainable ratios.
-/
def attainable_ratios (n : ℕ) : Set ℝ :=
  { r | ∃ lambda : Finset (Fin (w n)) → ℝ, Q_1 n lambda > 0 ∧ r = Ratio n lambda }

/--
Define $\mu_{min}(n)$ as the infimum of the attainable ratios.
-/
noncomputable def mu_min (n : ℕ) : ℝ := sInf (attainable_ratios n)

/-
Prove that if mu_min(n) < 1, then Krafft Admissibility holds.
-/
/--
Theorem: If the minimum attainable ratio $\mu_{min}(n)$ is strictly less than 1, then the Krafft Admissibility condition holds.
-/
theorem mu_min_lt_one_implies_admissibility (n : ℕ) (h : mu_min n < 1) :
    Krafft_Admissibility n := by
      -- By definition of infimum, there exists a ratio $r$ in the attainable set such that $r < 1$.
      obtain ⟨r, hr⟩ : ∃ r ∈ attainable_ratios n, r < 1 := by
        contrapose! h;
        apply le_csInf;
        · refine' ⟨ _, ⟨ fun S => if S = ∅ then 1 else 0, _, rfl ⟩ ⟩ ; norm_num;
          unfold Q_1;
          unfold Matrix_1; norm_num [ Finset.sum_ite ] ;
          unfold basis_cos; norm_num;
          exact ⟨ 6 * n ^ 2 - 2 * n, Finset.mem_Icc.mpr ⟨ by nlinarith [ Nat.sub_add_cancel ( by nlinarith : 2 * n ≤ 6 * n ^ 2 ) ], by nlinarith [ Nat.sub_add_cancel ( by nlinarith : 2 * n ≤ 6 * n ^ 2 ) ] ⟩ ⟩;
        · assumption;
      obtain ⟨lambda, hlambda_pos, hlambda_ratio⟩ := hr.left;
      have h_ratio_lt_one : Q_2 n lambda < Q_1 n lambda := by
        -- By definition of Ratio, we have r = Q_2 n lambda / Q_1 n lambda.
        have h_ratio_def : r = Q_2 n lambda / Q_1 n lambda := by
          exact hlambda_ratio.trans ( if_neg hlambda_pos.ne' ) |> Eq.trans <| rfl;
        generalize_proofs at *; (
        rw [ eq_div_iff ] at h_ratio_def <;> nlinarith [ hr.2 ] ;);
      exact sufficiency_of_Q n lambda h_ratio_lt_one;

/-
Define Idx(n) as the power set of prime indices.
-/
/--
Abbreviation for the index set of the coefficients, which is the power set of prime indices.
-/
abbrev Idx (n : ℕ) := Finset (Fin (w n))

/-
Define the kernel of Q_1 as a submodule.
-/
/--
The kernel of the quadratic form $Q_1$.
-/
def kernel_Q1 (n : ℕ) : Submodule ℝ (Idx n → ℝ) :=
  { carrier := { lambda | Q_1 n lambda = 0 },
    add_mem' := by
      intros a b ha hb
      have h_sum : Q_1 n (a + b) = Q_1 n a + Q_1 n b + 2 * (∑ S ∈ Finset.univ.powerset, ∑ T ∈ Finset.univ.powerset, a S * Matrix_1 n S T * b T) := by
        unfold Q_1;
        simp +decide [ Finset.sum_add_distrib, mul_add, mul_comm, mul_left_comm ] ; ring_nf;
        norm_num [ mul_two, add_assoc, Finset.sum_add_distrib ];
        rw [ Finset.sum_comm ];
        exact Finset.sum_congr rfl fun _ _ =>
          Finset.sum_congr rfl fun _ _ => by
            rw [ show Matrix_1 n _ _ = Matrix_1 n _ _ from by unfold Matrix_1; ac_rfl ] ;
      have h_sum : Q_1 n (a - b) = Q_1 n a + Q_1 n b - 2 * (∑ S ∈ Finset.univ.powerset, ∑ T ∈ Finset.univ.powerset, a S * Matrix_1 n S T * b T) := by
        unfold Q_1; simp +decide [ sub_mul, mul_sub ] ; ring_nf;
        rw [ show ( ∑ x : Idx n, ∑ x_1 : Idx n,
          b x * Matrix_1 n x x_1 * a x_1 ) = ∑ x : Idx n, ∑ x_1 : Idx n,
          a x * Matrix_1 n x x_1 * b x_1 from ?_ ] ;
        ring;
        rw [ Finset.sum_comm ] ; congr ; ext ; congr ; ext ; ring_nf;
        unfold Matrix_1; simp +decide [ mul_assoc, mul_comm ] ;
      have h_nonneg : ∀ (lambda : Idx n → ℝ), Q_1 n lambda ≥ 0 := by
        intro lambda
        have h_sum : Q_1 n lambda = ∑ x ∈ A_n n, (P_multi n lambda (x : ZMod (q n)))^2 := by
          unfold Q_1 P_multi Matrix_1;
          simp +decide [ Finset.mul_sum _ _ _, Finset.sum_mul _ _ _, mul_comm, mul_left_comm, sq ];
          ring_nf;
          exact Eq.symm ( by rw [ Finset.sum_comm ] ; exact Finset.sum_congr rfl fun _ _ => Finset.sum_comm.trans ( Finset.sum_congr rfl fun _ _ => Finset.sum_congr rfl fun _ _ => by ring ) ) ;
        exact h_sum.symm ▸ Finset.sum_nonneg fun x hx => sq_nonneg _;
      grind,
    zero_mem' := by
      unfold Q_1; aesop;,
    smul_mem' := by
      -- By definition of $Q_1$, we know that $Q_1(c • x) = c^2 * Q_1(x)$.
      have hQ1_smul : ∀ (c : ℝ) (x : Idx n → ℝ), Q_1 n (c • x) = c^2 * Q_1 n x := by
        simp_all +decide [ Q_1, Matrix_1 ];
        exact fun c x => by rw [ Finset.mul_sum _ _ _ ] ; exact Finset.sum_congr rfl fun _ _ => by rw [ Finset.mul_sum _ _ _ ] ; exact Finset.sum_congr rfl fun _ _ => by ring;
      aesop }

/-
Prove that Q_1(lambda) = 0 iff P_multi(lambda, x) = 0 for all x in A_n.
-/
/--
Lemma: $Q_1(\lambda) = 0$ if and only if $P_{multi}(\lambda, x) = 0$ for all $x \in \mathcal{A}_n$.
-/
lemma Q_1_eq_zero_iff (n : ℕ) (lambda : Idx n → ℝ) :
    Q_1 n lambda = 0 ↔ ∀ x ∈ A_n n, P_multi n lambda x = 0 := by
      -- By definition of $Q_1$, we know that
      have hQ1_def : Q_1 n lambda = ∑ x ∈ A_n n, (P_multi n lambda x) ^ 2 := by
        unfold Q_1 P_multi;
        simp +decide [ Matrix_1, pow_two, mul_comm, mul_left_comm, Finset.mul_sum _ _ _ ];
        exact Eq.symm ( by
          rw [ Finset.sum_comm ] ;
          exact Finset.sum_congr rfl fun _ _ =>
            Finset.sum_comm.trans ( Finset.sum_congr rfl fun _ _ =>
              Finset.sum_congr rfl fun _ _ => by ring ) );
      simp_all +decide [ Finset.sum_eq_zero_iff_of_nonneg, sq_nonneg ]

/-
Prove that Q_1 is non-negative.
-/
/--
Lemma: $Q_1$ is non-negative for all $\lambda$.
-/
lemma Q_1_nonneg (n : ℕ) (lambda : Idx n → ℝ) : Q_1 n lambda ≥ 0 := by
  -- By definition of $Q_1$, we know that $Q_1 n lambda = \sum_{x \in A_n n} (P_{\text{multi}} n \lambda x)^2$.
  have hQ1_def : Q_1 n lambda = ∑ x ∈ A_n n, (P_multi n lambda x)^2 := by
    unfold Q_1 P_multi Matrix_1
    simp [pow_two];
    simp +decide only [Finset.mul_sum _ _ _, mul_comm, mul_left_comm];
    exact Eq.symm ( Finset.sum_comm.trans ( Finset.sum_congr rfl fun _ _ => Finset.sum_comm ) )
  exact hQ1_def.symm ▸ Finset.sum_nonneg fun x hx => sq_nonneg _;

/-
Define dot product and orthogonal complement of kernel_Q1.
-/
/--
Define the standard dot product on the space of coefficients.
-/
def dot_product (n : ℕ) (u v : Idx n → ℝ) : ℝ :=
  ∑ S : Idx n, u S * v S

/--
The orthogonal complement of the kernel of $Q_1$ with respect to the standard dot product.
-/
def kernel_Q1_perp (n : ℕ) : Submodule ℝ (Idx n → ℝ) :=
  { carrier := { v | ∀ u ∈ kernel_Q1 n, dot_product n u v = 0 },
    add_mem' := by
      -- By definition of dot product, we have:
      have h_dot_product_linear : ∀ {a b : Idx n → ℝ}, ∀ u : Idx n → ℝ,
        dot_product n u (a + b) = dot_product n u a + dot_product n u b := by
        -- By definition of dot product, we can expand the left-hand side as the sum of the
        -- products of corresponding components.
        simp [dot_product, Finset.sum_add_distrib, mul_add];
      aesop,
    zero_mem' := by
      -- The dot product of any vector with the zero vector is zero.
      simp [dot_product],
    smul_mem' := by
      -- By definition of dot product, we have dot_product n u (c • x) = c * dot_product n u x.
      simp [dot_product];
      exact fun c x hx u hu => by
        simpa only [ mul_left_comm, Finset.mul_sum _ _ _ ] using
          mul_eq_zero_of_right c ( hx u hu ) ;
  }

/-
Define the unit sphere in the orthogonal complement and prove Q_1 is positive on it.
-/
/--
The unit sphere in the orthogonal complement of the kernel of $Q_1$.
-/
def sphere_perp (n : ℕ) : Set (Idx n → ℝ) :=
  { lambda | lambda ∈ kernel_Q1_perp n ∧ dot_product n lambda lambda = 1 }

/--
Lemma: $Q_1$ is strictly positive on the unit sphere of the orthogonal complement.
-/
lemma Q_1_pos_on_sphere_perp (n : ℕ) (lambda : Idx n → ℝ) (h : lambda ∈ sphere_perp n) :
    Q_1 n lambda > 0 := by
      -- By definition of $sphere_perp$, we know that $\lambda$ is in the orthogonal complement
      -- of $kernel_Q1$ and $\|\lambda\| = 1$.
      obtain ⟨h_lambda_perp, h_lambda_norm⟩ := h;
      contrapose! h_lambda_norm;
      have h_lambda_kernel : lambda ∈ kernel_Q1 n := by
        exact le_antisymm h_lambda_norm ( Q_1_nonneg n lambda );
      have := h_lambda_perp ( lambda ) h_lambda_kernel; simp_all +decide [ dot_product ] ;

/-
Prove that Q_1 is not identically zero.
-/
/--
Lemma: $Q_1$ is not identically zero.
-/
lemma Q_1_not_zero (n : ℕ) : ∃ lambda : Idx n → ℝ, Q_1 n lambda ≠ 0 := by
  use fun S => if S = ∅ then 1 else 0
  rw [← S_1_eq_Q_1]
  unfold S_1 W_truly_multi P_multi basis_cos
  simp
  -- The sum is over A_n. The term is (sum_S ...)^2.
  -- If lambda is delta_empty, sum_S is basis_cos(empty) = 1.
  -- So term is 1^2 = 1.
  -- Sum is |A_n| = L n.
  -- L n = 12n + 4 > 0.
  use 6 * n^2 - 2 * n;
  rcases n with ( _ | _ | n ) <;> simp +arith +decide [ Nat.mul_succ, sq ] at *;
  unfold A_n; ring_nf; norm_num;
  rw [ Nat.mod_eq_of_lt ] <;> norm_num;
  · constructor <;> nlinarith [ Nat.sub_add_cancel ( by
      nlinarith : n * 2 ≤ 20 + n * 24 + n ^ 2 * 6 ) ];
  · refine' lt_of_lt_of_le _ ( q_bound _ _ );
    · exact Nat.lt_succ_of_le ( Nat.sub_le_of_le_add <| by nlinarith );
    · linarith

/-
Prove that Ratio is scale-invariant.
-/
/--
Lemma: The Rayleigh quotient is scale-invariant.
-/
lemma Ratio_scale (n : ℕ) (lambda : Idx n → ℝ) (c : ℝ) (hc : c ≠ 0) :
    Ratio n (c • lambda) = Ratio n lambda := by
      unfold Ratio Q_1 Q_2;
      simp_all +decide [ mul_comm, mul_left_comm ] ;
      simp_all +decide [ ← Finset.mul_sum _ _ _, div_mul_eq_div_div ]

/-
Prove that (v i)^2 <= dot_product n v v.
-/
/--
Lemma: For any vector $v$, the square of any component is bounded by the dot product.
-/
lemma sq_le_dot_product (n : ℕ) (v : Idx n → ℝ) (i : Idx n) :
    (v i)^2 ≤ dot_product n v v := by
      exact Finset.single_le_sum ( fun a _ =>
        mul_self_nonneg ( v a ) ) ( Finset.mem_univ i ) |> le_trans ( by nlinarith )

/-
Prove that any vector can be decomposed into kernel and orthogonal complement components.
-/
/--
Lemma: Any vector can be decomposed into a component in the kernel of $Q_1$ and a component
in the orthogonal complement.
-/
lemma decomposition (n : ℕ) (x : Idx n → ℝ) :
  ∃ u ∈ kernel_Q1 n, ∃ v ∈ kernel_Q1_perp n, x = u + v := by
  -- Since kernel_Q1 n and kernel_Q1_perp n are complementary subspaces, their direct sum is
  -- the entire space.
  have h_compl : kernel_Q1 n ⊔ kernel_Q1_perp n = ⊤ := by
    convert Submodule.sup_orthogonal_of_hasOrthogonalProjection;
    rotate_left;
    exact ℝ;
    exact EuclideanSpace ℝ ( Idx n );
    all_goals try infer_instance;
    exact Submodule.span ℝ { v : EuclideanSpace ℝ ( Idx n ) | Q_1 n ( fun i => v i ) = 0 };
    · constructor;
      intro v;
      have h_decomp : ∀ v : EuclideanSpace ℝ (Idx n),
        ∃ w ∈ Submodule.span ℝ {v : EuclideanSpace ℝ (Idx n) | Q_1 n (fun i => v i) = 0},
        v - w ∈ (Submodule.span ℝ {v : EuclideanSpace ℝ (Idx n) | Q_1 n (fun i => v i) = 0})ᗮ := by
        intro v
        have h_subspace : ∀ (S : Submodule ℝ (EuclideanSpace ℝ (Idx n))), ∃ w ∈ S, v - w ∈ Sᗮ := by
          intro S;
          have h_decomp : ∀ (S : Submodule ℝ (EuclideanSpace ℝ (Idx n))), ∃ w ∈ S, v - w ∈ Sᗮ := by
            intro S
            have h_decomp : v ∈ S ⊔ Sᗮ := by
              rw [ Submodule.sup_orthogonal_of_hasOrthogonalProjection ] ; aesop
            rw [ Submodule.mem_sup ] at h_decomp;
            obtain ⟨ y, hy, z, hz, rfl ⟩ := h_decomp; exact ⟨ y, hy, by simpa using hz ⟩ ;
          exact h_decomp S
        exact h_subspace _;
      exact h_decomp v;
    · congr! 2;
      · refine' le_antisymm _ _;
        · exact fun x hx => Submodule.subset_span hx;
        · exact Submodule.span_le.mpr fun v hv => hv;
      · ext; simp [kernel_Q1_perp];
        simp +decide [ dot_product, Submodule.mem_orthogonal' ];
        simp +decide [ inner, Submodule.mem_span ];
        constructor <;> intro h u hu;
        · exact h u ( hu _ fun v hv => hv );
        · exact h u fun p hp => hp hu;
  simpa [ eq_comm ] using
    Submodule.mem_sup.mp ( h_compl.symm ▸ Submodule.mem_top : x ∈ kernel_Q1 n ⊔ kernel_Q1_perp n )

/-
Prove that P_multi is linear.
-/
/--
Lemma: The polynomial $P_{multi}$ is linear in $\lambda$.
-/
lemma P_multi_add (n : ℕ) (u v : Idx n → ℝ) (x : ZMod (q n)) :
    P_multi n (u + v) x = P_multi n u x + P_multi n v x := by
  unfold P_multi
  simp [Finset.sum_add_distrib, add_mul]

/-
Prove that sphere_perp is compact (final v2).
-/
/--
Lemma: The unit sphere in the orthogonal complement is compact.
-/
lemma sphere_perp_compact (n : ℕ) : IsCompact (sphere_perp n) := by
  rw [Metric.isCompact_iff_isClosed_bounded]
  constructor
  · -- Closed
    apply IsClosed.inter
    · -- kernel_Q1_perp is closed
      haveI : FiniteDimensional ℝ (Idx n → ℝ) := by infer_instance
      exact Submodule.closed_of_finiteDimensional (kernel_Q1_perp n)
    · -- sphere is closed
      apply isClosed_eq
      · -- dot_product is continuous
        apply continuous_finset_sum
        intro i hi
        apply Continuous.mul
        · apply continuous_apply
        · apply continuous_apply
      · exact continuous_const
  · -- Bounded
    rw [isBounded_iff_forall_norm_le]
    use 1
    intro lambda hlambda
    have h_dot : dot_product n lambda lambda = 1 := hlambda.2
    apply pi_norm_le_iff_of_nonneg (by norm_num) |>.2
    intro i
    rw [Real.norm_eq_abs]
    rw [← sq_le_one_iff_abs_le_one]
    rw [← h_dot]
    exact sq_le_dot_product n lambda i

/-
Prove that Q_2(u+v) = Q_2(v) if u is in the kernel of Q_1.
-/
/--
Lemma: If $u \in \text{kernel}(Q_1)$, then $Q_2(u + v) = Q_2(v)$.
-/
lemma Q_2_add_kernel (n : ℕ) (u v : Idx n → ℝ) (hu : u ∈ kernel_Q1 n) :
    Q_2 n (u + v) = Q_2 n v := by
      -- By definition of $P_{multi}$, we know that $P_{multi}(u + v) = P_{multi}(u) + P_{multi}(v)$ for any $u$ and $v$.
      have h_add : ∀ x : ZMod (q n), P_multi n (u + v) x = P_multi n u x + P_multi n v x := by
        exact fun x ↦ P_multi_add n u v x;
      -- By definition of $Q_2$, we know that $Q_2(u + v) = \sum_{x \in A_n} c(x) P_{multi}(u + v)(x)$.
      have h_Q2_def : ∀ (lambda : Idx n → ℝ), Q_2 n lambda = ∑ x ∈ A_n n, c n x * P_multi n lambda x ^ 2 := by
        intro lambda
        simp [Q_2, Matrix_2];
        simp +decide [ P_multi, Finset.mul_sum _ _ _, mul_comm, mul_left_comm, sq ];
        exact Eq.symm ( by
          rw [ Finset.sum_comm ] ;
          exact Finset.sum_congr rfl fun _ _ =>
            Finset.sum_comm.trans ( Finset.sum_congr rfl fun _ _ =>
              Finset.sum_congr rfl fun _ _ => by ring ) );
      -- By definition of $c$, we know that $c(x) P_{multi}(u)(x) = 0$ for all $x \in A_n$.
      have h_c_u_zero : ∀ x ∈ A_n n, c n x * P_multi n u x = 0 := by
        intro x hx
        have h_P_multi_u_zero : P_multi n u x = 0 := by
          have := Q_1_eq_zero_iff n u |>.1 hu x hx; aesop;
        simp [h_P_multi_u_zero];
      simp_all +decide [ Finset.sum_add_distrib, mul_add, add_sq ];
      rw [ ← Finset.sum_add_distrib ] ;
      exact Finset.sum_eq_zero fun x hx => by cases h_c_u_zero x hx <;> simp +decide [ * ] ;

/-
Prove that Ratio(u+v) = Ratio(v) if u is in the kernel of Q_1.
-/
/--
Lemma: The Rayleigh quotient is invariant under adding a vector from the kernel of $Q_1$.
-/
lemma Ratio_add_kernel (n : ℕ) (u v : Idx n → ℝ) (hu : u ∈ kernel_Q1 n) :
    Ratio n (u + v) = Ratio n v := by
      unfold Ratio;
      -- By definition of $Q_1$, we know that $Q_1(u + v) = Q_1(v)$ if $u$ is in the kernel of $Q_1$.
      have h_Q1_add : Q_1 n (u + v) = Q_1 n v := by
        -- By definition of $P_{\text{multi}}$, we have $P_{\text{multi}} n (u + v) x = P_{\text{multi}} n u x + P_{\text{multi}} n v x$.
        have hP_multi_add : ∀ x : ZMod (q n), P_multi n (u + v) x = P_multi n u x + P_multi n v x := by
          apply P_multi_add;
        -- By definition of $Q_1$, we have $Q_1(u + v) = \sum_{x \in A_n} (P_{\text{multi}} n (u + v) x)^2$.
        have hQ_1_def : ∀ (lambda : Idx n → ℝ), Q_1 n lambda = ∑ x ∈ A_n n, (P_multi n lambda x)^2 := by
          intros lambda
          simp [Q_1, Matrix_1];
          simp +decide [ P_multi, pow_two, mul_comm, mul_left_comm, Finset.mul_sum _ _ _ ];
          exact Eq.symm ( by
            rw [ Finset.sum_comm ] ;
            exact Finset.sum_congr rfl fun _ _ =>
              Finset.sum_comm.trans ( Finset.sum_congr rfl fun _ _ =>
                Finset.sum_congr rfl fun _ _ => by ring ) ) ;
        -- Since $u \in \ker(Q_1)$, we have $P_{\text{multi}} n u x = 0$ for all $x \in A_n$.
        have hP_multi_u_zero : ∀ x ∈ A_n n, P_multi n u x = 0 := by
          exact fun x hx => by simpa [ hQ_1_def ] using Q_1_eq_zero_iff n u |>.1 hu x hx;
        simp_all only [zero_add];
      rw [ h_Q1_add, Q_2_add_kernel n u v hu ]

/-
Prove that for any lambda with Q_1 > 0, there is a v in sphere_perp with the same Ratio.
-/
/--
Lemma: For any $\lambda$ with $Q_1(\lambda) > 0$, there exists $v \in \text{sphere\_perp}(n)$
such that $\text{Ratio}(n, \lambda) = \text{Ratio}(n, v)$.
-/
lemma exists_sphere_perp_ratio_eq (n : ℕ) (lambda : Idx n → ℝ) (hQ1 : Q_1 n lambda > 0) :
    ∃ v ∈ sphere_perp n, Ratio n lambda = Ratio n v := by
      -- By definition of decomposition, we can write lambda as u + v where u is in the kernel of
      -- Q_1 and v is in the orthogonal complement.
      obtain ⟨u, v, hu, hv, rfl⟩ : ∃ u ∈ kernel_Q1 n, ∃ v ∈ kernel_Q1_perp n, lambda = u + v :=
        decomposition n lambda;
      -- Since $hu$ is in the orthogonal complement of the kernel of $Q_1$, we can scale it to
      -- have unit length.
      obtain ⟨c, hc⟩ : ∃ c : ℝ, c ≠ 0 ∧ dot_product n (c • hu) (c • hu) = 1 := by
        by_cases h : dot_product n hu hu = 0 <;> simp_all +decide [ dot_product ];
        · simp_all +decide [ Finset.sum_eq_zero_iff_of_nonneg, mul_self_nonneg ];
          simp_all +decide [ show hu = 0 from funext h ];
          exact hQ1.ne' ( v );
        · use 1 / Real.sqrt (∑ S, hu S * hu S);
          field_simp [h];
          exact ⟨ one_div_ne_zero <| ne_of_gt <| Real.sqrt_pos.mpr <| lt_of_le_of_ne (
            Finset.sum_nonneg fun _ _ => sq_nonneg _ ) <| Ne.symm <| by
              simpa only [ sq ] using h, by
                rw [ ← Finset.sum_div, Real.sq_sqrt <| Finset.sum_nonneg fun _ _ => sq_nonneg _, 
                  div_self <| ne_of_gt <| lt_of_le_of_ne ( Finset.sum_nonneg fun _ _ =>
                    sq_nonneg _ ) <| Ne.symm <| by simpa only [ sq ] using h ] ⟩;
      refine' ⟨ c • hu, ⟨ _, hc.2 ⟩, _ ⟩;
      · intro w hw; simp_all +decide [ dot_product ] ;
        convert hv w hw |> fun h => congr_arg ( · * c ) h using 1 <;> ring_nf;
        simp +decide [ mul_comm, mul_left_comm, Finset.mul_sum _ _ _, dot_product ];
      · rw [ Ratio_add_kernel n u hu v, Ratio_scale n hu c hc.1 ]

/-
Prove that attainable_ratios is the image of sphere_perp under Ratio.
-/
/--
Lemma: The set of attainable ratios is the image of the unit sphere in the orthogonal complement
under the Rayleigh quotient map.
-/
lemma attainable_ratios_eq_image_sphere_perp (n : ℕ) :
    attainable_ratios n = (sphere_perp n).image (Ratio n) := by
  ext r
  constructor
  · intro h
    obtain ⟨lambda, hQ1, rfl⟩ := h
    obtain ⟨v, hv, h_ratio⟩ := exists_sphere_perp_ratio_eq n lambda hQ1
    use v
    exact ⟨hv, h_ratio.symm⟩
  · intro h
    obtain ⟨v, hv, rfl⟩ := h
    use v
    constructor
    · exact Q_1_pos_on_sphere_perp n v hv
    · rfl

/-
Prove that attainable_ratios is compact.
-/
/--
Lemma: The set of attainable ratios is compact.
-/
lemma attainable_ratios_compact (n : ℕ) : IsCompact (attainable_ratios n) := by
  rw [ attainable_ratios_eq_image_sphere_perp ];
  apply_rules [ IsCompact.image_of_continuousOn, sphere_perp_compact ];
  -- Since $Q_1$ and $Q_2$ are continuous functions, their ratio is continuous wherever $Q_1$ is non-zero.
  have h_cont : ContinuousOn (fun lambda : Idx n → ℝ => Q_2 n lambda / Q_1 n lambda) (sphere_perp n) := by
    refine' ContinuousOn.div _ _ _;
    · refine' Continuous.continuousOn _;
      refine' continuous_finset_sum _ fun S _ => continuous_finset_sum _ fun T _ => _;
      fun_prop;
    · refine' Continuous.continuousOn _;
      refine' continuous_finset_sum _ fun S _ => continuous_finset_sum _ fun T _ => _;
      fun_prop;
    · exact fun x hx => ne_of_gt <| Q_1_pos_on_sphere_perp n x hx;
  refine' h_cont.congr fun x hx => _ ; unfold Ratio ; aesop;

/-
Prove that the minimum attainable ratio is attained by some lambda.
-/
/--
Lemma: The minimum attainable ratio is attained by some coefficient vector $\lambda$.
-/
lemma exists_minimizer (n : ℕ) :
    ∃ lambda : Idx n → ℝ, Q_1 n lambda > 0 ∧ Ratio n lambda = mu_min n := by
  have h_compact : IsCompact (attainable_ratios n) := attainable_ratios_compact n
  have h_nonempty : (attainable_ratios n).Nonempty := by
    obtain ⟨lambda, hlambda⟩ := Q_1_not_zero n
    use Ratio n lambda
    use lambda
    exact ⟨lt_of_le_of_ne (Q_1_nonneg n lambda) (Ne.symm hlambda), rfl⟩
  have h_mem : mu_min n ∈ attainable_ratios n := by
    apply IsCompact.sInf_mem h_compact h_nonempty
  obtain ⟨lambda, hQ1, h_ratio⟩ := h_mem
  use lambda
  exact ⟨hQ1, h_ratio.symm⟩

/-
Define lambda_opt and W_opt.
-/
/--
Define the optimal coefficient vector $\lambda_{opt}$ which attains the minimum ratio.
-/
noncomputable def lambda_opt (n : ℕ) : Idx n → ℝ :=
  (exists_minimizer n).choose

/--
Properties of the optimal coefficient vector.
-/
lemma lambda_opt_spec (n : ℕ) :
    Q_1 n (lambda_opt n) > 0 ∧ Ratio n (lambda_opt n) = mu_min n :=
  (exists_minimizer n).choose_spec

/--
Define the optimal truly multidimensional weight function $W_{opt}$.
-/
noncomputable def W_opt (n : ℕ) : ZMod (q n) → ℝ :=
  W_truly_multi n (lambda_opt n)

/--
Theorem: The optimal weight function satisfies the Krafft Admissibility condition if and only if
$\mu_{min}(n) < 1$.
-/
theorem W_opt_is_admissible_iff (n : ℕ) :
    (S_2 n (W_opt n) < S_1 n (W_opt n)) ↔ mu_min n < 1 := by
      constructor;
      · intro h
        have h_lambda_opt : Q_2 n (lambda_opt n) < Q_1 n (lambda_opt n) := by
          rw [ ← S_1_eq_Q_1, ← S_2_eq_Q_2 ] at * ; aesop;
        exact lt_of_le_of_lt ( csInf_le ( by
          exact IsCompact.bddBelow ( attainable_ratios_compact n ) ) <| show (
            Ratio n ( lambda_opt n ) ) ∈ attainable_ratios n from by
              exact ⟨ _, ( lambda_opt_spec n ) |>.1, rfl ⟩ ) ( by
                rw [ show Ratio n ( lambda_opt n ) =
                  ( Q_2 n ( lambda_opt n ) ) / ( Q_1 n ( lambda_opt n ) ) from by
                    unfold Ratio; aesop ] ;
                exact div_lt_one ( ( lambda_opt_spec n ) |>.1 ) |>.2 h_lambda_opt );
      · have := lambda_opt_spec n;
        unfold W_opt;
        unfold Ratio at this;
        rw [ ← this.2, if_neg this.1.ne' ];
        exact fun h => by rw [ S_2_eq_Q_2, S_1_eq_Q_1 ] ; rw [ div_lt_iff₀ this.1 ] at h; linarith;

/--
Theorem: The Krafft Sieve Guarantee holds if $\mu_{min}(n) < 1$.
-/
theorem krafft_sieve_guarantee_with_mu_min (n : ℕ) (h : mu_min n < 1) :
    ∃ x ∈ A_n n, Nat.Prime (6 * x - 1) ∧ Nat.Prime (6 * x + 1) := by
      have := mu_min_lt_one_implies_admissibility n h;
      by_cases hn : n ≥ 1 <;> simp_all +decide [ Krafft_Admissibility ];
      obtain ⟨ W, hW₁, hW₂, hW₃ ⟩ := this;
      apply krafft_sieve_guarantee n hn ⟨ W, hW₁, hW₂, hW₃ ⟩
